### ISSUE TITLE
bench restana + turbo-http?

### ISSUE THREAD

**Issue by leeoniya** [uNetworking/uWebSockets.js#10]
hey @alexhultman,

https://medium.com/@kyberneees/building-ultra-fast-rest-apis-with-node-js-and-restana-1d65b0d524b7

looks to be about 2x faster than Node native. (and can do clustering for another 20%).

**Comment by alexhultman** [comment]
No need to benchmark, I already know it's not close.

**Comment by alexhultman** [comment]
It's not even ballpark

turbo-http without SSL (I don't even think they have SSL):
```
alexhultman@alexhultman-N56VZ:~/wrk$ ./wrk http://localhost:8080
Running 10s test @ http://localhost:8080
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   220.30us   27.02us   1.60ms   90.43%
    Req/Sec    22.66k     2.05k   45.04k    90.55%
  453423 requests in 10.10s, 32.00MB read
Requests/sec:  44896.51
Transfer/sec:      3.17MB
```

uws:
```
alexhultman@alexhultman-N56VZ:~/wrk$ ./wrk http://localhost:3000
Running 10s test @ http://localhost:3000
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    53.52us   19.67us 488.00us   73.45%
    Req/Sec    91.13k     7.06k  105.67k    60.89%
  1830880 requests in 10.10s, 89.05MB read
Requests/sec: 181274.01
Transfer/sec:      8.82MB
```

uws with SSL:
```
alexhultman@alexhultman-N56VZ:~/wrk$ ./wrk https://localhost:3000
Running 10s test @ https://localhost:3000
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    91.79us  326.94us  17.42ms   99.79%
    Req/Sec    60.19k     8.21k   71.15k    80.20%
  1209457 requests in 10.10s, 58.82MB read
Requests/sec: 119748.92
Transfer/sec:      5.82MB
```

**Comment by leeoniya** [comment]
i wasn't suggesting it would be close to uWSjs (i know what 2x means). was just curious how it stacked up to native node http in your testing. cool to see it roughly on par with Crystal.

thanks!

**Comment by alexhultman** [comment]
You mean turbo-http? Uws is not comparable with Crystal. Where do you publish these results?

**Comment by leeoniya** [comment]
https://github.com/uNetworking/uWebSockets/blob/master/misc/bigshot_lineup.png

**Comment by alexhultman** [comment]
Is turbo-http worth putting in? It's not very well known.

**Comment by alexhultman** [comment]
I don't follow.

> i think it's interesting since it shows you can do faster than Node "native" without compiled addons

This makes no sense. Turbo-http *is* using a native add-on. You can't go faster than "native" without using add-ons unless you manage to build something on net. Server that's somewhat faster. But none of these projects do

**Comment by leeoniya** [comment]
> Turbo-http is using a native add-on.

oops, guess i missed that dependency :man_facepalming:

this whole issue was pointless. sry!

**Comment by alexhultman** [comment]
It's not pointless for turbo http but it's pointless for everything else (restana, fastify, etc etc etc) since they all rely on node js

**Comment by leeoniya** [comment]
> but it's pointless for everything else (restana, fastify, etc etc etc) since

well, you do have Express in there to show how much it adds to bare Node http. restana does much better, presumably. including a router that does some form or uri interpolation in all cases rather than serving up static routes would be more apples-to-apples?
