### ISSUE TITLE
Websocket crash on connection

### ISSUE THREAD

**Issue by visbio** [uNetworking/uWebSockets.js#100]
The client example for websockets crashes after the "open" handler with a blank getUrl() when connecting with an external websocket library.

**Comment by alexhultman** [comment]
You need to provide a lot more info

**Comment by visbio** [comment]
Using a non-uWS client to connect without any options enabled server-side. I don't have much information to provide since uWS crashes without an error message. (Switching to a different websocket library works without issue.)

**Comment by alexhultman** [comment]
I can't reproduce any of this and you don't provide any info I can go by. There is no "uws client" you're not giving any useful info
