### ISSUE TITLE
H3App: segmentation fault

### ISSUE THREAD

**Issue by jimmywarting** [uNetworking/uWebSockets.js#1019]
Whenever i try the `H3App` i get a "segmentation fault"... 
some kind of unexpected token...

it crash the application and exit...

system:
(Mac pro M1) darwin arm64
(Node) v21.5.0

```js
// uWS.H3App({
uWS.SSLApp({
  key_file_name: './cert/key.pem',
  cert_file_name: './cert/cert.pem'
}).get('/*', (res, req) => {
  res.end('Nothing to see here!');
}).listen(3443, (token) => {
  // ...
})
```

The `SSLApp` works fine... do i need to generate a other http3 specific cert for it to work?

**Comment by uNetworkingAB** [comment]
HTTP3 support is experimental and not prioritized right now

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets.js/issues/1086

**Comment by uNetworkingAB** [comment]
This is a compilation issue, we need to properly cross-compile lsquic on macos
