### ISSUE TITLE
maybe intro should compare to well-known servers

### ISSUE THREAD

**Issue by leeoniya** [uNetworking/uWebSockets.js#102]
> It runs 15x faster than Deno and scales to millions of connections using less than half a GB of user space memory.

i know you like shaming Deno, which is perfectly fine. but i don't think it makes sense to advertise this project in terms of speedup factor over an unknown, unused, work-in-progress server. it's fine to leave it in the charts and as a footnote, but it would be more impressive to compare against well-known and widely-deployed production servers like nginx, node, maybe caddy even if the speedup factor is not as impressive as 15x.

"15x faster than Deno" is entirely meaningless to anyone looking to adopt this project over their current server.

**Comment by alexhultman** [comment]
The entire front page is going to be slimmed down and simplified in a while

**Comment by leeoniya** [comment]
btw, repo descr still says `TypeScript web server - 15x faster than Deno `
