### ISSUE TITLE
Setting idleTimeout to a big value crashes the process

### ISSUE THREAD

**Issue by FlorentMasson** [uNetworking/uWebSockets.js#1025]
Code:
`const app = uWS.App({}).ws('/*', { idleTimeout: 1000 });`

Output:
`Process exited with code 3221226505`

I determined that the highest value I can set without crashing is 960

Version: uWebSockets.js@20.42.0 on Windows 10

**Comment by uNetworkingAB** [comment]
Sounds about right. It doesn't crash, you get a message

**Comment by FlorentMasson** [comment]
???
No it crashes. You can add .listen(3000) and it will crash even before calling listen()

**Comment by uNetworkingAB** [comment]
/* Maximum idleTimeout is 16 minutes */
        if (behavior.idleTimeout > 240 * 4) {
            **std::cerr << "Error: idleTimeout must not be greater than 960 seconds!" << std::endl;**
            std::terminate();
        }
