### ISSUE TITLE
uWebSockets.js can't be installed using npm install uNetworking/uWebSockets.js#v20.43.0

### ISSUE THREAD

**Issue by dunadain** [uNetworking/uWebSockets.js#1041]
run the command and it will show the following errors:
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/uNetworking/uWebSockets.js.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by uNetworkingAB** [comment]
Looks like some issue with your npm. There are many issues with npm, you can try other similar alternatives. But its not an issue to be fixed here.
