### ISSUE TITLE
HttpResponse onData method 

### ISSUE THREAD

**Issue by andrew-modelsoftware** [uNetworking/uWebSockets.js#1046]
Question on the API design, just wondered why the `onData` method is on the `HttpResponse` object and not on the request? It seems that the method returns the body of the request, isn't that a bit counterintuitive?

**Comment by uNetworkingAB** [comment]
It's a common question. It's a naming thing, if you think HttpSocket and HttpHead it makes sense. But for being as compatible with Node.js naming as possible, it was named HttpResponse/HttpRequest even if their responsibilities mismatch a bit.

**Comment by uNetworkingAB** [comment]
HttpRequest/HttpHead is even better naming because the socket is shared between many requests, but that would confuse Node.js people even more
