### ISSUE TITLE
node 22

### ISSUE THREAD

**Issue by yovanoc** [uNetworking/uWebSockets.js#1049]
How can we help to ship node 22 binaries? thanks

**Comment by uNetworkingAB** [comment]
I will have a look within a week

**Comment by yovanoc** [comment]
Ok, thanks!

**Comment by aleksraiden** [comment]
Also waiting, a lot of thanks

**Comment by aleksraiden** [comment]
Current upstream from repo works fine with 21.1 node

**Comment by yovanoc** [comment]
> Current upstream from repo works fine with 22.1 node

the version 20.43 still doesn't work for me with node 22.1

**Comment by aleksraiden** [comment]
> > Current upstream from repo works fine with 22.1 node
> 
> the version 20.43 still doesn't work for me with node 22.1

check an version from repo, not release

**Comment by uNetworkingAB** [comment]
#1031

**Comment by Sceat** [comment]
> > > Current upstream from repo works fine with 22.1 node
> > 
> > 
> > the version 20.43 still doesn't work for me with node 22.1
> 
> check an version from repo, not release

we still the need to compiled binaries, how do you install from upstream ?

**Comment by aleksraiden** [comment]
> we still the need the compiled binaries, how do you install from upstream ?

We are using a binary from this commit - https://github.com/uNetworking/uWebSockets.js/tree/bcb70ea44395eb59f695860b4b37db90387d86de   and all works fine

**Comment by Sceat** [comment]
and on the latest commit for the binaries `4181846d36bf1f19a6f2eb59f5add8494dfabbe4`

I get `dyld[6162]: missing symbol called`

cc: @uNetworkingAB

**Comment by Veradictus** [comment]
^ Same here

**Comment by uNetworkingAB** [comment]
Node 22 support is not released yet

**Comment by Sceat** [comment]
Any blocker?

**Comment by uNetworkingAB** [comment]
Windows is not building

**Comment by Sceat** [comment]
Is it a blocker for other distros ?

**Comment by e3dio** [comment]
Just download correct file from here https://github.com/uNetworking/uWebSockets.js/tree/binaries

**Comment by uNetworkingAB** [comment]
this is now released
