### ISSUE TITLE
Handling multipart/form-data body

### ISSUE THREAD

**Issue by treble-snake** [uNetworking/uWebSockets.js#106]
Hi, I'm working on a multipart body parser and wondering if you could reveal the chunking logic for that data type. 

It looks like it's kinda supposed to pass one field per chunk for text fields, separate headers and body for file fields (starting chunk with headers, then N chunks with data), and the last chunk would be the closing boundary.

But sometimes the server concatenates all or some of the text fields, it also can concatenate (into one chunk) part of the file with field headers and/or closing boundary. With a file it's especially inconvenient since it makes steaming to the disk a complicated task.

I've confirmed it with the very basic example described in [examples/Upload.js](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Upload.js) (v15.8.0). 
Can't see any pattern yet, it just does it sometimes (maybe more ofter with smaller files).

I'm wondering if it's the intended behaviour or something went wrong (or maybe I'm doing something wrong ofc).

Thanks.

**Comment by alexhultman** [comment]
I can't help you

**Comment by treble-snake** [comment]
Well, I wasn't looking for help, more like reporting presumably unexpected behaviour.
Just to clarify things, this is the code (almost the same as the upload example):
```js
const uWS = require('uWebSockets.js');
const port = 3000;

uWS.App().post('/*', (res, req) => {
  let q = 0;
  res.onData((chunk, isLast) => {
    /* Buffer this anywhere you want to */
    console.log('Chunk #', q, ', size:', chunk.byteLength);

    if (q === 0 || isLast) {
      if (chunk.byteLength <= 180) {
        console.log('Handling chunk', Buffer.from(chunk).toString());
      } else {
        console.error('Boundary expected!');
        process.exit(1);
      }
    }

    q++;

    /* We respond when we are done */
    if (isLast) {
      res.end('Thanks for the data!');
    }
  });

  res.onAborted(() => {
    /* Request was prematurely aborted, stop reading */
    console.log('Eh, okay. Thanks for nothing!');
  });
}).listen(port, (token) => {
  if (token) {
    console.log('Listening to port ' + port);
  } else {
    console.log('Failed to listen to port ' + port);
  }
});
```

Then I sent the same simple form with just 1 field (a file), and here is the output of 2 tries:
```
➜ node example/pure.js
Listening to port 3000
Chunk # 0 , size: 180
Handling chunk ----------------------------499162952261603574929250
Content-Disposition: form-data; name="the_file"; filename="Screenshot 2019-03-18 at 13.45.02.png"
Content-Type: image/png


Chunk # 1 , size: 131072
Chunk # 2 , size: 48936
Chunk # 3 , size: 16600
Chunk # 4 , size: 65536
Chunk # 5 , size: 65536
Chunk # 6 , size: 65536
Chunk # 7 , size: 51394
Chunk # 8 , size: 58
Handling chunk
----------------------------499162952261603574929250--

➜ node example/pure.js
Listening to port 3000
Chunk # 0 , size: 16492
Boundary expected!
```

So, as you can see, 1st time chunks came as expected, and 2nd time field headers got merged with a part of the file data in the first chunk, and that looks wrong. 
But if you say it's OK, then OK.

**Comment by alexhultman** [comment]
I really cannot help you. You're making 101 mistakes. There are "coding camps" or schools for this.
