### ISSUE TITLE
404 File Not Found uWebSockets/20 Server on PATCH

### ISSUE THREAD

**Issue by josh-i386g** [uNetworking/uWebSockets.js#1061]
Hi everyone good day.

Has anyone encountered unbound handlers on PATCH method that redirects to 404 recently?

I'm generating CRUD endpoints for my tables. The following methods work:

- GET for reading one record
- GET for reading many records
- POST for creating a record
- PUT for updating a record
- DELETE for deleting a record

The problem is I also want to support PATCH handler because my PUT handler supports partial column updates. But when I try to bind it to PATCH handler, it doesn't get caught, and ends up to the default 404 handler.

I am using ` "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.43.0"`

![image](https://github.com/uNetworking/uWebSockets.js/assets/150557754/dfbcff11-895d-4d07-80c2-6b8c677d214c)

![image](https://github.com/uNetworking/uWebSockets.js/assets/150557754/4d5cef9b-317c-47eb-bb29-b5e91e770299)

![image](https://github.com/uNetworking/uWebSockets.js/assets/150557754/6e2dbf61-af2e-4827-b200-714f4965e42e)

![image](https://github.com/uNetworking/uWebSockets.js/assets/150557754/0badf53c-1d3f-4d51-9c73-37a35ffef865)

![image](https://github.com/uNetworking/uWebSockets.js/assets/150557754/b49265ec-98e8-4458-9b52-f53c847ae378)

When I remove the codes that use PATCH, all tests work:

![image](https://github.com/uNetworking/uWebSockets.js/assets/150557754/b233a6a2-d94f-4b29-bf87-ddd23bae144c)

For now I"ll be using PUT, but decided to create this issue in case someone else encounters similar issue, thank you.

**Comment by uNetworkingAB** [comment]
I can serve a PATCH request here, can you provide a small snippet that fails?

**Comment by uNetworkingAB** [comment]
```
alexhultman@Windows11:~/uWebSockets.js/uWebSockets$ curl --request PATCH --verbose http://localhost:3000
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> PATCH / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 22 May 2024 02:11:06 GMT
< uWebSockets: 20
< Content-Length: 12
< 
* Connection #0 to host localhost left intact
Hello world!alexhultman@Windows11:~/uWebSockets.js/uWebSockets$ 
```

**Comment by josh-i386g** [comment]
Hi, turns out the problem is in my test code, not in uWebSockets.js.

The cause is Node.js internal fetch (undici) doesn't normalize `"patch"` into `"PATCH"` (which surprisingly follows the spec).

Thread here: https://github.com/nodejs/undici/issues/2294

The fix in my code:

```diff
    const url = new URL("http://localhost:8080/");
    url.pathname = `/api/${resource}/${item.id}`;
-   const method = "patch";
+   const method = "PATCH";
    const headers = new Headers();
    if (typeof token === "string") {
      headers.set("authorization", `Bearer ${token}`);
    }
    headers.set("content-type", "application/json; charset=utf-8");
    const body = JSON.stringify(item);
    const response = await fetch(url, { method, headers, body });
```

Closing this, thank you!
