### ISSUE TITLE
TechEmpower ban 2024; the lore

### ISSUE THREAD

**Issue by uNetworkingAB** [uNetworking/uWebSockets.js#1078]
### Sour critique leads to ban

His ego couldn't take [me pointing out that his quality control is zero (which it is)](https://twitter.com/uNetworkingAB/status/1811425564764610926), so he permanently banned me on GitHub, Twitter, [removed and banned uWebSockets.js](https://github.com/TechEmpower/FrameworkBenchmarks/pull/9160) from the top and added a [code of conduct](https://github.com/TechEmpower/FrameworkBenchmarks/commit/4022ec349164c56929c47d283302ad531cac3d26). Yes the project itself is lifetime banned now.

The tweet:

<img width="588" alt="Screenshot 2024-07-18 at 19 17 05" src="https://github.com/user-attachments/assets/4fe12f5f-ea13-44f5-a88a-cdd206ae47ef">

The response:

**"[...] Happy to remove your framework. Seeing your tweets now as well. You're not interested in reviewing code and making things better; you're interested in being right and you're too toxic about it. [...]"**

<img width="1236" alt="Screenshot 2024-07-18 at 19 10 39" src="https://github.com/user-attachments/assets/9dc8650a-c277-4aca-8962-8971279fce08">

The ban:
<img width="926" alt="Screenshot 2024-07-18 at 19 51 40" src="https://github.com/user-attachments/assets/63430427-415c-4529-a9f4-8da308d634dc">

The block:
<img width="400" alt="Screenshot 2024-07-18 at 19 49 12" src="https://github.com/user-attachments/assets/cce19e77-bda9-4c5b-a39e-ca20574deb66">

### 1st place in TechEmpower performs half that of uWS.js
TechEmpower is a flawed benchmark for two main reasons:

1. **Fake Participants**: Many top participants use obvious hacks like simply splitting the TCP data on "\r\n\r\n", doing no real parsing or standards compliant interpretation whatsoever. There is no quality control to catch these fakes. For example, "gnet," which won Round 22, uses such a hack, making the entire test meaningless. "faf" also uses this hack.
2. **Misleading HTTP Pipelining**: By enabling the most bizarre level of HTTP pipelining ever seen in a benchmark, the test only measures how fast the parser can process these tightly packed requests, not its total I/O performance. Since all top participants simply fake the HTTP parsing step as explained above, the entire TechEmpower benchmark is meaningless.

We can very easily see this by running a regular non-pipelined benchmark showing uWS.js massively outperforms "mrhttp", which is the very 1st in TechEmpower.

![GSZjHKuWYAAEgji](https://github.com/user-attachments/assets/23656398-2ca8-4947-8e47-7099cb0639e2)

### Most recent run before ban
TechEmpower is not a credible benchmark.

Either way, uWS.js scores insignificantly different from 1st. If excluding obvious fakes & incorrect participants, it scores actually 1st (however, even this should be taken with a grain of salt given how statistically insignificant the win would be).

![techruncomplete](https://github.com/user-attachments/assets/e53151ca-7baa-4c87-8ae4-78f67e8d1a62)

### Some important nitpicks (elaborating the critique)

* **We send more data per request**: "Server: uWebSockets.js" and "uWebSockets: 20" vs. only sending "Server: F" like FaF does. It means we occupy more bandwidth per request. This could be fixed in a second run, but we are banned and can't participate any longer. TE does not keep track of CPU-usage, so we can only guess whether this single point makes all the difference, or not. Most likely, this has the most impact on the score.
* **We are entirely standards compliant** (RFC 9110) with all the request smuggling checks, invalid field name checks, conflicting body length checks, missing "host" header checks, PROXYv2 header check, performed according to spec. None of the others in top 5 do even close to this. Most of them simply scan until "\r\n\r\n" and assume that's a valid request. Most of them can't even receive a body because they don't even check "content-length".
* **We do dynamic URL routing with wildcard, static, parameter routes.** They (gnet, mrhttp, faf, pico.v) do just a hardcoded if (memcmp("GET") == 0) [[likely]] kind of "routing" and just copy a preformatted hardcoded buffer back.
* **Pipelining benchmarks only stress the HTTP parser and URL router** which conveniently are the very parts that are seriously non-compliant, outright broken or entirely missing in the TE top performers (gnet, mrhttp, faf). Anyone can make a fast HTTP parser that just skips to "\r\n\r\n" using 2 lines of SIMD intrinsics. Comparing a fully standards compliant parser with all the required header validation against such a solution is meaningless.
* **uWebSockets.js is a dynamic module** that dynamically links to Node.js's libuv. Native uWS does not use libuv, but links statically to its own epoll implementation with LTO linking and O3 optimizations, producing even better results. But, only uWS.js was added to TE, not native uWS. There is also no need for uWS.DeclarativeResponse in native uWS, cutting even more overhead. Likewise, the PROXYv2 parser pass can be disabled in native uWS, eliminating even more overhead.
* **Results are insignificantly different** among the top 5. There is a cutoff plateau where ordering is very tight and depends on essentially random noise. A 7th placement can be a 2nd placement next run, as the variance is enough to scramble the list between runs.

**Comment by uNetworkingAB** [comment]
<img width="1440" alt="Screenshot 2024-07-11 at 20 34 53" src="https://github.com/uNetworking/uWebSockets.js/assets/110806833/cb27ac60-0424-430b-8b31-d8042bb1ecaa">

**Comment by uNetworkingAB** [comment]
Knowing GitHub, I can still insert a link https://github.com/TechEmpower/FrameworkBenchmarks/pull/9160 on his PR 😉

**Comment by uNetworkingAB** [comment]
@remittor I got banned from the project, so I will respond here: yes I absolutely agree `mrhttp` is a broken project that nobody can use for anything real. 100% agree. But at least it does most of the basics of HTTP somewhat correctly. Comparing that with `gnet`, which does nothing correctly whatsoever - `mrhttp` is a saint. But yes, of course, none of those are usable in any kind of production app. They are joke projects. But there are worse offenders than `mrhttp` in my opinion, esp. since it actually has a somewhat novel approach with AVX2 (not really, but still)

**Comment by remittor** [comment]
Very strange things.
It turns out that if I review the code for `gnet`, I can also be banned?
Maybe there was another reason for the ban? (I didn’t keep track of what exactly caused this reaction)

**Comment by uNetworkingAB** [comment]
> How this slipped past quality control is beyond me, but also doesn't shock me.

This got him red faced

**Comment by uNetworkingAB** [comment]
Ok I will clean this thread (remove comments) and post the last complete run with uWS.js here, and lock the thread when it finishes (3 days remains). Then at least we have 1 full run to refer to.

**Comment by uNetworkingAB** [comment]
@remittor ok I will remove this comment soon, thanks for responding but I want this thread clean and locked without comments :D

**Comment by uNetworkingAB** [comment]
Ok, looks like the project can come back if someone other than me reverts the removal:

git clone https://github.com/TechEmpower/FrameworkBenchmarks
git checkout -b add_uwebsocketsjs
git revert 4b0a91f07147386c8f11b36b1410f00b34c7611c
git commit
git push origin add_uwebsocketsjs

and make a PR of that 👌

**Comment by porsager** [comment]
If you're fine with it, I'll add it?

**Comment by uNetworkingAB** [comment]
Absolutely, it's good PR regardless of credibility

**Comment by uNetworkingAB** [comment]
If you want you can also remove the MySQL subject since it's very obvious all the top ones use PostgreSQL, so why even have MySQL there at all

**Comment by uNetworkingAB** [comment]
The criticism has been given for many many years in far more civilised ways before. The problem with that appraoch is that nobody cares and nothing happens. Also, sensationalism sells. I have never seen any significant traffic to a civilised opinion. If you want to highlight something truly, fundamentally wrong, you need to kick the front door in and deliver the message. In my case here, it resolved itself as someone else can add it back now.

I don't even want to be in the test (because it is a nonsense test by incompetent people who don't understand how things work, for many reasons) - but that test is a necessary evil since most people use it for reference. So it's a de facto test you have to be in, regardless how poor its quality is.

This quote is pretty much spot on:

> The critiques I've seen - I think - all seemed valid. Could it be that Alex might already have a negative stance because his time is also wasted by people clamouring about his project not being represented here, and how sub-par projects are faster than his and only float to the top by employing bad tactics and incomplete implementations?

In an ideal world, people would verify benchmarks themselves. But people rather see to authority to tell them what is true and what is false. I don't want any centralized source be the authority, but that people critically compare things themselves. But this is not how most peolpe work.

**Comment by uNetworkingAB** [comment]
They could easily design a test that is impossible to cheat in, like this test:

https://github.com/SaltyAom/bun-http-framework-benchmark?tab=readme-ov-file#bun-http-framework-benchmark

By requiring the extraction of certain headers, queries and so on, you automatically weed out all the hardcoded cheats. But this far, they couldn't think. Because again, they don't understand what they are doing. They are typical "hardware geeks" that only think in terms of "oh wow, this server hardware is so beefy, we need it now".

Had they used their head, thought about the basics, they could have automatically weeded out all the fakes by just designing the test slighty more complex like linked. And all those steps are entirely web server related.

This is the difference between a smart person and a stupid moron who only buys expensive hardware because it is cool.

**Comment by uNetworkingAB** [comment]
So, nobody added it back?

**Comment by porsager** [comment]
Done ;) https://github.com/TechEmpower/FrameworkBenchmarks/pull/9189

Got delayed because I Wanted to make it run myself too first but that was unfortunately not as straight forward as it could have been.

**Comment by uNetworkingAB** [comment]
Ok. Thanks, guess that puts an end to this thing

**Comment by uNetworkingAB** [comment]
Aha, vacation. Pfft, no time for vacation

**Comment by porsager** [comment]
Sure thing: https://github.com/TechEmpower/FrameworkBenchmarks/pull/9194

**Comment by uNetworkingAB** [comment]
@porsager aha, it is uWebSockets._cfg

**Comment by porsager** [comment]
Already changed it ;)

**Comment by uNetworkingAB** [comment]
It needs to be `uWebSockets._cfg` can't be `webserver._cfg`

**Comment by porsager** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/pull/9194/commits/389ed041de728ae9448d7092249137fb548291ba ;)
