### ISSUE TITLE
ws.getRemoteAddressAsText() always reads 0.0.0.1 behind nginx proxy_pass

### ISSUE THREAD

**Issue by antonymott** [uNetworking/uWebSockets.js#1088]
I'm using uWebSockets.js behind nginx proxy_pass with:
```
proxy_set_header X-Real-IP $remote_addr;
```
in the nginx server block. I'm guessing the issue is with nginx.conf as the uWebSockets app works great, except I cannot access actual visitor $remote_addr in uWebSocket.js:

Here's my uWebSockets.js code:
```
...
open: (ws: uWS.WebSocket<unknown>) => {
    // helper
    function arrayBufferToString(buffer) {
        return decoderUtf8.decode(new Uint8Array(buffer))
    }
    const remoteAddr = ws.getRemoteAddressAsText()
    const ip = arrayBufferToString(remoteAddr)
    console.log('original IP: ', ip)
...

```
outputs one of:
    "0000:0000:0000:0000:0000:ffff:7f00:0001"
    "0000:0000:0000:0000:0000:0000:0000:0001"
    "0.0.0.1"

**Steps I've taken to solve**
Searched other questions and threads on this forum and StackExchange, which led me to add extra proxy_set_header in my nginx.conf file. nginx access.log shows $remote_addr with correct value. Here's nginx.conf:

```
map $http_upgrade $connection_upgrade {
	default upgrade;
	#'' close;
}

upstream websocket {
	server localhost:4000;
}

server {
	listen 8443 ssl;
	
	location / {
		proxy_pass http://websocket;
                proxy_http_version 1.1;

                # set request headers upstream
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_set_header Host $host;
		proxy_connect_timeout 300;
		proxy_send_timeout 300;
   		proxy_read_timeout 300;
		proxy_socket_keepalive on;
                proxy_set_header X-Real-IP $remote_addr;
        
                # tried various things from other questions in uWebSocket forum and stackexchange 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $remote_addr;
                proxy_set_header X-Forwarded_Port $remote_port;
	}
}
```

**Comment by e3dio** [comment]
Get the `X-Real-IP` header in the `upgrade` ws event and attach that IP to your ws data [Upgrade.js#L21](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Upgrade.js#L21)

**Comment by antonymott** [comment]
Thanks @e3dio:
I did look at Upgrade.js in the examples, but assumed upgrade.js example was only if I did nginx proxy_pass but without nginx requesting the upgrade...anyway I added the .upgrade section to my nodejs code, and for the time being kept identical my nginx.conf as above, but no output to that header.

I'm clearly not requesting the X-Real-IP header in the correct way, or perhaps I need to attach it before I leave .upgrade, but as upgrade event only accepts 5 arguments and all are used in the example, I assumed I have to getHeader in the first object. upgrade.js doesn't include an example of retrieving common header names like x-real-ip or x-forwarded-for. Here is what I tried, no errors but blank output for ws.xRealIp in open() event:
```
upgrade: (res, req, context) => {
      res.upgrade(
        // upgrade to websocket
        {
          myData: req.getUrl(), /* First argument is UserData (see WebSocket.getUserData()) */
          xRealIp: req.getHeader('x-real-ip'),
          ip: res.getRemoteAddressAsText(),
        }, // 1st argument sets which properties to pass to ws object, in this case ip address
        req.getHeader('sec-websocket-key'),
        req.getHeader('sec-websocket-protocol'),
        req.getHeader('sec-websocket-extensions'), // 3 headers are used to setup websocket
        context // also used to setup websocket
      )
    },
    open: (ws: uWS.WebSocket<unknown>) => {
      const funcName = ' .App().ws/chat:open'
      function arrayBufferToString(buffer) {
        return decoderUtf8.decode(new Uint8Array(buffer))
      }

      console.log('ws.xRealIp:', ws.xRealIp) // outputs blank
      console.log('ws.xRealIp:', arrayBufferToString(ws.xRealIp)) // outputs blank
      
      const remoteAddr = ws.getRemoteAddressAsText()
      const ip = arrayBufferToString(remoteAddr)
      console.log('original IP: ', ip) // outputs 0.0.0.1 or similar
```

**Comment by e3dio** [comment]
> Is there a reason ws.getRemoteAddressAsText() doesn't show the x-real-ip header?

`ws.getRemoteAddressAsText()` shows IP of your nginx server, because that is what is connecting to your Node server. The remote IP address of client connected to your nginx is passed in the `X-Real-IP` header

**Comment by antonymott** [comment]
@e3dio thanks. I see you are a main contributor, thanks again for being part of an outstanding project. Would it help other users do you think if i updated upgrade.js, through a pull request, to include these header retrievals, or do you think this thread is good enough and I'll mark it as closed?
