### ISSUE TITLE
LocalCluster from uWS

### ISSUE THREAD

**Issue by uNetworkingAB** [uNetworking/uWebSockets.js#1098]
Need to add macOS clustering like in uWS via LocalCluster

**Comment by uasan** [comment]
About memory usage for cache, will each worker have its own cache instance or will the cache be only in the main process, will requests processed by workers use a common cache?

**Comment by uNetworkingAB** [comment]
It is duplicated

**Comment by uNetworkingAB** [comment]
Big responses could possibly be shared. But not right now

**Comment by uasan** [comment]
Maybe it makes sense to store large responses in files, send the file to the socket using the `sendfile` system calls, the OS will be able to send this file to different processes and RAM will be saved.
Of course, status 304 is also very useful in this case)
