### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by NetOperatorWibby** [uNetworking/uWebSockets.js#11]
Hey there,

I saw this on Reddit last night and it looks/sounds neat. I'd like to replace socket.io with this in my fastify app but I'm not sure how to do so...the provided example uses this module itself as a server but (obviously), I already have one.

Any pointers?

**Comment by alexhultman** [comment]
It replaces both, it's not compatible with fastify or socket io. More examples will come when it's nearing a release

**Comment by NetOperatorWibby** [comment]
Ah okay, that's good to know.
