### ISSUE TITLE
Publishing security

### ISSUE THREAD

**Issue by benmccann** [uNetworking/uWebSockets.js#1106]
I wanted to share that grabbing code from GitHub is insecure because an attacker could change a tag to point at a malicious version. Would you be able to publish the package on npm? npm is immutable, so protects against such attacks

**Comment by uNetworkingAB** [comment]
I could write a 50 page book on why you're wrong, fundamentally.

But TLDR; click "fork" and refer to your fork. Then pull from this repo when you feel like updating. If you can't fast-forward then something is off, and you can easily show using Git what got messed up.

End of discussion.

**Comment by benmccann** [comment]
That does solve the security concern though is a bit burdensome. I'd hate to have to do that for every dependency. I respect your decision as it's your library, but I did want to offer that if the reason you don't publish to npm is that you want to keep it simple to release new versions then I'd be happy to figure out any of the tooling necessary to release to npm

**Comment by uNetworkingAB** [comment]
I fundamentally disagree with everything NPM stands for.

https://github.com/uNetworking/uWebSockets.js/blob/master/misc/npm.md
