### ISSUE TITLE
Attempts at a connection to websocket server hosted on AWS EC2 hang until it times out

### ISSUE THREAD

**Issue by platocrat** [uNetworking/uWebSockets.js#1109]
## Issue
I have hosted my uWebSocket server on an AWS EC2 instance at the following domain: https://schuage.com, but websocket connections timeout and never get connected.

### 1. Serving the uWebSocket server with [Caddy](https://caddyserver.com) server

Within the EC2 instance, I am serving the uWebSocket server with [Caddy](https://caddyserver.com) server.

Here is my `Caddyfile`, the configuration file for the server:

```apacheconf
https://schuage.com  {
    # WebSocket
    @ws `header({'Connection': '*Upgrade*', 'Upgrade': 'websocket'})`
    reverse_proxy @ws localhost:3001
}
```

This gives me an TLS certificate and private key file that I expose to the Docker container that I am running the uWebSocket server in.

### 2. Source of my uWebSocket server

The source of the uWebSocket simple server I am running looks like the following, with the `src/index.ts` file containing most of the websocket logic:

```ts
/* src/index.ts */
// Externals
import uWS, { 
  App, 
  WebSocket, 
  WebSocketBehavior 
} from 'uWebSockets.js'
// Locals
import { 
  PORT,
  SSL_OPTIONS,
  IDLE_TIMEOUT, 
  MAX_LIFETIME, 
  MAX_BACKPRESSURE, 
  MAX_PAYLOAD_LENGTH,
  UpdatePlayer__WebSocket, 
} from './utils'

const wsBehavior: WebSocketBehavior<any> = {
  compression: uWS.SHARED_COMPRESSOR,
  maxLifetime: MAX_LIFETIME,
  maxBackpressure: MAX_BACKPRESSURE,
  maxPayloadLength: MAX_PAYLOAD_LENGTH,
  idleTimeout: IDLE_TIMEOUT,

  open: (ws) => {
    console.log('A WebSocket connected')
    ws.subscribe('broadcast')
  },

  message: async (
    ws: WebSocket<any>,
    message: ArrayBuffer, 
    isBinary: boolean
  ): Promise<void> => {
    const msg = Buffer.from(message).toString('utf8')
    console.log(`Received message: ${msg}`)
    
    ws.publish('broadcast', msg, isBinary)
  },

  close: (
    ws: WebSocket<any>, 
    code: number, 
    message: ArrayBuffer
  ) => {
    const msg = Buffer.from(message).toString()
    console.log(`WebSocket closed with code: ${code}, message: ${ msg }`)
  }
}


const app = uWS.SSLApp(SSL_OPTIONS)
  .ws('/*', wsBehavior)
  .get('/*', (res, req) => {
    res.writeStatus('200 OK').end('WebSocket server is running')
  })
  .listen(PORT, (token: any) => {
    if (token) {
      console.log(`Server is listening on port ${PORT}`)
    } else {
      console.log('Failed to listen to port')
    }
  })
```

And here's what the `constants.ts` file looks like, which is where `src/index.ts` imports the constant values from:

```ts
/* src/utils/constants/index.ts */
export const SECONDS_PER_MINUTE = 60
export const ONE_MEGABYTE = 1 * 1024 * 1024
export const ONE_GIGABYTE = 1 * 1024 * 1024 * 1024

export const MAX_PAYLOAD_LENGTH = 128 * ONE_MEGABYTE
export const MAX_BACKPRESSURE = 1024
export const MAX_LIFETIME = 10 // minutes
export const IDLE_TIMEOUT = 3 * SECONDS_PER_MINUTE // seconds

export const PORT = 3001

const CERTIFICATES_FILE_PATH = `/tls/`
const CERT_FILE_NAME = `${ CERTIFICATES_FILE_PATH }schuage.com.crt`
const KEY_FILE_NAME = `${ CERTIFICATES_FILE_PATH }schuage.com.key`


// Read SSL/TLS certificate and private key
export const SSL_OPTIONS = {
  key_file_name: KEY_FILE_NAME,
  cert_file_name: CERT_FILE_NAME,
  // passphrase: '1234'  // Optional: Remove if no passphrase is set
}
```

### 3. Running the uWebSocket Docker container

To run the Docker container, I run the following command:

```zsh
docker run -it \
  -p 3001:3001 \
  --mount type="bind",source="/PATH/TO/CERT/schuage.com.crt",target="/tls/schuage.com.crt",readonly \
  --mount type="bind",source="/PATH/TO/KEY/schuage.com.key",target="/tls/schuage.com.key",readonly \
  <IMAGE_ID>
```

After starting the Docker container, I can see the log `Server is listening on port 3001`, indicating that the server is indeed running on port 3001.

### 4. Connecting to the websocket    

Then, I try to connect to the websocket at `wss://schuage.com:3001`.

However, whenever I try to connect to the websocket at `wss://schuage.com:3001`, using either `npx wscat -c wss://schuage.com:3001` or some browser-based websocket tester, the connection is never made and eventually the attempt times out and fails with the following error:

```zsh
error: connect ETIMEDOUT <IP_ADDRESS>:3001
```

-----

What I am I doing wrong?
I don't think there's an issue with the `SSLOptions`, since I would expect to have received an error from `uWebSockets.js` and I didn't receive one.

## Edit

I have the necessary ports (e.g. 80 for HTTP and 443 for HTTPS) open on my EC2 instance with the Security Group that is attached to it, so I am certain that I have the appropriate ports on the EC2 instance exposed for websocket connections.

Lastly, if there is an alternative method to hosting the uWebSocket on an EC2 instance that is simpler than the above implementation, then I will happily implement it.

## Edit 2

I have been banging my head against the wall with this issue for a few days now, and bothered the folks over at Caddy's community support forum on the Sept, 29th. So, I hope that I can get this issue resolved eventually.

https://caddy.community/t/where-is-the-tls-pem-certificate-and-key-on-remote-ec2-server/25815

**Comment by e3dio** [comment]
You are troubleshooting Caddy, EC2, Docker issues, not an issue with uWS.js, asking for help to get your entire stack set up is a little much I think. You seem to have basic misunderstandings of what you are doing, like Caddy terminates TLS and forwards clear traffic to local port, uWS.js does not need any cert for that. Then you try to connect to wss://schuage.com:3001 but 3001 is internal to your EC2 instance not public, you would connect to wss://schuage.com. Not the place to spam this repo for all these noob things though, probably go to a Caddy discord or something

**Comment by platocrat** [comment]
> You are troubleshooting Caddy, EC2, Docker issues, not an issue with uWS.js, asking for help to get your entire stack set up is a little much I think. You seem to have basic misunderstandings of what you are doing, like Caddy terminates TLS and forwards clear traffic to local port, uWS.js does not need any cert for that. Then you try to connect to wss://schuage.com:3001 but 3001 is internal to your EC2 instance not public, you would connect to wss://schuage.com. Not the place to spam this repo for all these noob things though, probably go to a Caddy discord or something

My entire stack is complete. The only issue I have is my setup of uWebSocket.
You inadvertently helped me, despite coming off like a condescending a******.

Removing the cert and key from `SSLOptions`  and just using `App()` instead of `SSLApp()` now results in connections being established.

**Comment by uNetworkingAB** [comment]
> Removing the cert and key from SSLOptions and just using App() instead of SSLApp() now results in connections being established.

👍

**Comment by uNetworkingAB** [comment]
> You inadvertently helped me

vs.

> You seem to have basic misunderstandings of what you are doing, like Caddy terminates TLS and forwards clear traffic to local port, uWS.js does not need any cert for that.

vs. 

> Removing the cert and key from SSLOptions and just using App() instead of SSLApp() now results in connections being established.

<img width="676" alt="Screenshot 2024-10-03 at 02 14 39" src="https://github.com/user-attachments/assets/22288926-23ee-42fd-a1a0-94420e93d58c">


No. He helped you with laser precision.

**Comment by e3dio** [comment]
Inadvertently 😄 kids these days no gratitude for anything, was just trying to help him out, I use Caddy on my server

**Comment by francislavoie** [comment]
As a Caddy maintainer, I'm shocked and disappointed at how rude both of you were @e3dio @uNetworkingAB. There was absolutely no reason to make personal attacks simply because someone is asking for help. Have some respect.

> No. He helped you with laser precision.

No, "laser precision" would include no insults. "laser precision" would've been saying only this (cutting out the rest):

> Caddy terminates TLS and forwards clear traffic to local port, uWS.js does not need any cert for that. Then you try to connect to wss://schuage.com:3001 but 3001 is internal to your EC2 instance not public, you would connect to wss://schuage.com.

**Comment by e3dio** [comment]
People get offended too easily. @francislavoie if you had done your job properly helping over [there](https://caddy.community/t/where-is-the-tls-pem-certificate-and-key-on-remote-ec2-server/25815/2) he wouldn't have needed to come over here for completely basic help

**Comment by francislavoie** [comment]
Nah, you're not gonna throw it back at me. He posted 5 hours ago, and I was away from home. You were rude _for no reason_. The user posted every bit of context you could ever need, that the dream as a maintainer and support. Calling someone a "noob" is completely uncalled for. Everyone has to learn somewhere.

**Comment by e3dio** [comment]
You had 3 days to help this poor guy who doesn't understand that Caddy terminates the TLS connection. That is literally the entire purpose of Caddy. It took me 2 seconds to read his post and tell him what the problem is. Then you come over here and blame me for something, and thumb down all my posts. Unreal.

**Comment by uNetworkingAB** [comment]
🍿

**Comment by uNetworkingAB** [comment]
> As a Caddy maintainer, I'm shocked and disappointed

Nobody cares who you are and your opinions are irrelevant.
