### ISSUE TITLE
How to implement user authorization?

### ISSUE THREAD

**Issue by caracal7** [uNetworking/uWebSockets.js#112]
How to implement reliable authorization? For example with passportJS or something like it.
And which is a proper way to manage user sessions with uWebSockets?

**Comment by Chathula** [comment]
+1

**Comment by mrlika** [comment]
It's a basic web server. It doesn't support middlewares like Passport.js. But you can implement almost everything on top of it. Read the documentation to understand how things work and go ahead!

**Comment by caracal7** [comment]
@mrlika 
I understand that it is a basic web server). And I implemented very simple authentication but I'm looking for the best practices and close to real world examples.
For now I simply send message from client with login/password after WebSocket opened and set `ws.logged = 'mylogin'` on server.
But something tell me that it is not a very safe and secure way)

**Comment by mrlika** [comment]
I don't think that the best practiced are related to this project. They are related to HTTP protocol in general.

**Comment by caracal7** [comment]
One more question is how can I share session ID between .ws() and other endpoints?

‘’’
UWebSockets.App({})
    .ws('/*', {
        compression: 0,
        maxPayloadLength: 16 * 1024 * 1024,
        idleTimeout: 10,
        open: (ws, req) => {
            ws.uuid = uniqueID();
        }
     })
    .get('/myroute', (res, req) => {
        // uuid ???????    <=======================
    })
    .listen(port, token => {});
‘’’

**Comment by mrlika** [comment]
I think that the cookies are the way to go:
https://devcenter.heroku.com/articles/websocket-security#authentication-authorization

**Comment by alexhultman** [comment]
https://m.youtube.com/watch?v=OP30okjpCko

Best practise right there :)

**Comment by girng** [comment]
> https://m.youtube.com/watch?v=OP30okjpCko
> 
> Best practise right there :)
😂😂🤣

**Comment by lagden** [comment]
@caracal7 and @Chathula 

Use cookie (`HttpOnly`)

```js
const {App} = require('uWebSockets.js')
const cookie = require('cookie')

const app = App()
app
  .ws('/*', {
    upgrade(res, req, context) {
      const _cookie = cookie.parse(req.getHeader('cookie'))
      // validate the cookie somehow
      // and set _logged true or false
      let _logged = true

      res.upgrade(
        {_logged},
        req.getHeader('sec-websocket-key'),
        req.getHeader('sec-websocket-protocol'),
        req.getHeader('sec-websocket-extensions'),
        context
      )
    },
    open(ws) {
      // disconnect if not logged
      if (!ws._logged) {
        ws.end()
        console.log('unauthorized', 'https://m.youtube.com/watch?v=OP30okjpCko')
        return
      }
    }
    // ...more code
  })
  .any('/*', (res, req) => {
    // set cookie
    res.writeHeader('Set-Cookie', '_token=jwt; SameSite=Strict; HttpOnly')
    res.end('cookie sample')
  })
  .listen('::', 3132, token => {
    console.info(token)
  })
```

**Comment by hst-m** [comment]
@lagden the point of the upgrade handler is to deny the request before the socket opens so you would want to update that

here is what I use for that, you will want to be using cookies with Secure, HttpOnly, and SameSite either Lax or Strict (probably will need both) and I use [JsonWebTokens ](https://www.npmjs.com/package/jsonwebtoken) because you can sign the cookies with a secret and store json 
```javascript
app.ws('/',{
   upgrade:(res,req,context)=>{
      try{var user=decodeJwtCookie(req,'cookieName').user;if(user.type!='type1')throw 1}
      catch{return res.writeStatus('401').end()}
      res.upgrade({uid:user._id},req.getHeader('sec-websocket-key'),req.getHeader('sec-websocket-protocol'),req.getHeader('sec-websocket-extensions'),context)
   },
   open:ws=>{console.log('open-ws',ws.uid)}
})

const cookieRegexObj={}
const cookieRegex=name=>cookieRegexObj[name]||(cookieRegexObj[name]=new RegExp(`(^| )${name}=([^;]+)`))
const getCookie=(req,name,cookies)=>(cookies||req.getHeader('cookie')).match(cookieRegex(name))?.[2]
const decodeJwtCookie=(req,name,cookies)=>require('jsonwebtoken').verify(getCookie(req,name,cookies),env.jwtSecret)
```

`decodeJwtCookie` throws an error if the cookie was not signed with the correct secret, and also if `user.type != type1` here it prevents the socket from opening with `res.writeStatus('401').end()`
