### ISSUE TITLE
Issue with snake_case Header Keys in extraHeaders Causing WebSocket Upgrade Failure

### ISSUE THREAD

**Issue by iakuf** [uNetworking/uWebSockets.js#1127]
I have encountered an issue while establishing WebSocket connections using the uWebSockets.js library. Specifically, when I attempt to use snake_case style keys (e.g., "device_id") in the extraHeaders configuration object, it results in a failure of the HTTP upgrade request to WebSocket.

Here is an example of my configuration:
```js
const socket1 = io(url, {
    extraHeaders: {
        "device_id": deviceRoom,
        // other header information...
    },
    connectionStateRecovery: {},
    reconnectionDelayMax: 10000,
    query: "debug=1" // enable debug mode
});
```
In this case, the WebSocket upgrade request fails. However, if I change the key name to kebab-case style, such as "device-id", everything works as expected.

I believe this might be a bug that needs fixing, as according to HTTP specifications, header keys are case-insensitive and typically allow kebab-case style. If possible, please investigate this issue and consider supporting snake_case style keys.

**Comment by uNetworkingAB** [comment]
It is supported. No idea what software you are running

**Comment by uNetworkingAB** [comment]
Snake_case is supported.
