### ISSUE TITLE
Latest 20.50  not working with pervious code?

### ISSUE THREAD

**Issue by aleksraiden** [uNetworking/uWebSockets.js#1141]
After update to latest v20.50 my old code not working.  All handlers not calling, and server returns: 

`
App.get('/api/v1/test', (res) => {
	return res.end('OK');
});

curl http://127.0.0.1:999/api/v1/test
< html >< body >< h1 >File Not Found< /h1 >< hr >< i >uWebSockets/20 Server< /i >< /body >< /html >
`
What's I doing wrong? 

If add any number at 3-th argument: 
`App.get('/api/v1/test', (res) => {
	return res.end('OK');
}, 5);

We have in stdout:

Registering cached get handler
`

But any calling return an error: Error: Returning from a request handler without responding or attaching an abort handler is forbidden! Any code, like this (worked in early versions) not work now: 
`
res.onAborted(() => { res.aborted = true; }); //Work on early, now not working

`

**Comment by uNetworkingAB** [comment]
Is fixed in next release 👍
