### ISSUE TITLE
Is it possible to manually route requests between workers

### ISSUE THREAD

**Issue by Mytrill** [uNetworking/uWebSockets.js#1143]
I am trying to build a game server which communicates with clients via websockets.
My idea was that I would have 1 nodejs instance with multiple worker threads that each handle one or more game (communication with clients + game logic).
As such, the worker thread that handles messages for a websocket should be the same worker that runs the game this player is currently connected to.

From what I gather from the docs, the uws.js distributes connections in a round-robin fashion, so I have no guarantee that I will receive messages for a client in the same thread as their game they are playing.

I tried creating different routes for each worker and connecting to these, but it doesn't seem to be working:
```
App().ws<WsUserData>("/" + workerIndex, { ... }).listen(...)
```

Only one of the route is actually working.

Is there a solution for me here so that I don't have to pass messages between sockets worker threads and game worker threads?

should I have multiple node instances instead of worker thread? With each instance managing it's own socket API & games?
In which case, how can I use the same port/SSL certificate on each instance? Do I have to use nginx?

Thank you for your help!

**Comment by uNetworkingAB** [comment]
Either you listen to a different port for each game, rather than having a
different url, or you have two servers; one that holds ip:port to all
instances and return with 304, so a two step connection.

Den tors 12 dec. 2024 18:05Anthony Ferrando ***@***.***>
skrev:

**Comment by Mytrill** [comment]
Oh yes of course, this is brilliant!
Thank you!

**Comment by uNetworkingAB** [comment]
304 is not correct should be 301 or something. Http moved

Den tors 12 dec. 2024 18:35Anthony Ferrando ***@***.***>
skrev:
