### ISSUE TITLE
req.getQuery() return ? sign

### ISSUE THREAD

**Issue by kng83** [uNetworking/uWebSockets.js#117]
### req.getQuery() return ? sign
In index.d.ts is written that HttpRequest.getQuery() :
/** Returns the part of URL after ? sign or empty string. */
but when I try something like localhost:9001/id?cat=1&dog=2
I get  ?cat=1&dog=2.
This is not big problem but when I use popular node  library like qs 
I get something like this:
{ '?cat': '1', dog: '2' }

Example:
.get('/id', (res, req) => {
  console.log(req.getQuery()) // ?cat=1&dog=2.
  console.log(qs.parse(req.getQuery())) //{ '?cat': '1', dog: '2' }
  res.end('');
})

Suggestion : change docs or change behavior
I use windows 7; 
node v10.15.3;
"uWebSockets.js": "github:uNetworking/uWebSockets.js#v15.8.0"

**Comment by alexhultman** [comment]
It makes sense to follow the docs

**Comment by zbot473** [comment]
Then change the docs lmao

**Comment by alexhultman** [comment]
> Suggestion : change docs or change behavior

It makes sense [for this project] to follow the docs.

**Comment by zbot473** [comment]
Ok, I didn't understand what you meant

**Comment by xiaomoer** [comment]
just remove the "?"
