### ISSUE TITLE
Disable IdleTimeout or create system PING\PONG

### ISSUE THREAD

**Issue by Koldunz** [uNetworking/uWebSockets.js#119]
I use v15.9.0

Tell me how to disable automatic connection disconnection( disable idleTimeout ) or how to send system ping \ pong from server to clients using OpCode 0x9 [PING] and 0xA [PONG]

If the opportunity to implement events ping\pong?
`uWS.App().ws('/*', {
    ping: (ws) => {
        console.log("PING")
    },
    drain: (ws) => {
        console.log("PONG")
    }`

Thanks!

**Comment by alexhultman** [comment]
Set it to 0

**Comment by roytan883** [comment]
@alexhultman  how to send system ping \ pong from server to clients ? If the clients is mobile phone, need server sending ping and receiving pong to check clients status.  Or is there anyway to set `heartbeat timeout` ?

**Comment by alexhultman** [comment]
You can't currently. Clients send messages to the server to keep alive

**Comment by manast** [comment]
Is the idleTimeout working? setting any value including 0 still results on the connection being closed after 10 seconds.

**Comment by RussCoder** [comment]
@alexhultman Also I want to point out that currently (I'm using v15.11.0) a connection is closed even if a message was sent by the server to the client, while the [documentation](https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#idletimeout) says that the `idleTimeout` is:

> Maximum amount of seconds that may pass without **sending** or getting a message.

I suppose either the behavior should be changed or the documentation must be corrected. 

And I would like to have the ping/pong feature too.

**Comment by alexhultman** [comment]
@RussCoder You mind creating a new bug for that?

**Comment by RussCoder** [comment]
@alexhultman 
Did  it: https://github.com/uNetworking/uWebSockets.js/issues/187
