### ISSUE TITLE
I don't get Function.apply

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#12]
How can I shorten this;

```javascript
		process.nextTick = (f, ...args) => {
			if (args.length == 1) {
				uWS.nextTick(() => {f(args[0]);});
			}

			if (args.length == 2) {
				uWS.nextTick(() => {f(args[0], args[1]);});
			}

			if (args.length == 3) {
				uWS.nextTick(() => {f(args[0], args[1], args[2]);});
			}

			if (args.length == 4) {
				uWS.nextTick(() => {f(args[0], args[1], args[2], args[3]);});
			}
		}
```

So that it works, presumably with apply, bind or any such thing.  I can't get it working with apply.

**Comment by frank-dspeed** [comment]
```js
process.nextTick = (f, ...args) => {
  uWS.nextTick(() => f(...args));
}
```

**Comment by frank-dspeed** [comment]
the speard works also with arrays thats why this gets (arg1,arg2,arg3)

**Comment by frank-dspeed** [comment]
i am glad that i could help i saw your rant about NPM and i want to tell you your right it was the right way to do it i am a big fan of it !!!!! :dancer:

**Comment by frank-dspeed** [comment]
but you got that already in your code apply would look like

```js
process.nextTick = (f, ...args) => {
  uWS.nextTick(() => f.apply(this, args));
}.bind(this) // this is in this case most time the global object  of nodejs or in case of browser window
```

**Comment by frank-dspeed** [comment]
cant write all examples but if you point me to a file with some pseudo code i get it working for you with comments

**Comment by alexhultman** [comment]
This is what I had:

```js
process.nextTick = (f, ...args) => uWS.nextTick(f.apply(...args));
```

Which is obviously wrong, but worked good enough for me not to find an issue until now.

I thought this would solve it:

```js
process.nextTick = (f, ...args) => uWS.nextTick(() => {f.apply(...args);});
```

But it doesn't work..?

If this works, that's like Golang and simple:
```js
process.nextTick = (f, ...args) => {
  uWS.nextTick(() => f(...args));
}
```

**Comment by slavaGanzin** [comment]
> While the syntax of this function is almost identical to that of call(), the fundamental difference is that call() accepts an argument list, while apply() accepts a single array of arguments.

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)

Apply signature: (context, args)

So when you call f.apply(context, ars) it's same as:
```
f.call(context, ...args)
```
and
```
f.bind(context)(...args)
```

But if you don't need context setting (set internal ```this``` of function), you can just use splat syntax:
```
f(...args)
```

Hope this helps

**Comment by alexhultman** [comment]
Yeah it helped, it works now at least. Thanks

**Comment by slavaGanzin** [comment]
You're welcome. Thank you for UWS

**Comment by frank-dspeed** [comment]
@alexhultman the code is wrong apply works directly with arrays

don't use spread 3 dot operator when using apply it expects a array as secund argument
```js
f.call(context, args)
```
