### ISSUE TITLE
Add arm64 builds

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#120]

**Comment by alexhultman** [comment]
Untested arm64 build for Node.js 10 and 11:

[uws_linux_arm64.zip](https://github.com/uNetworking/uWebSockets.js/files/3051134/uws_linux_arm64.zip)

**Comment by alexhultman** [comment]
Filenames will have to incorporate process.arch; arm64 for arm, x64 for intel:

uws_linux_arm64_67.node
uws_darwin_x64_67.node

etc

**Comment by alexhultman** [comment]
I tried scaleway ARMv8 instances, but their web UI just doesn't work. It completely bugs out creating instances and won't work. Intel instances it created with no issues.

Does anyone have ARM instances to test this on? Where can I find a competent ARM supplier?

**Comment by devcat** [comment]
Try their CLI to make a instance

**Comment by haluwen9** [comment]
Hi, 
I had tried this build on my Raspberry Pi 3B+ and I got this Error
```
/home/pi/CCTVRobot/node_modules/uWebSockets.js/uws.js:34
throw new Error('This version of µWS is not compatible with your Node.js build.\n\n' + e.toStri ng());
Error: This version of µWS is not compatible with your Node.js build.
Error: /home/pi/CCTVRobot/node_modules/uWebSockets.js/uws_linux_arm64_64.node: wrong ELF class: ELFCLASS64
          at module.exports (/home/pi/CCTVRobot/node_modules/uWebSockets.js/uws.js:34:9)
          at Object. (/home/pi/CCTVRobot/node_modules/uWebSockets.js/uws.js:36:3)
          at Module._compile (internal/modules/cjs/loader.js:701:30)    
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) 
          at Module.load (internal/modules/cjs/loader.js:600:32) 
          at tryModuleLoad (internal/modules/cjs/loader.js:539:12) 
          at Function.Module._load (internal/modules/cjs/loader.js:531:3) 
          at Module.require (internal/modules/cjs/loader.js:637:17)
          at require (internal/modules/cjs/helpers.js:22:18)      
          at Object. (/home/pi/CCTVRobot/app.js:4:13)
```

I'm using NodeJS version 
v10.15.3

Can you help me with this?

**Comment by alexhultman** [comment]
I just tested these binaries on a scaleway arm64 instance and it works right away without issues.

@haluwen9 You probably run 32 bit OS or something, it works for me

**Comment by alexhultman** [comment]
These cost efficient ARM instances are a perfect example of why perf. matters.

alexhultman@alexhultman-N56VZ:~/wrk$ ./wrk -c 500 http://51.158.111.36/
Running 10s test @ http://51.158.111.36/
  2 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    62.19ms   39.30ms **840.22ms**   98.72%
    Req/Sec     4.21k   594.70     4.99k    75.76%
  83108 requests in 10.03s, 5.63MB read
Requests/sec:   **8284.11**
Transfer/sec:    574.39KB

alexhultman@alexhultman-N56VZ:~/wrk$ ./wrk -c 500 http://51.158.111.36/
Running 10s test @ http://51.158.111.36/
  2 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   461.59ms  155.41ms   **1.50s**    92.03%
    Req/Sec   496.96    151.68   790.00     75.51%
  9729 requests in 10.04s, 0.96MB read
  Socket errors: connect 0, read 0, write 0, timeout 183
Requests/sec:    **969.51**
Transfer/sec:     98.47KB

A whopping **9x** difference compared to Node.js vanilla, and I'm stressing this Sweden to France.

**Comment by haluwen9** [comment]
@alexhultman Thanks for reply. 
It's true that my Raspberry Pi is running on 32bit OS. I'm trying to compile 64bit kernel for it and try again.

**Comment by alexhultman** [comment]
ARM64 builds are now automatic
