### ISSUE TITLE
resource temporary unavailable

### ISSUE THREAD

**Issue by orefalo** [uNetworking/uWebSockets.js#130]
Hi, recently did some benchmark to test apollo-server-uwebsockets.

During testing, I am getting 
```
iled                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0013] Request Failed                                error="Post http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"

    ✗ It returns HelloWorld
     ↳  97% — ✓ 16381 / ✗ 451
    ✗ Status was 200
     ↳  97% — ✓ 16381 / ✗ 451
```

I simplified the test to isolate the issue. It seems to be coming from UWS

to reproduce:

1. check out https://github.com/orefalo/apollo-server
2. switch to branch integration-uwebsockets
3. cd to apollo-server/packages/apollo-server-uwebsockets/test
4. run `yarn`
5. install k6 - `brew install k6`
6. in one window - start the uwn hello world - `node index_rawuws.js`
7. in the other, start the load test - `k6 run k6benchraw.js`

Error will show

I must point that it works perfectly well with express.js

**Comment by orefalo** [comment]
seems to be a rate per seconds issue.
when I tell k6 to limit rate say 500tps it works fine, however 800 will fail.

Express seems to have a protection built in.

**Comment by alexhultman** [comment]
Hello,

This is not a valid bug report - I don't know where to start, what the issue is, if there is an issue, where the issue is, etc.

**Comment by alexhultman** [comment]
I'm like 90% sure this is your k6 benchmark just spamming open a lot of connections -> it doesn't seem to keep them alive and reuse them. That's a client problem not a server problem. Use a better benchmarking client that actually reuse the connections it already has open. All modern web browsers will reuse open connections, that's the entire idea with keep-alive.

**Comment by orefalo** [comment]
correct, it's actually a setting in k6. I formally requested the clients not to reuse connections in order to stress test the implementation.

Why are you saying that is it not a bug? and if then, how come express handles it just fine?

**Comment by orefalo** [comment]
"All modern web browsers will reuse open connections, that's the entire idea with keep-alive."

agreed, however IMHO the test does show that the implementation has a flaw handling large number of connections.

**Comment by orefalo** [comment]
Basic UWS Server -> https://github.com/orefalo/apollo-server/blob/integration-uwebsockets/packages/apollo-server-uwebsockets/test/index_rawuws.js

K6 test -> https://github.com/orefalo/apollo-server/blob/integration-uwebsockets/packages/apollo-server-uwebsockets/test/k6benchraw.js

**Comment by alexhultman** [comment]
This is a quite common question by now. It's not an issue, is just that this server assumes the client will be doing keep alive. It does not listen to connection close. You can do that by yourself if you really want to.

If header connection is close then res.close

**Comment by alexhultman** [comment]
if (req.getHeader('connection').length == 5) res.close();

**Comment by alexhultman** [comment]
#114

**Comment by orefalo** [comment]
Good morning Alex,

My 2c,

So I took the time to create a separate project.  https://github.com/orefalo/test-http-benchmarks

In it, I have dummy servers built with:

* express -> standard node network stack
* polka ->  standard node network stack
* turbo-http -> turbo-net custom network stack
* uws ->  custom network stack

I also built two different k6 scripts simulating the load from 50 users:

1. one that formally **forbids the reuse of connection**
2. one that allows it, per connection and even virtual user

Here are my findings:

* All the implementations build on the standard node network stack work as expected.
* All custom socket implementation FAIL unless k6 is configured with a rate limiter (rps: 500)

What this means from a black box regression testing is that all custom socket implementations **do not carry capabilities to throttle maximum resource capacity**.
They probably simply drop the connection attempt, when they should queue.

Besides performance... I see this as a huge limitation.

What's your thoughts.

PS: I read #114 ; I believe it's different

**Comment by alexhultman** [comment]
Can you dump all headers k6 is sending?

**Comment by orefalo** [comment]
there is an option in the code, it's commented out . // httpDebug: "full"

Log all HTTP requests and responses. Excludes body by default, to include body use '--http-debug=full'

```

Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Request:
POST^Cncoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

0


Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
Request:
POST / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Transfer-Encoding: chunked
Content-Type: application/json
Accept-Encoding: gzip

```

**Comment by alexhultman** [comment]
Transfer-Encoding: chunked is not supported. So any reuse of that connection will fail. It's the same general "issue" as for 114.

**Comment by orefalo** [comment]
I see.

It fails both ways anyways - reuse or not.

**Comment by alexhultman** [comment]
Reuse fails because chunked is not understood, non reuse fails for the same reasons in 114.

**Comment by alexhultman** [comment]
I have added an issue regarding parsing chunked bodies

**Comment by orefalo** [comment]
I'll update my tests to use get in order to validate ;-)

Also... If I recall you have a file example - will have to see how you make it happen without chunked data.

**Comment by orefalo** [comment]
FYI, I am getting the very same issue with a GET.

This is for the noREUSE test - where I am stressing connections on the implementation

```
Request:
GET / HTTP/1.1
Host: localhost:9001
User-Agent: k6/0.24.0 (https://k6.io/)
Accept-Encoding: gzip

Response:
HTTP/1.1 200 OK
Content-Length: 12
Uwebsockets: v0.15

Hello World!
```

```
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
WARN[0018] Request Failed                                error="Get http://localhost:9001: dial tcp [::1]:9001: connect: resource temporarily unavailable"
```

K6 has two settings
// you can enable connection reuse
  noConnectionReuse: false,
// and you can even specify if those can be reused across clients
  noVUConnectionReuse: true,

When reuse is turned on across the board - the test passes.
However it's also not as realistic test - as all client share a limited sets of connections.

So I tried to mimic the reality - 50 clients reusing connections
Unfortunately same result. resource unavailable.


Can you detect the error in the C++ code?
 In which case it should be easy to implement a rate limiter on your side.

**Comment by orefalo** [comment]
You may want to reopen this ticket as an issue.. ;-/

**Comment by alexhultman** [comment]
What exactly is the issue you want to report? I don't see any issue here? Rate limit? How? This is not an issue with the server?

**Comment by alexhultman** [comment]
If this is your headers for the non reuse, they are invalid. There is no indication of them being non-keep alive. The server is doing what it should - it keeps them alive for ten seconds.

**Comment by orefalo** [comment]
You don't see the issue?   RACE_CONDITION: Too many connections - Express handles it just fine, UWS doesn't

It's pretty common for libraries to show problems when they are put under edge cases.

* It's not that the implementation is not doing what it should - it's more about what's missing. How do you explain that the express implementation doesn't fail with the same error (under the same test)?
* I switched the implementation to use GET in order to avoid the chunked issue. As a consequence, there are no chunked headers anymore.
* Finally, as far as a starting point, I created this repo https://github.com/orefalo/test-http-benchmarks to isolate the issue. I even added a README so you can figure how to run the project. The issue shows on **every** iteration.

Unfortunately I don't have your skills when it comes to C++ (that class was a looong time ago ;-0 ). But maybe a few printf will highlight the race condition or the error that is being raised internally.

Alright I will stop here.  Thanks for your time.

Sincerely,

**Comment by alexhultman** [comment]
Where do I send my bill?

I don't have k6, I don't have yarn, I don't have brew.

You are not presenting a valid bug report - nothing of the server behavior is specified more than "it does not work, fix it". What exactly is "it"? The only kind of issue you show is what _the client_ show you.

Again, I don't know what k6 is, I don't have it, I don't care. If you can show a request sent to the server, where the behavior of the server is somehow "wrong" more than "my software I have worked for in my company does not work so I need you to fix my issues for me".

That's not how I work. I don't lift one finger regarding stuff I don't care for unless there is monetary reason for it. You're not the first one to port such issues - I have seen plenty of "I have this issue, fix it for me because I am important".

I've already explained the situation - sockets time out after 10 seconds, if you spam invalid requests you will run out of connections. Fix that with IP filters, whatever it's your issue not mine.

Going to play 17 hours of Anthem now, then sleep.

**Comment by orefalo** [comment]
I think you need some sleep Alex.

Kind regards.
