### ISSUE TITLE
Nodejs 12

### ISSUE THREAD

**Issue by Vladislavik** [uNetworking/uWebSockets.js#133]
hi, on nodejs 12 it not work:
throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
		^
Error: This version of µWS is not compatible with your Node.js build:
Error: Cannot find module './uws_linux_x64_72.node'

**Comment by alexhultman** [comment]
Works now, latest

**Comment by alexhultman** [comment]
Node.js is really going downhill by every release.

In 10 I get 127k req/sec
In 12 I get 118k req/sec

And, you guessed it, in 11 I get 121k :face_with_thermometer:

**Comment by Vladislavik** [comment]
When will be new release to work with 12?

**Comment by waghanza** [comment]
@alexhultman Thanks for boosting performance of `node`, but `uWebSockets.js` seems **NOT** to be compatible with the latest `node` release (every 12.x)

**Comment by alexhultman** [comment]
I just ran it with Node.js 12 on Linux. The issue you referenced also lists one person confirming it works on macOS wiht Node.js 12 so I don't know. Pick any of the well known Linux:es

**Comment by yovanoc** [comment]
Yeah it's working for me on linux and mac perfectly with node 12.7

**Comment by waghanza** [comment]
@alexhultman @yovanoc it works

in fact, I was using using `15.10.0` instead of `15.11.0`

**Comment by colms** [comment]
FYI. I was getting the error `This version of µWS is not compatible with your Node.js build` when using Alpine but it worked with Debian, maybe because Alpine is musl and I'm using a pre-built binary which is probably built with libc.
