### ISSUE TITLE
uWS http vs llhttp parser benchmark

### ISSUE THREAD

**Issue by Annihil** [uNetworking/uWebSockets.js#135]
Hi
> llhttp parser in Node.js 12
llhttp is a port of http_parser that improves on maintainability and benchmark results. The library claims to be faster by 116%.

Would it be possible to have llhttp vs uWS.js http parser performance comparison please?
Thank you 😊

**Comment by alexhultman** [comment]
I already covered this, then deleted my answer because the whole idea is ignorant, OT and irrelevant.

Again though, **Node.js 12 scores worse than Node.js 11**. This takes 10 seconds to check, but Node.js people never checks anything. It's all about the hype and mindless following.

The whole premise is absurd.

**Comment by alexhultman** [comment]
https://en.wikipedia.org/wiki/The_Emperor%27s_New_Clothes

**Comment by Annihil** [comment]
I think we would benefit from a clear benchmark where we have:
- NodeJS native http module
- NodeJS express
- NodeJS koa
- uWS.js
With different scenarios
- http parsing of POST request with JSON or url encoded body with various sizes
- POST + fecthing of documents in a database like MongoDB with async results
- POST + GrapqhQL -> JWT -> DB -> response

Also I wonder, since uWS.js is focused on performance, would it makes sense to have another json parser, perhaps faster than the NodeJS one, if that's even possible?

What do you think?

**Comment by alexhultman** [comment]
*cerebral hemorrhage*

**Comment by alexhultman** [comment]
I only provide rough pointers compared to vanilla Node.js - it's the big fat red button on the very front page. Impossible to miss.

Anything else is your professional responsibility and out of scope for this project.
