### ISSUE TITLE
Express.js alternative built on top of uWebSockets.js

### ISSUE THREAD

**Issue by zaiste** [uNetworking/uWebSockets.js#137]
I'm working on a high(er)-level wrapper on top of this (fantastic) project. It is a response to a few recent requests/questions I stumbled upon here to incorporate features like middlewares, static file handling or request body parsing out-of-the-box, right in uWebSockets.js - in short functionalities that usually come with Express.js.

Some of them were marked as `wontfix` (which is totally understandable). I'd like to fill in this gap with some higher level abstractions and potentially help out uWebSockets.js to keep its focus.

Also, in one of the recent issues (https://github.com/uNetworking/uWebSockets.js/issues/81) @alexhultman  said:

> This project does not compare with Express, it compares with Nodejs itself.
You are essentially moving a large part away from Nodejs by using this code.

@alexhultman  please feel free to close this issue if you think it doesn't belong here. My goal was to help out with the issues I reference below.

My project is called [Huncwot](https://github.com/huncwotjs/huncwot), it builds on top of uWebSockets.js and it provides:

1. plain JavaScript objects as abstraction for responses (inspired by [Clojure's ring](https://github.com/ring-clojure/ring))

```js
{ status: '200 OK', headers: {}, body: 'C++ rocks!' }
```

```js
app.get('/', request => {
  return { status: '200 OK', headers: {}, body: 'C++ rocks!' }
})
```

2. simpler abstraction for routes, i.e. a function that takes a `request` and
  returns a `response` (in response to https://github.com/uNetworking/uWebSockets.js/issues/45)

```js
app.get('/', request => {
   return ok({ a: 1, b: 2 })  // => returns 200 OK with application/json
})
```

3. function chaining for handlers (as discussed in #31)

```js
app.get('/path', fn1, fn2, ..., fnk, handler)  // => fn1(fn2(...fnk(handler)))
```

For example, you can validate the body of the incoming request using built-in `params` helper:

```js
app.get('/path, params({ name: { type: String, required: true }}), request => {
  return <response>
})
```

For the completeness, it needs `setYield` to be implemented in uWebSockets.js
  (cf. https://github.com/uNetworking/uWebSockets.js/issues/31#issuecomment-467939712)

4. support for async functions out-of-the-box (cf https://github.com/uNetworking/uWebSockets.js/issues/50)

5. built-in request body parser (in response to https://github.com/uNetworking/uWebSockets.js/issues/64 and https://github.com/uNetworking/uWebSockets.js/issues/70). It automatically extracts the method, headers, cookies and params (either request body, dynamic routes or query params)

```js
app.post('/path/:name', ({ params, headers, cookies })=> {
  return <response>
});
```

Using HTTPie:

```
http :5544/path/uws?person=alex a=1 b:=2
```
This returns `params` as `{ name: 'uws', person: 'alex', a: '1', b: 2 }`

6. built-in file upload (cf. https://github.com/uNetworking/uWebSockets.js/issues/106)

7. static file handling (cf. https://github.com/uNetworking/uWebSockets.js/issues/110)

My goal is to keep it tightly integrated with uWebSockets.js and adapt according to
uWebSockets.js' vision.

Also, I share a bit of similar mindset as Alex. This is an alpha project. I do it for fun. It got me even motivated enough to refresh my C++ ...after 15 years. ;) I hope you will enjoy it, but **please** use it at your own risk - it's **not** production ready. I won't be able to support you.

**Comment by rodrigooler** [comment]
@zaiste I thought it was a good idea, in my case I made an alternative based not only on express.js but also on the facilities of zeit/micro, koajs and fastify. Came up with the idea of creating @fearlessjs/fearless but is still in beta with some things not yet well defined for production. I believe we had similar ideas but in different contexts

**Comment by Annihil** [comment]
Exciting!  
I wonder how does that compare to [sifrr-server](https://github.com/sifrr/sifrr/tree/master/packages/server/sifrr-server)?

**Comment by zaiste** [comment]
@rodrigooler thanks for the kind words! Just to clarify, this project is not « based » on Express.js, it's just an alternative with a relatively different API. Your project looks similar, indeed. I've just glanced the project, but it seems you're focusing on the server-side only. De qualquer forma, otimo trabalho! :)

@Annihil it's very similar to sifrr. I prefer, however, a single package approach. Many separate, independent modules sounds good only in theory; in practice, it is difficult to manage such projects imho.

**Comment by Annihil** [comment]
Nice project! Too bad it's monolithic and comes with Vue, a back-end only package would have been awesome 😕

**Comment by zaiste** [comment]
@Annihil Here's just [the core engine](https://github.com/huncwotjs/szelmostwo) of Huncwot. I've extracted it to a separate package. 

I also plan to remove Vue.js soon, and to replace it with something like Svelte, so it *compiles* the UI to a minimal set of JavaScript instruction and there is no need to include the run-time in the app bundles.

**Comment by slavaGanzin** [comment]
@zaiste You should be careful with your dependencies. You take uWS build from scratch with speed in mind and than use a lot of proven to be slow packages like bluebird... It will mitigate sole purpose of using non standard, but fast server

**Comment by zaiste** [comment]
@slavaGanzin that's a good point! Please consider it work-in-progress. I focused on making something that works in first place; hopefully the improvement will follow. Feel free to join the venture ;)

**Comment by alexhultman** [comment]
Hello Zaiste,

This is a big post. I'm trying to dissect it:

> My goal was to help out with the issues I reference below.

> For the completeness, it needs setYield to be implemented in uWebSockets.js
(cf. #31 (comment))

setYield can definitely be wrapped up, no problem there in fact it should have been.

> support for async functions out-of-the-box (cf #50)

This is supported, see examples?

> built-in request body parser (in response to #64 and #70). It automatically extracts the method, headers, cookies and params (either request body, dynamic routes or query params)

Some parts are still missing, like receiving chunked encoded data but other than that the user should take care of whatever data you get. Json or anything, multi-part or whatever is up to the user to implement.

> built-in file upload (cf. #106)

> static file handling (cf. #110)

These are, at best, suitable as examples. File upload / serving is an abstraction over this library that is up to the user.

**Comment by aadityataparia** [comment]
> @Annihil it's very similar to sifrr. I prefer, however, a single package approach. Many separate, independent modules sounds good only in theory; in practice, it is difficult to manage such projects imho.

Just FYI, [sifrr-server](https://github.com/sifrr/sifrr/tree/master/packages/server/sifrr-server) doesn't change uws's API in any way (no middleware), it just builds functionalities you mentioned on top of it without affecting any other parts/performance. So there is not really any learning curve if you know how to use uWS.

> built-in file upload (cf. #106)
> static file handling (cf. #110)
> body parser

Also mentioning that you prefer single package approach as opposed to sifrr is not really related to this discussion IMHO, as this issue only discusses about [sifrr-server](https://github.com/sifrr/sifrr/tree/master/packages/server/sifrr-server), which is a single separate library/project/package. 

Not related to this issue, but In my experience maintaining them in one monorepo has saved me a lot of time (because of my own structure though, if I had chose to build in a different way, maybe separate repo approach could have been better)

**Comment by zaiste** [comment]
> This is a big post. I'm trying to dissect it:

I appreciate your response!

> > My goal was to help out with the issues I reference below.
> 
> > For the completeness, it needs setYield to be implemented in uWebSockets.js
> > (cf. #31 (comment))
> 
> setYield can definitely be wrapped up, no problem there in fact it should have been.

Great! I'm still in the process of revising my C++ knowledge. I hope to help out either with this or upcoming challenges.

> > support for async functions out-of-the-box (cf #50)
> 
> This is supported, see examples?

Yes, I've phrased that wrongly. My intention was to point out the easy of use from the consumer side, i.e. you can directly use either sync or async handler, without additional steps i.e. explicitly adding `onAborted` for async handlers. I'm still lacking the knowledge in this area, so maybe hiding that part isn't good idea.

> > built-in request body parser (in response to #64 and #70). It automatically extracts the method, headers, cookies and params (either request body, dynamic routes or query params)
> 
> Some parts are still missing, like receiving chunked encoded data but other than that the user should take care of whatever data you get. Json or anything, multi-part or whatever is up to the user to implement.
> > built-in file upload (cf. #106)
> > static file handling (cf. #110)
> 
> These are, at best, suitable as examples. File upload / serving is an abstraction over this library that is up to the user.

Yes, I'd also prefer to keep uWebSockets as simple as possible here. I've decided to wrap by default for additional convenience to the end-users.

By the way, is there a particular reason why `onData` (which provides the incoming data) is on the response, and not the request parameter ?

**Comment by Annihil** [comment]
> By the way, is there a particular reason why onData (which provides the incoming data) is on the response, and not the request parameter ?

I was indeed wondering the same 😄 

I do believe we need a decent wrapper to ease the use of uWS.js, for now it's mostly a replacement of the `http` module + a basic router without middleware (this is not reproach, just a fact, I find uWS awesome).   

In the meantime, since GraphQL popularity is rising, I went ahead and created [µGQL](https://github.com/Annihil/ugql), a very basic replacement of [express-graphql](https://github.com/graphql/express-graphql) but using uWS.js.
It works great and is ridiculously fast!

**Comment by aadityataparia** [comment]
@Annihil https://github.com/sifrr/sifrr/tree/master/packages/server/sifrr-server#graphql-server 😂

**Comment by Annihil** [comment]
@aadityataparia yes I'm fully aware of that!
I'm planning to focus only on GraphQL, replicating express-graphql by adding support to graphiql, accepting query from GET query-string, other body formats (`application/x-www-form-urlencoded`, 
`application/graphq`), etc 🙂

**Comment by aadityataparia** [comment]
@Annihil Sounds awesome, I will try to contribute some improvements too :) 🚀

**Comment by arputcu** [comment]
how would it be possible to implement gzip compression for the http/https response ?

**Comment by aadityataparia** [comment]
@arputcu you can use zlib to compress, see https://nodejs.org/api/zlib.html#zlib_zlib_gzip_buffer_options_callback

**Comment by dalisoft** [comment]
@Annihil I also few days ago made [own GraphQL Server](https://github.com/dalisoft/graphql-dev-env) based powered by uWebSockets.js with GraphiQL, Mutation, Variables support. But i trying to make `subscription` work, are you find solution or your solution offers only for Query/Mutation?

**Comment by Annihil** [comment]
@dalisoft I haven't looked at it yet, seems a bit challenging indeed.
Yes for now it's just a port of graphql-express.

**Comment by dalisoft** [comment]
@Annihil Oh, i built it for my own needs, not for challenging. Who needs, uses as yours.
Performance of uWebSockets.js is crazy, very crazy =)

**Comment by dalisoft** [comment]
I also built own Express.js alternative and made API very similar to Express.js. You can see my library [here](https://github.com/dalisoft/nanoexpress)
