### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by yovanoc** [uNetworking/uWebSockets.js#140]
Hello, I'm using uWebSockets.js along with a Protobuf protocol for a production project. It's really amazing! But is there a way to broadcast data to all currently connected clients out of the box? or the best way to do it, thanks

**Comment by Kamil93** [comment]
If uWebsocket.js doesn't collect all connections in array or set, you should do it yourself and then, by iterating through this array send message to each of stored connection. It's how broadcasting works.

**Comment by yovanoc** [comment]
Yes I tried that but the « ws » in the close event is just an empty object so I don’t know how to keep track and correctly remove clients when they disconnects

**Comment by dbl0null** [comment]
might be related: https://github.com/uNetworking/uWebSockets/issues/875
https://github.com/uNetworking/uWebSockets.js/issues/57
https://github.com/uNetworking/uWebSockets/issues/790

**Comment by yovanoc** [comment]
Yes with pubsub we can do something like broadcasting but what if we want to keep track of connected users and when they disconnect to keep these events?

**Comment by Kamil93** [comment]
It's kind of weird that we can only publish by ws object, when it shouldn't be related. Publishing should be a thing of app.

https://github.com/uNetworking/uWebSockets.js/blob/master/examples/PubSub.js

backing to question: ws should be undefined when close event occurs, it has to be bug I guess

**Comment by dbl0null** [comment]
also there's currently no way to do "frame-once/send-many" (discussed somewhere in https://github.com/uNetworking/uWebSockets/issues)

so only thing we can do for now is to track active connections manually
personally i'm using two Sets: one for "active" connections, and one for "idle" connections
so emulating broadcast (pub/sub with url client connected to as group name) would be like:

```
const bufferToString = buf => new Uint8Array(buf).join('.')
const getIpAddress = (res, req) => (req && req.getHeader('x-forwarded-for')) || bufferToString(res.getRemoteAddress())

const main = uws.App({})

const clients = new Set()
const idle = new Set()

main.ws('*', {
  compression: 0,
  maxPayloadLength: 1e6,
  idleTimeout: 0,
  open: (client, req) => {
    client.endpoint = req.getUrl()
    client.ip = getIpAddress(client, req)
    clients.add(client)
  },
  message: (source, message) => {
    clients.forEach(source.endpoint, client => {
      if (!client.send(message, true, false)) {
        clients.delete(client)
        idle.add(client)
      }
    })
  },
  drain: client => {
    // actually it's better to check bufferedAmount here
    clients.add(client)
    idle.delete(client)
  },
  close: client => {
    clients.delete(client)
    idle.delete(client)
  }
})```

it works 
you know "waaay better than enything available out there"

**Comment by yovanoc** [comment]
@Kamil93 It's not undefined but look

<img width="640" alt="Capture d’écran 2019-05-10 à 11 35 17" src="https://user-images.githubusercontent.com/7302317/57517726-c8b11000-7317-11e9-9ce7-854d8ed247bb.png">
![Capture d’écran 2019-05-10 à 11 35 31](https://user-images.githubusercontent.com/7302317/57517727-c8b11000-7317-11e9-8c2a-9342ad866a0f.png)

**Comment by Kamil93** [comment]
@yovanoc show sth more, bit of code that displays it?

**Comment by yovanoc** [comment]
I've put the console.log in the second screen? what do you mean by "more code" ?

**Comment by dbl0null** [comment]
@yovanoc yes, you can not call any **ws** method, but it is same **ws** object you've received in **.open** handler7 so you can track it

**Comment by Kamil93** [comment]
@yovanoc nvm, I saw there 1 screen, now are 2

**Comment by yovanoc** [comment]
<img width="621" alt="Capture d’écran 2019-05-10 à 11 40 56" src="https://user-images.githubusercontent.com/7302317/57518097-96ec7900-7318-11e9-874e-41ae27ee3760.png">
<img width="621" alt="Capture d’écran 2019-05-10 à 11 41 01" src="https://user-images.githubusercontent.com/7302317/57518098-96ec7900-7318-11e9-9825-4091c1647280.png">

@dbl0null Oh yes I know what you mean now, I will try that

**Comment by yovanoc** [comment]
@dbl0null Your custom forEach is to broadcast to all users connected to the same endpoint?

**Comment by Kamil93** [comment]
@yovanoc 

Just use:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/forEach

**Comment by dbl0null** [comment]
@yovanoc
> forEach
drop-in replacement would be:
```    
    clients.forEach(client => {
      if (source.endpoint === client.endpoint) {
        if (!client.send(message, true, false)) {
          clients.delete(client)
          idle.add(client)
        }
      }
    })
```

*will update previous message

**Comment by alexhultman** [comment]
Broadcasting with a loop is the "bubble sort" solution, it works but is the least efficient way. The built in pub sub support, still unfinished, will be the way to go.

**Comment by coder456** [comment]
How much of a performance increase will there be? currently I do
```
open:(ws,req)=> {ws.id = ++socketCount; allSockets[ws.id] = ws},
close:(ws,req)=> {delete allSockets[ws.id]}
// broadcast to all
for(let s in allSockets) allSockets[s].send(message)
```
