### ISSUE TITLE
Upgrading http to ws

### ISSUE THREAD

**Issue by Kamil93** [uNetworking/uWebSockets.js#141]
Does uWebsocket.js supports upgrading from http socket to websocket **manually**?

**Comment by alexhultman** [comment]
No, why?

**Comment by Kamil93** [comment]
I'd like to use uWebsockets.js as replacement in engine.io and that feature would be handy for it.

**Comment by Sceat** [comment]
It is actually useful to deny clients before upgrading (ex: auth)

**Comment by alexhultman-2fa** [comment]
Yes that is a feature being worked on. But in any case you shouldn't use Engine.io it makes no sense

**Comment by Sceat** [comment]
Should this issue be reopened ? for the Upgrading part 
*(as indeed engine.io stuff is totally unrelated)*

I would actually use uWs instead of ws when this land

**Comment by alexhultman** [comment]
There is an open issue in the main repo
