### ISSUE TITLE
In need of getNamedParameters()

### ISSUE THREAD

**Issue by Tayo-00** [uNetworking/uWebSockets.js#144]
A way to get the parameter names in the url would be nice.

Where a url would be `/users/:id` or `/items/:code/:location`.
This would result in possibly an array like `['id']` or `['code', 'location']` respectively, or could return an object with the named parameter as key and the values.

Would this be possible?
Thanks in advance!

**Comment by alexhultman** [comment]
This is already documented

**Comment by arpu** [comment]
i only can find this
https://unetworking.github.io/uWebSockets.js/generated/interfaces/httprequest.html#getparameter

with the index

**Comment by arpu** [comment]
yes, i only want to clarify this for @Tayo-00  and there is no getNamedParameters()

**Comment by Tayo-00** [comment]
I know I can access the query parameters using an index. I need the parameter names though.

**Comment by arpu** [comment]
yes its @alexhultman  dissension if he wants to implement this or not

**Comment by alexhultman** [comment]
> I need the parameter names though.

Use an enum then. req->getParameter(ID). Lookup by string is algorithmically inferior and will not be implemented.

**Comment by Tayo-00** [comment]
Alright, how about the other option? Returning just the strings themselves? Lookup by string was a suggestion and I can understand why that'd be a no-go.

**Comment by alexhultman** [comment]
Okay I see. You want the _names_ of the parameters not the _value_. Alright. Why don't you just keep the name in the first place? If you set the names, you know the names so why do you need to get the names from the library? The names are only for readability, they make no change.

**Comment by alexhultman** [comment]
I mean you _could_ make a lookup by name, it would be possible but is it really that hard to use index? Do you really have super complex URLs?

**Comment by Tayo-00** [comment]
> Why don't you just keep the name in the first place?
> If you set the names, you know the names so why do you need to get the names from the library?

Because I built a recursive router which evaluates all routes at start time. Meaning a router class with a named parameter could be inside another router class with a named parameter as well. This essentially means I don't always know 100% which value corresponds to which parameter.

> Is it really that hard to use index?

No, it's just a matter of knowing either which exact route was matched, or knowing which parameters are in the URL.

Essentially this is a way the router could be used.
```typescript
const router = new Router();
const subroute = new Router();
const tables = new Router();
subroute.use('/:table', tables);
tables.get('', (req, res) => {
    res.end('all in table');
});
tables.get('/:id', async (req, res) => {
    setTimeout(() => {
        res.send('table with id');
    }, 2000);
});
router.use('/api', subroute);
router.all('/*', (req, res) => {
    res.end('404');
});
router.initialize();
router.listen(3000);
```

You may notice quite a bit of differences. Such as the `req` and `res` being reversed. That's because I'm trying to make the transition from Express to uWebSockets easier.
In a case like `/api/:table/:id` parameters are split over multiple routers. Internally they're split, but for uWebSockets they're in one URL. That's why getting the named parameters from the library seems like a better solution (imo) than trying to internally figure out which route was matched and getting the parameter names from there.

Apologies for the long comment.

**Comment by alexhultman** [comment]
I don't understand.

app.get('/:some/:route') is guaranteed to be matched as req.getParamter(0) and req.getParameter(1). They always match, ":some" is index 0, ":route" is index 1. Always. That's guaranteed. They never change.

**Comment by Tayo-00** [comment]
Yes, and the index access to the values is fine. I just need a way to get the parameter names themselves. Keeping track within the router is hard due to the recursive nature and after initialization the router is as good as useless. Hence trying to save the parameter names and matching the route somehow is a rather difficult thing to do while (provided a function which returns the names exists) the library already knows these parameter names.

**Comment by alexhultman** [comment]
This is not really an issue or feature of this library. What you are talking about is entirely up to you.

If you decide to wrap things up as A and B where A keeps 2 parameters then obviously B, which derives from A, will have to offset any index by 2. That's entirely your task, if you chose to build that thing.

This library, uWS has its own router and you get parameters by index. Whatever wrapper you build is up to you.

**Comment by Tayo-00** [comment]
Alright, thanks for your time anyway.
