### ISSUE TITLE
Equivalence of ws.readyState == WebSocket.OPEN ?

### ISSUE THREAD

**Issue by ohenepee** [uNetworking/uWebSockets.js#149]
Is there anyway to know if the client is still connected or if the client websocket is still open?

**Comment by alexhultman** [comment]
The connection is **considered** open until close event fires. This is determined by the idleTimeout. Keep sockets alive by having the client send phony messages (messages with no real content) from time to time.

**Comment by Cheddah** [comment]
@alexhultman Conversely, as soon as a close event fires, is the **connection already closed** (no waiting for an acknowledgement by the client)? Thank you!

**Comment by alexhultman** [comment]
Yes if you get close event it is closed, that's in the docs
