### ISSUE TITLE
Setting header again appends to header, not replaces

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uWebSockets.js#151]
Hi.

Related issue: #150 

As title says, when again setting `res.setHeader(key, value)` appends to same header, not replaces.

It is bug? Or am i doing something wrong?

**Comment by alexhultman** [comment]
There is no res.setHeader, you only have res.writeHeader

**Comment by dalisoft** [comment]
Yep, setHeader in my app :)
I forgot to say, yes, same bug applies to writeStatus too
