### ISSUE TITLE
VideoStreamer example doesn't work

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uWebSockets.js#153]
Hi.

I'm tried [this](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/VideoStreamer.js) demo and it doesn't work.

On Safari -- just not works.
On Chrome -- downloads, not streams.

Expected: Playing video on all browser

OS: macOS 10.13.6
Node: v12 (installed uWebSockets.js#binaries)
NPM: v6.9.0
Browser: Safari

**Comment by dalisoft** [comment]
Looks like i'm didn't it correctly, so it failed. Used code part from @siffr/server :)

**Comment by PatrissolJuns** [comment]
@dalisoft How did you do in order to make it work? because I'm facing the same issue
