### ISSUE TITLE
Techempower Framework Benchmarks

### ISSUE THREAD

**Issue by ohenepee** [uNetworking/uWebSockets.js#154]
@alexhultman Please include this awesome library in the [TF Benchmarks](https://github.com/TechEmpower/FrameworkBenchmarks) as it would first of all provide a greater exposure and also show where it fits among other frameworks. It would be great to see this particular JS variant added instead of the C++ one.

**Comment by alexhultman** [comment]
This is a common recurring question/request. I don't consider techempower a reliable set of people and I really do not care enough about not being listed
