### ISSUE TITLE
'uWebSockets.js@^15.10.0' is not in the npm registry.

### ISSUE THREAD

**Issue by elieobeid7** [uNetworking/uWebSockets.js#155]
If you install uwebsockets like that `npm install uNetworking/uWebSockets.js#v15.10.0`

And then someday, you have to update the packages `npm update` or npm `outdated`

What you get is 

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/uWebSockets.js - Not found
npm ERR! 404 
npm ERR! 404  'uWebSockets.js@^15.10.0' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/elie/.npm/_logs/2019-05-29T10_19_50_672Z-debug.log
```

So this package is preventing other packages from being updated because it's not registered in npm I think. In any case it needs to be fixed, I have an outdated package and can't figure out how to update it because of this error.

If fixing the error is not a priority then please let me know another way to update my other packages.

**Comment by dalisoft** [comment]
Hi Friend, @elieobeid7

`npm i uNetworking/uWebSockets.js#v15.10.0`
or
`npm i uNetworking/uWebSockets.js#binaries'

will work, in `npm` has old version (which named `uws`).
Newer version only in GitHub

**Comment by elieobeid7** [comment]
Yes I know

1. I can't use the old version, the one on npm, because It's outdated
2. I can't use the one on github, because I won't be able to update my packages

So either the one on npm has to be updated or the one on github needs to be registered on npm

**Comment by dalisoft** [comment]
Yes

**Comment by alexhultman** [comment]
If you have issues with NPM you have to take that with them, I only follow their docs and if they cannot keep track of where a package was installed from I would say that's an issue on their plate. They should better support their own features, or maybe I'm missing something in package.json?

**Comment by elieobeid7** [comment]
I contacted them, will let you know their reply.

**Comment by elieobeid7** [comment]
npm support don't know a thing, stackoverflow say there's no error so i uninstall it and reinstalled it and the error is gone, no idea what's the problem.

**Comment by manast** [comment]
It is quite important to understand that when you install this module as explained in the README you are not installing it from NPM. There are some implications to be known about this, some of them:
- upgrade will not work.
- releases are not immutable (a tag can be removed and point to a different commit)
- the repo can be deleted/renamed, etc at any time and it will break all your deployments.

The most trivial workaround for some of these issues is to fork the repo and install it from your fork.

**Comment by elieobeid7** [comment]
@manast 

If I fork it, would it work in NPM? why? Or do you mean that I should fork it and register it in NPM myself?
