### ISSUE TITLE
Is there any room based wrapper for websocket?

### ISSUE THREAD

**Issue by rebootcode** [uNetworking/uWebSockets.js#161]
Is there any `room` based wrapper for websocket?

Something like:

```
connectionID->joins("room")

connectionID->leave("room")

onMessage->To("room")->Emit("message", "back to you")
```

something like above?

or Any method to send message to a specific Client ID?

**Comment by mslatt** [comment]
just add sockets to objects as needed
`room1={}; room2={}; all={}`
`open:(ws)=>{ all[clientID]=ws; room1[clientID]=ws }`

then send messages by looping through or pick an id from the object
`all[clientID].send(message)`
`for(let s in room1) room1[s].send(message)`

**Comment by coder456** [comment]
just add sockets to objects as needed
`room1={}; room2={}; all={}`
`open:(ws)=>{ all[clientID]=ws; room1[clientID]=ws }`

then send messages by looping through or pick an id from the object
`all[clientID].send(message)`
`for(let s in room1) room1[s].send(message)`

**Comment by rebootcode** [comment]
Ok, and in the example here - https://github.com/uNetworking/uWebSockets.js/blob/master/examples/WebSockets.js

I can't find which one is "client / connection ID"

**Comment by slavaGanzin** [comment]
#35 just linking issues

**Comment by coder456** [comment]
@rebootcode you give the socket its ID
`open:(ws)=>{ ws.id=++socketCount; all[ws.id]=ws; room1[ws.id]=ws }`
`close:(ws)=>{ delete all[ws.id]; delete room1[ws.id] }`

**Comment by alexhultman** [comment]
This approach is heavily discouraged and the most inefficient way you can possibly solve it in.

I am working on it

**Comment by coder456** [comment]
well it's currently the only way to do it so why are you down voting me

**Comment by coder456** [comment]
dude makes a library unable to broadcast and then tries to tell everyone the only way to broadcast is the worst way to do it.. right..

**Comment by alexhultman** [comment]
The solution you recommend is exponential in syscalls, exponential in memory usage and requires more bookkeeping storage space than the size of an original socket in user space.

Exponential scaling in both memory and time is what we use to call "bad". You can solve things in linear time and space if you actually apply yourself.

The difference between linear and exponential in a stressful use case is the difference between soiling your pants on a first date and not doing so. Grand, very grand.

**Comment by coder456** [comment]
the point is that is the only way to do it currently so if you have a better solution post it here otherwise get busy with a fix

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/issues/790

**Comment by manast** [comment]
the solution that @coder456 proposed is not exponential, it is trivially linear relative to the amount of clients, at least for the operation of broadcasting.

**Comment by alexhultman** [comment]
For every 1 publish, it requires N syscalls. You bring that up to 100 publishes and you have 100 * N syscalls aka O(M * N) in _best case_ where M = number of publishes, N = number of clients.

A good solution is O(M * N) in _worst case_ and O(N) in best case.

**Comment by manast** [comment]
right, so for sending M messages the complexity is O(M * N), that is still not exponential but polynomial :). Not sure how this could be improved though with the APIs that are currently being exposed to JS now though.

**Comment by alexhultman** [comment]
So we are splitting hairs..? It _is_ exponential if M = N. Instead of trying to misunderstand a statement as far as possible, acting like a five-year-old, you could adapt what was said to best match. This discussion is completely pointless. I do not have time.

**Comment by coder456** [comment]
Its important to make the broadcast as efficient and fast as possible, its likely the bottleneck for many apps broadcasting to large numbers of clients, while it may be linear relative to the number of clients I'm sure it is many times faster to hard code that in

**Comment by manast** [comment]
@alexhultman if M = N then it is quadratic actually.

**Comment by manast** [comment]
@coder456 algorithmically your solution is linear. Broadcasting a message to N clients. It is O(N). However with a big constant since you have to prepare every message to every client, etc, which would be redundant. @alexhultman is trying to say in his particular way of saying things that it can be done much faster if implemented at a lower level, since you can reuse many operations. But implemented on top of this library there is no trivial way of doing it much better than how you proposed.

**Comment by alexhultman** [comment]
Can we please stop spreading speculations and misinformation? I already have everything tested, benchmarked and ready to go. You even have an example, just look at it and stop speculating. I already have numbers of multiple thousands of X improvement over, say Socket.IO. We already did this back in 2016.
