### ISSUE TITLE
Pub/Sub example doesn't work

### ISSUE THREAD

**Issue by tukida** [uNetworking/uWebSockets.js#164]
Hi all, I'm using uWebSockets.js for a project. I'm tried this demo [https://github.com/uNetworking/uWebSockets.js/blob/master/examples/PubSub.js] and it doesn't work. Client doesn't receive message that is published to topic

**Comment by claudiobonifazi** [comment]
The developer is currently working on that, subscribe and publish are there but don't do anything for now

**Comment by tukida** [comment]
I want to send message from client A to client B. My way is store websocket with id in a object. Like this:
```
let clients = {}
this._app
.ws(this.settings.websockets.path, {
	compression: this.settings.websockets.compression,
	maxPayloadLength: this.settings.websockets.maxPayloadLength,
	idleTimeout: this.settings.websockets.idleTimeout,
	open: (ws, req) => {
		clients[ws.id] = ws
	},
	message: (ws, message, isBinary) => {
		const data = message
		clients[data.target].send(data.message, true, false)
	},
	drain: (ws) => {

	},
	close: (ws, code, message) => {
		/* The library guarantees proper unsubscription at close */
	}
});
```
Is there best way to do it, Thanks

**Comment by coder456** [comment]
seems fine to me unless there is an issue with having an object with references to 300k socket objects, currently only way to do it

**Comment by alexhultman** [comment]
uNetworking/uWebSockets#790

**Comment by alexhultman** [comment]
#161

**Comment by alexhultman** [comment]
#140

**Comment by alexhultman** [comment]
#57

**Comment by alexhultman** [comment]
Once I have fixed all fuzzing issues and everything is completely stable in that regard, I will re-enable pub/sub support and finish it up.

**Comment by tukida** [comment]
Thank you for your answer! This library is awesome and I hope that feature will work soon

**Comment by dioptre** [comment]
+1

**Comment by Wallacy** [comment]
Just to know: This Pub/Sub will be only between clients? Theres no "App.ws.publish()" (or similar) to make the server notify all clients without store one client (to call publish). (Or this last case is the goal?)

**Comment by dioptre** [comment]
@Wallacy you can take the first available socket and publish for now

**Comment by elieobeid7** [comment]
@Wallacy  Even in ws there's no App.ws.publish() unless you're talking about a different library than [this one](https://github.com/websockets/ws) or unless I'm missing something.

**Comment by dioptre** [comment]
What's the ETA on this @alexhultman

**Comment by elieobeid7** [comment]
I'm also interested in knowing how hard would it be if we submit a pull request for this, is it that hard that only he can do it?

**Comment by dioptre** [comment]
Yeah, there's a commit disabled in the c ver. @elieobeid7 but seems there's a bug too. Wanted to get an ETA til I also jumped in. Maybe if it's going to take @alexhultman you and me can fix it instead?

**Comment by elieobeid7** [comment]
Yeah sure, I'd love to work on it, I need this feature so badly in my project. For now, I'm stuck with WebSockets until it gets fixed, so yep we can work on it, Alex can't. I'm sure I'm not as good as him, but at least I'm not sitting waiting for things to happen.

**Comment by alexhultman** [comment]
Probably this month, I don't know.

**Comment by alexhultman** [comment]
There is now a new example and benchmark for broadcasts in the main repo:

Naive for-loop:
```
alexhultman@clr-9c9c4beff725453db9688b589234d573~/uWebSockets.js/uWebSockets/benchmarks $ ./broadcast_test 40 localhost 9001 0
Running benchmark now...
Iterations/second (40 clients): 156.750000
Iterations/second (40 clients): 157.500000
Iterations/second (40 clients): 158.000000
Iterations/second (40 clients): 158.000000
```

Using the pub/sub functions:
```
alexhultman@clr-9c9c4beff725453db9688b589234d573~/uWebSockets.js/uWebSockets/benchmarks $ ./broadcast_test 40 localhost 9001 0
Running benchmark now...
Iterations/second (40 clients): 2089.000000
Iterations/second (40 clients): 2092.000000
Iterations/second (40 clients): 2100.750000
Iterations/second (40 clients): 2099.250000
Iterations/second (40 clients): 2251.750000
```

You can see there is a 13x difference in performance for only 40 connections.

**Comment by alexhultman** [comment]
npm install uNetworking/uWebSockets.js#binaries

It is enabled in latest build - still heavily WIP

**Comment by coder456** [comment]
I ran the broadcast benchmark code on vms on my machine, the difference between `forEach` and `publish` increases to a 100x difference at 320 clients
```
# node pubsub - 102,400 total messages per iteration sent to 320 clients (320 per client)
user@ubuntu1904:/uWebSockets/benchmarks$ ./broadcast_test 320 localhost 9001 0
Running benchmark now...
Iterations/second (320 clients): 373.500000
Iterations/second (320 clients): 375.000000
Iterations/second (320 clients): 372.750000
# total messages sent per second: 32,768,000

# node forEach - 102,400 total messages per iteration sent to 320 clients (320 per client)
user@ubuntu1904:/uWebSockets/benchmarks$ ./broadcast_test 320 localhost 9001 0
Running benchmark now...
Iterations/second (320 clients): 3.000000
Iterations/second (320 clients): 3.500000
Iterations/second (320 clients): 3.250000
# total messages sent per second: 332,800
```
But this is for the special case of each client broadcasting to every other client, where the `publish` function can optimize sending many (in this case 320) messages to the same client per iteration, most likely a server will only be sending a couple messages per second to each client for a large number of clients (10k-100k). I tried updating the benchmark code to simulate that, you will have to tell me if that was done correctly, I changed `num_web_sockets` to `1` on [this line](https://github.com/uNetworking/uWebSockets/blob/master/benchmarks/broadcast_test.c#L57) and [this line](https://github.com/uNetworking/uWebSockets/blob/master/benchmarks/broadcast_test.c#L114) to broadcast 1 message to each client per iteration, then increased the number of clients to 1000 (the client code was exiting with too many more than that, can that be fixed?) and I got:
```
# node pubsub - 1000 total messages per iteration sent to 1000 clients (1 per client)
user@ubuntu1904:/uWebSockets/benchmarks$ ./broadcast_test2 1000 localhost 9001 0
Running benchmark now...
Iterations/second (1000 clients): 299.000000
Iterations/second (1000 clients): 300.500000
# total messages sent per second: 300,000

# node forEach - 1000 total messages per iteration sent to 1000 clients (1 per client)
user@ubuntu1904:/uWebSockets/benchmarks$ ./broadcast_test2 1000 localhost 9001 0
Running benchmark now...
Iterations/second (1000 clients): 269.500000
Iterations/second (1000 clients): 279.250000
# total messages sent per second: 275,000
```
which shows a 9% increase in performance for `publish` over `forEach`. I am wondering if this accurately shows what a broadcast with a single message to large number of clients per iteration would be? These numbers (300,000 sent per second) are still pretty high and higher than the echos per second benchmarks you have posted at 200,000 per second, and looks like if multiple messages are sent to the same client the `publish` function will optimize that to be basically the same performance of sending 1 message to the client

**Comment by alexhultman** [comment]
If you consider a "chat room" with 10k clients, where messages are published 10 times per second to the room that would mean a 10x improvement.

Also, if the server clogs up that number can go up as more will be done per iteration. So it kind of balances itself out - when the server is busy doing stuff it will accumulate more work to be done next iteration, meaning it can merge more work into less work more efficient.

Memory usage is another big thing you are not considering - a forEach that fails will result in backpressure per every socket while a publishing that fails will result in only that data being stored as backpressure.

All in all, you can't go wrong with the pub/sub functions.

**Comment by Wallacy** [comment]
FWIW: Any plan to the "server" send broadcast messages to all clients without store the first WS client to relay the publish?.

**Comment by coder456** [comment]
@Wallacy I think I see what you are saying, the only `publish` function I see is attached to a specific socket, do you need to pick and use any random socket if you want to send a broadcast to a channel, and the docs dont say if the current socket is excluded from the broadcast, I dont think it is

**Comment by alexhultman** [comment]
I haven't come that far yet. App.publish vs. socket.publish is probably "exclude sender" or something like that.

**Comment by noguilty4you** [comment]
> I haven't come that far yet. App.publish vs. socket.publish is probably "exclude sender" or something like that.

Hello, is the .publish interface for all clients pushed to github yet? I can not find smth like that in `index.d.ts`

**Comment by alexhultman** [comment]
I'm tracking this in main repo
