### ISSUE TITLE
Wrap setYield

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#165]

**Comment by dalisoft** [comment]
I checked this method because i did think does [like this](https://github.com/uNetworking/uWebSockets.js/issues/31#issuecomment-467537039), but not work like that.

The code i'm tested:
```js
const { App } = require("uWebSockets.js");

const app = App();

app
  .any("/*", (res, req) => {
    console.log("req #1", req); // <-- this works like before
    req.foo = true;
    req.setYield(true);
  })
  .get("/get/*", (res, req) => {
    console.log("req #2", req); // <-- excepted req.foo = true
    req.bar = true;
    req.setYield(true);
  })
  .get("/get/user", (res, req) => {
    console.log("req #3", req); // <-- excepted req.foo = true and req.bar = true, but these does not exist
    res.end("done :)");
  });

app.listen(4000, token => token && console.log("listens at 4000"));
```

Try go to `localhost:4000/get/user` and see.
May i missing something?

**Comment by vimalmistry** [comment]
@dalisoft Did you found any solution??

**Comment by dalisoft** [comment]
@vimalmistry I used workaround at high-level with simulating middlewares layer before every route request

**Comment by vimalmistry** [comment]
@dalisoft can you share sample code?

**Comment by dalisoft** [comment]
@vimalmistry Here snippet
https://github.com/nanoexpress/nanoexpress/blob/96813ee82b788eb9eca0114fcf471dc189faeec2/src/Route.js#L453-L464
