### ISSUE TITLE
Make Req and Res a Stream

### ISSUE THREAD

**Issue by Wallacy** [uNetworking/uWebSockets.js#171]
Hello,

First, tanks for the project, very good to see a project with a performance goal in mind.

So... Its possible to make Req and Res (from ws or/and http) a Node Stream?

*quick reference: "https://www.freecodecamp.org/news/node-js-streams-everything-you-need-to-know-c9141306be93/"

Current the core HTTP/TCP stack is already a stream object, and this a very userfull feature. Of couse we can do some kind of intermediary stream like you did on the video sample, but the full drain/cork/uncork/pipe/unpipe... cicle probably can be made on the c++ side (plugin/addon/host) improving performance and reducing the some type conversions.

**Comment by alexhultman** [comment]
Hi,

From v0.15 and forward the project is not concerned with or tied to any particular Node.js design. So this means it does not try to mimic any particular interface such as Node.js Streams or anything like that.

It also does not try and mimic Express or anything similar.

**Comment by Wallacy** [comment]
Understood.

Anyway, the Stream interface probably is very good for you C/C++ side too (IMHO). It's an interesting pattern.
Basically it is only necessary to implement these methods:


<table class="tableblock frame-all grid-all stretch stripes-none">
<colgroup>
<col style="width: 14.2857%;">
<col style="width: 42.8571%;">
<col style="width: 42.8572%;">
</colgroup>
<thead>
<tr>
<th class="tableblock halign-left valign-top"></th>
<th class="tableblock halign-left valign-top">Readable Streams</th>
<th class="tableblock halign-left valign-top">Writable Streams</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock"><strong>Events</strong></p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">data, end, error, close, readable</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">drain, finish, error, close, pipe, unpipe</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock"><strong>Methods</strong></p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">pipe(), unpipe(), wrap(), destroy()</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">write(), destroy(), end()</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">read(), unshift(), resume(), pause(), isPaused(), setEncoding()</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">cork(), uncork(), setDefaultEncoding()</p></td>
</tr>
</tbody>
</table>



And you already have some functions using the same logic (like getBufferedAmount / onAborted, onWritable etc) to make a good pipe. Then at the end of the day, it may not require many changes.

My only concern is to reduce some of the hacking necessary to make a streaming (as in the example), avoiding things like "buffer.buffer.slice".

Anyway, thank you very much for your attention.

**Comment by alexhultman** [comment]
> not concerned with or tied to any particular Node.js design

What Node.js does with **their** streams has no significance to **this** project. If you see similarities - good - but that doesn't mean anything more than that there **are** similarities.

The entire premise, the hypothesis of this project since day 1 has always been and will continue to be:

# "Node.js is doing things unreasonably inefficient."

In other words - the **differences** between this project and Node.js is no act of random.

**Comment by alexhultman** [comment]
I just remember I have a lot of opinions on this subject.
