### ISSUE TITLE
Question: compression

### ISSUE THREAD

**Issue by markmcdowell** [uNetworking/uWebSockets.js#172]
Hey Alex, I'm trying to dig into compression a bit and find out when it kicks in. I have a few questions:

Is there a minimum size before compression kicks in?

On the send message definition it has a third parameter, I don't think this is actually used for anything?
```
send(message: RecognizedString, isBinary: boolean, compress: boolean) : boolean;
```

If `isBinary` is set is compression still enabled?

I've looked at the data going through wireshark but I don't notice any difference in sizing switching the compression flags.

Thanks, Mark

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets.js/blob/master/src/WebSocketWrapper.h#L110

It doesn't seem to actually pass compress further, so clearly a bug

**Comment by jpambrun** [comment]
is `, args[2]->BooleanValue(isolate->GetCurrentContext()).ToChecked()` the only thing needed? I would like to try, but building and testing is not trivial.

**Comment by alexhultman** [comment]
Yes you can PR that and CI will build it

send takes message, opCode, compress
