### ISSUE TITLE
Undefined argument `res` in callback for onAborted

### ISSUE THREAD

**Issue by uasan** [uNetworking/uWebSockets.js#176]
```JS
res.onAborted(res => {
    res === undefined; // true
});
```
In documentation `(res: HttpResponse): void`
https://unetworking.github.io/uWebSockets.js/generated/interfaces/httpresponse.html#onaborted

**Comment by alexhultman** [comment]
That's probably a documentation bug, you can just capture res

**Comment by uasan** [comment]
Maybe better implement as documentation?
-1 anonim closure, is less use memory and proc...

**Comment by alexhultman** [comment]
No the docs should change

**Comment by alexhultman** [comment]
The C++ version does not pass any res, you just capture things as you need. JavaScript version should follow original.
