### ISSUE TITLE
HTTP2 Supports?

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uWebSockets.js#178]
Hi @alexhultman 

Is uWebSockets.js supports HTTP2?
If yes, there any flag need or supports out-of-the-box?

Thanks.

Related issue: [#27](https://github.com/dalisoft/nanoexpress/issues/27)

**Comment by alexhultman** [comment]
No that is not a goal for this project right now

**Comment by dalisoft** [comment]
Thanks for reply. I just wanna to know and now know. Without http2 is this project is very fast and flexible
