### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#18]
Windows is far more unstable than Linux version, be aware.

**Comment by alexhultman** [comment]
It's acting really nice now, fixed

**Comment by danikane** [comment]
Hi Alex, are there any Windows binaries, namely uws_win32_64.node?
Thank you for µWS. :)

**Comment by alexhultman** [comment]
Nope but they will be included when I release first stable version. It works nicely on Linux and Windows, macOS is having issues right now.

**Comment by danikane** [comment]
Thank you very much, Alex!

**Comment by alexhultman** [comment]
There are now Linux, Windows and macOS binaries in last version

**Comment by danikane** [comment]
Wow ... amazing. :)
