### ISSUE TITLE
Lowercase headers

### ISSUE THREAD

**Issue by maximmasterr** [uNetworking/uWebSockets.js#180]
Why there are lower cased headers

**Comment by alexhultman** [comment]
The key is lower cased so that you don't have to try looking up all permutations of the key

**Comment by maximmasterr** [comment]
Ok, but why when forEach res it returns me lowercase header name that is the main problem

**Comment by alexhultman** [comment]
Yes they are lower cased. Like explained, they are indeed lower cased
