### ISSUE TITLE
GitHub Package Registry

### ISSUE THREAD

**Issue by ghost** [uNetworking/uWebSockets.js#190]
Hello Alex,
Since you no longer use https://www.npmjs.com/ , is there any chance you could use GitHub Package Registry ?
https://github.com/features/package-registry
Cheers

**Comment by yovanoc** [comment]
I would love that too

**Comment by alexhultman** [comment]
I don't know what it is but I did apply for the beta. Still pending

**Comment by yovanoc** [comment]
I'ts a package registry just like NPM. With other tabs like Commits, Branches, etc you will have "Packages" and you can put releases of your project, manages versions, etc and allowing users to install from npm.

Some screens of mine:

![image](https://user-images.githubusercontent.com/7302317/64201330-be9aba80-ce8e-11e9-9621-fe333c826253.png)
![image](https://user-images.githubusercontent.com/7302317/64201353-cb1f1300-ce8e-11e9-8c95-4613165a8585.png)
![image](https://user-images.githubusercontent.com/7302317/64201387-dffba680-ce8e-11e9-9b12-c2f4b9c1e664.png)

**Comment by PeterHewat** [comment]
You can even setup a GitHub Actions workflow to automatically generate a package release on a push event.
https://github.com/features/actions
Storing binaries in a branch like what you are doing is a bit of a hack ;-)

**Comment by alexhultman** [comment]
Okay so GitHub actions can replace AppVeyor and Travis, sure. But what is the minimal steps for installing from GitHub packages with npm?

**Comment by PeterHewat** [comment]
Give me a day or two and I'll give you an example (too busy right now).

**Comment by alexhultman** [comment]
> To avoid breaking projects that may depend on your packages, GitHub Package Registry does not support package deletion or deleting a version of a package. Under special circumstances, such as for legal reasons or to conform with GDPR standards, you can request deleting a package through GitHub Support. Contact GitHub Support using our contact form and the subject line "GitHub Package Registry."

I'm not interested in this

**Comment by yovanoc** [comment]
Why it's a problem for you?

**Comment by alexhultman** [comment]
There already is a dead simple way of installing, `npm install uNetworking/uWebSockets.js#v15.11.0`

I'm not interested in moving to something less liberal.

**Comment by PeterHewat** [comment]
I had a fealing you would choke on the ToS for the same reason you fled npm.org...
As you know, they do this to garanty the users against braking builds due to disappearing dependencies. Package registries also enable you to automatically handle SemVer updates.
As I stated before, your solution is a hack but if it rocks your boat ;-)
It unfortunatly prevents many users to even consider your solution.
I guess there is no point in me showing you how to setup GitHub Actions to automatically generate your package to GitHub Package Registery.
Farewell!
