### ISSUE TITLE
Release 16

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#201]
* Update docs
* Wrap maxBackpressure and set their default values properly
* App. Publish

**Comment by FlorianBELLAZOUZ** [comment]
Hi Alex!
Thanks for this new release and for keeping the good work years after years.

I try to publish globally a message
You write in examples/PubSub.js
"send to all including us, or not? That's not a setting really just use ws.publish or global uWS.publish"
After reading the documentation and tried the functions suggest in examples I didn't succeed to do it.

Can we still globally publish a message or it's only possible with a WebSocket object?

**Comment by yovanoc** [comment]
@FlorianBELLAZOUZ I'm looking for this global publish too, it would be good to broadcast over all clients at once
