### ISSUE TITLE
Unix socket support

### ISSUE THREAD

**Issue by marcj** [uNetworking/uWebSockets.js#202]
Currently, the given API in index.d.ts listens `listen(host: string, port: number)` and `listen(port: number` which implies to me there's no official unix socket support yet. Is this correct, or is there a way around it? Do you plan to support unix sockets?

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uSockets/issues/15

This is doable at the lower levels, not prioritized right now but could be

**Comment by marcj** [comment]
From my experience this would lead to a substantial performance improvement when server is behind of a reverse proxy or when both client and server are running on the same machine. Would be great if possible 👍

**Comment by alexhultman** [comment]
Sure, Unix sockets are simpler than TCP sockets but a Linux kernel can do way more TCP than your proxy software can handle in any case. It's a low priority, esp if you plan on doing SSL

**Comment by sarumjanuch** [comment]
More interesting would be to write zeromq plugin to uWebSockets.. And use something like IPC socket type. I am doing that with JS bindings, and keeping uWebSocket.js node process away of any my businesses logic ...

**Comment by alexhultman** [comment]
This thread is not about zeromq, I don't see how that relates to anything here. "IPC socket type" is literally Unix sockets. This thread is about Unix sockets

**Comment by alexhultman** [comment]
This is already tracked in usockets

**Comment by zdm** [comment]
Unclear is this feature is implemented or not and how we can use it if yes?

**Comment by alexhultman** [comment]
It's not implemented. It could be, but given how incredibly efficient localhost TCP is on Linux, far far more efficient than your Nginx proxy process can handle - esp when you consider SSL, it's super low priority and quite pointless. Also, why would you put a proxy on the same very machine?

**Comment by slavaGanzin** [comment]
> Also, why would you put a proxy on the same very machine?

@alexhultman It's convenient way for SSL termination and app separation.
In my case nginx decode HTTPS, serve static (by himself) and forwards non-static into UWS and auth server (packaged express app).

**Comment by alexey-v-paramonov** [comment]
On more usecase for this - is if you don't want to have several ports open, like I could use a single 8080 port of Nginx to host the www app and use 8080/ws path for websocket connections with /ws being proxied to a local Unix stream.

**Comment by slavaGanzin** [comment]
https://lists.freebsd.org/pipermail/freebsd-performance/2005-February/001143.html

https://momjian.us/main/blogs/pgblog/2012.html#June_6_2012

I don't know what had changed with IP stack in linux since 2012, but I think not much in this case.

**Comment by alexhultman** [comment]
The argument being Unix sockets are 60% faster than localhost is not relevant. Yes, Unix sockets are faster than TCP sockets - but Nginx modules are faster than Unix sockets, and not having Nginx at all is faster still.

Adding Unix sockets is a feature, yes, but it is low priority right now because you don't critically need it. It doesn't really matter because your proxy will bottleneck long before localhost will, anyways.

**Comment by alexhultman** [comment]
It's kind of bizarre to use Node.js but still argue about the need for kernel space optimizations. If you care that much for performance, first step is to eliminate Node.js because it is by far the most immediate bottleneck. Node.js I/O is 800% slower than what you can get without it.

**Comment by zdm** [comment]
Unix sockets will allow to establish inter-process communiction between docker containers more easily and secure. They will allow to run isolated docker containers and share sockets using file system instead of run containers in host network and use random ports (very unhandful).

**Comment by uasan** [comment]
> Postgresq core developer measurements: tcp/ip, no ssl vs UNIX = +31%

If used [pg](https://github.com/brianc/node-postgres) client, you increase performance by ~300% using a new postgres client
https://github.com/porsager/postgres

**Comment by alexey-v-paramonov** [comment]
For me it is not abut performance, but more that I don't have (and in my cases I just can't) open another network port.
