### ISSUE TITLE
Compression Enum

### ISSUE THREAD

**Issue by yovanoc** [uNetworking/uWebSockets.js#205]
![image](https://user-images.githubusercontent.com/7302317/66708623-b4a08d00-ed53-11e9-973b-c682a3ebb6a8.png)
<img width="700" alt="Screen Shot 2019-10-13 at 12 52 44 AM" src="https://user-images.githubusercontent.com/7302317/66708633-df8ae100-ed53-11e9-8f95-ed38c4dc2c13.png">

**Comment by abenhamdine** [comment]
I didn't check, but it's probably that the .d.ts file is not transpiled (see https://lukasbehal.com/2017-05-22-enums-in-declaration-files/)

**Comment by yovanoc** [comment]
Nope, there is the enum in the .d.ts (https://github.com/uNetworking/uWebSockets.js/blob/ea8d4c784d2eeb70ac6884c30b68b17070118d21/docs/index.d.ts#L168) but apparently not in the real js

**Comment by alexhultman** [comment]
It is uWS.SHARED_COMPRESSOR

**Comment by alexhultman** [comment]
There is no JavaScript portion, only typescript definition. These enums are exported as integers from C++

**Comment by yovanoc** [comment]
![image](https://user-images.githubusercontent.com/7302317/68507550-7a4fe000-026c-11ea-90a0-41342ba991a2.png)

Look, typescript want to get it from CompressOptions, thats why it its not there

**Comment by alexhultman** [comment]
Is it possible to have anonymous enums?

**Comment by yovanoc** [comment]
No for me the best solution is to put this in constants directly :/

**Comment by Cheddah** [comment]
This was recently fixed for me, VS Code now picks up on my `uWS.CompressOptions.DISABLED` (v 16.1.0)

**Comment by yovanoc** [comment]
The problem is not VSCode, that's the typing, there is just "constants" in fact.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets.js/blob/5e205adfbf51892cf3ac32c2db924a7117e79bd5/src/addon.cpp#L94

**Comment by Cheddah** [comment]
> The problem is not VSCode, that's the typing, there is just "constants" in fact.

I wasn't implying that the issue was VSCode

@alexhultman Thanks!

**Comment by alexhultman** [comment]
Does this work?

[types.zip](https://github.com/uNetworking/uWebSockets.js/files/3860100/types.zip)

**Comment by alexhultman** [comment]
This should be fixed in 16.3.0
