### ISSUE TITLE
Cluster of uWeboscket.js

### ISSUE THREAD

**Issue by emdotem** [uNetworking/uWebSockets.js#214]
Is it possible to have multiple instances of the server and make sure the communication among sockets connected to different instance works?

I'm thinking about having a message broker in the middle for communication

**Comment by dioptre** [comment]
i use nats for that, works well

**Comment by alexhultman** [comment]
You can scale with multiple instances, yes. Either listen to the same port (Linux only) or listen to a set of ports which are then proxied or whatever. You can also scale using DNS, etc.

**Comment by dalisoft** [comment]
@emdotem It is works only in Linux, just add `NODE_CLUSTER_SCHED_POLICY=rr` as ENV to be sure everything will work as expected. And works so fast, i checked

**Comment by alexhultman** [comment]
NODE_CLUSTER_SCHED_POLICY does not affect uws

**Comment by yovanoc** [comment]
Sorry to comment this closed issue, I hope you will see it but when you talk about cluster you mean the nodejs cluster module https://nodejs.org/docs/latest/api/cluster.html ?

**Comment by alexhultman** [comment]
It doesn't matter. I'm pretty sure Workers works also. Or just start separate processes altogether. None of it matters, it is the Linux kernel which does the load balancing. Or use a proxy it doesn't matter
