### ISSUE TITLE
WebRTC or similar function?

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uWebSockets.js#216]
Hi @alexhultman 

Thanks for library, it's great and powerful (performance + stability).

It is possible send/receive videos like WebRTC?
Any demo or hints? With websocket possible, but that use a lot of CPU (80% CPU usage).

Any help appreciated.

Thanks

**Comment by alexhultman** [comment]
No that is not part of this project. You usually build WebRTC using websockets for signalling though, so they are not mutually exclusive. You still need some signalling server in any case.
