### ISSUE TITLE
Win32 path separator on  AsyncFileStreamer::streamFile

### ISSUE THREAD

**Issue by mbsteixeira** [uNetworking/uWebSockets.js#225]
In the method "AsyncFileStreamer::streamFile",  the   "auto it = asyncFileReaders.find(url);" fails because of the **windows** plataform path separator.
It's necessary a   change from '/' to '\\' , so the search succeeds.

**Comment by alexhultman** [comment]
Yes one could work on that however it is just a simple example and could be solved in a cross platform way if wanted

**Comment by mbsteixeira** [comment]
Ok.

**Comment by alexhultman** [comment]
Feel free to PR though
