### ISSUE TITLE
Porting uWS(C++) to Deno.land (Rust)

### ISSUE THREAD

**Issue by uasan** [uNetworking/uWebSockets.js#230]
Hi.

I know your difficult relationship with the Deno community ), but can someone tell me if there is or is planning to porting the uWS to Deno?

Thanks.

**Comment by alexhultman** [comment]
Deno has no support for native modules

**Comment by alexhultman** [comment]
Possibly as a fork, but that is quite the work and it's still a long way before we know if deno will be adopted by any real sum of people. Node.js is a smashing hit popularity wise, and people don't really seem to care that much for deno. Why would they? Deno offers nothing over nodejs

**Comment by uasan** [comment]
> Why would they? Deno offers nothing over nodejs

Yes, Deno unused in production.
But I like his work with modules (without NPM) and TypeScript from the box, and similarity of Deno API with WebAPI of browser.

Ok, I hope someone makes a port sometime.
Thanks for the answer.

**Comment by alexhultman** [comment]
Yes but it doesn't support native modules, so any native code has to be as an entire fork of deno itself. So people would have to swap the entire deno binary.

**Comment by alexhultman** [comment]
https://github.com/denoland/deno/blob/508d728b5e27fd0c81669050869cf52c41538a87/core/libdeno/api.cc#L110

deno_init is where V8 is set up. That's where you want to register uWebSockets.js functionality and expose in the global namespace. Basically you would have "Deno" namespace and "uWS" namespace to use from JS.

That's not so much of a port, more of gettings things to build and link.

Then you need an MIO backend to uSockets.

You can't "port" uWebSockets to Rust or anything like that, it doesn't work that way. You can link it as is, but you cannot "port" it. Of course it would still be entirely Alien to anything Deno.

**Comment by alexhultman** [comment]
This libuv.c in uSockets would have to be ported to Rust using MIO:

https://github.com/uNetworking/uSockets/blob/master/src/eventing/libuv.c

That's pretty much first step and like 90% of the task.

**Comment by alexhultman** [comment]
Wait what? Did they remove all that MIO stuff and only rely on Rust poll stuff? https://github.com/rust-lang/rust/blob/master/src/libcore/task/poll.rs

**Comment by uasan** [comment]
Ry Dahl, replied about the new API plug-ins for connecting native modules, what do you think about this?
https://github.com/denoland/deno/issues/3366#issuecomment-554797627

**Comment by alexhultman** [comment]
I'm not interested in anything like that. I'm closing this now, this is of lowest priority here. Deno is still an experimentation with no corporate users.
