### ISSUE TITLE
Maximum wait time during TCP closing handshake (FIN)?

### ISSUE THREAD

**Issue by michaelnwani** [uNetworking/uWebSockets.js#240]
Hi Alex,

Given a client with a spotty wifi connection/bad network conditions, is there a maximum amount of time that websockets might wait for the client to respond during a (graceful) closing handshake? This would be after calling `ws.end(<code>, <msg>)`. I hope this question makes sense.

Thanks!

**Comment by alexhultman** [comment]
Yes the timeout is the same as idleTimeout

**Comment by michaelnwani** [comment]
@alexhultman thanks! Feel free to close this
