### ISSUE TITLE
Broadcasting to all clients

### ISSUE THREAD

**Issue by car1ot** [uNetworking/uWebSockets.js#243]
How to broadcast data to all connected clients? For example, broadcasting every minute bot notifications etc.

**Comment by car1ot** [comment]
I need to store all connected users in some variable, or I could access to all connected users other way?

**Comment by alexhultman** [comment]
Subscribe to a topic then publish to it. Check documentation

**Comment by car1ot** [comment]
> 
> 
> Subscribe to a topic then publish to it. Check documentation

??? Publish data to topic only allowed from one of active websockets.

**Comment by yovanoc** [comment]
You can do an `app.publish`

**Comment by car1ot** [comment]
> 
> 
> You can do an `app.publish`

What did you mean of "app"? How can I access app? Is it require('uWebSockets.js').App(...).ws(...).listen(...) ?

**Comment by car1ot** [comment]
> 
> 
> You can do an `app.publish`

**Comment by car1ot** [comment]
Thanks

**Comment by alexhultman** [comment]
Which is written in the docs, you should read it
