### ISSUE TITLE
Wrap PING/PONG

### ISSUE THREAD

**Issue by frimuchkov** [uNetworking/uWebSockets.js#257]
Hello! There are exist PONG and PONG OpCodes in https://github.com/uNetworking/uWebSockets/blob/master/src/WebSocket.h
And these codes are declared in the protocol, but there is no way to send ping message via uWebSockets.js
Can you support ping method?

**Comment by alexhultman** [comment]
Hmm, yes it seems impossible for JS users.

Maybe a ping method, or send that takes any op code (that's how the native project does it)

**Comment by alexhultman** [comment]
Fixed in 17.1 see docs
