### ISSUE TITLE
Possible memory leak-- `processPromiseRejections ` never called?

### ISSUE THREAD

**Issue by mattkrick** [uNetworking/uWebSockets.js#262]
After migrating from express to uwebsockets, i noticed a memory leak caused by node holding onto unhandled rejections and never flushing them
<img width="677" alt="Screen Shot 2020-01-12 at 7 54 53 PM" src="https://user-images.githubusercontent.com/5514175/72228579-e6eda080-3575-11ea-88b5-d614fcff43c2.png">

The `pendingUnhandledRejections` array is emptied when `processPromiseRejections` is called: https://github.com/nodejs/node/blob/c9b93e234454322ac0b7a6cd29d394f428f3e37d/lib/internal/process/promises.js#L171

It should get called every tick here: https://github.com/nodejs/node/blob/68abaab8baac203833889c9106abf6fe82a5900f/lib/internal/process/task_queues.js#L98

Perhaps the task queue is never empty, so `!queue.isEmpty() || processPromiseRejections()` always shortcircuits? Any guidance appreciated

**Comment by alexhultman** [comment]
That's probably a correct find, I've been spending far too long trying to fight that whole dreadful nextTick nonsense.

It has been the finger nail in my eye for a long time and I properly hate it for existing.

The only proper way is to use node::MakeCallback which is a massive performance hit since nodejs is a pile of garbage.

In any case, I'll probably have to accept nodejs is nodejs. It's easier to deal with knowing Python has no such nonsense.

**Comment by mattkrick** [comment]
i hear ya,
dumb idea because i'm not familiar with node internals-- is it possible to just call `process.runNextTicks`? 
Since `_tickCallback` was deprecated, that looks like the new userland way to handle it.

issue: https://github.com/nodejs/node/pull/29671
old example from node v10: https://blog.insiderattack.net/crossing-the-js-c-boundary-advanced-nodejs-internals-part-1-cb52957758d8

**Comment by alexhultman** [comment]
It's an easy fix, all you have to do is resort to the "correct" way of calling in to JavaScript.

Problem is, that "correct" way is really bad, and limits performance a lot.

Vanilla V8 Function calls are fast, I get 123k messages/second while node::MakeCallback is down to 99k. It's a major hit to performance.

However, since I have found Python and already do 137k messages/second there I think it is time to just let nodejs be nodejs like I said earlier, and work more on the Python extension when it comes to showcasing performance.

Moving back to the "correct" way would solve a lot of strange crashes when debugging and just overall make it more robust.

I see it as a speeding ticket, now it's time to pay the price.

**Comment by alexhultman** [comment]
You know it's actually good if there's a big difference between the Node.js addon and the Python extension because then I can stir up more controversies.

Nothing triggers fanatics like a performance war, and I'll reap the fruits :smiling_imp: 

I'm in.

**Comment by jardicc** [comment]
Author of Node.js admitted some flaws. Do we already know if they solved performance properly in the new Deno project? https://github.com/denoland/deno/issues/205

**Comment by alexhultman** [comment]
Please read your own links. It is ironic you post that particular issue. Please, read what you post.

Deno is even more of a fuck up than nodejs

**Comment by alexhultman** [comment]
https://github.com/denoland/deno/issues/205#issuecomment-397116115

**Comment by alexhultman** [comment]
https://github.com/denoland/deno/issues/205#issuecomment-397128489

**Comment by alexhultman** [comment]
Just leave it be, nodejs is what it is and nobody can fix it.

**Comment by jardicc** [comment]
I did. But it is a year and a half ago. I just want to know if your prediction met reality in a measurable way in latest version ;-)

**Comment by alexhultman** [comment]
Ofc my prediction held, Ryan Dahl has no clue about performance

**Comment by alexhultman** [comment]
The problem with nodejs and Deno is they preach inclusivity, rather than exclusivity.

If you want good things you cannot let a bunch of undecorated morons design it, you need to cull out the best people. That's the issue. They bring in morons who know nothing

**Comment by alexhultman** [comment]
Look at Lua or Python, it's made by the people who wrote the interpreter themselves. Nodejs is just some stapled together mix of V8 (excellent Google project) and amateur scripts (garbage)

**Comment by IhsanMujdeci** [comment]
Does this mean you will stop developing the js library?

**Comment by alexhultman** [comment]
No I'm just saying, writing the Python extension is a pleasure. It's the scripting environment that really lets uWS shine

**Comment by alexhultman** [comment]
@mattkrick Please try `npm install uNetworking/uWebsockets.js#binaries` and see if that solves your problems

**Comment by mattiasewers** [comment]
@alexhultman why do this if performance is sacrificed? Is this a non issue if you just catch all promises?

**Comment by alexhultman** [comment]
Because there are other problems such as the debugger crashing.

**Comment by mattkrick** [comment]
verified that the leak no longer exists after installing binaries. thank you!

sidenote-- i tried to downgrade to v16.5.0 to reproduce the leak, but kept getting an error during heap dump (`/usr/local/bin/node[6355]: ../src/api/callback.cc:110:void node::InternalCallbackScope::Close(): Assertion `(env_->execution_async_id()) == (0)' failed.`). blew away the yarn cache, node_modules & lockfile, still couldn't get the heapdump to work for the old version. not a huge deal, just stumped on what could've broken

**Comment by alexhultman** [comment]
That crash you got in v16.5 is exactly the kind of issues this commit solves, so it further highlights the need for it

**Comment by alexhultman** [comment]
Having debugger, heap dump and this memory leak fixed is probably worth it even though I hate to say it. Great
