### ISSUE TITLE
EXPERIMENTAL_FASTCALL

### ISSUE THREAD

**Issue by yovanoc** [uNetworking/uWebSockets.js#267]
![image](https://user-images.githubusercontent.com/7302317/72807128-ff854700-3c56-11ea-9fac-e073f7eb8a8c.png)

Why don't you try to speak with nodejs core team about that?

**Comment by alexhultman** [comment]
I raised that issue in 2016 and all it resulted in was me getting permanently banned from nodejs repos. So no I'm not going to bother, besides it works pretty fast anyways.

**Comment by yovanoc** [comment]
For sure, but 25% it's a lot, so if there are things to improve it would be nice but why get you banned? seems weird to ban people for asking some questions or exposing these kind of things

**Comment by alexhultman** [comment]
I have strong opinions and I don't agree with their ways. I can't help they enforce a particular low perf path to everything that touches nodejs. My opinion is that they run V8 potentials into the ground, by bolting on a bunch of bloated and mandatory nonsense.

Nodejs is nodejs, there's nothing I can do about it. I can only watch them iteratively worsen performance with every new release.

**Comment by yovanoc** [comment]
I think it's sad, but when deno will be more mature it will be time to move on for new projects maybe

**Comment by alexhultman** [comment]
Deno is even slower than nodejs... It always will be.

**Comment by alexhultman** [comment]
If you think native addons are being slowed down in nodejs, wait and see deno. They route every single "function call" through their own dynamic dispatcher written in typescript. Imagine a native module having to serialize its operations via this dynamic dispatcher it's entirely mad and crazy

**Comment by alexhultman** [comment]
Python.. now that's a project.

**Comment by yovanoc** [comment]
You're right I think, but I really love typescript, but is just a javascript superset and don't run on its own, we must rely on node or deno for now :/

**Comment by M-jerez** [comment]
Hi @alexhultman  thanks for the great work. 

Are the related issues appearing only during debugging?  If so could we not detect debug mode in V8 and set `PERFORM_LIKE_GARBAGE` accordingly?

PS: I can see you have some issues with node.js 😂🤣

**Comment by alexhultman** [comment]
You could probably have an environment variable like DONT_PERFORM_LIKE_GARBAGE=1 node not_garbage.js

**Comment by Nishchit14** [comment]
I have tested the basic benchmark with `Hello Word` API and found that It is still the fastest server with Nodejs. from my benchmark on 8gb, 8-core Macbook pro-2019

| Server  | req/sec  |
|---|---|
| Nodejs (uws)  |  ~155k |
| Express | ~30k |
| Go- Iris | ~88k |
| Haskel  | ~75k |

**Comment by michaelnwani** [comment]
Hi @alexhultman ,

Thanks again for all your work on this project 😀. I know this issue is closed, but I thought it'd be an appropriate place to ask you two questions:

1. To be straightforward, there's a lot of people out there that want to use this project (I've been using it for months), but are afraid that at an undisclosed point in time in the future, it will suddenly be removed from Github (I'm sure you can see where they're coming from). Forking and maintaining it would be a non-trivial undertaking.... basically I wanted to ask, how likely is this? Because it seems that you don't like Node.js, and are under no obligation to continue this. 🙂 I hope you don't mind sharing your thoughts here.

2. > Moving from vanilla V8 function calls to Node.js wrappers results in up to 25% performance loss, but is the only true solution to the various issues reported regarding process.nextTick and debugging.
^ Can we just say "fuck it"? If you truly feel the issue is with Node itself, and this project is pristine without those wrappers, that's more than fair. It's just a quirk of the trade, y'know? Either that, or could we opt out of this performance degradation (not rely on the wrappers)?

Thanks again man.

**Comment by alexhultman** [comment]
No we cannot just say fuck it, this project is four years old and used by financial companies

**Comment by michaelnwani** [comment]
@alexhultman Gotcha 👍 . Would it be feasible to make it optional then, or is that a bad path to go down?

**Comment by abenhamdine** [comment]
> 
> 
> @alexhultman Gotcha 👍 . Would it be feasible to make it optional then, or is that a bad path to go down? I'm trying to say that, depending on how one's project is architected, some of us value that 25% performance boost over fixing Node's issue.

I agree it would be great to opt out from this mode. 
We currently use uws 16.0 with no trouble, so we would prefer to have a supported version without 25% perf loss.

Anyways it's your project, up to you. Just a user point of view.

**Comment by alexhultman** [comment]
Environment variable like mentioned above could swap between default (this new) and old behavior.

EXPERIMENTAL_FASTCALL=1 node runfast.js

That adds dynamic dispatch in CallJS but is probably negligible

**Comment by maxxcs** [comment]
Particularly I did not experience any loss of performance from version 0.17.0 to 0.17.1, I still had an average of 80k requests per second with uWS.js, the same as 0.17.0 version.

**Comment by edreal** [comment]
@alexhultman How did you measure the performance?
I did simple while(1) { ws.send('hello') } and incremented counter in the client when it received the message (gets logged and cleared every second). The results below are tested without TLS/SSL.

With uws 1.7.1.0, the client received around 180k messages per second.
It was pretty much same with the 1.7.0.0 and even 1.6.4.0.
What kind of situation it was when you got it 25% worse?
With websockets/ws library I got around 100k msg/s.

Also what is your opinion on this library/fork: https://github.com/ClusterWS/cWS
It had around 190k r/s but lacking SSL support so Nginx would be needed.

Thanks.

**Comment by abenhamdine** [comment]
@maxxcs @edreal did you normalise cpu-time spent in your benchmarks ?

**Comment by edreal** [comment]
@abenhamdine I am not sure what does it mean

**Comment by abenhamdine** [comment]
I mean, did you see some change in CPU usage between 16.4 vs 17.1 ?

**Comment by edreal** [comment]
@abenhamdine oh, I didnt actually even look the CPU usage.
Would it tell more than the messages per second?

**Comment by alexhultman** [comment]
This only affects C++ to JS calls aka "events". Calling from JS to C++ is unaffected (send, publish, etc). So maximum perf loss is for things like Http req/sec and WebSocket msg/sec while pubsub is practically unaffected.

**Comment by edreal** [comment]
@alexhultman oh you mean open, message and close events? So the performance is mostly decreased when there is a lot of messages sent from client to server when the server fires the message event?

**Comment by alexhultman** [comment]
Yes and most commercial use cases are pubsub, distributing some event to many clients such as share ups and downs. So those see practically no difference

**Comment by edreal** [comment]
Okay! What was the thing with EXPERIMENTAL_FASTCALL, is it coming later?

**Comment by alexhultman** [comment]
> I did simple while(1) loop in server sending "hello" and when client received it, the counter increments (which gets cleared and logged every second).

This is not a good idea as it will just flood the send buffer. Also, you're not using corking or drain events properly.

Benchmarking a library without even reading the user manual of how it works is very lazy.

**Comment by alexhultman** [comment]
Also, how are you benchmarking a fast server? I guess you use websockets/ws as client? That's just going to benchmark the client, as that side cannot keep up. It's pointless. You need an optimized C client to see any perf difference here.

With what you're trying to do you should be in the five millions, not a few hundreds.

Please don't perform benchmarks if you don't know what you're doing.

**Comment by Nishchit14** [comment]
@alexhultman thanks for your suggestion on benchmarking. Is there any doc or article about benchmarking best practices? It would help a lot. thanks.

**Comment by alexhultman** [comment]
There are optimized C clients in benchmarks folder

**Comment by uasan** [comment]
I hope in the future will become popular, browser (Chrome Web API) based server solutions, IBM is already successfully experimenting with this.
https://medium.com/@richardyoung00/browser-functions-a-new-serverless-platform-using-web-browser-execution-engines-31d2293e650b

P.S.
I'm interested in uWS (C++), can plug into to a browser on the server?

**Comment by alexhultman** [comment]
With added EXPERIMENTAL_FASTCALL I can trigger these differences when running wrk with pipelining:

**v17.0.0**
Requests/sec: 274626.65 (best)

**v17.1.0**
Requests/sec: 246552.92

**v17.2.0 default**
Requests/sec: 245258.78 (worst)

**v17.2.0 EXPERIMENTAL_FASTCALL=1**
Requests/sec: 265362.05 (second best)

The added dynamic dispatch has measurable overhead, but can restore **some** perf.
