### ISSUE TITLE
Allow ping/pong handlers cofiguration

### ISSUE THREAD

**Issue by VectorWpl** [uNetworking/uWebSockets.js#271]
Hi, Thanks for implementing  ping() method. Can I ask for possibility to configure ping/pong handlers? I saw that those have been left out in https://github.com/uNetworking/uWebSockets.js/blob/886de7ab3cc737f33a71424298517a61d1c570d2/src/AppWrapper.h#L126

**Comment by yovanoc** [comment]
Oh yeah it could be really great!

**Comment by Coldzer0** [comment]
Yep this will help a lot

**Comment by alialparslan** [comment]
Also protocol level ping does not avoid idleTimeout.

**Comment by alexhultman** [comment]
> Also protocol level ping does not avoid idleTimeout.

The timeout does not reset when the server gets a websocket ping? I will look at that, and this issue.

**Comment by alexhultman** [comment]
You can try the ping/pong handlers now; npm install uNetworking/uWebSockets.js#binaries

It does not reset idleTimeout, yet

**Comment by alexhultman** [comment]
Closing; tracking remaining issue here: https://github.com/uNetworking/uWebSockets/issues/1009

**Comment by alexhultman** [comment]
@alialparslan Receiving a ping does reset the timeout. What do you mean?

**Comment by alialparslan** [comment]
@alexhultman I am sorry. My bad. I assumed it wasn't working because  when i set up ping with 2 seconds interval and set idleTimeout to 5s. Connection always get closed by server withing 5 sec. But its not specific to or about protocol level ping. Right now i am using normal messages to ping. When i set idleTimeout to anything greater than 5 sec it works without problem.

**Comment by astahmer** [comment]
Hey, great lib.
Just so you know, I just stumbled upon the bug with the idleTimeout <6s auto-closing connection after 5sec, so I guess it's still here with the version `"uWebSockets.js": "github:uNetworking/uWebSockets.js#v18.11.0",`
