### ISSUE TITLE
request: HttpRequestWrapper.forEach() idiosyncrasy

### ISSUE THREAD

**Issue by taylorsmithgg** [uNetworking/uWebSockets.js#272]
`HttpRequestWrapper.forEach()`, as currently implemented (and a common prototype in JS), does not make sense as the function name for iterating over headers from a request.

`HttpRequestWrapper.getHeaders()` returning an array or object of headers would be more concise, and would provide the same functionality with `forEach` natively.

**Comment by alexhultman** [comment]
So you have an opinion; congratulations we all have opinions. I disagree.

**Comment by yovanoc** [comment]
Why being so rude ? :0

**Comment by alexhultman** [comment]
This "bug report" has no backing argument, motivation, or importance other than conveying an opinion which really doesn't matter. In fact it would introduce memory allocations where there were none before, making it a bad opinion.

**Comment by kinsi55** [comment]
For the reason of the request object being stack allocated and the async nature of JS / Node its pretty likely having to "clone" the request object before going on and doing async stuff and eventually creating a response - this obviously introduces an overhead either way, but I'm guessing the overhead of looping trough all headers with the forEach and creating an object out of it within the app would be (significantly?) higher than having that done by a native implementation, if that assumption is correct or not is something that you would have to confirm as a c++ project of this scale is way beyond what I can call my knowledge :D
