### ISSUE TITLE
Browser opens multiple ws connections

### ISSUE THREAD

**Issue by sirganya** [uNetworking/uWebSockets.js#279]
If I open a single ws client connection in a browser to a uWs.js server and push a lot of data down the wire the browser opens multiple ws connections. getBufferedAmount is never more than 0 and ws.send always returns true. What is this behavior?

**Comment by alexhultman** [comment]
That's not how browsers work. You have to distill your issue down to a more technical description and do more debugging yourself. The behavior you describe makes no sense and I would rather report that kind of issue to whatever web browser you're using.

**Comment by sirganya** [comment]
It exhibits the behavior on Chrome, Firefox and Safari, I've been attempting to debug it but I'm at a loss.

**Comment by alexhultman** [comment]
A server does not initiate connections and web browsers do not reconnect websockets on their own. You have to debug your logic on your own and determine why the browser would end up like that. This is not my task and it has nothing to do with this project. Did you check the max payload limit?

I'm closing this as it's essentially the same as reporting "my app is broken, fix my issue"

**Comment by sirganya** [comment]
Right you are.
