### ISSUE TITLE
Cannot install - premature close

### ISSUE THREAD

**Issue by OmgImAlexis** [uNetworking/uWebSockets.js#283]
I'm trying to install this on my Macbook running `node v12.5.0`. Any ideas on how to debug this?

```shell
➜  proxy git:(master) ✗ npm install uNetworking/uWebSockets.js                       
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xo/.npm/_logs/2020-03-15T04_29_08_579Z-debug.log
```
```shell
➜  proxy git:(master) ✗ cat  /Users/xo/.npm/_logs/2020-03-15T04_29_08_579Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'uNetworking/uWebSockets.js'
1 verbose cli ]
2 info using npm@6.13.0
3 info using node@v12.5.0
4 verbose npm-session c5eedc51b34d9932
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:uNetworking/uWebSockets.js premature close
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 34529ms
10 verbose stack Error: premature close
10 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
10 verbose stack     at PassThrough.emit (events.js:205:15)
10 verbose stack     at emitCloseNT (internal/streams/destroy.js:68:8)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:74:11)
11 verbose cwd /Users/xo/code/unraid/proxy
12 verbose Darwin 19.2.0
13 verbose argv "/usr/local/Cellar/node/12.5.0/bin/node" "/usr/local/bin/npm" "install" "uNetworking/uWebSockets.js"
14 verbose node v12.5.0
15 verbose npm  v6.13.0
16 error premature close
17 verbose exit [ 1, true ]
```

**Comment by OmgImAlexis** [comment]
Would make sense to tag the latest stable release as `latest` so users won't need to pin a specific version.

**Comment by ChrisGitIt** [comment]
Hi, I'm getting probably the same error with "npm install uNetworking/uWebSockets.js#v17.3.0".

I than just manually downloaded "uWebSockets.js" and added it to my node_modules folder.

But when i cd "./node_modules/uWebSockets.js" and try a "nom install":

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/uWebSockets.js - Not found
npm ERR! 404
npm ERR! 404  'uWebSockets.js@^17.3.0' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
... see the last line: "can no longer contain capital letters" ... is the a major problem for all installs? Your package does not seem to be in the registry ... or how do I do install this?

**Comment by OmgImAlexis** [comment]
@alexhultman why was this closed? You could at least have the courtesy of replying before closing the issue.

**Comment by alexhultman-2fa** [comment]
Hello. I marked this issue won't fix and FAQ. It is courteous to read the frequently asked questions so that I do not have to personally respond to the same questions over and over. Thank you for understanding

**Comment by OmgImAlexis** [comment]
You're not helping yourself here. I read the FAQ. Why not spending the same amount of time and just link me to the issue if it's already been asked.

I would like to use your library, sorry I need a little help.

**Comment by alexhultman** [comment]
@ChrisGitIt what version of npm do you have? I have seen that issue before I think you need to update your npm I have 6.13.4 and no issues here

**Comment by Joncom** [comment]
`npm install uNetworking/uWebSockets.js` results in the `premature close` error.

`npm install uNetworking/uWebSockets.js#v17.4.0` seems to work though.

**Comment by ChrisGitIt** [comment]
Sorry for the late feedback. Will check (and close this issue) shortly with my new project setup!

**Comment by Radiergummi** [comment]
@alexhultman there is neither a link to nor even a mention of the FAQ in the [project readme](https://github.com/uNetworking/uWebSockets.js), [the uWebSockets project readme](https://github.com/uNetworking/uWebSockets) or the ["read more..." link](https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md). The project Wiki is disabled for both. A search for issues labelled with _"FAQ"_ and the term _"npm"_ doesn't bring up anything else related to the topic.

If one crawls the web a little instead, there's two relevant stories hinting at what actually happened: 
 - [Beware of uWebsockets.js!](https://medium.com/@rockstudillo/beware-of-uwebsockets-js-b51c92cac83f) written by Manuel Astudillo, and
 - [The story of “uws” so far](https://medium.com/@alexhultman/the-story-of-uws-so-far-493ac0c05ccb), written by @alexhultman

You claim you don't want to be hold liable for legacy versions of your library, even though it's licensed under the [Apache License 2.0](https://github.com/uNetworking/uWebSockets.js/blob/master/LICENSE). I perfectly understand that, as an Open Source developer, you don't want to be held accountable for bugs in your software, much less so in old versions. However there's neither a precedent here nor does your license choice leave any legal foothold for that.  
Instead, you chose to not distribute uWebSockets via npm but from your GitHub repository instead, providing pre-compiled binary bindings to users. While I absolutely do not want to insinuate any sort of malevolence from your side, this theoretically gives you the opportunity to include malware in your binary bindings without anyone noticing.  

You're free to shrug all this off with a "don't use it then", but if you request courtesy at least have the courtesy to make the situation clear for users of your library, _which you chose to publish on the internet for others to use_. If you decide to do things differently than the rest of the entire software world, at least include a notice about what is going on and why. Don't just close issues and point to a non-existent FAQ.

**Comment by hst-m** [comment]
@Radiergummi You are getting all upset for no reason. There is clearly an [install section](https://github.com/uNetworking/uWebSockets.js#package-install-anywhere) in the readme where it says to do `npm install uNetworking/uWebSockets.js#v18.3.0` which I just ran and works fine.

If you want to compile it from source which is what I do you simply run `git clone --recurse-submodules https://github.com/uNetworking/uWebSockets.js` and then run `make`. I am confused why you are all upset and wrote this large rambling paragraph. Does this help your issue?

**Comment by alexhultman** [comment]
> While I absolutely do not want to insinuate any sort of malevolence from your side, this theoretically gives you the opportunity to include malware in your binary bindings without anyone noticing.

In Sweden - best country on earth - we have laws of "Förtal" where slanderous rumors that end up hurting a company or person are penalized by the relative damages. You say you don't want to spread rumors, yet you indirectly hint of such a possibility - causing rumors among people who are as incompetent with **basic unix tools** as you.

That's right - I'm legally allowed to call you incompetent, because being incompetent is not a **crime** as the act of "Dataintrång" is, which you're spreading rumors about.

**Comment by alexhultman** [comment]
I also want to add that in Sweden - best country on earth - you **are** allowed to spread **any** defamatory information, even regarding the very king himself, if it is **true**. So please, find this supposed malware and pop this supposed conspiracy wide open.

Binaries - they are clearly magical containers of uninterpretable secrecy! Your CPU and kernel dail God himself on Viber to ask how to read this magical sorcery no man will ever understand - every time you double click anything on your desktop.

Did you compile Node.js from source? Did you compile your compiler from source? Did you compile your compiler compiler from source? Did you call the president of Zimbabwe and tell him to change his socks?

Clearly, we have a conspiracy here! Also, Earth is a triangle!

![image](https://user-images.githubusercontent.com/3397140/87465512-165c9300-c615-11ea-8724-e02d87e84645.png)
