### ISSUE TITLE
This version of µWS is not compatible with your Node.js build

### ISSUE THREAD

**Issue by marcoippolito** [uNetworking/uWebSockets.js#297]
I installed uWebSockets.js and imported in the vue file:

nano /src/components$ nano Peerjs.vue  : 

    <script>
    import * as uWebSockets from "uWebSockets.js";
    uWebSockets.App();

But when compiling with npm run serve I get this warning message:

    warning  in ./node_modules/uWebSockets.js/uws_linux_arm64_72.node

    Module parse failed: Unexpected character '' (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to
    process this file. See https://webpack.js.org/concepts#loaders
    (Source code omitted for this binary file)

     @ ./node_modules/uWebSockets.js sync ^\.\/uws_.*\.node$
     @ ./node_modules/uWebSockets.js/uws.js

As suggested here: https://webpack.js.org/concepts/#loaders
I installed different loaders but the problem persists:

        "module": {
            "rules": [
                {
                    "test": /\.vue$/,
                    "exclude": /node_modules/,
                    "use": "vue-loader"
                },
                {
                    "test": /\.pem$/,
                    "use": "file-loader"
                }
            ],
        "rules": [
            {
                "test": /\.uws_.*$/,
                "use": ["script-loader", "raw-loader", "style-loader"]
            }
        ],

In console.log I get also this error:

    uws.js?8992:31 Uncaught Error: This version of µWS is not compatible with your Node.js build:

    TypeError: Cannot read property 'modules' of undefined
        at eval (uws.js?8992:31)
        at Object.eval (uws.js?8992:33)
        at eval (uws.js:35)
        at Object../node_modules/uWebSockets.js/uws.js (chunk-vendors.js:1596)
        at __webpack_require__ (app.js:785)
        at fn (app.js:151)
        at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader 
    /dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components  
    /Peerjs.vue?vue&type=script&lang=js&:10)
        at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./ 
    node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components
    /Peerjs.vue?vue&type=script&lang=js& (app.js:886)
        at __webpack_require__ (app.js:785)
        at fn (app.js:151)

vue info

    Environment Info:

      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
        Yarn: 1.22.4 - ~/.nvm/versions/node/v12.15.0/bin/yarn
        npm: 6.14.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Browsers:
        Chrome: 81.0.4044.122
        Firefox: 75.0
      npmPackages:
        @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
        @vue/babel-plugin-transform-vue-jsx:  1.1.2 
        @vue/babel-preset-app:  4.2.3 
        @vue/babel-preset-jsx:  1.1.2 
        @vue/babel-sugar-functional-vue:  1.1.2 
        @vue/babel-sugar-inject-h:  1.1.2 
        @vue/babel-sugar-v-model:  1.1.2 
        @vue/babel-sugar-v-on:  1.1.2 
        @vue/cli-overlay:  4.2.3 
        @vue/cli-plugin-babel: ^4.1.2 => 4.2.3 
        @vue/cli-plugin-eslint: ^4.1.2 => 4.2.3 
        @vue/cli-plugin-router:  4.2.3 
        @vue/cli-plugin-vuex:  4.2.3 
        @vue/cli-service: ^4.1.0 => 4.2.3 
        @vue/cli-shared-utils:  4.2.3 
        @vue/component-compiler-utils:  3.1.1 
        @vue/preload-webpack-plugin:  1.1.1 
        @vue/web-component-wrapper:  1.2.0 
        bootstrap-vue: ^2.10.1 => 2.10.1 
        eslint-plugin-vue: ^6.2.1 => 6.2.1 
        portal-vue:  2.1.7 
        vue: ^2.6.10 => 2.6.11 
        vue-eslint-parser:  7.0.0 
        vue-functional-data-merge:  3.1.0 
        vue-hot-reload-api:  2.3.4 
        vue-loader:  15.9.0 
        vue-qrcode-reader: ^2.1.1 => 2.1.1 
        vue-qriously: ^1.1.1 => 1.1.1 
        vue-router: ^3.1.6 => 3.1.6 
        vue-style-loader:  4.1.2 
        vue-template-compiler: ^2.6.10 => 2.6.11 
        vue-template-es2015-compiler:  1.9.1 
        vuetify: ^2.2.20 => 2.2.20 
        vuex: ^3.1.3 => 3.1.3 
      npmGlobalPackages:
        @vue/cli: 4.2.3

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by alexhultman** [comment]
It's not a front end project. You've ignored so much written text to end up here.

**Comment by marcoippolito** [comment]
@alexhultman Would you please be so kind to indicate me some of the information I should gain before ending up here? I'm willing to learn.
Thank you in advance
