### ISSUE TITLE
Any way to see the list of channels a client is subscribed to or the list of clients subscribed to a channel?

### ISSUE THREAD

**Issue by smnzhu** [uNetworking/uWebSockets.js#305]
What is the easiest way for me to to see the list of channels a client is subscribed, as well as the list of clients subscribed to a channel?

For example, before allowing a client to publish to a channel, I may want to check that it is first subscribed to the channel

**Comment by mikeandtherest** [comment]
I think this was answered before. The only way, for now at least, to achieve that, is to track it yourself with lists/dictionaries.

**Comment by smnzhu** [comment]
I see. The library itself must keep track of this information somewhere though, right? Is it just not possible to access this information?

**Comment by alexhultman** [comment]
It's not possible right now, but something like that could be added.

**Comment by alexhultman** [comment]
There is an issue for this in the main repo. Please subscribe to that issue. I'm closing this one
