### ISSUE TITLE
Install instructions unclear

### ISSUE THREAD

**Issue by ernest4** [uNetworking/uWebSockets.js#309]
i was driven nearly mad with this, running the install command on the Readme as is

`npm install uNetworking/uWebSockets.js#v17.4.0`

does not work. It produces an error:

`zsh: no matches found: uNetworking/uWebSockets.js#v17.4.0`

turns out you need quotes, which i've never seen needed anywhere else for npm commands before:

`npm install 'uNetworking/uWebSockets.js#v17.4.0'`

Can you please update the Readme to reflect that? Thanks

**Comment by jessereitsma** [comment]
Works for me though (Windows 10, npm v6.13.1)
Perhaps it has something to do with zsh? Maybe you can try without

**Comment by alexhultman** [comment]
We can wait and see if anyone else has this issue. I've never heard of this issue before.

**Comment by danielbarion** [comment]
Hi guys, I'm having the same problem.. `npm install uNetworking/uWebSockets.js` to get the latest version doesn't work and I just found this command in this issue...


Installed now with `npm install uNetworking/uWebSockets.js#v17.6.0` but the readme doesn't have that information and search by 'npm uWebSockets.js' just brig me to https://www.npmjs.com/package/uws
