### ISSUE TITLE
app.use

### ISSUE THREAD

**Issue by dekdevy** [uNetworking/uWebSockets.js#31]
Are you planning on implementing `app.use` functionality in the router?
```js
app.use((req, res, next)=>{ next() })  

app.use('/path', handler)
```
This would make it possible for developers to easily replace their current framework such as polka with µWS.

**Comment by alexhultman** [comment]
I don't get why it has to be part of the library itself. It's just function changing, you can do that simply by calling functions in a chain?

**Comment by alexhultman** [comment]
It's way more incompatible than that. You can't just replace Express with this lib, you'll have to make changes throughout. It's not intended to be compatible with Express, just offer similar basic features.

**Comment by aadityataparia** [comment]
I think if we want to make it easier for developers to switch to uWS, it will be better. Lesser the friction, better it is.

**Comment by aadityataparia** [comment]
@alexhultman The main difference here, I think is `use` matches all types of route (GET, POST, PUT, etc.., but uWS doesn't without copying the code for every type of route.

**Comment by ansarizafar** [comment]
There are so many connect/express middleware available on npm and every nodejs application use these middlewares. If somehow we can use these available middlewares with amazing UWS then I will replace expressjs,polkajs with UWS immediately.

**Comment by alexhultman** [comment]
So putting your chain of "middleware" in a function, then calling that function in your routes (1 line of code per route) is too much work?

It's like, the basics of programming -> functions. You put code, you call code.

If you want something to happen for all methods, it makes sense to add "app.all" as a route that matches all methods. That makes sense. Middleware does not make sense to me.

**Comment by alexhultman** [comment]
No available "middleware" is going to be compatible with this project. This project is completely different and will absolutely not be compatible with available code. Absolutely not.

**Comment by aadityataparia** [comment]
👍 `.all` works for me!

**Comment by alexhultman** [comment]
app.all makes perfect sense.

**Comment by alexhultman** [comment]
However app.all will "eat" all requests, right?

So app.all(/*).get(/hello) will eat /hello in the .all handler, yes?

**Comment by aadityataparia** [comment]
No, I meant `.all('/abcd', (res, req) => { res.end('abcd') })` will respond `abcd` for all these requests:
```
GET /abcd
PUT /abcd
POST /abcd
... etc
```

**Comment by dvergeylen** [comment]
`.any` might be cleaner in that sens then 🤔

**Comment by alexhultman** [comment]
@aadityataparia That's what I mean also.
@dvergeylen That makes sense too, it's a perspective thing, doesn't really matter.

**Comment by kyle-mccarthy** [comment]
@alexhultman I think that some sort of `use` function should be added, this basically lets the developer intercept the request and apply some sort of context or middleware to it.  For example

```
let count = 0;

app.use('*', (res, req, next) => {
  count += 1;
  req.id = count;
  next();
});

app.get('/abc', (res, req) => {
  // have access to modified res/req
});
```

I understand that you don't intend, nor want people to look at this as a drop in for express, but the middleware idea extends to other libs like fastifty and koa.

The above example is a little trivial but being able to intercept requests would be really helpful for things like authorization.

```
app.use('/api/*', (res, req, next) => {
  try {
    authorizeJwt(req);
  }  catch (e) {
    return res.writeStatus(403).end("Unauthorized");
  }
  next();
});

app.get('/api/user/me', (res, req) => {
  // already authorized
  // authorizeJwt could attach state/context to the request
});
```

**Comment by alexhultman** [comment]
You can do the same like so:

```
app.any('/api/*', (res, req) => {
  try {
    authorizeJwt(req);
  }  catch (e) {
    return res.writeStatus(403).end("Unauthorized");
  }
  req.setYield(true); // we did not handle it, keep matching
});

app.get('/api/user/me', (res, req) => {
  // already authorized
  // authorizeJwt could attach state/context to the request
});
```

This is how websockets are upgraded OR passed over to an http handler. 

I don't think setYield is wrapped. req.yield() could be added. To just say, fall through to next.

**Comment by alexhultman** [comment]
Is authorizeJwt a normal function, or will it async/await/promise?

**Comment by ansarizafar** [comment]
authorizeJwt is async/await/promise in my use case.

**Comment by kyle-mccarthy** [comment]
It could technically be either, it was more of a general example. I think ideally it would be able to use synchronous and asynchronous middlewares. Based on your example maybe I am not understanding something correctly?

```
app
  .any('*', (res, req) => {
    count += 1;
    (req as any).id = count;
    res.onAborted(() => {
      (res as any).aborted = true;
    });
  })
  .get('/', (res, req) => {
    console.log((req as any).id); // undefined?
    res.end(JSON.stringify({ hello: 'world' }));
  })
```

**Comment by alexhultman** [comment]
Can't have async middleware here, it doesn't fit very well with how req works. Middleware can be swapped for a simple funtion call, you just put your auth in a function and call it boom done

**Comment by kyle-mccarthy** [comment]
@alexhultman It looks like I am able to just handle middleware inside my own server that would wrap uWebSockets. Is there any disadvantage/concern to defining a single `app.any('*', ...)` and handling the middleware and routing within that? FWIW I am getting 90k-100k req/sec, this is incredibly fast.

**Comment by alexhultman** [comment]
I'm closing this, "middleware" in the sense of having app.use with async middleware does not fit this lib - you have to put your "middleware" in a function and call it

**Comment by aadityataparia** [comment]
> I don't think setYield is wrapped. req.yield() could be added. To just say, fall through to next.

👍

**Comment by coder456** [comment]
I find it best to just do `.any('*',(res,req)=>{` and handle all requests with whatever js is needed, can implement any structure needed, don't really need anything else
```
.any('*',(res,req)=>{
  const method=req.getMethod()
  const path=req.getUrl()
  if(method=='get'){
    if(path=='/){ }
    if(path=='/123){ }
  }
}
```

**Comment by slavaGanzin** [comment]
> No, app.use will only serve to fool users into thinking it is Express, then make them demand it to be Express.


@alexhultman Hell yeah. I think this point should be clarified in README. It's not "Express, but faster" and it will never be. And maybe it will suppress all this "may I use express middleware" requests. 

For example you shouldn't use [serve-static](https://github.com/expressjs/serve-static) if you want speed. But everybody used to use it. So you will end up with fastest server running slowest code.


Generally I think `app.use`-like way is preferred for many use cases. For example, when I need basic auth for uWS I created objects with routes:
```js
routes = {
get: [['/signin', ()=>{}], [['/signup', ()=>{}], ['/', () => {}]],
post: [['/signin', ()=>{}], [['/signup', ()=>{}]],
}
//And then
for (const method in routes) {
    for (const f in routes[method]) {
       app[method](f[0], compose(f[1], basicAuth))
    }
}
```

Where `basicAuth` is middleware and `compose` is composition function. And all of this extremely harder then express(and Django and many others)-way:
```js
app.use(basicAuth)
app.get('/signin', () => {})
app.post('/signin', () => {}) 
```

I'm perfectly fine with my code, but I think it's hard for unexperienced developer to develop the same. And, even for me, it's annoying to copy this code from one project to another.

So I think this pre-hook and post-hook approach may be implemented in uWS. Because it's basic server functionality.

> Can't have async middleware here, it doesn't fit very well with how req works. 

As I understand it's ambiguous when to call `res.end`? And you can't use `res` destructor because it will harm speed?

**Comment by slavaGanzin** [comment]
Generally I think `app.use`-like way is preferred for many use cases. For example, when I need basic auth for uWS I created objects with routes:
```js
routes = {
get: [['/signin', ()=>{}], [['/signup', ()=>{}], ['/', () => {}]],
post: [['/signin', ()=>{}], [['/signup', ()=>{}]],
}
//And then
for (const method in routes) {
    for (const f in routes[method]) {
       app[method](f[0], compose(f[1], basicAuth))
    }
}
```

Where `basicAuth` is middleware and `compose` is composition function. And all of this extremely harder then express(and Django and many others)-way:
```js
app.use(basicAuth)
app.get('/signin', () => {})
app.post('/signin', () => {}) 
```

I'm perfectly fine with my code, but I think it's hard for unexperienced developer to develop the same. And, even for me, it's annoying to copy this code from one project to another.

So I think this pre-hook and post-hook approach may be implemented in uWS. Because it's basic server functionality.

> Can't have async middleware here, it doesn't fit very well with how req works. 

As I understand it's ambiguous when to call `res.end`? And you can't use `res` destructor because it will harm speed?

**Comment by aadityataparia** [comment]
> Where basicAuth/postHook are middlewares and compose is composition function. And all of this extremely harder then express(and Django and many others)-way:

I think this can be done using `yield` wrapper as Alex mentioned.

**Comment by YamiteruXYZ** [comment]
What do you think about this approach? Is it a good DX?
```typescript
any("/*").rateLimit(5, 1000);

post("/article/:authorName")
    .matchSchema(articleSchema)
    .handle(({ res, { params, body } }) => {
        const [ authorName ] = params;

        return ArticleService
            .create(authorName, body)
            .then(article => res.code(200).send(article))
            .catch(error => res.code(400).send(error));
    });
```

**Comment by endel** [comment]
I have been working on uWebSockets.js/Express compatibility layer and made it available here: https://github.com/endel/uWebSockets-express

Discussion thread: https://github.com/uNetworking/uWebSockets.js/discussions/565

I hope this will be useful to allow transitioning existing projects into uWebSockets.js, and eventually allowing you to migrate over without using the compatibility layer at all. It is meant to be a transitionary solution.

**Comment by a-tonchev** [comment]
I manage successfully to migrate all my projects from KOA to uWS, without any external library - and I like it really much. 

Here is a link how I did it: 

https://dev.to/atonchev/migrating-from-koa-to-uwebsocketsjs-in-less-than-2-hours-51h3
