### ISSUE TITLE
Plans to add a HTTP Client implementation?

### ISSUE THREAD

**Issue by timsuchanek** [uNetworking/uWebSockets.js#311]
It seems that if the server part is already very fast, exposing a client would also make sense.

Are there any plans to expose an HTTP client that can be used from Node.js?

Thanks!

**Comment by alexhultman** [comment]
I haven't fully decided yet, but it is very low prio in any case. I'm trying to polish things up for the server side, and there are still big todos on that end. If everything goes smoothly and according to plan, yes, otherwise, no.
