### ISSUE TITLE
Can not build a wss server

### ISSUE THREAD

**Issue by Shinefallen** [uNetworking/uWebSockets.js#315]
I compiled the EchoServer.cpp with WITH_OPENSSL=1 flag successfully. But when i ran EchoServer, it failed directly without output. I debugged it and it didn't stop when executed to app.run(). Thanks~!

**Comment by hst-m** [comment]
![image](https://user-images.githubusercontent.com/65402951/82837680-9de01e00-9e7e-11ea-9e06-14e0b7a5d6df.png)

**Comment by alexhultman** [comment]
What does "failed" mean here? Are you on latest version, did it return? Segfault? I can't make much sense of this report.

**Comment by Shinefallen** [comment]
> What does "failed" mean here? Are you on latest version, did it return? Segfault? I can't make much sense of this report.

Sorry i was confused with uWebSockets.js and uWebSockets. I compiled the uWebSockets.
