### ISSUE TITLE
cors request

### ISSUE THREAD

**Issue by MoJongleur** [uNetworking/uWebSockets.js#316]
I could not find any information at all on this topic, is it even possible to setup cors in uWS.js? since I need server permission to accept a request from a specific Url but there is simply no information about this.

I'm trying to just get data from a GET server with a request with a cors header, 
but I get: net :: ERR_EMPTY_RESPONSE

**Comment by mattiasewers** [comment]
Why do think it would not be possible? There is a ton of information on the internet about this, have you tried to google cors?

Seems like you do not know what cors is to begin with.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by MoJongleur** [comment]
On stackoverflow could get rid of such comments (go to google), but unfortunately they still remained here. Naturally, I already read this information on mdn, and yes, I'm not a backend developer, maybe I don’t understand something, I look at the analogue of uWS (express) and I see the use of middleware there for such purposes, and try to understand how I can do something like this in uWS.

> Why do think it would not be possible? There is a ton of information on the internet about this, have you tried to google cors?
> 
> Seems like you do not know what cors is to begin with.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by mattiasewers** [comment]
@MoJongleur uws does not have middlewares, so you need to write that yourself. How cors works I suggest you take a look how express is doing it https://github.com/expressjs/cors/blob/master/lib/index.js is a good start

I suggest you learn more about how express works internally (which is not that complicated) and basic backend stuff

**Comment by alexhultman** [comment]
Isn't this really just setting a header to your response?

**Comment by MoJongleur** [comment]
> Isn't this really just setting a header to your response?

Initially, I thought so, but my poor understanding of the topic did not allow me to understand that this should be done not only in GET but also in OPTION.

Anyway, thanks to everyone for the advice, and sorry for such stupid questions)

**Comment by alexhultman** [comment]
Once we have github discussions here we can have a more stackoverflow-ish community where anything goes.
