### ISSUE TITLE
Passing value from 'upgrade' to 'open' handler

### ISSUE THREAD

**Issue by PlainBane** [uNetworking/uWebSockets.js#322]
Hello,
Is there a way to do something like this:

` upgrade: (res, req, context) => {`
 `   userId = req.getFromCookiesToken();`
`    if(userId) {`
 `// Upgrade to Websocket`
`}`

` open: (ws) => {`
  `ws.uid = userId; // Passed from upgrade handler. <--- Can this be done?`
`}`

**Comment by PlainBane** [comment]
Found the answer. I'm blind.
`res.upgrade({url: url,` **customValueHere** `}, secWebSocketKey, secWebSocketProtocol, secWebSocketExtensions, context);`

**Comment by alexhultman-2fa** [comment]
Haha, great 👍
