### ISSUE TITLE
domain.enter is not a function

### ISSUE THREAD

**Issue by supahero1** [uNetworking/uWebSockets.js#325]
1.14.4 nodejs
doesn't work both on windows 10 (latest version 64bit) and on linux centos8 4.18.0-147.8.1.el8_1.x86_64

`npm install uNetworking/uWebSockets.js#v18.1.0`

>"use strict";
const uWS = require('uWebSockets.js');
const backpressure = 0;
uWS.App({}).ws('/*', {
  compression: uWS.SHARED_COMPRESSOR,
  maxPayloadLength: 16 * 1024 * 1024,
  idleTimeout: 0,
  open: (ws) => {
    console.log('A WebSocket connected!');
  },
  drain: (ws) => {
    console.log("drained")
  },
  close: (ws, code, message) => {
    console.log('WebSocket closed');
  },
  message: (ws, data, isBinary) => {
    console.log("got a new message")
  }
}).any("/*", function(res, req) {
  res.end("Nothing to see here.");
}).listen(8080, (token) => {
  if (token) {
    console.log('Listening to port ' + 8080);
  } else {
    console.log('Failed to listen to port ' + 8080);
  }
});`

Then make a new WebSocket using for instance browser's console and connect to the server.
It will throw the following error:
> domain.js:136
    domain.enter();
           ^

TypeError: domain.enter is not a function
    at topLevelDomainCallback (domain.js:136:12)

The problem does not appear with, for instance, `websocket` npm package which provides server functionality too.

The problem appears always, not randomly.

https://stackoverflow.com/questions/62358947/node-js-typeerror-domain-enter-is-not-a-function
For eventual extra information, but I do not think it is revelant.

**Comment by alexhultman-2fa** [comment]
https://github.com/uNetworking/uWebSockets.js/issues/282

Thanks for reporting, this only happens in REPL mode. If you instead put that JavaScript in a file and run it, it will work. I can only trigger your issue if I paste that code in REPL mode, not int regular run mode.

Node.js 14 had major performance loss compares to 13 in this regard, so maybe I should benchmark that thing again maybe it runs faster in 14?

**Comment by alexhultman-2fa** [comment]
I've benchmarked that for Node.js 14 and it doesn't fix the performance. I've tried to contact Node.js people to report this major performance bug but I guess they rather ban me than listen to me. I can't fix Node.js being run by a bunch of PC babies who can't take civil criticism of technical issues. Therefore, wontfix
