### ISSUE TITLE
Extend res object with async method

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#328]
Hi,

I want to extend res object with async method, like this:
```
res.sendStrream = async function (path) {...}

// then in http request handler:
uws.get("/", (res) => {
    res.sendStream(path);
})
```
But getting this error at runtime, when calling this new method:
```
(node:44040) UnhandledPromiseRejectionWarning: Using uWS.HttpRequest past its request handler return is forbidden (it is stack allocated).
(
(
```

Is it possible to avoid this error?

**Comment by alexhultman-2fa** [comment]
> Using uWS.HttpRequest past its request handler return is forbidden (it is stack allocated).

This is a message for you to read. When you await anything, that's technically a return. So you cannot use the HttpRequest after this point, you have to copy out whatever you want to keep before you return or await.
