### ISSUE TITLE
Is it safe to send large buffer with res.end()?

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#329]
Hi.
I have relatively large data, that is already in memory.
In your examples I see, that you send video file with res.end().
So my question - is it safe to just call end(buffer) or I need to use tryEnd() + onWritable() combination?
Thank you.

**Comment by alexhultman** [comment]
I never send video files with res.end. I have an example that explicitly say in bold letters at the top to NEVER do this. So no, the answer is absolutely not.

**Comment by alexhultman** [comment]
```
/* This is an example of sync copying of large files.
 * NEVER DO THIS; ONLY FOR TESTING PURPOSES. WILL CAUSE
 * SEVERE BACKPRESSURE AND HORRIBLE PERFORMANCE.
 * Try navigating to the adderss with Chrome and see the video
 * in real time. */
```

and

````
console.log('WARNING: NEVER DO LIKE THIS; WILL CAUSE HORRIBLE BACKPRESSURE!');
````

cannot be any more obvious even if I hut you in the head with a hammer, yelling in a megaphone

**Comment by zdm** [comment]
sorry, i didn't saw cautions in example. ok, thanks.

**Comment by alexhultman** [comment]
It's literally the first line in the file and you even have a runtime console log in capital letters you must be entirely incapable of reading text to miss it so why should I write MORE text here when you dont read the fucking text already written fuck me
