### ISSUE TITLE
stream long string with res.end() vs res.tryEnd()

### ISSUE THREAD

**Issue by hst-m** [uNetworking/uWebSockets.js#330]
I saw @zdm ask related question about sending out data with `res.end()` vs `res.tryEnd()`

In my case I have similar situation where I have a long string of data in Json format to send out, usually around 400k bytes. Technically it works with `res.end()` but if you use `res.tryEnd()` it breaks it down into chunks which I believe is preferred

I coded a function that can be re-used for streaming out a long string response, taken from the VideoStreamer.js example but simplified for the case of pre-loaded string, in case anyone needs something similar. This is better for [Discussions ](https://github.com/uNetworking/uWebSockets/issues/1048) page but that is not out yet so can close this issue, or if anyone thinks this code is not good I will update it

```javascript
// example function sends out 1MB long string, breaking down into chunks as needed

uws.App().any('/*', (res, req) => {
    const longString = 'x'.repeat(1000000) // 1000 kilobyte long string
    resStreamString(res, longString)
})

const resStreamString = (res, str) => {
    const totalSize = str.length // only use length if using simple/ASCII text, otherwise use: totalSize = new TextEncoder().encode(str).length
    const [ok, done] = res.tryEnd(str, totalSize)
    if (ok) return
    res.data = str
    res.onWritable(offset => {
        const [ok, done] = res.tryEnd(res.data.slice(offset), totalSize)
        return ok
    })
    res.onAborted(() => res.aborted = true) // onAborted required for async responses
}
```
if you add console logs for tryEnd for that example you get:
> tryEnd(data, totalSize:1000000): ok: false, done: false
tryEnd(data.slice(110916), totalSize:1000000): ok: false, done: false
tryEnd(data.slice(267136), totalSize:1000000): ok: false, done: false
tryEnd(data.slice(462776), totalSize:1000000): ok: false, done: false
tryEnd(data.slice(700756), totalSize:1000000): ok: false, done: false
tryEnd(data.slice(982536), totalSize:1000000): ok: true, done: true

looks like anything over 110KB gets broken down into chunks so anything over that size you would want to use this for. I just coded this today because I need to use this for my API

**Comment by zdm** [comment]
Thank you, I already wrote similar code

**Comment by hst-m** [comment]
I think my question would be, I think this 110KB first chunk might depend on server load? so should this be used for smaller sizes as well, at what size should this be used for, or just use it for every string because its a simple function?
