### ISSUE TITLE
SSL broken in 18.2

### ISSUE THREAD

**Issue by yovanoc** [uNetworking/uWebSockets.js#333]
Hello since the 18.2 I can't start my server anymore

<img width="702" alt="image" src="https://user-images.githubusercontent.com/7302317/85406077-8c636200-b561-11ea-8697-c8a66271aa0b.png">

**Comment by alexhultman** [comment]
I can trigger this with 18.2 but not with 18.1. It fails when you call uWS.SSLApp(). Don't know why this function wouldn't be defined anymore - will check

**Comment by alexhultman** [comment]
Fixed with v18.3.0. Thanks for reporting
