### ISSUE TITLE
"Apple Silicon" on GitHub Actions

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#334]
GitHub Actions does have Windows, macOS and Linux VMs, so swapping from AppVeyor & TravisCI to only using GitHub Actions could be a good decision now that we need to build ARM64 binaries for macOS anyways.

This requires Xcode 12 and I bet GH actsions will be the first to add such a support.

**Comment by dalisoft** [comment]
But Intel Mac users still using this project or you support only ARM builds for macOS?

**Comment by alexhultman** [comment]
Well yes, obviously. You just add arm64

**Comment by alexhultman-2fa** [comment]
There is xcode 12 on GitHub actions now

**Comment by alexhultman** [comment]
I've ported AppVeyor, TravisCI over to GitHub Actions now. Xcode 12 is still beta 6 on GitHub Actions and I've not managed to build arm64 binaries yet, but it should be simple when we want to add it now that everything lives on GitHub and nothing else.

**Comment by alexhultman** [comment]
In October when Node.js 15 releases, GitHub Actions should have XCode 12.2 so that ARM64 binaries can be built. This could be released together. Also, older binaries might get deprecated and removed.

**Comment by alexhultman** [comment]
I've built Node.js 15 binaries from a nightly version and it works, so should be no issue adding Node.js 15 when it releases.

**Comment by l10r** [comment]
> I've built Node.js 15 binaries from a nightly version and it works, so should be no issue adding Node.js 15 when it releases.

It has been released, Waiting for a version that supports it ^^

**Comment by alexhultman** [comment]
Node.js 15 is supported now, ARM64 for macOS will have to wait
