### ISSUE TITLE
Rate limit for websocket messages (add an example)

### ISSUE THREAD

**Issue by uasan** [uNetworking/uWebSockets.js#335]
Hi.
There is an idea how to implement prevent spam (aka DDoS) messages on a socket?

We use Redis to control of message speed, for example - non than 100 messages per second for one client, but the solution Redis, is a narrow neck, is there a better idea?

Thanks.

**Comment by hst-m** [comment]
the `RateLimit` function is very helpful for limiting different types of ws messages and also [http requests](https://github.com/uNetworking/uWebSockets.js/issues/464#issuecomment-782792022), I use it in my apps for both cases, could potentially add it to the uWS.js library to save me 1 line of code and make it easy for other people to use:
```javascript
const limit = uWS.RateLimit(1, 1000) // creates a function that returns true when passed an object over the limit per interval

app.ws('/', {
   message: (ws, message) => {
      if (limit(ws)) console.log('over limit')
   }
})
```

**Comment by SuspiciousLookingOwl** [comment]
For TypeScript folks, since TypeScript doesn't allow indexing with symbol ([yet](https://github.com/microsoft/TypeScript/issues/1863)), you have to assert the `last` and `count` as `string` 

```ts
import { WebSocket } from "uWebSockets.js";

const RateLimit = (limit: number, interval: number) => {
	let now = 0;
	const last = (Symbol() as unknown) as string;
	const count = (Symbol() as unknown) as string;
	setInterval(() => ++now, interval);
	return (ws: WebSocket) => {
		if (ws[last] != now) {
			ws[last] = now;
			ws[count] = 1;
		} else {
			return ++ws[count] > limit;
		}
	};
};
```

**Comment by hst-m** [comment]
TypeScript is annoying I never use it for anything, the last comment in your link describes the negatives, and it adds a ton of extra code when the reason I use JS is I want the least amount of code possible, I don't need my hand held with bunch of type descriptions, what is someone supposed to think when they see this? what does this even mean?
```javascript
const count = (Symbol() as unknown) as string;
```
when you write this, now you lose the flexibility to use this function for objects other than websocket objects, see the http limit exmaple above

**Comment by SuspiciousLookingOwl** [comment]
To Each Their Own 😬

**Comment by hst-m** [comment]
I am kind of amazed there is no basic support for Symbol, that issue been open for 6.5 years and they still trying to figure out how to make it work, they push it back every release, some of these comments are pretty funny though

![image](https://user-images.githubusercontent.com/65402951/117583626-0d194700-b0bd-11eb-9926-9733c0a66d3b.png)

![image](https://user-images.githubusercontent.com/65402951/117583643-23bf9e00-b0bd-11eb-8d05-eb6c702e26dc.png)

![image](https://user-images.githubusercontent.com/65402951/117583771-e90a3580-b0bd-11eb-9e5b-05e9f9fd53c4.png)

**Comment by alexhultman-2fa** [comment]
Should we add this as an example RateLimit.js and close this issue?

**Comment by alexhultman** [comment]
Can someone add this example?

**Comment by e3dio** [comment]
I could do a combined middleware + ratelimit example, all my code is compressed down tho need to match existing style

**Comment by MehdizadeMilad** [comment]
hey Alex, I like to help, I'll send a pull request today or tomorrow.

**Comment by MehdizadeMilad** [comment]
here it is: #566
