### ISSUE TITLE
Path is mismatching?

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uWebSockets.js#336]
Hi.
I found bug related to `uWS.App()` methods (get, post)

## Code

```js
import uWS from 'uWebSockets.js';

const app = uWS.App();

app.get('/', (res) => {
  res.end('hello world');
});

app.get('/foo/', (res) => {
  res.end('hello at /foo/');
});

app.get('/bar', (res) => {
  res.end('hello at /bar');
});

app.listen(
  4000,
  (token) => token && console.debug('server started at port', 4000)
);
```

## Test

1. Run the code above
2. Go-to browsers and try to run these urls

|URL|Passing|Error|
|-|-|-|
|`/foo`|No|Yes|
|`/foo/`|Yes|No|
|`/bar`|Yes|No|
|`/bar/`|No|Yes|

## Question

Is there possible to define path which works both with `/foo` and `/foo/` or `/bar` and `/bar/`?

Thanks for best project

**Comment by hst-m** [comment]
ya just do this:
```javascript
const handler = (res, req) => res.end(`hello at ${req.getUrl()}`)
app.get('/foo', handler)
app.get('/foo/', handler)
```

can also do this way, I prefer to process the path/method in the js part of `any('/*')` handler:
```javascript
app.any('/*', (res, req) => {
  const method = req.getMethod()
  const path = req.getUrl()
  switch(path) {
    case '/foo':
    case '/foo/':
      return res.end(`hello at ${path}`)
  }
  return res.writeStatus('404').end()
})
```

**Comment by hst-m** [comment]
Also see this issue: https://github.com/uNetworking/uWebSockets/issues/1049#issuecomment-626508774

trailing slash is considered a different URL so it's not a bug, a solution could be to check for trailing slash in your handler and redirect to non-trailing slash url

```javascript
app.any('/*', (res, req) => {
  const host = req.getHeader('host')
  const path = req.getUrl()
  const query = req.getQuery()
  if(path.endsWith('/')) return res.writeStatus('301').writeHeader('Location','https://'+host+path+query).end()
  // handle rest here
})
```

**Comment by dalisoft** [comment]
@hst-m Thanks for temporarily solution, but it worked before (not remember on which version).
But recently got new bug at [here](https://github.com/nanoexpress/pro/issues/41) and myself also faced this issue

**Comment by dalisoft** [comment]
I fixed it in my project new [release](https://github.com/nanoexpress/pro/releases/tag/v2.0.2) with [hot-fix temporarily solution](https://github.com/nanoexpress/pro/commit/5b24de2edaaca383df895ff2b8784659140eba98).

I'm think will be correct if this behavior fixed, but i may be wrong as i don't have enough experience in HTTP Specs.
Anyway thank you @hst-m for fast reply

**Comment by hst-m** [comment]
ok just to note, they are different urls can read here: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

but looks like you got a fix for your project 👍

**Comment by dalisoft** [comment]
As i know, express exposes on both slash and without slash
