### ISSUE TITLE
req removed from ws open handler

### ISSUE THREAD

**Issue by acharkov** [uNetworking/uWebSockets.js#339]
I used _req_ from _open_ handler to get the real client address in case of proxy.
My old code was like this (at least in version 17.4.0)
```
open: (wsConn, req) => {
   ...
   this.ip = req.getHeader('cf-connecting-ip') || remoteAddressToString(conn.getRemoteAddress())
}
```
but in latest version _open_ handler is changed - _req_ removed. How I could get proxied ip for websocket connection in this case?

**Comment by hst-m** [comment]
there are recent issues for this, see here https://github.com/uNetworking/uWebSockets.js/issues/322
https://github.com/uNetworking/uWebSockets.js/releases/tag/v18.0.0
https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#upgrade
https://unetworking.github.io/uWebSockets.js/generated/interfaces/httpresponse.html#upgrade

but this is how you get the ip:
```javascript
// pass values from ws upgrade handler

uws.App().ws('/', {
   upgrade: (res, req, context) => {
      res.upgrade(
         { ip: res.getRemoteAddress() }, // properties here passed to ws object
         req.getHeader('sec-websocket-key'),
         req.getHeader('sec-websocket-protocol'),
         req.getHeader('sec-websocket-extensions'),
         context
      )
   },
   open: (ws,req) => {
      console.log(ws.ip)
   }
})
```

**Comment by alexhultman** [comment]
Alright
