### ISSUE TITLE
Major performance regression in Node.js 14

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#340]
Here's a bit of history for you,

In 2016 I reported a performance issue with node::MakeCallback. I posted scientific measurements supporting my claim. Node.js people said that they knew things much better than I do and that there are no performance issues with node::MakeCallback.

Then of course they did find, and eventually fix this bug I reported, but by that time I had been permanently banned. So my first encounter with these Node.js people ended with me being permanently banned.

Now in 2020, I'm still banned, and they even ban my secondary account (@alexhultman-2fa), so I cannot contact them to submit bugs.

The issue here is that node::MakeCallback is the single most critical gateway for any native code (addon, or Node.js itself). It's the only Node.js function that is obligatory and has to be used. Everything else can be done with vanilla, native V8 calls.

As of Node.js 14, the difference between calling from native land to Node.js using `node::MakeCallback` and the vanilla V8 counterpart `Local<Function>:Call` is 28%. Prior to Node.js 14 (13, 12, 11, 10) this overhead used to be about 5% (after they fixed my initial bug report).

Now, recently I have measured a major drop introduced in Node.js 14 and forwards, and I've even reported a suspected commit that happened just in time for 14, and that majorly refactors the node::MakeCallback related code.

This issue report I did with my secondary account, but they quickly hid the report/question and banned that account as well.

----

So, because I know what I'm talking about when it comes to overhead of node::MakeCallback (it has been a nail in my eye for 5 years now), I need someone to report this issue to the Node.js people and drive the issue. I cannot do it, because I'm banned and they do not want my input.

# Scientific facts
Just like always, I deal with science in everything I do. I do not make claims that have no scientific backing.

In Node.js 13, 12, 11, and 10 - we can benchmark a simple hello world program that is entirely bottlenecked by nothing other than node::MakeCallback. We know this because running the same program with EXPERIMENTAL_FASTCALL, which does nothing but swap node::MakeCallback with the vanilla V8 `Local<Function>::Call` counterpart, presents increasingly deviating results:

The results from Node.js 10, 11, 12, 13 with node::MakeCallback are roughly:

```
Running 10s test @ http://localhost:9001
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    81.12us   27.14us 425.00us   83.48%
    Req/Sec    61.50k     8.71k   83.21k    69.80%
  1235471 requests in 10.10s, 80.12MB read
Requests/sec: 122330.17
Transfer/sec:      7.93MB
```

And if we enable EXPERIMENTAL_FASTCALL (as described above) we see the following:

```
Running 10s test @ http://localhost:9001
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    77.06us   26.27us   1.40ms   85.54%
    Req/Sec    64.80k     7.25k   76.53k    62.38%
  1302500 requests in 10.10s, 84.47MB read
Requests/sec: 128960.00
Transfer/sec:      8.36MB
```

Which is not a big difference; node::MakeCallback had quite okay peformance prior to Node.js 14, only a minor 5% difference.

While with Node.js 14 they are:

```
Running 10s test @ http://localhost:9001
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   102.41us   32.61us 471.00us   86.56%
    Req/Sec    48.84k     5.70k   61.53k    69.31%
  981155 requests in 10.10s, 63.63MB read
Requests/sec:  97149.85
Transfer/sec:      6.30MB
```

Some 21% lower.

Enabling EXPERIMENTAL_FASTCALL for Node.js 14 (swapping the node::MakeCallback with vanilla V8 function calls as detailed above), we get the following:

```
Running 10s test @ http://localhost:9001
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    78.75us   24.94us 424.00us   85.03%
    Req/Sec    63.16k     7.83k   82.84k    61.39%
  1269292 requests in 10.10s, 82.31MB read
Requests/sec: 125678.17
Transfer/sec:      8.15MB
```

Which is roughly on par with what we had with Node.js 13, 12, 11, 10.

The conclusion is, by changing NOTHING AT ALL, except for swapping node::MakeCallback to vanilla V8 counterparts, we see a small increase in Node.js 10, 11, 12, 13 of 5%-10%.

With Node.js 14, the difference between the two are 28% - we now only see 97k req/sec vs the 122k we saw in prior Node.js versions.

This is a major performance regression, and we have clinically tested NOTHING BUT node::MakeCallback - that's the only single variable here, and results show great deviation -> leading to a conclusion recent code changes in Node.js regarding node::MakeCallback has resulted in major performance regressions.

I would like to see this fixed upstream at Node.js repos, but like explained I do not have the ability to instigate a conversation with these people.

**Comment by alexhultman** [comment]
I did some bisecting and found this kind of drop between v12.16.3 and v12.17.0 as well as between v13.8.0 and v13.9.0.

I also compiled an erly v14.0.0-pre version and it did not have the drop.

Doing a git diff between those tags brings up all kinds of changes to the callback mess.

The thing is, I did not know they backported these changes to old versions - this issue is not about v14 in particular, but it affects the entire Node.js lineup, that still get backported changes.

So the same drop in perf. you can see in later versions of v12, v13 and v14.

This makes it a lot more complicated to say when and where this change was made, and looking at the diff, it's clear that they change a lot of stuff in every single release. Even internal stuff that shouldn't need any changes at all, they edit that and make significant changes.

Therefore, it makes no sense for me to bother with this. I have no say in Node.js, they don't want me there, and if I would try and point fingers at what changes are stupid and what are not - they would kick me out in 2 seconds anyways because it doesn't fit their agenda.

Alright, that makes it simple. I have no say here, and I cannot fix what I don't control.

**Comment by alexhultman** [comment]
It really is a shame they take in people, that do a bunch of internal refactoring to fundamental things - with motivation that it "fixes" stuff and makes the code "better". They really should just stop, never touch anything internal, leave it be.

They really do believe that they are making the code better, and every single release it drops a few percentages here, a few there, and when you settle for mediocre, constantly lowering your standards slightly with every point release, you get worse and worse every day.

We used to be three digits, now we're two digits. And they talk about writing http-parsers in assembly... they are out of their mind. If you cannot even nail a function call, it won't matter the slightest. They're overfocusing on benchmarking C and assembly code and entirely give no fucks for the JavaScript code. Makes a lot of sense to micro-optimize handwritten assembly for a parser that can do 5 million req/sec, when you cannot even deliver 50k function calls a second.

Now we all have to swallow this drop across all versions of Node.js because there is no way you can refuse an update since there are so many security flaws in every release. And they make significant changes to fundamental internal stuff all the time.

It's staggering how much you can over-complicate a function call, while still believe that you make things better. It's micro optimization of things that don't matter, for the cost of things that actually do bottleneck the overall data flow.

Alright, I better stop before I pop an artery.

**Comment by sirganya** [comment]
I’ll report it

**Comment by alexhultman** [comment]
I hope they can take this negative input without interpreting it as personal abuse for the sake of being evil. It's technical and scientific, nothing else.

**Comment by hst-m** [comment]
> We used to be three digits, now we're two digits

I ran helloworld benchmarks on one of these google compute C2 series "compute optimized" with 4 vCpu Ubuntu 20.04 Node v14.5.0 uWebSockets.js v18.3.0 which is what I use in production and get consistent 147k Req/Sec 
`./wrk -t2 -c10 -d10s http://127.0.0.1:3000`

when you throw in some compute per request, I used a JWT cookie decode because all my requests have at least a JWT decode it brings it down to 28k Req/Sec
`./wrk -t2 -c10 -d10s -s s.lua http://127.0.0.1:3000`

using straight Node 14 (no uWS) gives 27k for helloworld and 17k for token decode

I tried switching to Node v12.18.2 got about the same results for all tests, possibly a bit faster but hard to say

**Comment by alexhultman** [comment]
@hst-m That's OT and irrelevant to this issue.
