### ISSUE TITLE
Better checks for callback types

### ISSUE THREAD

**Issue by alexhultman-2fa** [uNetworking/uWebSockets.js#343]
It should not be possible to segfault the process by passing a 3 or something non-function as callback.

A helper function should check this and throw an exception if wrong type

**Comment by alexhultman** [comment]
It is possible to segfault the library by passing wrong number of arguments to publish. This should also be checked.

**Comment by alexhultman** [comment]
There are still issues to fix but the most common cases are fixed and checked now
