### ISSUE TITLE
Unexpected listen result with invalid port

### ISSUE THREAD

**Issue by CDoughty08** [uNetworking/uWebSockets.js#350]
When using `.listen` with only an invalid port
```ts
const port = 'bad port';
uws.App()
  .listen(
    port,
    (token) => {
      if (token) {
        console.log(`Listening on port: ${port}`);
      }
      else {
        console.log(`Failed to start server`);
      }
    });
```
The expected result happens `Failed to start server`

However if a host is specified with an invalid port
```ts
const port = 'bad port';
uws.App()
  .listen(
    '127.0.0.2',
    port,
    (token) => {
      if (token) {
        console.log(`Listening on port: ${port}`);
      }
      else {
        console.log(`Failed to start server`);
      }
    });
```
The result is `Listening on port: bad port` and the server is started as though the port `0` was given.

**Comment by hst-m** [comment]
have you tried using a valid port number instead of a random string? the docs say to pass a number and you are passing a random string https://unetworking.github.io/uWebSockets.js/generated/interfaces/templatedapp.html#listen

**Comment by CDoughty08** [comment]
@hst-m Absolutely, that works as expected. Although IMO if given an invalid port should satisfy the `Listens to hostname & port. Callback hands either false or a listen socket.` rather than falling back as if 0 was given.

Upon a slightly closer look it appears that this binding also passes through undocumented options to the lower level uSockets library as well.

**Comment by hst-m** [comment]
you can see here https://github.com/uNetworking/uWebSockets.js/blob/master/src/AppWrapper.h#L283 it is determining which is the port and which is the host by it being a number or not, and you are throwing it off (purposefully?) by using strings instead of numbers, then you can see below it defaults to zero https://github.com/uNetworking/uWebSockets.js/blob/master/src/AppWrapper.h#L298 if you simply use numbers like supposed to there is no issue, you are saying you want more 'hand-holding' type of thing to cover your incorrect usage?

**Comment by hst-m** [comment]
I'm not sure what the default to zero is about, I supposed you could throw an error if there is no valid port number supplied, would need to ask someone else about that

**Comment by hst-m** [comment]
> asking to bind TCP on port 0 indicates a request to dynamically generate an unused port number

so port zero has a function there. looks like you just need to use a Number as your port. otherwise it thinks you want 'bad port' as your host in your 1st example, or in your 2nd example it doesn't get recognized as a port because its a string so it defaults to zero. make sense?

**Comment by alexhultman-2fa** [comment]
This could be improved with better type checks but it's also possible to follow documented APIs.

**Comment by alexhultman** [comment]
#343 Has the same problematics - types are not checked very strictly
