### ISSUE TITLE
special sample causes server disconnection directly. 

### ISSUE THREAD

**Issue by pianoboysai** [uNetworking/uWebSockets.js#356]
https://anonfiles.com/z6M5YdN9o1/aa_js

download this file and send to a websocket server, no response.

My server code is 
`
function start_websocket_by_uWebSockets(port, process_callback){
    const uWS = require('uWebSockets.js');
    uWS.App().ws('/*', {
        compression: uWS.SHARED_COMPRESSOR,
        idleTimeout: 1000,
        open: (ws) => {
            console.log('A WebSocket connected!');
        },
        message: async (ws, message, isBinary) => {
            /* Ok is false if backpressure was built up, wait for drain */
            try{
                ws.send("good",false);
                return;
            }
            catch(e){
                console.log(e);
            }
        },
        drain: (ws) => {
            console.log('WebSocket backpressure: ' + ws.getBufferedAmount());
        },
        close: (ws, code, message) => {
            console.log('WebSocket closed');
        }
    }).listen(port, (listenSocket) => {
        if (listenSocket) {
            console.log('Listening to port %d', port);
        }
    });
}

`

**Comment by alexhultman-2fa** [comment]
The reason for close is given by message. Print it

**Comment by hst-m** [comment]
Should not allow sketchy links in issues, and no idea that the problem is, what does this mean:
> download this file and send to a websocket server, no response

Issue makes no sense, very bad write-up

**Comment by pianoboysai** [comment]
@hst-m 

WebSocket closed, code 1006 ArrayBuffer { [Uint8Contents]: <>, byteLength: 0 }

The linked file could have special character, I am not sure, it is a malware, so I don't put code here.

A  websocket client sends the file content as request body,  it will make server directly close connection.

**Comment by hst-m** [comment]
you shared a malware file here and tell people to download it, without mentioning it is malware?

**Comment by hst-m** [comment]
> A websocket client sends the file content as request body

What client are you using to send this file with a websocket message? What code is it using to send?

**Comment by hst-m** [comment]
Why is this guy trying to send malware files around with websockets?

**Comment by hst-m** [comment]
@pianoboysai have you seen the `maxPayloadLength` setting ?https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#maxpayloadlength

```
maxPayloadLength:

Maximum length of received message. If a client tries to send you a message larger than this, the connection is immediately closed.
```

**Comment by pianoboysai** [comment]
@hst-m  man,  it is a javascript,  can not directly run even if you double click it,  it requires special condition to execute.
  

`Why is this guy trying to send malware files around with websockets?`

it is a web server to receive uploaded script and detect it with antivirus detection engine.

**Comment by hst-m** [comment]
You are telling people to download a Malware JS file? JS is just text files, why can't you post the text file here? https://gist.github.com/

You did not answer question, How are you trying to send this file? What client? What code are you using to send?

**Comment by pianoboysai** [comment]
a client example

`
const WebSocket = require('ws');
const fs = require('fs');
var sample_fpath = process.argv[2];
var sample_content = fs.readFileSync(sample_fpath);
const ws = new WebSocket('ws://127.0.0.1:9000/');

ws.on('open', function open() {
  ws.send(sample_content);
});

ws.on('message', function incoming(data) {
  console.log(data);
});
`

I said it could have special character ( >0x80), i am not sure, but if I put code in gist, maybe it can not display correct or be escaped (or \n -> \r\n) ,   who knows?  

the file hash is c5ef94ddfaa6bbda60cc412d0a07b5a698a94a395fa12469b07f5e2ab721f6a0,  just make sure you test  the right one.

**Comment by pianoboysai** [comment]
you can use the client to send a common file,  it works,  but if send that malicious file,  it will disconnect immediately

**Comment by hst-m** [comment]
You are using the "[ws](https://www.npmjs.com/package/ws)" library to send the file, don't you think that is important info to know for your issue? Did you try sending this to a ws server instead of a uWS server, does it work for ws server? I don't use "ws" library so dont really want to debug their ws client for you

**Comment by pianoboysai** [comment]
do you think I will only test one file and one client and say "hey, there is a bug" ?
I tested some normal files with this "ws" client and python "websocket" client,  all work well,  don't you think the client will not have problem ? 

and of course, I tested "ws" server, and no problem to process this malicious js file.

I don't find uWebSockets client code,  exist?
https://github.com/uNetworking/uWebSockets/issues/854

**Comment by hst-m** [comment]
You are saying your "ws" client and python "websocket" client both disconnect the uWS connection for this file? or is it just the ws client? What about a Browser client did you try sending the file from a Browser client, does that work?

**Comment by pianoboysai** [comment]
yes,  "ws" client and python "websocket" client both disconnected  the uWS connection for this file.  

I don't test browser client.

I have tested 2 clients (ws and python),  I think that's enough to prove it is not client problem, because when I use both of clients to send normal file, there is no problem.    but if I  send  this file,  both disconnected  the uWS.

**Comment by alexhultman** [comment]
If you get close code 1006 you should always have a reason message. What version do you run?

**Comment by pianoboysai** [comment]
v18.3.0,  the message is " ArrayBuffer { [Uint8Contents]: <>, byteLength: 0 }"

**Comment by hst-m** [comment]
>if I put code in gist, maybe it can not display correct

You could add the Hex encoding of the file to a Gist, or just Drag and Drop file into these comments to share file. But you should probably let people know is Malware file before sharing. I did not bother trying your link so I dont have the file
