### ISSUE TITLE
response.close() is throwing pointer allocation or segmentation fault error

### ISSUE THREAD

**Issue by d4n5h** [uNetworking/uWebSockets.js#361]
This:
```javascript
    res.onAborted(()=>{
        console.log('Stopped')
    })
    res.close();
```
Will output this:
`node(25980,0x10538fdc0) malloc: *** error for object 0x104704660: pointer being freed was not allocated
node(25980,0x10538fdc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6`
Or this:
`Segmentation fault: 11`

Using version v18.4.0

By the way, there's a way to write a response back to the client and then close the connection?
This doesn't seem to work:
```javascript
    res.write('Bye');
    res.close();
```

**Comment by alexhultman** [comment]
I cannot trigger this. You have provided almost no info to go by.

**Comment by d4n5h** [comment]
Try this
```javascript
res.onAborted(()=>{
    console.log("aborted");
})
res.write("bye");
res.close();
```

**Comment by alexhultman** [comment]
> I cannot trigger this. You have provided almost no info to go by.

**Comment by hst-m** [comment]
Not able to repro this, you should post the full code of the simplest app that throws error, not just two lines of code, and how are you running this, node/os version
