### ISSUE TITLE
Publish all but self

### ISSUE THREAD

**Issue by Napzu** [uNetworking/uWebSockets.js#362]
There is todo-comment in [PubSub.js](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/PubSub.js) example stating:
/* Todo, Setting 4: send to all including us, or not? That's not a setting really just use ws.publish or global uWS.publish */

I propose it could work almost as commented:
ws.publish to sends message to all subscribers but the ws itself.
let myApp = uWS.App(),  myApp.publish should send to all subscribers.

Any progress regarding this feature?

For context my use case is creating realtime UI between browsers so it's really wasteful to get ie. mouse coordinates back, when only other browser should get those.

**Comment by alexhultman-2fa** [comment]
Absolutely. This is a big feature that should be fixed at some point. I totally agree, but this is quite complex to do.

**Comment by alexhultman** [comment]
This is fixed in v19
