### ISSUE TITLE
Can I decline the connection in the upgrade handler?

### ISSUE THREAD

**Issue by Fxlr8** [uNetworking/uWebSockets.js#367]
In the latest update the `req` is no longer passed to the `open` handler. Previously I used `open` handler to check cookies and implement the authorization. I could call `ws.close()` to close the connection immediately. Is it possible to prevent the connection in the `upgrade` handler?

**Comment by alexhultman-2fa** [comment]
It's not req.end it is res.end.

So yes you can do res.end or res.close while checking headers in upgrade handler

**Comment by alexhultman-2fa** [comment]
Also it's not correct that you could immediately close the connection before. You only had ws and req so the http response had already been sent.

There are examples for this

https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Upgrade.js

**Comment by Fxlr8** [comment]
Oops, you are right there were a couple of mistakes in my question. 
1. Of course I meant `res.end()`.
2. I used `ws.close()` metod in the `open` handler to close it immediately

Now about the `upgrade` handler:
The `res.close()` method is too aggressive. It causes `ECONNRESET` error that does not give any useful information to the client.
```
res.writeStatus('401 Unauthorized')
res.end()
```
is a little better, but it causes `Uncaught Error: Unexpected server response: 401` on the client. 

Is there a way for server to say "pls go away I don't want to connect with you" which is expected by the client?

**Comment by alexhultman-2fa** [comment]
I don't think so. That's something you have to handle on the client side.

**Comment by hst-m** [comment]
using `res.writeStatus('401').end()` in the upgrade handler results in the chrome websocket client `onclose` event being called with code:1006, wasClean:false, reason:(null), so it seems there is no way to get the reason for the denied request. The `onerror` event also gets called but with a generic error without the 401 info. Normally after the websocket is open you can call `ws.end(code, reason)` to specify the code and reason, but I don't know if it should apply to a socket that isn't open yet. None of the [close event codes](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) have something like "Unauthorized" so I'm not sure if the close event should apply to a denied upgrade request. Is it possible to send code/reason with the upgrade handler denying request? Looks like currently you just have to detect if the open failed and react to it without knowing the reason

**Comment by hst-m** [comment]
This answer has good explanation: https://stackoverflow.com/a/50685387

"The spec forbids reading the HTTP status code (or anything like it) from the WebSocket object because otherwise the WebSocket object could be used to probe non-WebSocket endpoints"

But it says the server can accept the Websocket and immediately close it with code and reason if you want to send a reason, so you would do that in the open handler if needed
