### ISSUE TITLE
Publish enhancement, Assigning elements.

### ISSUE THREAD

**Issue by l10r** [uNetworking/uWebSockets.js#378]
uWebSockets_App.publish(`users/id/${userID}`, 'message goes here', false, false, { stuff to assign });

example
```uWebSockets_App.publish(`users/id/${userID}`, 'message goes here', false, false, { hey: true, new_id: '12345' });```
and then it will do something like Object.assign does, to the socket object, and when accessed next it will be return the updated values.

This can be really useful for performance aswell if it will be coded in uWebSockets core, because at the moment in order to do such thing, you have to make an array containing all of the connections and update them through that array, by using .find() or something similiar.

That's just a suggestion that could be a perofrmance beast!

**Comment by alexhultman** [comment]
The purpose of publish is to publish messages over the affected connections. If you want to change values to objects that is out of scope and does not belong in that function.

You don't need to solve it the way you propose, you can easily solve it in O(log n) or even O(1) by using smarter algorithms in your coding. It doesn't belong in this library.

**Comment by hst-m** [comment]
> you have to make an array containing all of the connections and update them through that array by using .find()

@l10r I don't think you want an array for that, I use Maps and Sets to store ws connections by user ID, the Map of uid's points to a Set of ws connections for the user, the open event checks if uid exists and adds it in

```javascript
const wsUIDs = new Map()

app.ws('/',{
   open:ws=>{
      if(!wsUIDs.get(ws.uid)?.add(ws)){const s=new Set();s.add(ws);wsUIDs.set(ws.uid,s)} // add to wsUIDs
   },
   close:(ws,code,message)=>{
      const set=wsUIDs.get(ws.uid);set.delete(ws);if(!set.size)wsUIDs.delete(ws.uid) // remove
   }
})
```
