### ISSUE TITLE
How to retrieve the listening port when using 0?

### ISSUE THREAD

**Issue by Zabrane** [uNetworking/uWebSockets.js#381]
i would like to pick up a random port number (hence the `0`) for my uWebSockets.js app and be able to retrieve what the OS selected for me as a port:

```javascript
require('uWebSockets.js').App({})
.ws('/*', {
  ...
}).listen(0, (listenSocket) => {
  if (listenSocket) {
    console.log('Listening to port ???');
  }
});
```

Is there any property i can access from `listenSocket` to get the port number?

**Comment by alexhultman** [comment]
I think that is possible but I have forgotten how. Maybe leave it out?

**Comment by Zabrane** [comment]
Appreciated if you can remember how.

**Comment by Zabrane** [comment]
@alexhultman in C, it's very easy to retrieve the assigned port number.
I assume you already call `listen()` on your socket, and then `getsockname()` to get back the port number on which it is listening. Something along these lines:

```c
struct sockaddr_in sin;
socklen_t len = sizeof(sin);
if (getsockname(sock, (struct sockaddr *)&sin, &len) == -1)
    perror("getsockname");
else
    printf("port number %d\n", ntohs(sin.sin_port));
```

But i have no idea how to export this to NodeJS.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uSockets/blob/7683672d87067cd75b854f4e36b9820f4809a4be/src/bsd.c#L187

**Comment by alexhultman** [comment]
Oh, so you *are* passing 0? And that works?

Alright, then I would say we need a new function us_listen_socket_get_port or something more general.

**Comment by Zabrane** [comment]
@alexhultman yup, I’m passing 0 and it works of course. Would be great if you can implement this new us_listen_socket_get_port.

**Comment by alexhultman** [comment]
Maybe you can solve it externally. If you know the pid you can get the ports on Linux at least

**Comment by Zabrane** [comment]
I doubt it’s a proper solution to the issue IMHO. A NodeJS app can open more than one socket at a time and you’ll never be able to figure out which one belongs to uWebSockets.js.

**Comment by alexhultman** [comment]
It's not perfect but I don't have time to add a proper solution right now

**Comment by Zabrane** [comment]
@alexhultman I do understand you are busy. But in the mean time, could you please at least point me to where the call `us_listen_socket` is implemented (C + NodeJS)?
I will try to come up with something similar for ` us_listen_socket_get_port `

**Comment by alexhultman** [comment]
It would be added in three steps:

* in bsd.c, bsd.h bsd_get_listen_port or something like that would be implemented.
* In context.c this call would be wrapped in us_listen_socket_get_port
* in libusockets.h this function prototype would be added.

It has to be cross-platform. You can make your own fork in the mean time and I can look at this when I have more time.

**Comment by alexhultman** [comment]
maybe you can make it more general and have it be us_socket_get_port so that it works for all sockets.

**Comment by alexhultman-2fa** [comment]
https://github.com/uNetworking/uSockets/blob/5440dbac79bd76444175b76ee95dfcade12a6aac/src/libusockets.h#L255

This needs wrapping

**Comment by alexhultman-2fa** [comment]
See newly added example
