### ISSUE TITLE
Data reaches the client for a very long time

### ISSUE THREAD

**Issue by xtreh** [uNetworking/uWebSockets.js#384]
Me create a server which handle sending data from CLIENT_1 (PC) by using nodejs/net module ( net.createServer ). And use websocket server (uWebSocket.js) for sending data from CLIENT_1 (PC) to CLIENT_2 (browser).
**[ CLIENT_1 send data by tcp connection -> net server handle data and call socket.send(...) for some socket's -> CLIENT_2 (browser) get data by onmessage callback ]** 
But data comes to CLIENT_2 with very high delay (arount 14 sec). Not immediately.
The server has about 200 simultaneous connections.

![CPU performance](https://i.imgur.com/DZ2ZyYv.png)
![WS dump](https://i.imgur.com/I4JvyvI.png)

**Environment**
- Node.js v14.15.0
- uWebSockets.js v18.9.0
- Node.js Net Module
- Ubuntu 18.04
- 3.1 GHz Core x4
- 4 GB DDR4 Ram x1

**Comment by alexhultman** [comment]
This is an open ended question without enough info to make anything out of it. Your image doesn't say anything other than there's a gap of 12 seconds at the very browser (?). This doesn't really rule out anything other than there's not, not a gap of 12 seconds.

**Comment by xtreh** [comment]
Server.js
[code]
var io = require('uWebSockets.js').App();
var net = require('net');

var clients = [];
io.ws('/*', {
    message: (socket, message, isBinary) => {
        const uuid = parseInt(String.fromCharCode.apply(null, new Uint8Array(message))) || -1;
        if (uuid)
            return;
        
        for (var index = 0; index < clients.length; index++) {
            if (clients[index] === socket) {
                clients[index].uuid = uuid;
                break;
            }
        }
    },
    open: (socket) => {
        for (var index = 0; index < clients.length; index++) {
            if (clients[index] === socket)
                return;
        }
        clients.push(socket);
    }, 
    close: (socket) => {
        for (var index = 0; index < clients.length; index++) {
            if (clients[index] === socket) {               
                clients.splice(index, 1);
            }
        }
    }
}).listen(wsPort);

net.createServer(function (connection) {    
    connection.on('data', function (data) {
    for (var index = 0; index < clients.length; index++) {
        const socket = clients[index];
        if (data.buffer.readUint32LE(0, 4) == socket.uuid) {
            socket.send(data.buffer, true, false);
        }
    }
}).listen(dataPort);
[/code]

Client.js
[code]
const ws = new WebSocket('ws://server:wsPort');
ws.onmessage = function(data) { console.log(data); };
[/code]

**Comment by alexhultman** [comment]
This is not really how I want to do things - you should debug on your side until you have concrete, absolute info on this being a bug. Otherwise I spend ages and ages doing everybody's homework.

**Comment by alexhultman** [comment]
Closing until you have an actual concrete bug report.
