### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by wthoutanymmries** [uNetworking/uWebSockets.js#385]
I read #26 very carefully and I hope this is actually a bug
I removed all installed node versions
Downloaded latest 15.1.0 for macos from [https://nodejs.org/](https://nodejs.org/)

I did the following
`git clone --recursive https://github.com/uNetworking/uWebSockets.js.git tmp`
`cd tmp`
`make`

I modified your build.c so it would compile for my macos version and node 15
[build.c.zip](https://github.com/uNetworking/uWebSockets.js/files/5493538/build.c.zip)

I followed [this tutorial](https://edisonchee.com/writing/intro-to-%C2%B5websockets.js/) for pub/sub
cloned [this example repo](https://github.com/edisonchee/uwebsockets-nodejsl)
modified it so it would work on my machine and ended up with [this](https://github.com/wthoutanymmries/uws_test)

`node src/server/server.js`
opened index.html in the browser and uWS server crashed with segmentation fault

I am sincerely sorry if it is my fault, your work is amazing and I want to use it
I wish you would have full working example on pub/sub with node.js client

**Comment by hst-m** [comment]
The [Readme](https://github.com/uNetworking/uWebSockets.js#package-easily-installed) says to install with `npm install uNetworking/uWebSockets.js#v18.9.0` have you tried that? Why are you trying to compile it if you have no idea what you are doing? Don't follow that guys tutorial. There is Pub/Sub example [here](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/PubSub.js) so what do you mean there is no example? install with the line above and replace the 1st line in the example with `const uWS = require('uWebSockets.js')`

**Comment by wthoutanymmries** [comment]
@hst-m  Yeah i tried like a dozen of different versions, tried to reinstall node several times and it just does not work
Found [this one](https://github.com/uNetworking/pubsub-example) tho
It actually has a client but the one you mentioned does not that what I meant
Feel free to correct me I'm here to learn

**Comment by hst-m** [comment]
> Yeah i tried like a dozen of different versions, tried to reinstall node several times and it just does not work

you have provided no info on how what does not work

> It actually has a client but the one you mentioned does not that what I meant
Feel free to correct me I'm here to learn

websocket client is easy just google it, you sound like total noob should not be creating issues to teach you basic stuff, you cant even do a basic install so not sure what to say

**Comment by wthoutanymmries** [comment]
I don't ask you to teach me
I sound like a noob because I am one
uWS.App() and uWS.SSLApp() were crashing with segmentation fault as soon as I made connection
To my eye there is no mistake in my code and clearly if the error was segmentation fault then something was trying to access something that was already deleted or something was going out of bounds
It was a mistake in native code, not in js runtime
I tested multiple node versions so most likely it's not node
I reported what I found so may be it could help in some way
I do not have any questions
Feel free to close/delete this issue

**Comment by hst-m** [comment]
I don't use Mac to check and this is not my repo but I am saying if you want to report something you should be using the easy Readme install and using one of the included examples to make sure you are doing it correctly, and report the specifics of your problem, not doing your custom compile and using someone else's old library for the example

**Comment by wthoutanymmries** [comment]
@hst-m yeah) solution turned out to be embarrassingly simple

**Comment by alexhultman** [comment]
What was the solution?

**Comment by hst-m** [comment]
@wthoutanymmries sorry about that previous post I was a little grumpy from just waking up I update that post

**Comment by shaggyrec** [comment]
@wthoutanymmries I have "segmentation fault 11". What is your solution?

**Comment by wthoutanymmries** [comment]
@shaggyrec basic type checking. Make sure you pass strings not js objects

**Comment by shaggyrec** [comment]
I made `.ws(...).listen(parseInt(PORT), () => {})` and it works. `PORT` is the variable from env. It is string. 
It wasn't obvious.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets.js/issues/343

**Comment by hst-m** [comment]
Ah the OP was using Publish with an object instead of stringify it first, likes like the tutorial repo he tried to use was bad https://github.com/wthoutanymmries/uws_test/blob/master/src/server/server.js#L59

**Comment by alexhultman** [comment]
I have added stricter type checks here https://github.com/uNetworking/uWebSockets.js/commit/cee33dc003a18407374a86a8440f8e84c825882e

**Comment by hst-m** [comment]
That looks like silent fail, and extra processing for every publish call just to make sure called correctly, when can just follow docs correctly

**Comment by alexhultman** [comment]
They are not silent,

https://github.com/uNetworking/uWebSockets.js/blob/master/src/AppWrapper.h#L338

There are now three checks that will throw exceptions with accurate info on wrong arguments passed.
