### ISSUE TITLE
Previous version in package.json

### ISSUE THREAD

**Issue by AskeFC** [uNetworking/uWebSockets.js#392]
Just noticed the release 18.10.0 is defined as version 18.9.0 in it's package.json.

**Comment by alexhultman** [comment]
Ah crap, you're right. Does it still install?

**Comment by alexhultman** [comment]
It does install, but "npm ls" shows it as 18.9.0 so I guess updating will not work. But updating is broken in NPM 7 either way and people install from GitHub tag so it kind of doesn't matter (that much) as far as I can tell.

**Comment by AskeFC** [comment]
Yea, it's no biggie. Install works fine either way, I just had to double check because after installing I wasn't sure if I had typed the wrong version number  :)
