### ISSUE TITLE
Deploy Websocket.js on Azure, AWS or Heroku

### ISSUE THREAD

**Issue by szarkowicz** [uNetworking/uWebSockets.js#393]
Hi,

As anyone been able to get this library installed on Azure, AWS, or Heroku. I have been trying to get this installed on Azure Web Service using the latest version 18.8.0.

I have have deployed the project with Azure App in Windows 64 and Linux and I am unable to get it to work. I have my project working on MacOS and Windows Laptop as well.  The project installs successfully but when I try and create a simple websocket connection in the Chrome Command line using new WebSocket('wss://server-url/'); the websocket just says pending. If I call that same command multiple time it will eventually timeout with a 500 error.

I also tested using some of the provided examples. (websockets.js https://github.com/uNetworking/uWebSockets.js/blob/master/examples/WebSockets.js) but I get the same error and behavior.

I can provide my code example if necessary.

If anyone has been able to get this deployed or if I am missing something please let me know. Any help will be greatly appreciated. 

Thank You

**Comment by hst-m** [comment]
Do http/s requests go through to the server? You are using wss, is SSL set up correctly?

**Comment by alexhultman** [comment]
> If anyone has been able to get this deployed [...] please let me know.

🤔

Yes. They have been.

**Comment by hst-m** [comment]
@szarkowicz Looks like you are trying to do one of those "Serverless" things with Azure App Service, haven't tried it but seems like it wouldn't work, normally you want to run this on a full VM? I run this on VM instances

**Comment by alexhultman** [comment]
> and I am unable to get it to work.

This is not a valid bug report and I'm fairly sure you haven't put any effort in reading already written text (not here, not on Microsoft).

Closing until you can describe an actual bug

**Comment by szarkowicz** [comment]
@hst-m - I got it working on windows Virtual Machine using App() with ws: and SSLApp() with wss and SSL certs generated for the VM. 

I have been working with Azure support and they are able to reproduce the issue with Windows and Linux Web App services.

@alexhultman - thats a kinda rude assumption - we have done all kinds of debugging and creating various App services instances to compare and working with Azure support as well. We also have poured over all the documentation and try to google as much as possible .They also do not know why at the moment that uwebsocket does not work on Window or Linux App service.

Post here was an absolute last resort because of how you treat other people with questions and was 100% correct with your above comment.

Was waiting to see if we could advance it any farther and hopefully post a successful update before replying to the original question incase it was something minor that was overlooked.

**Comment by hst-m** [comment]
But have you tried using the VM service instead of this App Service thing? This is meant to be run on a full VM  https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ It is very easy to install and spin up VM instances

**Comment by szarkowicz** [comment]
@hst-m We got it working with a Windows VM, which is the 1st thing we tried once Azure support wanted more time to investigate the issue with Window and Linux, we did not try to get it working with a Linux VM. I am confident we could get it working there as well if needed. 

2 of the benefits of being able to use Windows or Linux App service is the ability to Auto Scale if needed and being able to point it at a Github repo and have the App Service auto update when new versions of our app are ready for deployment.

**Comment by hst-m** [comment]
You can auto-scale VM instances. Why run this on Windows when you can use Linux. I have my apps set up to have Github push new commit events to the VM, the VM downloads the new version and is auto-deployed as I described in other issue https://github.com/uNetworking/uWebSockets.js/issues/324#issuecomment-643684128, you don't need to have them do it for you. I just don't know if uWS works on these App Service things, sounds like it is not working. From what I understand it is meant to be run on a full VM

**Comment by szarkowicz** [comment]
@hst-m - thanks appreciate the info. Most of our deployments are with App Services and thats what we tried to get working first but I will look into the Linux VM, we had to get this working for a demo that we are doing tomorrow. We will probably revisit Linux after that. 

We are able to get the App Service to start the uWebsocket.js server and can view the console log of the sever starting in the server logs, it seems to crash when you make a websocket request from the browser.

We were not sure what the system requirements were if it needed to be a full VM or not so that was one of the main reasons for posting. There was no information about it anywhere here or google about it having to be full VM, so hopefully this thread can help the community of uwebsocket.js users in the future because it is a great library.

**Comment by alexhultman** [comment]
> because of how you treat other people with questions

Your issue falls under "Do not report start-up crashes" which is pinned in the very top, and if you seriously ask "has anyone been able to deploy this" you obviously did not read the very README. You haven't provided any concrete bug from the point of view of the library itself.

All your issue really explains is that you cannot (**for any reason**) get a **hello world** example working - you haven't distilled the issue down to anything useful that I could actually take and consider without spending ages on debugging your app. Do you want me to enter my VISA, sign up to this whatever service and try myself? Based on what?

95% of all "issues" posted here are the fault of the poster, and I guesstimated based on the above. Maybe there is an issue, but it still falls under the "Do not report start-up crashes" which is also the case for when people try and run on Alpine Linux.

**Comment by szarkowicz** [comment]
Your just cherry picking my post. I clearly didn't just ask if "has anyone been able to deployed this..." as you have posted a couple times. I asked if anyone has deployed this library to azure, aws, or heroku. Obviously with 55 million downloads it's deployed and in production around the world.

I didn't tag you in the original post and I never expected you to spend anytime or money debugging my issue
 It's a terrible assumption to assume everyone just wants you do things for free or needs your help with every question. It was a simple question if anyone in the community had got it deployed to the services mentioned. I love the sarcastic post and negative assumptions about a question. I even mentioned that I have it working on 2 various computers and simply asking if it was possible or not with those services again.

**Comment by hst-m** [comment]
Azure, Aws have large variety of services including VM's and the App engine things so it was kind of confusing. And never answered if basic http was working or not etc, no specifics mentioned. I tried creating Azure account, yikes the UI is bad I much prefer Google Cloud. I still need to try if App Engine (google version) works or not

**Comment by alexhultman** [comment]
> terrible assumption to assume everyone just wants you do things for free

Well, walk a mile in my shoes and tell me about it.

**Comment by szarkowicz** [comment]
@hst-m it did not work with basic http. Okay thanks for info about Google cloud.

**Comment by hst-m** [comment]
See google App Engine allows selecting different versions of the engine, one supports "frameworks that include native code" which might be what is needed

https://cloud.google.com/appengine/docs/the-appengine-environments

**Comment by modelorona** [comment]
I managed to get it deployed on Heroku, at least a very basic version. This is the skeleton of the code I used

```javascript
'use strict';

const Uws = require('uWebSockets.js');

Uws.App({})
    .ws('/socket', {
        message: (ws, message, isBinary) => {
            console.log(new TextDecoder('utf-8').decode(message) + ' ' + isBinary)
        },
        close: (ws, code, message) => {
            console.log('websocket closing');
        },
        open: ws => {
            console.log('websocket opened');
        },
    })
    .listen('0.0.0.0', Number.parseInt(process.env.PORT) || 9001, (token => {
        if (token) {
            console.log(`listening to port ${process.env.PORT || 9001}`);
        } else {
            console.log('failed to listen')
        }
    }))
```

```PORT``` is set by Heroku automatically. I can access the websocket by wss://{heroku-dyno-url}/socket.

I also have a Procfile with the following content:
```web: node websocket.js```

Forgive me if a bracket or else is missing, I had to delete some stuff before posting.

**Comment by alexhultman** [comment]
That's good but it should run on *any* platform that provides a proper, official Node.js build that honors official ABIs.

**Comment by zeluspudding** [comment]
@modelorona  I'm curious how your `client.html` looks for this. I can't figure out how to serve mine over `http://` in addition to serving the websockets over `wss://`

**Comment by modelorona** [comment]
@zeluspudding I actually do not have an html file, or any front-facing content. I connect to the socket from an android application directly.

However, when playing around, I did try to have a very basic http server alongside the socket server but failed to do so. I'm not sure if Heroku lets you have two different applications on the same dyno listening, because they give you just one port to bind to. I may be wrong, as I've only been using it for a very short time...but this is my experience with it and the conclusion I've come to.
