### ISSUE TITLE
handle ping/pong in ws

### ISSUE THREAD

**Issue by hosseinhojjatyar** [uNetworking/uWebSockets.js#394]
hi,
how handle ping/pong in ws?
i can't find an example in [https://github.com/uNetworking/uWebSockets.js/tree/master/examples](https://github.com/uNetworking/uWebSockets.js/tree/master/examples)

**Comment by hst-m** [comment]
Docs for ping/pong:
Sending Ping from server: https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocket.html#ping
Receiving Ping event: https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#ping
Receiving Pong event: https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#pong

If you want to send keep-alive "ping" messages from browser client, send empty websocket message on interval `setInterval(()=>ws.send(''),10000)` and on the server ignore empty message which resets the idleTimeout:
```javascript
app.ws('/',{idleTimeout:16,
   message:(ws,ab)=>{
      if(!ab.byteLength)return
      // message code
   }
})
```
10 sec ping interval and 16 sec idleTimeout works best for me

**Comment by dragonbane0** [comment]
@hst-m Thank you a lot for all these little snippets btw. Helps a lot starting out :)
