### ISSUE TITLE
[feature] is it possible to add autoPingTime work with idleTimeout?

### ISSUE THREAD

**Issue by roytan883** [uNetworking/uWebSockets.js#395]
Is it possible to add `autoPingTime` work with `idleTimeout` in `WebSocketBehavior` config ?
like this:
```
/** Maximum amount of seconds that may pass without sending or getting a message. Connection is closed if this timeout passes. Resolution (granularity) for timeouts are typically 4 seconds, rounded to closest.
     * Disable by leaving 0.
     */
idleTimeout: 250,
/** auto send ping to remote client interval time (seconds) 
     * the response pong will auto refresh idleTimeout, make sure remote client is alive
     * Disable by leaving 0.
     */
autoPingTime: 120,
```

This can make sure remote client is alive especially in mobile network.

Right now i'm recording all websocket, loop sending `ping` and handle `pong` at nodejs APP layer. If this feature can be add to uWebSockets core layer, maybe the performance will be better and APP layer will be easier.

**Comment by hst-m** [comment]
Why are you not having the Client send the ping message? You want the server to do as little work as possible

**Comment by roytan883** [comment]
@hst-m 
1, It's a big topic about APP background alive on Android and iOS. At some scenario, only the server sending `ping` can keep the APP socket alive.
2, if the client are not write by us, other partner's websocket client may not send ping.
3, html websocket client not provide send ping method directly. 
https://developer.mozilla.org/docs/Web/API/WebSocket

**Comment by hst-m** [comment]
Docs for [idleTimeout ](https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#idletimeout) says it works like this: "Maximum amount of seconds that may pass without **sending** or getting a message" so sending any message/ping resets the idleTimeout even if you don't receive a response, so what you are trying to do won't work (I just tested this with ping)

1) I tried this on my Android Chrome, the client continues to send ping messages when in different tab, or when in different app, the only time it stops is when you lock the phone. Even if there are other cases like iOS (don't have on me to try) when it stops sending ping, seems ok to just re-open connection when app resumes
2) tell them to send ping message if they want to keep connection open, otherwise they can just re-open connection when it closes
3) I just posted in other issue https://github.com/uNetworking/uWebSockets.js/issues/394 to just send empty message from client, the server doesn't even need to respond to it (better performance?)

**Comment by roytan883** [comment]
@hst-m did you mean the `pong` will not reset `idleTimeout` ?

**Comment by hst-m** [comment]
You can send a Ping from the server and it will reset the idleTimeout, it does not need to receive a Pong back to reset idleTimeout

**Comment by roytan883** [comment]
oh, sending will also reset the `idleTimeout`. I used to treat it only refresh when receive any data. 
So if the client not respond `pong`, the `idleTimeout` will still be refreshed? Then i can't use `idleTimeout` to check whether client is alive.

Maybe i need `aliveTimeout` with `autoPingTime`, stand for client alive, client -> server data make socket connection alive.
So I should keep my server APP layer sending `ping` and handle `pong`, not depend on `idleTimeout`.

**Comment by hst-m** [comment]
You can still keep idleTimeout, I see that if you send a Ping and there is no response the server closes the connection in 20 seconds with `1006 Abnormal Closure` where as idleTimeout violation closes the connection with `1006 Abnormal Closure WebSocket timed out from inactivity` after the timeout time. So just keep that in mind, its 20 seconds and a different close message if you send a Ping with no response

**Comment by roytan883** [comment]
> You can still keep idleTimeout, I see that if you send a Ping and there is no response the server closes the connection in 20 seconds with `1006 Abnormal Closure` where as idleTimeout violation closes the connection with `1006 Abnormal Closure WebSocket timed out from inactivity` after the timeout time. So just keep that in mind, its 20 seconds and a different close message if you send a Ping with no response

It looks good when no response close.

So what the bad side about adding `autoPingTime` ? It can be disabled by default 0. But in my case, APP layer no need do anything to trace `ping` and `pong`. The `idleTimeout` + `autoPingTime` can make sure the client is  `really` alive no matter what network scenario. I guess lots of user need this feature.

**Comment by alexhultman** [comment]
> The idleTimeout + autoPingTime can make sure the client is really alive no matter what network scenario.

idleTimeout already does this. You can't send on a broken connection. The kernel has a retransmission timeout that will cause the app to see the connection as broken unless it gets a TCP ack for the send in time. The default of this timeout is maybe a little off, but not that much.

Timeout is definitely not something you should do in scripted business logic. This is and should be part of the library. It can be tweaked, sure, but it works as is.

**Comment by hst-m** [comment]
@roytan883 No, people should be sending ping from the client so the client is doing the work. Then you don't need to be "tracing" Ping and Pong on the server like you said. See issue for example sending Ping from client https://github.com/uNetworking/uWebSockets.js/issues/394

**Comment by roytan883** [comment]
> @roytan883 No, people should be sending "ping" keep-alive from the client with idleTimeout on the server. Then you don't need to be "tracing" Ping and Pong on the server like you said. See issue for example sending "ping" keep-alive from client #394

Ok, I see the problem why you insist on `client sending ping`. I can explain more about problem 1.

In China, all Android device can not use Google GMS, So we must develop our own `push service`. The big problem is about `APP alive`. It stand for two side: app process alive, app socket alive. 
About `app socket alive`, we have different android phone and different android system version, test on China three big mobile companies: `China Mobile`, `China Telecom`  and `China Unicom`. The real test result is different, use different mobile company's phone card, the tcp socket alive time is different, and in some case, need both side `ping pong` to keep socket alive( for example: on some phone card if 6 minutes no data from server to client, although the connect looks good, no callback for socket close or error, but when client use it sending data, the socket return error immediately). As i said, mobile tcp socket is not stable as normal tcp socket, there are many edge case and different scenario which related to phone, phone system, network router, network carrier company.

**Comment by hst-m** [comment]
Have you looked into this for Push notifications, and you are sure this does not work for you? https://developers.google.com/web/fundamentals/push-notifications

**Comment by roytan883** [comment]
> idleTimeout already does this. You can't send on a broken connection. The kernel has a retransmission timeout that will cause the app to see the connection as broken unless it gets a TCP ack for the send in time. The default of this timeout is maybe a little off, but not that much.
> 
> Timeout is definitely not something you should do in scripted business logic. This is and should be part of the library. It can be tweaked, sure, but it works as is.

@alexhultman  If `idleTimeout` is 10 minutes, no sending data to client and not receive any data from client, how can we make sure the client is really alive? especially for mobile device client.

As i understand, the kernel `SO_KEEPALIVE` default  is disabled, and `tcp_keepalive_time` is 7200 seconds (2 hours).

**Comment by roytan883** [comment]
> Have you looked into Web Push Notifications, and you are sure this does not work for you? https://developers.google.com/web/fundamentals/push-notifications

As i said, in China. Most of Google service is forbidden, both politics and technical. It is LAW we must follow.  Even the link you provide can't not open in China.

**Comment by hst-m** [comment]
I have no idea what is going on China but if you need to send some Pings from the server to the client go ahead and do it, but don't expect to add an autoping feature that no one else needs

**Comment by roytan883** [comment]
> I have no idea what is going on in China but if you need to send some Pings from the server to the client go ahead and do it, but don't expect to add an autoping feature that no one else needs

Its not about in China or not. Technically, its about tcp socket NAT on mobile base station. Each mobile base station keep NAT hole time for tcp socket is different on different mobile company. some is 6 minutes, some is 28 minutes. So each APP must do heartbeat to keep socket alive. There are some example: WhatsApp 4m45s, Line 7m.

**Comment by hst-m** [comment]
If you want to use native feature, just do `ws.subscribe('all')` in the open handler and then do `app.publish('all','ping')` to send a ping message to every client. This should be faster than looping through websockets in JS

**Comment by roytan883** [comment]
> If you want to use native feature, just do `ws.subscribe('all')` in the open handler and then do `app.publish('all','ping')` to send a ping message to every client. This should be faster than looping through websockets in JS. The `close` event should trigger if there is problem with connection

Its a good idea, i think it will have better performance than my current solution.

Also, there is a topic about Carrier Grade NAT Timeout. At France mobile network, how to config its XMPP server to send keepalive(ping). Its NAT time is like China mobile company, around 5 minutes. That's why I take example for 4~5 minutes autoPing. His solution is change kernel `tcp_keepalive_time`, my suggestion is add this feature `autoPingTime` in uWebSockets core.

https://blog.wirelessmoves.com/2020/09/carrier-grade-nat-timeouts-and-how-to-configure-your-xmpp-server.html

**Comment by alexhultman** [comment]
> If idleTimeout is 10 minutes, no sending data to client and not receive any data from client, how can we make sure the client is really alive? especially for mobile device client.

You can't. That's why you send pings. Even if you have 10 minutes idleTimeout (which is really high) you still have to make sure to send pings every, say 1 minute. Either you do this from the client side (which you do not seem to want) or you do this from the server (which is more demanding for the server).

Most users, I would guess, have idleTimeout of about 1 minute and send pings from clients with maybe 30 second interval. That works over whatever Chinese or Russian phone or sputnik. It doesn't matter if you live in China or not, you still play by TCP rules.

I don't have any immediate plan to change any of this, but I might tweak things and (maybe) add this autoPingInterval, but not because it is needed, but rather because in some cases the client (application) protocol is so stupidly designed that it cannot handle client-side pings.

**Comment by uasan** [comment]
> As i understand, the kernel SO_KEEPALIVE default is disabled, and tcp_keepalive_time is 7200 seconds (2 hours).

If you are using Nginx as reverse proxy, you can try to configure TCP
> so_keepalive=on|off|[keepidle]:[keepintvl]:[keepcnt]
this parameter configures the “TCP keepalive” behavior for the listening socket. If this parameter is omitted then the operating system’s settings will be in effect for the socket. If it is set to the value “on”, the SO_KEEPALIVE option is turned on for the socket. If it is set to the value “off”, the SO_KEEPALIVE option is turned off for the socket. Some operating systems support setting of TCP keepalive parameters on a per-socket basis using the TCP_KEEPIDLE, TCP_KEEPINTVL, and TCP_KEEPCNT socket options. On such systems (currently, Linux 2.4+, NetBSD 5+, and FreeBSD 9.0-STABLE), they can be configured using the keepidle, keepintvl, and keepcnt parameters. One or two parameters may be omitted, in which case the system default setting for the corresponding socket option will be in effect. For example,
so_keepalive=30m::10
will set the idle timeout (TCP_KEEPIDLE) to 30 minutes, leave the probe interval (TCP_KEEPINTVL) at its system default, and set the probes count (TCP_KEEPCNT) to 10 probes.

http://nginx.org/en/docs/stream/ngx_stream_core_module.html#tcp_nodelay

**Comment by roytan883** [comment]
@alexhultman 

At beginning we do send ping from client to server. 

But after more real test and more search, we find at mobile network, only client->server ping can't not cover all case. That's why i'm talking about server->client ping. Different mobile company, 3G, 4G, 5G, NAT timeout, tcp socket is not stable as we expect.

Thanks for consider adding `autoPingInterval` to uWebSockets core.

**Comment by alexhultman** [comment]
> If you want to use native feature, just do `ws.subscribe('all')` in the open handler and then do `app.publish('all','ping')` to send a ping message to every client. This should be faster than looping through websockets in JS. The `close` event should trigger if there is problem with connection after 20 seconds (or sooner if the client officially closes the connection)

Smart. That's a quite simple solution really. Just do a setInterval in JS and make it publish to some topic that all clients are subscribed to.

**Comment by hst-m** [comment]
The only problem is it sounds like he is not controlling the client code so it will show up on the client as a websocket message where a real Ping is not a websocket message, but is up to him. Maybe better performance for server to not receive bunch of Pong messages but I don't know

**Comment by roytan883** [comment]
Another case client->server not work is Android APP background scenario. Android APP have some kind of sleep rule when at background, light sleep and deep sleep. When light sleep, APP can wake up itself and send ping to server. But in deep sleep, the APP process can not even wake up itself process. At this time, if a server->client ping is received from cell mobile down layer, system will wake up the APP process handle it.

**Comment by alexhultman** [comment]
> Another case client->server not work is Android APP background scenario. Android APP have some kind of sleep rule when at background, light sleep and deep sleep. When light sleep, APP can wake up itself and send ping to server. But in deep sleep, the APP process can not even wake up itself process. At this time, if a server->client ping is received from cell mobile down layer, system will wake up the APP process handle it.

This makes sense (I don't know for sure, but I can buy it), but do you really want a WebSocket to be kept alive during deep sleep? Isn't it better to just reconnect? So to not hog resources on the server?

**Comment by roytan883** [comment]
> > If you want to use native feature, just do `ws.subscribe('all')` in the open handler and then do `app.publish('all','ping')` to send a ping message to every client. This should be faster than looping through websockets in JS. The `close` event should trigger if there is problem with connection after 20 seconds (or sooner if the client officially closes the connection)
> 
> Smart. That's a quite simple solution really. Just do a setInterval in JS and make it publish to some topic that all clients are subscribed to.

@hst-m @alexhultman  will it cause big network traffic flow? If 100K client connect to server, it send all ping at one time. 

Right now, my solution is JS loop all ws, and send 1000 ping then await 500ms, then continue.

```
sendAutoPing = async () => {
    let sendCount = 0
    let clientInfos = _.values(this.clientMap)
    for (let index = 0; index < clientInfos.length; index++) {
      const clientInfo = clientInfos[index];
      if (_.isNil(clientInfo) || _.isNil(clientInfo.p)) {
        continue
      }
      sendCount++
      if (sendCount === 1000) {
        //send ping smooth
        await Bluebird.delay(500)
        sendCount = 0
      }
      _.each(clientInfo.p, (platformInfo, platform) => {
        if (platformInfo && platformInfo.ws) {
          let ws = platformInfo.ws
          if (!ws._isKicked) {
            ws.ping()
          }
        }
      })
    }
  }
```

**Comment by alexhultman** [comment]
On the other hand, if you can be woken from deep sleep from a network interrupt then surely you can register a timer to be woken up when to send the client side ping. I know for a fact that you can register timer interrupts to basically any processor ever created.

**Comment by roytan883** [comment]
> On the other hand, if you can be woken from deep sleep from a network interrupt then surely you can register a timer to be woken up when to send the client side ping. I know for a fact that you can register timer interrupts to basically any processor ever created.

Yes, in our APP we do have timer send client->server ping. But also we need server->client ping.

Network interrupt not work as timer. The Android system will disable all timer for APP in deep sleep. But the socket data event is from some kind of mobile cell down layer module service, it can always wake up APP.

**Comment by roytan883** [comment]
> WebSocket to be kept alive during deep sleep?

@alexhultman 

As i said, in China, we can't use GCM(Google Cloud Messaging) or FCM(Firebase Cloud Messaging), both technical and LAW. we must develop our own `push service`. Implement a `push service`, need long-alive socket connection.

**Comment by roytan883** [comment]
@hst-m @alexhultman 
Actually, i used to create a `smart keep alive` solution.
Server normally do not send any ping. it trace all received data(pong, message) to refresh internal updateTime. If the updateTime is old than `autoPingInterval`, server will send ping to client, if still no response, than treat client is disconnected, call close.

**Comment by uasan** [comment]
It looks like your function is only useful for determining on the server side that the connection client is closed, your function detects this before the TCP timeout or idleTimeout, this is the only benefit of your function.

**Comment by roytan883** [comment]
> It looks like your function is only useful for determining on the server side that the connection client is closed, your function detects this before the TCP timeout or idleTimeout, this is the only benefit of your function.

@uasan Yes, at beginning i thought the idleTimeout is only refreshed by receiving data. Then @hst-m clear it for me that also effect on sending data.

But the purpose is to make sure all client is alive. not-alive clients should be delete (@hst-m  said it will auto close when no `pong` after 20s). Keep not-alive clients do not make sense.

**Comment by alexhultman** [comment]
> @uasan Yes, at beginning i thought the idleTimeout is only refreshed by receiving data. Then @hst-m clear it for me that also effect on sending data.

TCP cannot send data without also receiving data (within a reasonable time). <--- **impoartant**

So idleTimeout works "as if" it measured only received data. I might change this back so that idleTimeout only resets on data receive, but that is only a minor tweak - in practice it already does this.

**Comment by uasan** [comment]
We have two technical arguments in favor of the add `autoPingInterval` setting.
1. Rapid detection of dead connections
2. Ping to client who cannot send pings on their own

**Comment by alexhultman** [comment]
I can definitely make sense to add this support, and maybe tweak the rule about resetting idleTimeout on sends. However like said none of this is currently "broken". We are talking about subtle improvements.

**Comment by anilanar** [comment]
> On the other hand, if you can be woken from deep sleep from a network interrupt then surely you can register a timer to be woken up when to send the client side ping. I know for a fact that you can register timer interrupts to basically any processor ever created.

Let me give the browser perspective on this: 

Modern browsers, regardless of device type, started "throttling" background tabs (since a year?). Safari's throttling is the most aggressive one, it throttles CPU clocks to an absolute minimum. One exception to throttling is a network interrupt. Once the tab receives a network interrupt, Safari allows the tab's thread to run at full speed for a couple milliseconds.

**Comment by alexhultman** [comment]
Thanks for adding more info. What do you think about autoPing: true/false?

Only going by idleTimeout, being entirely automatic.

**Comment by hst-m** [comment]
autoPing option probably a good idea, I noticed when only having idleTimeout: phone sleeps and triggers the idleTimeout close connection, but this close event gets sent to client which wakes the client back up and it re-opens the connection, goes back to sleep, triggers idleTimeout again so loop of open/close events which is no good. Ended up increasing idleTimeout to 2:30 minutes to prevent this on phone, or can just send some server autoPings at interval and the connection will close if it doesn't go through

**Comment by slavaGanzin** [comment]
OFF TOP

@hst-m Did constant pinging prevent throttling in modern safari? 2 years ago when I tried this, it doesn't. In IOS safari I used to use:
```html
<meta id=backgroundRefresh http-equiv="refresh" content=-1>
<script>
setInterval(() => document.getElementById('backgroundRefresh').content = 5, 1000)
</script>
```
JavaScript constantly updating time to reload page, and when safari throttles JS, it wakes up in 5 seconds.

**Comment by alexhultman** [comment]
(this support is implemented in v19, "binaries" branch has it but it is not released yet)
