### ISSUE TITLE
Unexpected client ip behavior

### ISSUE THREAD

**Issue by Zaseth** [uNetworking/uWebSockets.js#402]
I'm running an uws server on localhost. Whenever I retrieve the clients ip address, it throws 127.0.0.1. I'm expecting it to throw my public ipv4. Why's that?

Note: I'm using the same device for both client and server.

**Comment by hst-m** [comment]
127.0.0.1 is localhost so not sure what you are expecting, this is basic stuff. it would only show the ip if you were coming in externally from that ip. but you are coming from localhost

**Comment by hst-m** [comment]
If you want to send a note to someone who lives in your house, do you write your address down and ship it out in the mail? Nope you put localhost 127.0.0.1 and keep it in the house
