### ISSUE TITLE
 Avoiding repetitive code

### ISSUE THREAD

**Issue by Cri5-W** [uNetworking/uWebSockets.js#407]
The code below is to send the main.js file from the server on request. And I have to write something like that for every single file that the client requests. Is there a way to do it more efficiently?
The client can request any file from the /public folder. Is there a way to put the request link and add it directly with the _dirname without doing it all manually for each file?
Even for files that are not .js (for example: model.glb)

```javascript
uwss.get('/public/js/main.js', (res, req) => {
    var data = fs.readFileSync(__dirname + '/public/js/main.js');
    if(data){
        res.write(data);
    }
    res.end();
});
```

**Comment by alexhultman** [comment]
In the user manual and in examples you can see the use of parameter routes.

/public/js/:filename

Where you can do

let filename = req.getParameter(0);
