### ISSUE TITLE
message pack disconnect

### ISSUE THREAD

**Issue by Tuner32** [uNetworking/uWebSockets.js#427]
If I send data used message pack, It logged WebSocket connection to 'wss://localhost:3333/' failed: Could not decode a text frame as UTF-8. this and disconnected

**Comment by slavaGanzin** [comment]
Hello. I use [notepack](https://www.npmjs.com/package/notepack.io) like this:
```
      ws.send(notepackIo.encode({key: 'value'}), true)
   // ....
      message: (ws, message, isBinary) => {
        const m = notepackIo.decode(Buffer.from(message))
```

Works just fine

**Comment by uasan** [comment]
Just need set second argument `isBinary` in method `send`  as `true`
