### ISSUE TITLE
How to attach data on request variable

### ISSUE THREAD

**Issue by vimalmistry** [uNetworking/uWebSockets.js#429]
I know there is no middleware on uWeb. But i figured out something like this by reading all threads. It's working.
But I just want to attach data on req variable so I can access further. Just like I can attach anything on `ws: WebSocket`

```
app.any('/api/*', (res, req) => {
    try {
        // @ts-ignore
        req.user = authorizeJwt(req); //---> like this
    } catch (e) {
        return res.writeStatus('403').end("Unauthorized");
    }
    req.setYield(true); // we did not handle it, keep matching
});

app.get('/api/user', (res, req) => {
    // @ts-ignore
    return res.end(JSON.stringify({ user: req.user || 'x' })); //---> So I can use here
});
```

I can attach on websocket upgrade
```
res.upgrade({
        url: url,
        id: url
    }, secWebSocketKey,
        secWebSocketProtocol,
        secWebSocketExtensions,
        context);
```

**Comment by hst-m** [comment]
seems that would make sense to pass the same res/req object through so you can set values, looks like currently you cant do that

**Comment by alexhultman** [comment]
res, req are isolated per handler, so this is invalid. If you want to share behavior between handlers, you can put that behavior in a function. Middlewares are really just glorified functions.

**Comment by hst-m** [comment]
so you have 2 options, can do this:
```javascript
app.any('/api/*',(res,req)=>{
    try{req.user=authorizeJwt(req)}catch(e){return res.writeStatus('403').end("Unauthorized")}
    switch(req.getUrl()){
    	'/api/user': return res.end(JSON.stringify({ user: req.user || 'x' }))
    	'/api/123': return res.end('123')
    }
})
```
you lose some small amount of performance by doing `req.getUrl()` and route in JS but not much. alternatively do this:
```javascript

app.get('/api/user', (res, req) => {
    try{auth(req)}catch(e){return res.writeStatus('403').end("Unauthorized")}
    res.end(JSON.stringify({ user: req.user || 'x' }))
})
.get('/api/123', (res, req) => {
    try{auth(req)}catch(e){return res.writeStatus('403').end("Unauthorized")}
    res.end('123')
})
const auth=req=>{req.user=authorizeJwt(req)}
```

**Comment by alexhultman** [comment]
If you think for a while you can easily solve this much more elegantly.

For instance you can easily decorate the get function into something like getAuthorized which has the authorization check decorated onto the get, or anything similar. I mean functional programming can solve the issue of middlewares just as elegant as middlewares themselves

**Comment by hst-m** [comment]
the key part missing to be able to do "middleware" is being able to pass values between handlers, but as said handlers are isolated. This is why a single handler solves the problem, and parse the url in JS. If you dont need any values passed between you can use multiple handlers with setYield

**Comment by vimalmistry** [comment]
@alexhultman Can you show by example. Aur hint. anything?

**Comment by alexhultman** [comment]
I mean this is a general programming thing. If you have a function that takes a function and returns a function, you can have it "decorate" it with added behavior much like a middleware.

**Comment by hst-m** [comment]
@vimalmistry I added example above, do one of those, I prefer the 1st option

**Comment by alexhultman** [comment]
Well the first option is really stupid. You turn a log2 router into linear which basically sucks as much as Express js

**Comment by hst-m** [comment]
It is a tiny amount to do getUrl and switch statement esp. compared to authJwt. I have benched this before. If you need the absolute best perf. that is why I include 2 options, but #2 has more redundancy. Most people need performance in the websockets.

**Comment by alexhultman** [comment]
Why on earth aren't you doing something like

```
.get('/api/user', authorized((res,req)=>{
    
}))

.get('/api/123', authorized((res,req)=>{
    
}))


```

**Comment by vimalmistry** [comment]
@hst-m, Thank you for your code. I also did same thing as per your second code. First one I think not suitable for dynamic routes. 

@alexhultman Yep. I tried higher order things like function returns function with contain req/res clouser. But I think it become to complicated.

There should be middleware or higher order things. So we can apply more and more common logic. like auth, adding headers, checking permissions etc.

Also. the `HttpRequest` typescript interface need to add dynamic user field type same as `HttpResponse` and `WebSocket`

**Comment by vimalmistry** [comment]
> Why on earth aren't you doing something like
> 
> ```
> .get('/api/user', authorized((res,req)=>{
>     
> }))
> 
> .get('/api/123', authorized((res,req)=>{
>     
> }))
> ```

Yep. Already did that. 
But my problem was I can not get value of `req.user`.
Now I can understand. Thanks @hst-m. The `app/* ` executed after `app/user'.
Thanks.

**Comment by vimalmistry** [comment]
> Why on earth aren't you doing something like
> 
> ```
> .get('/api/user', authorized((res,req)=>{
>     
> }))
> 
> .get('/api/123', authorized((res,req)=>{
>     
> }))
> ```

Now, How can I get res,req on authorized function.

Following code will not work.

```
.get('/api/123', authorized(req,(res,req)=>{
     
 }))
```

**Comment by alexhultman** [comment]
function authorized (f) {
return (res, req) =>{
// Decorated behavior
f(res, req)
}
}

**Comment by hst-m** [comment]
ok that helps clean up the look of the code which is good, though it takes some extra looking to understand what the code is doing
```javascript
.get('/api/user',authorized((res,req)=>{
    res.end(JSON.stringify({ user: req.user || 'x' }))
}))
.get('/api/123',authorized((res,req)=>{
    res.end('123')
}))

const authorized=callback=>(res,req)=>{
    try{req.user=authorizeJwt(req)}catch(e){return res.writeStatus('403').end("Unauthorized")}
    callback(res,req)
}
```

**Comment by alexhultman** [comment]
If you rename "callback" to "next" that essentially forms exactly the same chain you have in middlewares

**Comment by vimalmistry** [comment]
Thank you guys @alexhultman  @hst-m . Finally working solution :)
