### ISSUE TITLE
How to server static files from folder & Upload file save on this folder.

### ISSUE THREAD

**Issue by vimalmistry** [uNetworking/uWebSockets.js#431]
I am stuck at following problem
- How to serve static file folder (Just like express.static('/files'))
- How to save file from chunk with original mime types (tried example code)

My app have 4 api so I don't want to manage another server for this :) 
Thank you.

**Comment by hst-m** [comment]
use the [Discussions ](https://github.com/uNetworking/uWebSockets.js/discussions) tab for questions, for basic folder serve example see https://github.com/uNetworking/uWebSockets.js/discussions/407#discussioncomment-218059

**Comment by alexhultman** [comment]
That snippet works for small files only - if you reach GB of data you **have** to properly stream the data - and really, you kind of always should stream!

**Comment by alexhultman** [comment]
Look at examples/VideoStreamer.js instead - it shows how you can properly stream huge files with minimal backpressure.
