### ISSUE TITLE
Performance patch for Node.js MakeCallback

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#443]
Because I'm banned from Node.js for saying their MakeCallback is bloated and slow,

I need someone to write a PR in Node.js repo of the following patch:

```
diff --git a/src/api/callback.cc b/src/api/callback.cc
index a7b23dd492..ba5e32fec8 100644
--- a/src/api/callback.cc
+++ b/src/api/callback.cc
@@ -51,6 +51,12 @@ InternalCallbackScope::InternalCallbackScope(Environment* env,
   CHECK_NOT_NULL(env);
   env->PushAsyncCallbackScope();

+  // Skip costly pushing/popping if we pass zeroes as async context
+  if (async_context_.async_id == 0) {
+    pushed_ids_ = false;
+    return;
+  }
+
   if (!env->can_call_into_js()) {
     failed_ = true;
     return;
```

This de-bloats MakeCallback a bit, increasing the performance of native addons calling into JS by about 40%. Because MakeCallback is our bottleneck overall, this also improves overall performance of uWS.js by 9%.

Please open a PR and have this merged or at least looked at (I'm sure they will reject it because it doesn't check the same check 6 times in a row, which is standard in Node.js code), but worth a try.

**Tests are running...**

**Comment by alexhultman** [comment]
This doesn't seem to pass tests.. will try and fix it first.

**Comment by alexhultman** [comment]
Well, it doesn't pass tests without the fix either - fails at the same places so maybe this works after all

**Comment by alexhultman** [comment]
Node.js C++ source code is the worst, misguided piece of insanity I've ever seen.

**Comment by alexhultman** [comment]
All Node.js tests actually do pass 🤔

**Comment by alexhultman** [comment]
<img width="960" alt="wsl2" src="https://user-images.githubusercontent.com/3397140/106974086-638c8780-6754-11eb-9e35-e89f0f584faf.png">

Haven't really seen any perf. gains on Linux yet but will do more testing. Here clearly WSL2 performs significantly better.

**Comment by alexhultman** [comment]
This patch reliably boosts performance by 12% of req/sec on Linux. Please have it merged.

**Comment by alexhultman** [comment]
@benjamingr

**Comment by alexhultman** [comment]
Tested over Ethernet on my Pi 4; goes from a stable 70k req/sec to a stable 75k req/sec.

Both loaded at 400% CPU time.

**Comment by alexhultman** [comment]
How do I get unbanned? Do I have to color my hair purple and reject all basic biology, start drinking oatmeal coffee made by monks of Tibet and explicitly list my gender and start using zhie/xzyt pronouns? Definitely a vegan diet, that's a given.

How to be do a nodejs? Plix halp

**Comment by benjamingr** [comment]
> How do I get unbanned? Do I have to color my hair purple and reject all basic biology, start drinking oatmeal coffee made by monks of Tibet and explicitly list my gender and start using zhie/xzyt pronouns? Definitely a vegan diet, that's a given.

You start by not dissing project maintainers and being respectful :D You made some pretty snarky comments (and still are) and honestly people just don't want to put up with that sort of bullshit when contributing to open source.

It's pretty simple:
 - The project has some pretty reasonable rules (don't be mean to other people for no reason, don't discriminate people based on common-sense stuff like gender or race etc).
 - People working on the project mostly like (or don't feel strongly about) those rules.
 - When someone wants to collaborate with the project - they don't piss off lots of other people for no reason. Instead they act respectfully ^^

You are of course always welcome to fork Node and do a better job with a governance than those people.


------

So to answer your question directly:
 - You reach out to report@nodejs.org asking to be unbanned. This typically includes a rather straightforward apology: you acknowledge your conduct was inappropriate, you express regret and you pledge not to violate the code of conduct in the repo in the future.
 - You contribute (in good faith, _not_ being snarky) a patch (or just open an issue in the Node.js repo about the issue.

Also:

> Because I'm banned from Node.js for saying their MakeCallback is bloated and slow,

I think you need to reflect that is __not__ why you were banned from Node.js at all.

Lots of the code of Node.js is terrible, maintainers are honestly totally _fine_ with talking about how certain parts of the code aren't great. Most of the bad parts are blocked on people doing the (often tedious) work of improving them.

You were banned for BM and being needlessly confrontational.

**Comment by alexhultman** [comment]
> you acknowledge your conduct was inappropriate, you express regret

Not going to happen.

> you pledge not to violate the code of conduct in the repo in the future

I can do that.

**Comment by benjamingr** [comment]
> Not going to happen.

Are you perfectly content with your previous conduct in the Node.js repo?

**Comment by alexhultman** [comment]
Well if you want to analyze 5 year old texts then sure.

I just read the first texts of that issue and it starts off very scientific, factual and correct. Everything I said was correct and I would say it again today. In fact I'm impressed with how correct I was.

Then it begins to de-rail when I get these comments which are highly **belittling** and **invalidating**:

> Simply spouting that it's "bloated" **without anything technical to back up your claim** only makes it tedious **for those of us who are actually** investigating.

And

> Please, I beg of you to **stop arguing things you haven't tested or validated**. It's honestly **a waste of developer's time**. But to appease your insistence on something you're so sure of, let's simplify this.

If anything, this is belittling and classical "my time is more important than yours" kind of high horse talk.

And the fact that I was correct, had done my homework and had extensive proofs to back things up with only makes these belittling comments more intense.

After these comments it de-railed.

**Comment by alexhultman** [comment]
Basically I believe in peace until war. That's to say if you're nice and respectful to me I'll be nice and respectful to you. But if you belittle me and say that I'm a waste of time I'm going to mock you with sarcasm until you shut up. And that's exactly what I did.

It's a huge difference to mock an item vs. to mock a person. Mocking an item is basic freedom of expression and criticism. Mocking persons are... usually not necessary (but sometimes efficient).

So really, why should I apologise for being called a waste of time? For being all about openness and acceptance you sure are good at rejecting different thinking input and people who call a stone a stone.

**Comment by alexhultman** [comment]
@hst-m You interested in making a PR of this for me?

**Comment by alexhultman** [comment]
If this ever gets merged, I have another 13% optimizations for MakeCallback. This function truly is a complete train-wreck. There are remnants from 2018 that are semi-forgotten mid-thought and lines and jumps that makes no sense whatsoever. It's like someone forgot how an if-statement works mid-writing it and just commited and forgotten about it.

I've squeezed its overhead down by 53% by now. It is pretty much as fast as EXPERIMENTAL_FASTCALL by now.

**Comment by alexhultman** [comment]
Node.js source code is like "oh, this is a function that returns a C++ pointer, it must be a simple getter function" but OH SHIT IT ACTUALLY CREATES A TEMPORARY GARBAGE COLLECTION SCOPE, CREATES GARBAGE COLLECTED OBJECTS, USES THOSE OBJECTS TO LOOKUP SOME THREADSAFE SHIT ONLY TO THEN LEAVE THE GARBAGE AND RETURN WHAT YOU **ALREADY HAD BEFORE YOU EVEN CALLED THIS GETTER-HELLHOLE**

Sounds about right.

**Comment by alexhultman** [comment]
Or the fact that the authors seem to believe that 58 sequential conditional jumps marked as UNLIKELY are same same as 0 conditional jumps. They aren't. They are most likely going to be 58 god damn conditional jumps.
