### ISSUE TITLE
Update docs, getParts

### ISSUE THREAD

**Issue by paradis-A** [uNetworking/uWebSockets.js#455]
Im trying to send post method which has a json and a file. I've seen the jsonpost and upload example but i cant find the combination of those two. 

Heres the parsed from google chrome devtools from network tab
`
orm: [{"7920afe5-35d4-4bb8":[{"table":"filtest","refOnly":false,"id":null,"o":"i","d":{"image":"p@r@d1&41|e$-//ac428a17-d310-44a3","message":"adsadasd"},"relTable":null,"relID":null,"relType":null,"rID":"d6d46472-618c-4935"}]}]
type: write
7920afe5-35d4-4bb8.image.ac428a17-d310-44a3: (binary)
`
Heres the formdata
`
------WebKitFormBoundaryCZAzpwArS08GV2Cp
Content-Disposition: form-data; name="orm"

[{"7920afe5-35d4-4bb8":[{"table":"filtest","refOnly":false,"id":null,"o":"i","d":{"image":"p@r@d1&41|e$-//ac428a17-d310-44a3","message":"adsadasd"},"relTable":null,"relID":null,"relType":null,"rID":"d6d46472-618c-4935"}]}]
------WebKitFormBoundaryCZAzpwArS08GV2Cp
Content-Disposition: form-data; name="type"

write
------WebKitFormBoundaryCZAzpwArS08GV2Cp
Content-Disposition: form-data; name="7920afe5-35d4-4bb8.image.ac428a17-d310-44a3"; filename="svelte preproess bug.png"
Content-Type: image/png

------WebKitFormBoundaryCZAzpwArS08GV2Cp--
`

**Comment by alexhultman** [comment]
uWS.getParts(arrayBuffer) is your friend

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets.js/blob/61fa4bd06cf9db078716dc0c70bc5e8274d742f6/docs/index.d.ts#L319

**Comment by paradis-A** [comment]
@alexhultman 
Im not able to make it work
```javascript
 // im using babel-node
import server from "./uws"
import contentType from "content-type"
async function serve() {
    let prom = Promise
    let app = server.App()
    app.get("/*", async (res, req) => {
        console.log("log")
        res.writeHeader("Access-Control-Allow-Origin", "*") //allow cors
        res.end("hello world")
    })

    app.post("/paradis", async (res, req) => {
        res.writeHeader("Access-Control-Allow-Origin", "*") //allow cors
        let headers = {}
        req.forEach((k, v) => {
            headers[k] = v
        })
        //content-type
        let type = contentType.parse(headers["content-type"]).type
        res.onData(async (chunk, isLast) => {
            /* Buffer this anywhere you want to */
            console.log("Got chunk of data with length " + chunk.byteLength + ", isLast: " + isLast)
            /* We respond when we are done */
            if (isLast) {
                let buffer = Buffer.from(chunk)
                let string = Buffer.from(chunk).toString()
                let payloadFromChunk = server.getParts(chunk,type)
                let payloadFromBuffer = server.getParts(buffer,type) 
                let payloadFromString = server.getParts(string,type) 
                console.log(payloadFromChunk) //returns undefined
                console.log(payloadFromBuffer) //returns undefined
                console.log(payloadFromBuffer) //returns undefined
                res.end('Thanks for the data!');
            }
        })

        console.log("request received")
        res.onAborted(() => {
            console.log("aborted")
        })
        return Promise.resolve(true)
    })

    app.listen(1234, (token) => {
        if (token) {
            return prom.resolve(true)
        } else {


            console.log("failed listening")
            return prom.reject()
        }
    })
}

;(async function main() {
    await serve()
    console.log("Server is now listening")
})()

```

Log
![multipart uws](https://user-images.githubusercontent.com/42695235/108012938-d654f880-6fc7-11eb-9b18-ffa0c21d0f2d.jpg)

**Comment by paradis-A** [comment]
Im only able to get parts using Busboy. I hope there's a better way coz i dont want to uws to slow down a bit bcoz of Busboy.

```javascript
let buffer = Buffer.from(chunk)
let bb = new Busboy({headers: {'content-type': headers["content-type"]}})
//some Busboy events
bb.end(buffer)
```

**Comment by alexhultman** [comment]
You are not passing content-type, you're passing some kind of parsed-up nonsense. Why would the library have a feature that would be dependent on some other module? It makes no sense, but I'll give you a pass since there is in fact no documentation explicitly stating that, yes, you pass contentType as in content-type...

**Comment by alexhultman** [comment]
It's a puzzle of two pieces so I guess there are a dozen ways to fuck it up

**Comment by paradis-A** [comment]
@alexhultman 
Yay. I fucked it up seriously.
``javascript
let payloadFromChunk = getParts(chunk,headers["content-type"]) // that worked,
```
Thank you for your quick respond and I really appreciate your hard-work. God bless.

**Comment by alexhultman** [comment]
Well I cannot sleep so nothing else to do
