### ISSUE TITLE
How to supply host to listen()

### ISSUE THREAD

**Issue by thomasb892** [uNetworking/uWebSockets.js#456]
I have code like this -

```
require('uWebSockets.js').App().ws('/*', ... ).get('/*', ...).listen(9001, (listenSocket) => {

  if (listenSocket) {
    console.log('Listening to port 9001');
  }
  
```

How do I make this listen at 127.0.0.1:9001 or 192.168.0.1:9001 ?

**Comment by alexhultman** [comment]
You can read the docs https://unetworking.github.io/uWebSockets.js/generated/interfaces/templatedapp.html#listen
