### ISSUE TITLE
Pattern matching

### ISSUE THREAD

**Issue by lusatiro** [uNetworking/uWebSockets.js#464]
Hey, congrats for the great project!

I was reading about the way pattern matching is done: https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#pattern-matching

And I got a question. If someone needs to use a route as a middleware, for example:
```typescript
app.get('/account/*', ...
...
app.get('/account/:id' ...
```
where all requests with the `account` prefix must pass through this middleware. How could I do that once that routes with `*` have the lowest priority and are not registered by order? Is that even possible?

**Comment by hst-m** [comment]
your 2 options are these:
```javascript
app.get('/account/:id',(res,req)=>{
   middleware()
   // code here
})

app.get('/account/:id',middleware((res,req)=>{
   // code here
}))
```
the 2nd option gives more flexibility for handling response, see https://github.com/uNetworking/uWebSockets.js/issues/429#issuecomment-758492087

**Comment by hst-m** [comment]
You are trying to do multiple `app.get()` routes to stack together middleware but it doesn't work that way because you can't pass data between them. Also there is route ordering requirements like you mentioned. If you don't need to pass data between them you could use [setYeild ](https://unetworking.github.io/uWebSockets.js/generated/interfaces/httprequest.html#setyield) to do multiple `app.get()` routes per request. But generally for what people consider middleware you want to do as described above, add middleware to each route, and not use a different route for each middleware (can't pass data between)

**Comment by lusatiro** [comment]
Sounds good. But just in case I had more than one middleware, won't the code be bloated?
Anyway, your answer is pretty good and the high-order function approach seems the best to me.

**Comment by hst-m** [comment]
> in case I had more than one middleware, won't the code be bloated?

if you have many different routes you do need to specify the middleware in each route, rather than doing a middleware route and mixing with other routes, as routes don't share data. if you have more examples come back and post and can discuss if is good way

**Comment by hst-m** [comment]
having many middlewares can be very clean with minimal code, here is example with 3 middlewares (auth, limit, stats) plus route:
```javascript
.get('/account/:id',auth(limit(stats(account))))
```
I did full mini example below that you can run, refresh the page for users `/account/1` and `/account/2` and it will rate limit your requests per user (1 per second) and track request counts

```javascript
const start=()=>require('uWebSockets.js').App()
.get('/account/:id',auth(limit(stats(account)))) // 3 middlewares (auth, limit, stats) + account route
.get('/*',res=>res.writeStatus('404').end('not found'))
.listen(3000,()=>{})

// routes
const account=(res,req)=>res.end(`account ${JSON.stringify(req.user)}`)

// middlewares
const auth=next=>(res,req)=>{
   req.user=users.get(req.getParameter(0))
   if(!req.user)return res.writeStatus('404').end('not found')
   next(res,req)
}
const limit=next=>(res,req)=>{
   if(reqLimit(req.user))return res.writeStatus('429').end('overlimit')
   next(res,req)
}
const stats=next=>(res,req)=>{
   req.user.requests++
   console.log('add stats', JSON.stringify(req.user))
   next(res,req)
}

// setup
const users=new Map().set('1',{id:1,requests:0}).set('2',{id:2,requests:0})
const RateLimit=(limit,interval)=>{let now=0;const last=Symbol(),count=Symbol();setInterval(()=>++now,interval);return obj=>{if(obj[last]!=now){obj[last]=now;obj[count]=1}else{return ++obj[count]>limit}}}
const reqLimit=RateLimit(1,1000)

start()
```

**Comment by hst-m** [comment]
can also reduce code by combining middleware into 1 function 
```javascript
const stack=route=>auth(limit(stats(route)))

app.get('/account/:id',stack(account))
```

**Comment by lusatiro** [comment]
Thank @hst-m for your examples and time. I working on an adapter using uws to work with a set of interfaces I defined. That will help!
