### ISSUE TITLE
Cluster in Linux Debian [Solved]

### ISSUE THREAD

**Issue by incapdns** [uNetworking/uWebSockets.js#467]
**Error:**
Only one process is receiving requests, as the PID displayed in a request is the same for all connections
Example: (Line 18)
1 request: PID 5839
2 request: PID 5839
3 request: PID 5839

**Observation:**
This problem happens only with the uWebSockets.js module, when using the standard HTTP module of NodeJS or a c ++ addon module for NodeJS like Mitol or Hellepoll the load distribution works correctly

**HTTP command:**
curl --no-keepalive http://127.0.0.1:1000

**WS code:**
```
const WebSocket = require('ws');

for(let i = 0; i < 5; i++){
	let ws = new WebSocket('ws://127.0.0.1:1000/test');

	ws.on('open', function () {
	  ws.send('test')
	})

	ws.on('message', function (data) {
	  console.log(data.toString());
	})
}
```

**Linux version:**
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

**uws Server Code:**
```
const cluster = require('cluster')
const numCPUs = require('os').cpus().length

function masterProc() {
    console.log(`Master ${process.pid} is running`);
    for (let i = 0; i < numCPUs; i++) {
        console.log(`Forking process number ${i}...`);
        cluster.fork();
    }
}

function childProc() {
    console.log(`Child PID: ${process.pid} running`);

    const app = require('uWebSockets.js').App()

    app.any("/*", res => {
      res.end('PID '+process.pid+'')
    }).listen(1000, () => {})
}

if (cluster.isMaster) {
  masterProc();
} else {
  childProc()
}
```

If debugging is necessary, I would like to request remote access to my computer via TeamViewer or Anydesk or another tool.

**Comment by hst-m** [comment]
I just tried this with Cluster and Worker Threads and I got it working on both using different workers, I have 2 suggestions to try:

1) depending on how you make requests to the server it might re-use the same worker, for example it does that for me with server on VM virtual machine on local machine when I make requests through forwarded ports. Instead try running `wget localhost:1000` on the same machine as server and it will use different worker each time

2) You might need to test by making concurrent requests with enough load to make it split between workers. Use a http test program to give it concurrent load like [autocannon ](https://github.com/mcollina/autocannon) `sudo npm i autocannon -g` and run `autocannon localhost:1000`

**Comment by hst-m** [comment]
I see that it uses different workers if I use 2 different browsers to make the requests (firefox/chrome) to local machine, otherwise it used the same worker with 1 browser

**Comment by hst-m** [comment]
Actually only Chrome browser was re-using the same worker, Firefox used different worker each time. Chrome probably re-using the connection or something

**Comment by incapdns** [comment]
I have a doubt: I am running Debian through WSL (Windows Subsystem for Linux), and not a 100% Linux version (such as: Virtualbox or VMWare etc), could this be resulting in this problem?

I've tried using Firefox and even created a NodeJS application to generate a new connection (using request plugin) but the problem continues, so I think it may be related to WSL (Windows Subsystem for Linux)

**Comment by hst-m** [comment]
> I have a doubt: I am running Debian through WSL (Windows Subsystem for Linux), and not a 100% Linux version (such as: Virtualbox or VMWare etc), could this be resulting in this problem?

You should do `wget localhost:1000` on the same machine as server and it will very likely work, it will alternate each request between each worker. Did you try that? From what I am showing on cloud vms and local vm browsers can re-use connections/workers staying on 1 worker. If you alternate requests between different browsers it will switch to different workers

**Comment by hst-m** [comment]
Oh you are on Debian so you can use `curl` which is pre-installed `curl localhost:1000`

**Comment by incapdns** [comment]
> > I have a doubt: I am running Debian through WSL (Windows Subsystem for Linux), and not a 100% Linux version (such as: Virtualbox or VMWare etc), could this be resulting in this problem?
> 
> If you want to know for sure you should use `wget` to make requests to server, use it like `wget localhost:1000` or `wget mydomain.com` and it will alternate workers each request

Yes, plz verify:
1 Request: Google Chrome
2 Request: Firefox (Recent install + Anonymous tab)
3 Request: wget http://127.0.0.1:1000
4 Request: curl http://127.0.0.1:1000
![image](https://user-images.githubusercontent.com/40347728/110067755-1ef40c00-7d53-11eb-8303-e79bf42fa18e.png)

**Comment by hst-m** [comment]
So looks like probably something up with WSL preventing that. I dont have WSL to try it. I use VirtualBox with [Vagrant](https://www.vagrantup.com/) to automate stuff. You should probably be running the full VM and not the WSL to get more accurate virtual environment

**Comment by incapdns** [comment]
Yes, it really seems to be the case.

I tested it on a virtualized Linux server (using VirtualBox) and it worked 100%, The printscreen of the operation on the virtual machine below:

![image](https://user-images.githubusercontent.com/40347728/110069397-76e04200-7d56-11eb-85f9-faeaf68b93de.png)

**Problem solved !**

But I'm curious because it doesn't work on WIndows or on Linux subversions like WSL

**Comment by hst-m** [comment]
A google search produces stuff like "WSL Network communication (although possible) requires several layers to pass through, making the WSL not ideal for low-level networking processes" and "Networking on WSL isn't fully reliable. WSL allows you to communicate with a network, but it may not be the best way to do so as it needs to pass through a few layers in order to do work"

**Comment by incapdns** [comment]
Got it, thanks anyway for helping.

I will be using uWebSockets.js for a VPS server application with the Centos 8 operating system, now that the question has been resolved, I feel more relaxed.

I will be closing the topic, thank you!

**Comment by alexhultman** [comment]
Multithreading is known to work: https://levelup.gitconnected.com/serving-100k-requests-second-from-a-fanless-raspberry-pi-4-over-ethernet-fdd2c2e05a1e
