### ISSUE TITLE
Alternative Node.js integration

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.js#478]
Currently we use libuv and node::MakeCallback to integrate with Node.js.

libuv is not terrible but certainly not great and MakeCallback is the worst thing to happen to man kind.

Alternatively one could integrate by throwing out both of these and instead using a polling integration where a loop of setImmediate is used to poll for new events from the uWS event-loop.

Doing so entirely eliminates the need for MakeCallback and is according to benchmarks about 15% faster. This also eliminates libuv, meaning we would no longer depend on anything from the Node.js camp, which is great.

Polling is more CPU-demanding in idle situations but could be replaced for a slow path after a few milliseconds of inactivity or similar.

Doing this could also be accompanied by a swap from OpenSSL to BoringSSL since that means about 18% faster SSL, and further distances this project from the Node.js camp.

Once this is done, if necessary, a similar integration could be ported to Deno since we then would not need to depend on anything from the Deno camp. I don't think Deno will be relevant any time soon, or ever, but having a plan for the worst case scenario is always a good idea.

By dropping libuv and all that stuff, it also opens up for radical tech that would not be possible otherwise.

**Comment by uasan** [comment]
> using a polling integration where a loop of setImmediate is used to poll for new events from the uWS event-loop.

and
> is according to benchmarks about 15% faster

It looks like you increased your CPU utilization so you got better performance, if I'm right, does this mean that the performance per watt of power has gotten worse?

**Comment by alexhultman** [comment]
No the CPU-time spent is 100% in both cases. The polling solution does not use node::MakeCallback and is thus not fundamentally crippled by bottomless incompetence.

**Comment by uasan** [comment]
Another question, will it be potentially to integrate the uWS to the process `Chrome Headless` or `NW.js`?

**Comment by alexhultman** [comment]
I've mostly considered Deno. If Deno blows up, this integration would be necessary.

**Comment by mattiasewers** [comment]
Maybe https://github.com/just-js/just could be of inspiration

**Comment by alexhultman** [comment]
> Maybe https://github.com/just-js/just could be of inspiration

A standard can only be a standard if people stop making new standards. We have Node.js and now we also have Deno. Deno is stillborn for now, maybe it starts kicking in the future and if it does then it might be necessary to support. I would write my own stack if I had the gazillions of hype that Ryan has, which I do not have.
