### ISSUE TITLE
wildcard path don't processed when you go to specific path

### ISSUE THREAD

**Issue by Adidi** [uNetworking/uWebSockets.js#479]
If i want to make some `middleware` that always check something (lets say auth) before any other route if i go to specific route - this general `middleware` is never called:
```ts
uWSApp.any(
		'/api/*',
		async (res, req): Promise<void | uWS.HttpResponse> => {
			const jwt = req.getHeader('authorization');

			console.log('api any check auth');

			try {
				await JWT.verifyToken<{ uid: string }>(jwt);
			} catch (ex) {
				logger.logError(`rest connection failed with token:`);
				return res.writeStatus('403').end('unauthorized');
			}

			req.setYield(true);
		}
	)
	.get('/api/users', res => {
		res.end('secure users');
	});
```

if i `curl` to wildcard path lets say `/api/stam` - then the `any(/api/*)` will executed and will check if this user is authorized
but if i go to a specific route like in the code above  `get /api/users` then the any will not occure.
is this intentional ? how can i make lets say function `middleware` like that check for auth (or whatever) ?

**Comment by hst-m** [comment]
This other guy had the same question couple days ago, did you see this https://github.com/uNetworking/uWebSockets.js/issues/464 how to do middleware. I am using this method for all my routes

**Comment by alexhultman** [comment]
This behavior is very much intentional and the user manual covers this questionnaire

**Comment by Adidi** [comment]
@alexhultman so I think its very unclear api - what is `setYield` for in that case ? 
Can u send me also a link to the user manual ?

Thanks

**Comment by hst-m** [comment]
@Adidi the manual is the first link on the [ReadMe](https://github.com/uNetworking/uWebSockets.js) page. Did you review the issue I linked above to answer your question

**Comment by alexhultman-2fa** [comment]
There are plenty of discussions regarding middleware already. Look in Discussions
