### ISSUE TITLE
uWebsockets publish dropping messages

### ISSUE THREAD

**Issue by rpgehlot** [uNetworking/uWebSockets.js#499]
Hi @alexhultman  ,
Thanks for this great and efficient library which i have to started to use recently in place of socket.io which was giving us horrible performance in production.
Basically we are using it in context of a trading platform which is in house to our firm. There we get around ~400 msg/sec of ~2KB with ~60 connected websocket clients. We are using uWebsockets pub-sub with maxBackPressure setting of 6KB.
Everything was fine, but we noticed some messages are being dropped. I understand its happening because of built up backpressure because of which it drops messages for slow client or either drops their connection.
Also i tried using ws.send method and manage backpressure using ws.getBufferedAmount() and implement my own pub-sub over it but obviously it was much slower and useless.

I really want to use your library becuase its way efficient than others, but if you can help me to fix this problem of message drop, that would be very grateful of you.

**Comment by hst-m** [comment]
> I understand its happening because of built up backpressure because of which it drops messages

Are you saying you'd prefer it drop the connection rather than drop messages? This was discussed previously to add this option but don't think it was added yet. Currently just drops message if backpressure > maxBackPressure. Raise your maxBackPressure if you need to

**Comment by hst-m** [comment]
Docs need to be updated, there is new option closeOnBackpressureLimit to drop connection rather than drop message

**Comment by alexhultman-2fa** [comment]
Hi, https://github.com/uNetworking/uWebSockets/releases/tag/v18.22.0 did introduce closeOnBackpressureLimit but it looks like that option was never wrapped here.

**Comment by alexhultman-2fa** [comment]
@rpgehlot Can you test the very latest binaries? https://github.com/uNetworking/uWebSockets.js/tree/binaries

they should have closeOnBackpressureLimit option

**Comment by rpgehlot** [comment]
Thanks for the quick replu

> > I understand its happening because of built up backpressure because of which it drops messages
> 
> Are you saying you'd prefer it drop the connection rather than drop messages? Docs need to be updated, there is new option closeOnBackpressureLimit to drop connection rather than drop message. If you don't want it doing either you should raise limit

**Comment by rpgehlot** [comment]
Thanks for your prompt reply, but i needed centos 7 binary and i actually dont have root access so can't build that bin right now. will  get it built and try out it this option.

**Comment by rpgehlot** [comment]
Hi, if i increase the maxBackpressure to 11MB for e.g,  how would it affect the latency of packets reaching the browsers ? would the perf suffer because of high maxbackpressure ?

**Comment by rpgehlot** [comment]
I am seeing poor performance with  maxBackpressure=11MB and closeOnBackpressureLimit : true and no drops, and  low latency with maxBackpressure=6KB and closeOnBackpressureLimit:false but with message drops, i guess there is no middle ground. or is there ?

**Comment by alexhultman-2fa** [comment]
11MB backpressure sounds like a lot if you care about latency. If latency is a concern, set backpressure low. But either way you cannot just shove messages like there's no tomorrow - if you constantly end up with messages stuck in backpressure then you're sending too quick.

**Comment by rpgehlot** [comment]
So, if we can't control that incoming rate, would some kind of rate limiter would be helpful which can control outward messages sent per sec to each client ? and is there a possibility we can use such a thing with publish ?

**Comment by hst-m** [comment]
> i guess there is no middle ground. or is there ?

11MB is 2000 times larger than 6KB, the middle ground would be all the values in between

> we get around ~400 msg/sec of ~2KB with ~60 connected websocket clients

each message is 2KB? so you are publishing 800KB per second to 60 clients? or is that 2KB per sec, 5 bytes per message?

**Comment by rpgehlot** [comment]
thats the worst case figures i have mentioned, message rate is actually variable depending on the trading volume. So yes it would amount to 800KB per sec for a single client and we have 60 such clients. most of the messages are 2KB but initial first message amounts to a little bigger value  upon connection start, so thats why i used 11MB. if i use a smaller value of 6KB then it actually closes the connection at start itself and stuck in a infinite loop since i used closeOnBackpressureLimit : true

**Comment by uasan** [comment]
I think you need to pause before sending the next message if there is backpressure on the socket
```JS
if (socket.write(msg) === false) {
  await socket.onDrain();
}
```

**Comment by hst-m** [comment]
So you tried 6KB which is smaller than a single message, and you tried 11MB which is 14 seconds of 800KB/sec. Have you considered trying anything between those 2 values?

800KB/sec seems like a lot, are you sure these are efficiently packed messages? Binary format etc?

**Comment by rpgehlot** [comment]
No i haven't tried anything b/w. I encode json messages to `arraybuffer(binary message)` as that is preferred in uWS (from docs). 
Currenlty i am sending all messages using 
`uApp.publish(<message_room>, binarybuffer, true, true)` and it should do compression as last flag is true.
I am thinking to break the bigger message in chunks size smaller than maxbackpressure, and send using `ws.send`  if there is no backpressure  else wait for drain to send the next chunk. So a combination of ws.send and ws.publish but publishing only when whole chunk is sent. (as there io no order guarantee b/w publish and send).
This hopefully should give me the perf boost using smaller maxbackpressure and also to avoid the problem of connection close on first message.

**Comment by uasan** [comment]
On the client in Chrome, this problem is nicely solved with the help of the interface `WebSocketStream`
https://web.dev/websocketstream/

You need to do something like this for the server

**Comment by hst-m** [comment]
> I encode json messages to arraybuffer

What does this mean? does not make any sense. JSON is a utf8 string of encoded values. Sounds like you are sending JSON and trying to compress it which is inefficient way to send large amounts of data

> No i haven't tried anything between

You may want to trying something between 6KB and 11MB if you are looking for middle ground

**Comment by rpgehlot** [comment]
Can you suggest a good soln for efficiently sending large data ?
Ok will try

**Comment by hst-m** [comment]
JSON vs binary:
```javascript
// data to send
data={field1:3751923517,field2:1842963572}
```
```javascript
// JSON encode
ws.send(JSON.stringify(data)) // 41 bytes of JSON utf8 string + cpu time to encode
```
```javascript
// Binary encode
buf=Buffer.allocUnsafe(8)
buf.writeUInt32BE(data.field1)
buf.writeUInt32BE(data.field2,4)
ws.send(buf,true) // 8 bytes of Binary
```
JSON with 41 bytes is sending 5 times more than the 8 bytes of Binary and it uses more CPU to encode string. So your 800KB/sec would then be 160KB/sec. Probably would help your backpressure issue
