### ISSUE TITLE
Node v15 support - Centos 7/8

### ISSUE THREAD

**Issue by ramiroaisen** [uNetworking/uWebSockets.js#500]
First of all, thanks for this great sofware...
Are you planning to support node v15.x ? Centos 7/8 pre-built binaries would be great too.
Thanks

**Comment by hst-m** [comment]
Where did you get idea Node 15 was not supported? Centos is Linux and yes Linux is also supported with the standard install which includes binaries

**Comment by ramiroaisen** [comment]
I tried to use the library in node v15 with no success "Module did not self register error"
Also I had to install uws from here https://github.com/dominicklee/uWebSockets.js-for-Centos7 to make it run in centos 7.

**Comment by hst-m** [comment]
Install with `npm install uWebSockets.js@uNetworking/uWebSockets.js#v18.14.0` and use `require('uWebSockets.js')`

I have not tried uWS on Debian 7/8. Aren't they on Debian 10 now? Seems like as long as you install Node correctly the uWS binaries should work. I was going to start a Digital Ocean droplet to try but they don't even offer Debian 8, only 9/10

**Comment by hst-m** [comment]
Ah Centos thats right, try the above install lines

**Comment by alexhultman-2fa** [comment]
Centos 7 has a 6 year old compiler installed and is not a target platform

**Comment by ramiroaisen** [comment]
Is the same with Centos 8?

**Comment by hst-m** [comment]
I just booted up CentOS 8 and installed Node 15 + uWS.js and ran a server in like 1 minute with no issues, just needed to install Git, not sure where you are having problem

**Comment by ramiroaisen** [comment]
No. I have Centos 7 in my machine, i was just asking if the same problem was there in Centos 8, glad it doesnt
Thank you!

**Comment by hst-m** [comment]
I just tried CentOS 7 and I did hit that `GLIBC_2.18 not found` error, so ya something up with CentOS 7 but yes CentOS 8 works fine
