### ISSUE TITLE
Node.js 16

### ISSUE THREAD

**Issue by alexhultman-2fa** [uNetworking/uWebSockets.js#503]
Releases in 10 days which is a nice sync up with v19 release and from what I understand official Apple ARM support

**Comment by alexhultman-2fa** [comment]
At this point 10, 11, 13 binaries should be deleted as they are all deprecated - only 12, 14,15, 16 are currently maintained

**Comment by Dmitry-N-Medvedev** [comment]
Node.js v16.0.0 has just been released :) Waiting for the uWS to catch up :)

**Comment by gjovanov** [comment]
What about win port for node 16?

we are getting this:
```
Error: This version of µWS is not compatible with your Node.js build:
Error: Cannot find module './uws_win32_x64_93.node'
```

**Comment by gjovanov** [comment]
actually, ignore my last comment, after cleaning up node_modules and reinstalling, it works just fine.

**Comment by alexhultman-2fa** [comment]
Yep, you're hitting an NPM bug. Use Yarn instead, it does not suck asshole for breakfast.

**Comment by gjovanov** [comment]
actually we are using `pnpm`, which is much better than `npm`, but still somehow we have managed to have left-overs from old installations.  Anyways, the important this it's that it's working nice.

Great stuff . Appreciate your effort put in `uWebSockets` and `uWebSockets.js`!

**Comment by talentlessguy** [comment]
same error

node 16.2
pnpm 6.2.5

**Comment by alexhultman-2fa** [comment]
Node.js 16 is definitely supported and has been since day 1, if that is what is being reported here.

**Comment by talentlessguy** [comment]
@alexhultman-2fa probably it's an installation issue then :thinking: 

i tried pnpm, npm and yarn and this error occurs in all 3 package managers (a low-http-server project depends on uws git repo)

**Comment by alexhultman-2fa** [comment]
uWebSockets.js has definitely and absolutely supported Node.js 16 since day 1. I don't care what third party wrappers do and don't do.

**Comment by alexhultman-2fa** [comment]
Well that's not my problem

**Comment by alexhultman** [comment]
It fails because you are installing an old version.

**Comment by Stunext** [comment]
I change the version in package.json and use "npm update" comand and it works. This can resolve "npm install" issues

**Comment by alexhultman** [comment]
That's always good to know but IMO it's still a bug in NPM when it's behavior differs from old versions / docs.

Yarn doesn't have these blatant breakages and it's way faster so NPM is really irrelevant

**Comment by dzcpy** [comment]
What about node.js 17?

**Comment by stkeers** [comment]
> mesmo erro
> 
> nó 16.2 pnpm 6.2.5
> 
> acontece com o fio 1.22.5 também
> 
> código de reprodução:
> 
> ```js
> // index.mjs
> 
> import createServer from 'low-http-server'
> import { App } from '@tinyhttp/app'
> 
> const server = createServer()
> 
> const app = new App()
> 
> app.get('/', (res) => {
>   res.send('hello world')
> })
> 
> server.on('request', app.attach)
> 
> server.listen(3000, () => console.log('Server listening on http://localhost:3000'))
> ```

Onde acho esse arquivo para editar? estou perdido, sou novo com soketi. Pode me ajudar?

**Comment by uNetworkingAB** [comment]
Please translate
