### ISSUE TITLE
How to use ejs with uWebSockets.js?

### ISSUE THREAD

**Issue by Doumor** [uNetworking/uWebSockets.js#516]
https://ejs.co/

I need to add data to the HTML files I send. How do I do this with ejs in uWebSockets.js?

**Comment by hst-m** [comment]
the same way you do it in node.js, why are you opening issue for this, ejs is a basic string template library

**Comment by Doumor** [comment]
> the same way you do it in node.js, why are you opening issue for this, ejs is a basic string template library

Okay, thank you!
