### ISSUE TITLE
Is uWebSockets.js compatible with Passport.js?

### ISSUE THREAD

**Issue by Doumor** [uNetworking/uWebSockets.js#517]
https://www.passportjs.org/

**Comment by hst-m** [comment]
not compatible, passport.js is express middleware but you don't need it

**Comment by Doumor** [comment]
> not compatible, passport.js is express middleware but you don't need it

How do I authorize users then?

**Comment by Doumor** [comment]
https://github.com/fastify/fastify-passport

Fastify has a port to work with passport.js.

Anyway, the problem is actually that I'm migrating from Express. I need something +/- secure and VERY fast. If you can't use passport.js in uWebSockets, I'll migrate to fastify. Even simply very fast ws:// is already cool.

**Comment by hst-m** [comment]
> How do I authorize users then?

look at the headers of the request, authorize users as needed, if you are not capable of doing something simple like this this library is not for you

**Comment by hst-m** [comment]
normally this involves looking at and setting secure http Cookies

**Comment by Doumor** [comment]
> look at the headers of the request, authorize users as needed, if you are not capable of doing something simple like this this library is not for you

Well... That's not the problem. The problem is that I have more than one authorization strategy. Describing them all would be quite difficult.

**Comment by Doumor** [comment]
> normally this involves looking at and setting secure http Cookies

The last time I did this was when I was writing PHP. It was fun and exciting, until I wanted to write something huge and scary...
