### ISSUE TITLE
What are you doing with process.nextTick?

### ISSUE THREAD

**Issue by AlexTolmachev** [uNetworking/uWebSockets.js#52]
Just importing your library does some strange things to other libraries, ex. [amqplib](https://www.npmjs.com/package/amqplib). I think it's related to this code from uws.js file:
```javascript
/* We are not compatible with Node.js nextTick and/or domains */
process.nextTick = (f, ...args) => {
  uWS.nextTick(() => {
    f(...args);
  });
};
process.on('beforeExit', () => {
  if (uWS.processNextTickQueue()) {
    setImmediate(() => {

    });
  }
});
/* process.nextTick = setImmediate; */
```

When i import uWS amqplib's [channel.sendToQueue](https://www.npmjs.com/package/amqplib#promise-api-example) method execution delays by exactly 30 seconds (ofc. without importing uWS there's no delay at all).

And i can manipulate this delay with following code:
```javascript
setInterval(() => {
  uWS.processNextTickQueue(); // found this method in uws.js file
}, INTERVAL_VALUE);
```
With such interval amqplib's channel.sendToQueue execution delay becomes __almost equal to INTERVAL_VALUE__.

Can you explain this behavior?

**Comment by alexhultman** [comment]
We need a few fixes here then

**Comment by alexhultman** [comment]
Can you provide a full example demonstrating the issue

**Comment by AlexTolmachev** [comment]
Oh, my project is a little bit to big for github issue  🤓

So here's short example, which you can use for debugging:
```javascript
import uWS from 'uWebSockets.js';
import amqplib from 'amqplib';

const app = uWS.App();

app.get('/test', async (res) => {
  res.onAborted(() => {
    res.aborted = true;
  });

  console.time('5. total');

  console.time('1. connection');
  const connection = await amqplib.connect('amqp://localhost');
  console.timeEnd('1. connection');

  console.time('2. channel');
  const channel = await connection.createChannel();
  console.timeEnd('2. channel');

  console.time('3. assertQueue');
  await channel.assertQueue('uws-example-queue', {
    arguments: {
      expires: 5000,
      messageTtl: 5000,
    },
  });
  console.timeEnd('3. assertQueue');

  console.time('4. sendToQueue');
  await channel.sendToQueue('uws-example-queue', Buffer.from(JSON.stringify({ foo: 'bar' })));
  console.timeEnd('4. sendToQueue');

  console.timeEnd('5. total');

  if (!res.aborted) {
    res.end('');
  }
});

app.listen(80, () => {});
```

Here's "benchmarking" results:
![image](https://user-images.githubusercontent.com/33148533/52525062-0d93bf00-2cb5-11e9-837a-cfe47ba6da31.png)

RabbitMQ installation instructions:
https://www.rabbitmq.com/download.html

To use ES6-modules use "--experimental-modules" node flag when running example above.

**Comment by alexhultman** [comment]
I got this:

```
1. connection: 118.306ms
2. channel: 4.756ms
3. assertQueue: 38.321ms
4. sendToQueue: 4.308ms
5. total: 167.952ms
1. connection: 45.734ms
2. channel: 0.926ms
3. assertQueue: 0.565ms
4. sendToQueue: 0.185ms
5. total: 47.692ms
1. connection: 44.532ms
2. channel: 1.310ms
3. assertQueue: 0.805ms
4. sendToQueue: 0.123ms
5. total: 47.213ms
```

What OS are you running? Are you really running last version, compiled yourself?

**Comment by AlexTolmachev** [comment]
I'm running MacOS Mojave 10.14.2 (18C54)

Installed uWS via `npm install uNetworking/uWebSockets.js#v15.0.0`

**Comment by alexhultman** [comment]
Ah yes then you haven't got the fix. I don't build new versions that often.

Btw, pretty damn cool that you can actually have a proper async/await flow using other libraries and resulting in some Http response. That's amazing haha :) Almost makes me want to use it myself :)

Anyways, it's not that hard to build this code. You basically clone it and hit "make" and it's done. You can try that and make sure it works.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets.js#build-from-source

**Comment by AlexTolmachev** [comment]
Yeah, this is amazing!

What about using CI to build new code as soon as you push it to the repo? It would be very nice not to brake node.js dependencies installation flow (using npm i and package.json, you know)

**Comment by alexhultman** [comment]
Maybe later, did you manage to built it and make it work?

**Comment by alexhultman** [comment]
Please test newest release, every commit is now automatically built for all platforms :+1:

**Comment by AlexTolmachev** [comment]
Thanks a lot, everything works now!
