### ISSUE TITLE
socket.publish failure?

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets.js#525]
I have a use case where a socket sends a message and the server is supposed to broadcast it to all others:

```js
if (sender) {
  sender.publish(subscription.id, subscription.message)
} else {
  app.publish(subscription.id, subscription.message)
}
```

However, if the `sender` is closed then this code will actually not send the message to anyone. What's the best way to handle this?

Wouldn't it better to have a different signature on `app.publish`? Something like:

```js
app.publish(sender, subscription.id, subscription.message) // if first arg is socket, don't publish to it
```

**Comment by alexhultman-2fa** [comment]
If sender "is closed" you cannot do anything with it - it should throw in that case. So either keep track of when sender closes, or handle the exception. If sender is closed then app.publish will have the same behavior (send to all but sender is the same if sender is closed).

**Comment by ronag** [comment]
> If sender "is closed" you cannot do anything with it - it should throw in that case. 

Looking at the [code](https://github.com/uNetworking/uWebSockets.js/blob/master/src/WebSocketWrapper.h#L79) I'm not sure that's the case?

>  If sender is closed then app.publish will have the same behavior (send to all but sender is the same if sender is closed).

So you suggest something like:

```js
if (sender) {
  try {
    sender.publish(subscription.id, subscription.message)
  } catch (err) {
    if (err.code == WHAT_CODE_???) {
      app.publish(subscription.id, subscription.message)
    } else {
       throw err
    }
  }
} else {
  app.publish(subscription.id, subscription.message)
}
```

**Comment by alexhultman-2fa** [comment]
https://github.com/uNetworking/uWebSockets.js/blob/master/src/WebSocketWrapper.h#L29

No I would prefer keeping track of when sender is closed, but otherwise, yes.

**Comment by ronag** [comment]
Thanks!
