### ISSUE TITLE
socket.unsubscribe is very slow

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets.js#527]
After moving over to subscribe/unsubscribe/publish API we've noticed some heavy performance regressions.

Seems like `unsubscribe` is extremely slow.

![image (2)](https://user-images.githubusercontent.com/3065230/118794200-a0126800-b899-11eb-8571-09ae14181375.png)

"github:uNetworking/uWebSockets.js#v19.2.0",

**Comment by ronag** [comment]
We're reverting back to a for socket of sockets do socket.write loop for now.

**Comment by ronag** [comment]
Since I know all the sockets it want to publish to it would be nice to have something like:

```js
endpoint.publish(socketArr, message)
```

and bypass the topic tree entirely.

**Comment by alexhultman** [comment]
Both unsubscribe and subscribe can be very slow in certain uses. By default they force a flush to ensure strict ordering of publish/subscribe/unsubscribe.

There is a second argument called bool nonStrict you can set to true in both subscribe and unsubscribe. This can in certain cases yield a lot better perf.

But it depends on what you're doing.

**Comment by ronag** [comment]
> strict ordering of publish/subscribe/unsubscribe.

Can you elaborate a little about this?

**Comment by ronag** [comment]
I think I'm abusing this as publish to list of sockets. Should probably just stick with the normal for loop.

**Comment by alexhultman** [comment]
Well the whole point of the pub sub support is to handle those cases much faster than a simple loop.

Unsubscribing is log(n) overall topics, but linear in number of subscriptions per socket. So you can have many topics overall but one individual socket should have less than 50.

With nonStrict, unsubscribe should definitely not be slow for these use cases

**Comment by ronag** [comment]
I'll try non strict. Thanks.

**Comment by alexhultman-2fa** [comment]
Problem solved? 66% CPU-time in unsubscribe is not okay

**Comment by ronag** [comment]
@alexhultman The profile is from a production system which I can't try on at the moment. I'll do some testing next week. We went back to an explicit for loop for now.

**Comment by ronag** [comment]
We're down to 23%. Better but still high.

**Comment by ronag** [comment]
@alexhultman-2fa Do you still do consultancy? I'm located in Helsingborg and might be interested to hire you to help sort out some of our performance issues. What's the best way to contact you?

**Comment by alexhultman-2fa** [comment]
It's impossible to say without any info on how it is used. What is this benchmark doing? Subscribing / unsubscribing is supposed to be "fast" but if your benchmark is constantly subscribing/unsubscribing to deep topics you can of course trigger slowdowns. 24% does not have to automatically mean "slow", but it is weird.

I do consulting but I have no time in the immediate future.

**Comment by ronag** [comment]
It’s from a profile of a system in production. Not benchmark.

We are getting better performance at e moment with a js for loop writing to sockets. I guess this API is not suitable for us due to high frequency or sub and unsub.

What we want is a an API where we can send a list of sockets and a message we want to send to all of them. That way we can skip the whole overhead of book keeping and matching topics.

Let me know if/when you get any time.

**Comment by alexhultman** [comment]
> What we want is a an API where we can send a list of sockets and a message we want to send to all of them. That way we can skip the whole overhead of book keeping and matching topics.

This literally is pub/sub.

You haven't provided any usable information to try and pinpoint what is going wrong - how many sockets, how many topics per socket, how long do a socket stay subscribed, how long messages are sent, how often are messages sent, what is your overall CPU-time (not just profiling relative numbers - 21% of nothing is still nothing), how many topics overall, how deep are topics (number of slashes), are you using wildcards, etc etc etc

**Comment by ronag** [comment]
> > What we want is a an API where we can send a list of sockets and a message we want to send to all of them. That way we can skip the whole overhead of book keeping and matching topics.
> 
> This literally is pub/sub.

Maybe. But I don't need the overhead of the bookeeping in uws. The whole topic tree is unnecessary for our use case.

> 
> You haven't provided any usable information to try and pinpoint what is going wrong -

> how many sockets, 

~200

> how many topics per socket, 

Several thousand

> how long do a socket stay subscribed, 

Minimum 1 second, no max. Most sockets stay subscribed to a topic for less than a minute.

> how long messages are sent, 

Usually ~1kb

> how often are messages sent,

Don't have any useful metric. All the time...?

> what is your overall CPU-time (not just profiling relative numbers - 21% of nothing is still nothing),

100% of a core

> how many topics overall, 

several thousand

> how deep are topics (number of slashes), are you using wildcards, etc etc etc

As I wrote before, topics are just a `(counter++).toString(16)` identifier for a group of sockets.

**Comment by hst-m** [comment]
> What we want is a an API where we can send a list of sockets and a message we want to send to all of them

thousands of topics per socket changing all the time so this seems pretty simple just use the for loop
```javascript
sendTo=(set,arrayBuffer)=>{for(const ws of set)ws.send(arrayBuffer,true)}
```

**Comment by ronag** [comment]
> > What we want is a an API where we can send a list of sockets and a message we want to send to all of them
> 
> thousands of topics per socket changing all the time so this seems pretty simple just use the for loop
> 
> ```js
> sendTo=(set,arrayBuffer)=>{for(const ws of set)ws.send(arrayBuffer,true)}
> ```

That's what we are doing. However, it would be faster to have a `app.send(set, messageString)`

**Comment by hst-m** [comment]
whats the difference between `app.send(set, messageString)` and `sendTo(set,arrayBuffer)`? Also if you are sending strings you want to convert to buffer first so you don't have to convert the string to buffer per each send call, do it before the for loop

**Comment by ronag** [comment]
> whats the difference between app.send(set, messageString) and sendTo(set,arrayBuffer)?

Fewer js->cpp calls. Also don't know what uws can do under the hood to send a buffer to multiple sockets at the same time.

>  Also if you are sending strings you want to convert to buffer first so you don't have to convert the string to buffer per each send call, do it before the for loop

**Comment by alexhultman-2fa** [comment]
Well there you have it. Like I said unsubscribe is log(n) in overall topic but linear in per-socket topic so the ideal number of per-socket topics is less than a handful.

You have "several thousands" topics per socket and you join/leave possibly every second meaning you have 200 * several thousands unsubscriptions per second. Let's assume you have 2 million unsubscriptions per second.

While only having 200 sockets, a for loop is obviously ideal since a linear loop over 200 is practically nothing. Any optimization you'd get from packing 200 sockets in an array you'll surely lose in terms of extra garbage collection and.... added complexity for a special case.

I would just use a for loop; most customers use pub/sub for ten of thousands of sockets, but only a handful of topics (100 or less). This is where pub/sub excels.

**Comment by ronag** [comment]
Sounds reasonable. Thank you.

**Comment by hst-m** [comment]
@ronag I tested doing `Buffer.from(string)` before ws.send but it was the same speed as doing `ws.send(string)` so no need to do that, the biggest effect on performance is just the length of the message sent, so you want to reduce that as much as possible, are you sending Json strings with number data?
