### ISSUE TITLE
faster way to convert to string?

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets.js#528]
Converting the `ArrayBuffer` which uws provides into a string is rather slow. Is there a faster way?

```js
      message: (ws, msg) => {
        try {
          const socket = ws._socket
          if (socket) {
            socket.onMessage(Buffer.from(msg).toString())
          }
        } catch (err) {
          this._logger.error({ err }, 'uws.message')
        }
      },
```

**Comment by alexhultman** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder might do better. Otherwise.. sucks to be you :P

**Comment by ronag** [comment]
TextDecore is a lot slower. So this is the best we can do.

**Comment by hst-m** [comment]
`Buffer.from(arrayBuffer).toString()` is 5x faster than `textDecoder.decode(arrayBuffer)` from my test, but if you want the fastest speed you should not be sending strings, what are you sending in there bunch of JSON?

**Comment by alexhultman** [comment]
Sounds like unrealistic expectations from a scripting language then

**Comment by SecretsNetwork** [comment]
```
function ArrayBuffer2String(buffer) {
  return String.fromCharCode.apply(null, new Uint8Array(buffer));
}
```
