### ISSUE TITLE
Lifetime of ArrayBuffer from message callback?

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets.js#535]
It seems that the `ArrayBuffer` from the `message` callback gets detached if just wrapped into a `Buffer.from`call. Is there a way to maintain the buffer without making a copy of it?

At the moment I eventually get:

```js
"Cannot perform Construct on a detached ArrayBuffer".
```

**Comment by alexhultman** [comment]
Read docs https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#message

**Comment by Shonke** [comment]
> Read docs https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#message

This page, it 404

**Comment by e3dio** [comment]
@Shonke https://unetworking.github.io/uWebSockets.js/generated/interfaces/WebSocketBehavior.html#message
