### ISSUE TITLE
Compressing a string before sending to multiple clients

### ISSUE THREAD

**Issue by michaeltheory** [uNetworking/uWebSockets.js#538]
Hello,

I hope it's not inappropriate to ask questions here. My use case is that I am using compression, but I am sending a rather large message to hundreds of clients at the same time. Currently, I assume it compresses the message each time it gets sent. Is it possible to compress it once and then send that resulting data to the clients?

Thanks!

**Comment by alexhultman-2fa** [comment]
If you use SHARED_COMPRESSOR and pub/sub then it compresses the message once and sends to many.

**Comment by michaeltheory** [comment]
This worked, thank you! For anyone who happens to find this thread, [this medium article](https://alexhultman.medium.com/how-%C2%B5websockets-achieves-efficient-pub-sub-18ceda373997) and [this example](https://github.com/uNetworking/uWebSockets.js/blob/master/examples/PubSub.js) are very helpful. One gotchya I noticed was the topic must have a slash in it. So even if I wanted to publish to a topic with just a single room ID, I had to add `/main` to it -- so `xyz/main`
