### ISSUE TITLE
Add TypeScript declarations and generate docs

### ISSUE THREAD

**Issue by AlexTolmachev** [uNetworking/uWebSockets.js#54]
Because of native nature of your library it's impossible for IDEs to list methods of req and res objects. Also it's impossible to get methods and properties of this objects via Object.enties or Object.keys.

So the question is where to find an uWS's HTTP API reference?

**Comment by xxzefgh** [comment]
If you understand a little bit of C++, you can explore wrapper headers. From a quick look, I can tell that HttpRequest has following methods:
```
getHeader
getParameter
getUrl
getMethod
getQuery
```
and HttpResponse:
```
writeStatus
end
tryEnd
write
writeHeader
close
getWriteOffset
onWritable
onAborted
onData
```

**Comment by alexhultman** [comment]
What happens if you print res.prototype? Or res.prototype.entries etc?

**Comment by AlexTolmachev** [comment]
My bad, forgot to take a look at the res's prototype 🧐

![image](https://user-images.githubusercontent.com/33148533/52538564-4307dd80-2d85-11e9-8cbb-315ed84e1ba8.png)

Anyway, I already used method described by @xxzefgh.

But I think, that for some js-developers it can be hard to even look at c++ source code :) So docs would be great addition to such a cool library 🤓

Thank you, guys!

**Comment by alexhultman** [comment]
Printing res should print also the __proto__? Or? It would be nice.

**Comment by alexhultman** [comment]
Adding typescript declarations would probably help a lot both documenting (TypeDoc) and for IDEs. How do I add that? I don't want third parties involved who cannot keep up

**Comment by alexhultman** [comment]
I'm talking about definitelytyped - they don't care about quality just quantity

**Comment by alexhultman** [comment]
Where do I put my d.ts file for best effect? Can I just ship it in the NPM package and be done?

**Comment by alexhultman** [comment]
Oh I just create uws.d.ts and put types field in package.json and boom! Now the project is TypeScript wow.

A smart IDE will pick up that declaration file and apply to JavaScript as well yes?

**Comment by xxzefgh** [comment]
@alexhultman yes, either [filename].d.ts or index.d.ts will work.

**Comment by xxzefgh** [comment]
if you provide `types` or `typings` field in package.json, than anything will work I think

**Comment by alexhultman** [comment]
Oh wow it works. Visual Studio Code did pick up on the index.d.ts in node_modules right away and shows exactly what is what. I love solutions like these, one file, compatible with JS, adds documentation too. 👍

**Comment by alexhultman** [comment]
interface TemplatedApp {
    z: number;
}

export function App(): TemplatedApp;

I want TemplateApp to have functions how do I achieve such a dream

**Comment by alexhultman** [comment]
interface TemplatedApp {
    listen(host: string, port: number): TemplatedApp;
}

export function App(): TemplatedApp;

There's no integer type?

**Comment by alexhultman** [comment]
There are now documentation generated from decl file: https://github.com/uNetworking/uWebSockets.js/blob/master/docs/index.d.ts

WIP, but looks very beautiful!

**Comment by alexhultman** [comment]
Documentation is pretty much done now, just need to have a release include that index.d.ts.

**Comment by olivier65** [comment]
Please do consider uploading this stub to the DefinitelyTyped repository as well: https://github.com/DefinitelyTyped/DefinitelyTyped. That is where, e.g., the JetBrains IDEs look for them.

**Comment by alexhultman-2fa** [comment]
You don't need to upload them to third party, definitions are shipped with the module. Visual studio code pick up on them

**Comment by olivier65** [comment]
If you prefer to include the definitions with the module then you should include a `"types": "./index.d.ts"` entry in your package.json to tell tools where to look for it. These are the only two standard ways to publish your definitions: see [here](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

It's possible VS Code goes beyond the call of duty and additionally looks for index.d.ts under the root but you can't expect every IDE to emulate VS Code.

**Comment by mikeandtherest** [comment]
Hi Alex.

I'm on VS Code using node 12+ with TS, but for some reason the IDE does not see the type definitions. I tried to manually reference them via `/// <reference path="../node_modules/uWebSockets.js/index.d.ts" />`, to no avail.

So I can confirm the need of what olivier65 and xxzefgh suggested, i.e. add the `"types": "./index.d.ts"`  entry to the package.json file of the lib. I'm sure a lot of use would appreciate that. Thanks!

**Comment by alexhultman** [comment]
If that helps can you PR it I forgot this issue

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets.js/blob/a1d30bbc84927a55dd1ae7af3572caa86c51e39b/package.json#L5

I added that line if it helps

**Comment by alexhultman** [comment]
Is ./index.d.ts really Windows-compatible?

**Comment by alexhultman** [comment]
I tested an older release on Windows / Visual Studio Code and it picked up on the type docs perfectly. According to the docs for package.json it should default to index.d.ts anyways.
