### ISSUE TITLE
[Request] Make the invalid access of closed uWS.Websocket show the stack

### ISSUE THREAD

**Issue by xrnss** [uNetworking/uWebSockets.js#540]
Specifically the line. This is annoying

**Comment by alexhultman** [comment]
It already does. All exceptions do.

**Comment by xrnss** [comment]
```js
process.on('uncaughtException', function (err) {
    console.log(err.stack);
    console.log(err);
    process.exit(1);
});
```

From the above code, err.stack is undefined and err only shows the line mentioned in the title.

**Comment by xrnss** [comment]
excuse me um hi i gave you code answer pleaze

**Comment by hst-m** [comment]
If you catch it like that it will not show line number if you let it throw without catch it shows number, also worker thread does not show line number

**Comment by xrnss** [comment]
Thank you for the help

**Comment by hst-m** [comment]
I played around with this and looks like this can be fixed to include stack with error, I tested this and added PR https://github.com/uNetworking/uWebSockets.js/pull/541

**Comment by hst-m** [comment]
This fixes worker thread not showing error location as discussed in other issue https://github.com/uNetworking/uWebSockets.js/issues/465, and adds stack for @xrnss issue
