### ISSUE TITLE
Support for 32bit ARM os

### ISSUE THREAD

**Issue by CatalinMustata** [uNetworking/uWebSockets.js#546]
I've tried using the latest version (19.2.0) on a RPi running RaspberryOS (which is 32bit) and obviously it didn't work. Looked around and only found 64bit binaries (namely uws_linux_arm64_83.node).

Reading through other issues I take it this was initially for 32bit, but then it was migrated to 64bit (without retaining support for 32bit?).

In any case, can you recommend a version that still has 32bit support? Or some instructions to build manually?

Much appreciated!

**Comment by alexhultman-2fa** [comment]
It never had 32-bit binaries, only 64-bit. You can definitely compile it for 32-bit ARM.

**Comment by CatalinMustata** [comment]
Ah, I must have assumed wrongly.

Anyways, can you help me with some pointers as to how I can build locally? I've build many things, but native node modules is not among them and I've looked around the repo but I couldn't find anything to help.

**Comment by adonespitogo** [comment]
I'm unable to build using raspberry pi 3B due to the following error:

```
In file included from /home/pi/Projects/uWebSockets.js/uWebSockets/uSockets/boringssl/crypto/fipsmodule/bcm.c:31:                                                         
In function ‘OPENSSL_memset’,                                                                                                                                             
    inlined from ‘bn_big_endian_to_words.constprop’ at /home/pi/Projects/uWebSockets.js/uWebSockets/uSockets/boringssl/crypto/fipsmodule/bn/bytes.c:76:7,                 
    inlined from ‘BN_bin2bn.constprop’ at /home/pi/Projects/uWebSockets.js/uWebSockets/uSockets/boringssl/crypto/fipsmodule/bn/bytes.c:115:3:                             
/home/pi/Projects/uWebSockets.js/uWebSockets/uSockets/boringssl/crypto/fipsmodule/../internal.h:857:10: error: ‘memset’ specified size 4294967292 exceeds maximum object s
ize 2147483647 [-Werror=stringop-overflow=]                                                                                                                               
   return memset(dst, c, n); 
```

**Comment by adonespitogo** [comment]
(Solved) It was due to outdated system libraries. I was using an older version of raspbian OS. I was able to successfully build using the latest raspbian OS. 

I made a PR this: https://github.com/uNetworking/uWebSockets.js/pull/822
