### ISSUE TITLE
Missing types: addServerName, removeServerName, missingServerName

### ISSUE THREAD

**Issue by joshxyzhimself** [uNetworking/uWebSockets.js#548]
Not really a bug, just some missing types (we're using `// @ts-check` on our files, noticed it).

- `TemplatedApp.addServerName`
- `TemplatedApp.removeServerName`
- `TemplatedApp.missingServerName`

```ts
export interface TemplatedApp {
    /** DESCRIPTION */
    addServerName(hostname: string, options: AppOptions): TemplatedApp;
    /** DESCRIPTION */
    removeServerName(hostname: string): TemplatedApp;
    /** DESCRIPTION */
    missingServerName(cb: (hostname: string) => void): TemplatedApp;
}

// i could be wrong lol
```

References

- https://github.com/uNetworking/uWebSockets.js/blob/master/src/AppWrapper.h#L448 (addServerName)
- https://github.com/uNetworking/uWebSockets.js/blob/master/src/AppWrapper.h#L472 (removeServerName)
- https://github.com/uNetworking/uWebSockets.js/blob/master/src/AppWrapper.h#L491 (missingServerName)
- https://github.com/uNetworking/uWebSockets.js/blob/master/examples/ServerName.js (usage example)

**Comment by alexhultman** [comment]
Go ahead and make a PR please
