### ISSUE TITLE
segmentation fault when passing host parameter

### ISSUE THREAD

**Issue by xxzefgh** [uNetworking/uWebSockets.js#56]
I see [here](https://github.com/uNetworking/uWebSockets.js/blob/master/src/AppWrapper.h#L193) that `listen` function takes `host` parameter too, but I get segmentation fault. Is it not supported yet?
```js
const uWS = require('uWebSockets.js')
const port = 3000

uWS
  .App()
  .get('/*', (res, req) => {
    res.writeHeader('content-type', 'application/json; charset= utf-8')
    res.end(JSON.stringify({ hello: 'world' }))
  })
  .listen('127.0.0.1', port, token => {
    if (token) {
      console.log('Listening to port ' + port)
    } else {
      console.log('Failed to listen to port ' + port)
    }
  })

```

**Comment by alexhultman** [comment]
What version did you install?

**Comment by xxzefgh** [comment]
Oh I looked at commits now and support was added after 15.1.0, my mistake

**Comment by mrlika** [comment]
Still, segmentation fault when `host` parameter is specified. Version 15.4.0

**Comment by alexhultman** [comment]
It still does...

**Comment by alexhultman** [comment]
fixed
