### ISSUE TITLE
Freebsd uWebSockets.js module not available

### ISSUE THREAD

**Issue by eswdevplus** [uNetworking/uWebSockets.js#567]
Dear Sir, 
I kindly would like your assistance to build the module for FreeBSD; as I understood that there is no support for uwebsockets.js for FreeBSD.
I have found the library in the BSD ports tree but it is used for c++...
kindly note my error
`Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_freebsd_x64_88.node'`

I appreciate your fast response.
Rebards

**Comment by alexhultman-2fa** [comment]
Supreme Lord,

I don't know, because I do not support or have FreeBSD available. It should be possible to figure out, it does compile on FreeBSD so installing the requirements and hitting make should do it. Or not, I do not know.
