### ISSUE TITLE
ws.end() not sending a close message

### ISSUE THREAD

**Issue by gmencz** [uNetworking/uWebSockets.js#568]
I want to send a message with some data before closing the connection, I thought this is what `ws.end()` is for but I'm not seeing a message on the client, the connection is closed properly but the message never gets to the client. This is how I'm currently trying to do this:
```js
ws.end(undefined, JSON.stringify({ some: "data" }))
```
And as you can see there are no messages, the code above is indeed running because I made sure of it.

![image](https://user-images.githubusercontent.com/43379549/124195840-7caf1f80-dacb-11eb-8b0d-342d284de8af.png)

**Comment by alexhultman** [comment]
https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocket.html#end

Undefined is not a valid close code.

**Comment by gmencz** [comment]
I've just tried sending a code and it didn't work either, I tried most codes documented here: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

**Comment by gmencz** [comment]
As a workaround I'm calling ws.send() and then ws.end() which is doing what I want in case this is helpful for anyone else:
```js
ws.send(JSON.stringify({ the: "error" }))
ws.end()
```

**Comment by e3dio** [comment]
@gmencz you are not checking the reason correctly, its not a standard message its part of the close event, like this:
```javascript
ws.onclose=e=>console.log(e.code, e.reason)
```
