### ISSUE TITLE
Can you please provide some example on how to scale this ?

### ISSUE THREAD

**Issue by anuragvohraec** [uNetworking/uWebSockets.js#579]
Hi team,

Can you please explain how to scale uWebSockets.js onto kubernetes. There seems no doc on how to scale this, which is must for selecting any software in today's world.
It will be nice if you can document or provide me a link to simlar document.

**Comment by e3dio** [comment]
How is this different than any other server? You create instances and connect them to the internet. If you need help with "Kubernetes" you should google "How to use Kubernetes"

**Comment by anuragvohraec** [comment]
> How is this different than any other server? You create instances and connect them to the internet.

And how do you manage inter instance communication ?
A user connects to an instance and the other user to another one, now how do this solution make web socket communication between two instance?
An obvious round robin load balancer would create a very frequent situation like that.

Why as user i would not use out of the box solution like socketcluster.io or deepstream.io which provide scalable websocket solutions, where I don't have to worry about scaling?

I asked a genuine question , why would it trigger any one, when it can be simply summed as :
No scaling layer available!

**Comment by e3dio** [comment]
> how do you manage inter instance communication ?
> why would it trigger any one

No one is triggered, you handle inter instance communication yourself

**Comment by e3dio** [comment]
You can see people discussing Redis here https://github.com/uNetworking/uWebSockets.js/discussions/441 or possible built in cross-instance pub/sub here https://github.com/uNetworking/uTracker
