### ISSUE TITLE
WebSockets client ip address

### ISSUE THREAD

**Issue by anton-piliugin** [uNetworking/uWebSockets.js#58]
Hello. This is a very nice project although i have one question: how can i get a websockets client ip? Thank you.

**Comment by alexhultman** [comment]
Hello this is not possible right now, will probably lie in req.getIP() or something like that

**Comment by anton-piliugin** [comment]
Thank you for your answer. How soon do you plan to add this feature?

**Comment by alexhultman** [comment]
In what way do you need to know the IP?

**Comment by alexhultman** [comment]
Fow what purpose*

**Comment by alexhultman** [comment]
For*

**Comment by anton-piliugin** [comment]
For access control managment

**Comment by alexhultman** [comment]
So you want to filter certain IP addresses solely based on IP alone?

**Comment by anton-piliugin** [comment]
I want to control the access from ip address another usage is geo location by ip address

**Comment by DiegoRBaquero** [comment]
I use the IP to count unique users connected to server, instead of counting sockets, which could be many per IP.

**Comment by alexhultman** [comment]
Like I said this will be added

**Comment by slavaGanzin** [comment]
> I want to control the access from ip address + another usage is geo location by ip address

You'll mess up when two users come to your server through one NAT: they will have same IP. And from my experience, mobile internet providers sometimes use NAT, so even on mobile devices you can't be sure that one IP is definitely linked one user. 

My advice is to generate unique hash cookie or localstorage key and use it for combining multiple socket connections of one user.

**Comment by SupremeTechnopriest** [comment]
Hey @alexhultman I've been using this package for 3 years now.  Love your work in general but I really like what you have done here with the new node bindings.  This issue is a blocker for me getting off the old npm package.  I have a branch ready to go as soon as this is closed!  Thanks for your work!

**Comment by wehriam** [comment]
Great project! I would also be interested in request IP addresses. We often deploy web applications on LANs with static IPs within defined IP ranges. Knowing the IP address of a request allows us to make assumptions about where and who the client is, and we often surface the information to administrators.

**Comment by alexhultman** [comment]
console.log(Buffer.from(res.getIP()).toString('hex'));

00000000000000000000000000000001 = ipv6 localhost
00000000000000000000ffffc0a80086 = 192.168.0.134 mapped as ipv6

res.getIP() should be req.getIP so that websockets can do this while in open

**Comment by alexhultman** [comment]
This will be ws.getRemoteAddress() and res.getRemoteAddress()

**Comment by leeoniya** [comment]
not `req.getRemoteAddress()`?

**Comment by alexhultman** [comment]
Throught about it but it makes no sense. IP is a property of the socket, not any one particular http request. Both ws and res are derivatives of a socket while req is a stack allocated temporary thing only holding http-related parsed out properties.

**Comment by alexhultman** [comment]
Please try latest build,

npm install uNetworking/uWebSockets.js#binaries

**Comment by PeterHewat** [comment]
Hello,
I have tested the latest #binaries build and ws.getRemoteAddress() returns an ArrayBuffer(16). I guess you output an IPv6 address.

I have tested it with a websocket connected to my server both are on localhost and here is the output:
```
console.log('RemoteAddress: ' + new Uint16Array(ws.getRemoteAddress()));
> RemoteAddress: 0,0,0,0,0,0,0,256
```
I was expecting 127.0.0.1 in IPv6 format which is 0:0:0:0:0:ffff:7f00:1 as follows:
```
console.log('ipv6Localhost: ' + new Uint16Array([0, 0, 0, 0, 0, 0xffff, 0x7f00, 1]));
> ipv6Localhost: 0,0,0,0,0,65535,32512,1
```
Am I doing something wrong or is ws.getRemoteAddress() not implemented yet?

**Comment by ozra** [comment]
It's fairly uncommon _not_ to have a load balancer, or reverse proxy for other reasons, in between the end-user client and the services (potentially using this lib). So I think it's rather prudent to consider req  the natural go-to place for sourcing it (_refer back to #93_), since the (real) client's IP would have to be derived from a header that naturally must have precedence over the socket-IP — which very likely just might be localhost, but if there are no such headers, it might be because one has it exposed raw to the public (for instance allowing client who are _not_ blocked by internet cafe proxies where they use wifi, to connect to a non "standard" port, whilst the others have to go through the load balancer. You catch my drift. Common deployment scenarios.

**Comment by alexhultman** [comment]
You're mixing different topics. This feature is regarding getting the IP address, not whether any one header value might or might not be more relevant.

**Comment by ozra** [comment]
My bad.

**Comment by PeterHewat** [comment]
For those reading this wondering how to get the "real" IP from the headers due to uWS being behind a reverse proxy like what ozra suggests, you simply do this:
```
open: (ws, req) => {
  console.log('X-Real-IP: ' + req.getHeader('x-real-ip'));
  // or...
  console.log('X-Forwarded-For: ' + req.getHeader('x-forwarded-for'));
}
```

**Comment by alexhultman** [comment]
@PeterHewat it is working, you're messing up with the uint16array. It's easy to see with uint8array:

Uint8Array [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1 ] = 127.0.0.1
Uint8Array [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] = ::1
Uint8Array [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ]

**Comment by coder456** [comment]
For anyone else looking for how to get the IPv6 string from the res.getRemoteAddress() function, here is what you can do:

`let ip='';(new Uint8Array(res.getRemoteAddress())).forEach((a,i)=>ip+=a.toString(16)+(i%2&&i!=15?':':''))`

`ip` will come out in this format: `"00:00:00:00:00:ffff:244b:8cca"`

**Comment by alexhultman** [comment]
You can also just do buffer.toString('hex') it's really not any different from any other binary string

**Comment by richcorbs** [comment]
Is there a way to get the ipv4 address from getRemoteAddress?

**Comment by alexhultman** [comment]
getRemoteAddress returns either 4 (ipv4) or 16 (ipv6) bytes. That is the address. You may want to format it in human readable ways like mentioned above.

**Comment by edreal** [comment]
@alexhultman how would you do it? Would it be difficult to add it to the library or should people write own function for it?

**Comment by FlorentMasson** [comment]
```
 function remoteAddressToString(address) {
        if (address.byteLength == 4) {//IPv4
            return new Uint8Array(address).join('.');
        } else if (address.byteLength == 16) {//IPv6
            return Array.from(new Uint8Array(address)).map(v => v.toString(16)).join(':').replace(/((^|:)(0(:|$))+)/, '::');
        }
    }
```

with inspiration from [ipaddr.js](https://github.com/whitequark/ipaddr.js)

**Comment by pkxpp** [comment]
> ```
>  function remoteAddressToString(address) {
>         if (address.byteLength == 4) {//IPv4
>             return new Uint8Array(address).join('.');
>         } else if (address.byteLength == 16) {//IPv6
>             return Array.from(new Uint16Array(address)).map(v => v.toString(16)).join(':').replace(/((^|:)(0(:|$))+)/, '::');
>         }
>     }
> ```
> 
> with inspiration from [ipaddr.js](https://github.com/whitequark/ipaddr.js)
> 
> If you need to convert IPv4 addresses mapped to IPv6...
> (I'm not sure whether this is my computer, but although netstat shows IPv4 connections, I get a mapped IPv6 address with getRemoteAddress())
> 
> ```
> function remoteAddressToString(address) {
>         if (address.byteLength == 4) {//IPv4
>             return new Uint8Array(address).join('.');
>         } else if (address.byteLength == 16) {//IPv6
>             let arr = Array.from(new Uint16Array(address));
>             if (arr[0] == 0 && arr[1] == 0 && arr[2] == 0 && arr[3] == 0 && arr[4] == 0 && arr[5] == 0xffff)  //IPv4 mapped to IPv6
>                 return new Uint8Array(address.slice(12)).join('.');
>             else
>                 return Array.from(new Uint16Array(address)).map(v => v.toString(16)).join(':').replace(/((^|:)(0(:|$))+)/, '::');
>         }
>     }
> ```

It's helpful for me.

**Comment by Joncom** [comment]
> ```
> function remoteAddressToString(address) {
>         if (address.byteLength == 4) {//IPv4
>             return new Uint8Array(address).join('.');
>         } else if (address.byteLength == 16) {//IPv6
>             let arr = Array.from(new Uint16Array(address));
>             if (arr[0] == 0 && arr[1] == 0 && arr[2] == 0 && arr[3] == 0 && arr[4] == 0 && arr[5] == 0xffff)  //IPv4 mapped to IPv6
>                 return new Uint8Array(address.slice(12)).join('.');
>             else
>                 return Array.from(new Uint16Array(address)).map(v => v.toString(16)).join(':').replace(/((^|:)(0(:|$))+)/, '::');
>         }
>     }
> ```

Even though I was connecting to my server with IPv4, `ws.getRemoteAddress()` was returning 16 bytes instead of 4. This function converts it nicely, thanks.

**Comment by alexhultman-2fa** [comment]
In 18.1 you'll have getProxiedRemoteAddressAsText() and getRemoteAddressAsText().

Proxied follows the proxy protocol v2

**Comment by FlorentMasson** [comment]
@alexhultman-2fa How can we get the proxied IP in open handler with 18.4?
getProxiedRemoteAddressAsText() is not available on Websocket, and request/response objects are not available either
