### ISSUE TITLE
"WebSocket timed out from inactivity" for user that sends ping messages every 8 seconds (idleTimeout set to 60 seconds)

### ISSUE THREAD

**Issue by mauriciogior** [uNetworking/uWebSockets.js#587]
One of our developer's computer disconnects every 120 seconds with "1006: WebSocket timed out from inactivity" error even though the `idleTimeout` is set to 60 seconds and his tab is sending `ping` messages every 8 seconds (and he's also active, sending all kind of messages).

This is my setup:

```javascript
const app = uWS.App().ws('/*', {
	idleTimeout: 60,

	open: (ws) => {
		log('open');
	},
	close: async (ws, code, message) => {
		try {
			log('person disconnected', ws.id, code + ": " + Buffer.from(message).toString());
			if (!ws.personAdded) {
				try {
					await Person.remove(ws.eventID, ws.personID + "_nj");
				} catch (error) {
					log(error);
				}
			}
			logout(app, ws);
		} catch (e) {
			log('close error', e);
		}

	},
	drain: (ws) => {
		log('drain', ws.id);
	},
	message: (ws, message, isBinary) => {
		try {
			if (!ws.personAdded) {
				if (ws._nj) {
					Person.keepAlive(ws.eventID, ws.personID + "_nj");
				}
			} else {
				Person.keepAlive(ws.eventID, ws.personID);
			}
		} catch (ignore) { }

		if (!message.byteLength || message == "1") {
			ws.ping();
			return;
		}

		message = jsonDecoder(message);
		if (!message) return;

		if (routes[message.R]) {
			if (config.DEBUG) {
				console.log(new Date().toISOString(), '\033[1m\x1b[32m', 'IN ', '\x1b[0m', '[' + message.R + ']', JSON.stringify(message));
			}
			routes[message.R](app, ws, message);
		} else if (message == 1) {
			ws.ping();
		} else {
			log('route not found', ws, message);
		}
	},
})
```

**Comment by alexhultman-2fa** [comment]
https://github.com/uNetworking/uWebSockets/blob/d94bf2cd43bed5e0de396a8412f156e15c141e98/src/WebSocketProtocol.h#L30

If you get this close reason in the server then it timed out. Check if you really do receive those pings by adding a ping handler, log when it is called.

**Comment by mauriciogior** [comment]
I don't get any log messages on `ping` and `pong` when my client sends an empty message (using `socket.send("");`), but my user remains connected correctly over the `idleTimeout`. The only time I get any logs is from the `pong` handle after I send a `ws.ping()` directly from the server.

**Comment by alexhultman-2fa** [comment]
You have to be specific - give me a minimal snippet that fails and I can check it.

**Comment by e3dio** [comment]
> Check if you really do receive those pings by adding a ping handler, log when it is called

> I don't get any log messages on ping and pong when my client sends an empty message

@mauriciogior he asked about the client that was causing the issue, you answered with your own user that did not have issue. Also an empty message is not a "ping" and will not trigger the ping handler, you should not refer to them as pings. Did you confirm the user with issue was connected to your server and sending messages by checking server console.logs? v19 automatically sends pings to client to keep connection open so there is no need to send messages

**Comment by mauriciogior** [comment]
Hi @e3dio, thanks for the info, I'm using 18.14.0, but will upgrade it to v19. The current setup is running inside a Kubernetes with a `proxy_pass` on `nginx`, and I just created a standalone instance with just uwebsockets exposed to the internet without any proxies to see if it fixes the issue. I should have updated results next Tuesday - we will have a session with over 100 people connected.

**Comment by e3dio** [comment]
I don't remember exactly but I think v18 only resets idleTimeout when server successfully sends message to client, was assuming you were using v19, I would switch to 19

**Comment by mauriciogior** [comment]
@e3dio If that's the case, then it totally makes sense and v19 will indeed fix the issue.

**Comment by e3dio** [comment]
Ya I think that is it, see https://github.com/uNetworking/uWebSockets/issues/1136#issue-754960069

**Comment by alexhultman** [comment]
See point 4 in https://github.com/uNetworking/uWebSockets/releases/tag/v19.0.0
