### ISSUE TITLE
about AppOptions

### ISSUE THREAD

**Issue by sharper** [uNetworking/uWebSockets.js#589]
current:
export interface AppOptions {
    key_file_name?: RecognizedString;
    cert_file_name?: RecognizedString;
    passphrase?: RecognizedString;
    dh_params_file_name?: RecognizedString;
    /** This translates to SSL_MODE_RELEASE_BUFFERS */
    ssl_prefer_low_memory_usage?: boolean;
}

node:
https.createServer({
      requestCert: true,
      rejectUnauthorized: true,
      ca:..., key:..., cert:...
});

HTTPS server to request a client certificate, use requestCert  = true

how to add requestCert  and verify client cert valid in uWebSockets.js ?

**Comment by alexhultman-2fa** [comment]
https://blog.cloudflare.com/introducing-tls-client-auth/

Server authenticating the client is not the most common thing, so is not currently supported. What I am working on right now is QUIC support which might affect what TLS options and features the app will support.

**Comment by sharper** [comment]
> https://blog.cloudflare.com/introducing-tls-client-auth/
> 
> Server authenticating the client is not the most common thing, so is not currently supported. What I am working on right now is QUIC support which might affect what TLS options and features the app will support.
