### ISSUE TITLE
How to make cluster mode work (MacOS)

### ISSUE THREAD

**Issue by mauriciogior** [uNetworking/uWebSockets.js#593]
I'm trying to run this example: https://github.com/uNetworking/uWebSockets.js/blob/master/examples/WorkerThreads.js but it always fails. Basically one thread manages to start correctly and the other one fails to listen to that port.

I did an exact copy & paste, just changed the `SSLApp` to `App`. I'm running it on MacOS. When I try this on my Ubuntu machine it works.

<img width="338" alt="Screen Shot 2021-08-04 at 6 13 23 PM" src="https://user-images.githubusercontent.com/2918286/128262315-5fe9e3f6-e988-485d-b21c-0d8d126cc701.png">

**Comment by mattiasewers** [comment]
It only works on Linux

**Comment by mauriciogior** [comment]
> It only works on Linux

Why though? Is it a MacOS limitation? If it is, which one?

**Comment by e3dio** [comment]
See https://github.com/uNetworking/uWebSockets/issues/1194

**Comment by mauriciogior** [comment]
Thanks!

**Comment by mauriciogior** [comment]
Actually, `v19.3.0` works on `MacOS`! I was using 18.14.0.
