### ISSUE TITLE
Parallization mechanism \ oppurtunity

### ISSUE THREAD

**Issue by zouhir** [uNetworking/uWebSockets.js#6]
I have noticed in the benchmarks in readme that the test ran on single thread.

Rust's actix, Go's fast http and C++ can do multi-thread. Would this implementation for Node allow clustering? or is it something on the roadmap?

Thank you!

**Comment by lukeed** [comment]
Are you planning to expose it thru native `cluster` module? Typical `http` clustering setup is here: https://nodejs.org/api/cluster.html#cluster_cluster

**Comment by alexhultman** [comment]
Nope. Nothing Node.js-specific is going in here, this is its own server which just happens to work in Node.js. Probably it will work just fine though, there will definitely be support to move sockets over threads.

**Comment by alexhultman** [comment]
I will keep that in mind anyways, there needs to be an example using the cluster feature.

**Comment by lukeed** [comment]
Sounds good. It doesn't work as of now, but you're probably aware already 😀

Looking forward to this!

**Comment by alexhultman** [comment]
This looks like a problem - I guess cluster worked before because before uws was using the Node.js Http server which obviously works with the cluster module. You're just trading one hacky solution for another one really. Before it was very hacky to work with Node.js Http server and now it's hacky to work with cluster module.

Best would probably be to have a complete replacement or just skip this for Node.js

**Comment by alexhultman** [comment]
One possible solution is to use net.Server to listen and accept, and then import the FD to the uWS.App and have it do everything else.

That's kind of the same as old uws, but instead of using the HTTP server of Node.js it only makes use of the very minimal net.Server thing.

It will make it slower though, at least for short lived connections

**Comment by alexhultman** [comment]
Nope, not going to work

**Comment by alexhultman** [comment]
Technically, all you need to do really is to call Unix fork syscall in the listen callback. That would enable some kind of clustering. More work can be done to even the distribution and balan e connections but this fork call should be enough to have basic clustering. What Node.js does is some kind of non-Unix-Windows-compatible black magic hack that I simply cannot support. Standard Unix fork should do it (along with similar Unix features). Windows is what it is..

**Comment by alexhultman** [comment]
I'm pretty much sure V8 is properly compatible with Unix fork but Node.js itself might very well break I don't know

**Comment by alexhultman** [comment]
Well quick tests show that it is at least possible to have SOME kind of clustering with Node.js, all you need is SO_RESUSEPORT and it works decently actually. 120k up to 380k. It doesn't seem to be very round-robin ish though, but all instances gets loaded fully at least for this load test

**Comment by zorro-fr24** [comment]
>  It doesn't seem to be very round-robin ish though, but all instances gets loaded fully at least for this load test
If you are still using Cluster in any capacity to achieve this, then by default node lets the OS decide how to route connections - you can change the behaviour with:

`Cluster.schedulingPolicy = Cluster.SCHED_RR; `

before forking.

**Comment by alexhultman** [comment]
https://nodejs.org/api/cluster.html#cluster_cluster_schedulingpolicy

Interesting. Round robin is possible to achieve with SO_REUSEPORT with just a few changes - currently it is undefined behavior. Very promising, then clustering will work at least on Linux which is the main platform anyways

**Comment by alexhultman** [comment]
I'm closing this, will be up to uSockets to solve. Will work nicely on Linux, other platforms might be supported at some point.

**Comment by dalisoft** [comment]
@alexhultman any news? i can't make it work, on linux too. on osx/macos too.
any example and/or guide here available?
