### ISSUE TITLE
onData is not firing when coming back from an async "middleware" function

### ISSUE THREAD

**Issue by animaonline** [uNetworking/uWebSockets.js#602]
```
Version 19.3.0
OS: macOS 11.4
Node: v16.6.1
```

Consider the following example:

My code is executing a "middleware" function that performs a db check to verify that the user is authenticated, the calls to the db are async (I'm awaiting the result), for the sake of simplicity I'm using a "sleep" promise to illustrate this.

`onData` is not firing because I'm awaiting `this.sleep(100)`, if I skip that line and execute `next(res, req)` directly, it works as expected.

Question: How can I circumvent this? 
I would rather wrap my routes in a middleware function instead of performing auth checks in each api route.

```
private sleep = (ms: number): Promise<void> => {
    return new Promise<void>((resolve, reject) => {
        setTimeout(() => {
            resolve();
        }, ms);
    });
}
```

```
private middleware = (next: any) => async (res: HttpResponse, req: HttpRequest) => {
    let isAborted = false;

    res.onAborted(() => {
        isAborted = true;
    });

    await this.sleep(100);

    next(res, req);
}
```

```
app.post("/test", this.middleware((res: HttpResponse, req: HttpRequest) => {
    res.onData((chunk, isLast) => {
        console.log("got data");
        res.writeStatus("404").end();
    });
}))
```

**Comment by joshxyzhimself** [comment]
hi, iirc you gotta set the onData callback before  calling any `await`

```js
res.onData((chunk_arraybuffer, is_last) => {
  const chunk_buffer = Buffer.from(chunk_arraybuffer.slice(0));
  buffer = Buffer.concat([buffer, chunk_buffer]);
  if (is_last === true) {
    // buffer parsing, if its json or multipart or what not
    // ideally this is where you call your `next(res, req);` too
  }
});
res.onAborted(() => {
  // some handler too
});
```

**Comment by animaonline** [comment]
@joshxyzhimself yeah, handling onData in the middleware was the solution to this problem.

**Comment by e3dio** [comment]
Yes this is common thing so is good question, @joshxyzhimself is correct before doing Async you need to get all your Request related info and also set your res.onData callback. You don't need to wait for Body to finish just get it set and can check it after doing async. I use this getBody helper function like this, to match your example:

```javascript

app.post('/test',middleware(async res=>res.end(await res.body)))

const middleware=next=>async(res,req)=>{
   res.body=getBody(res)
   await sleep(100)
   next(res)
}

const getBody=res=>new Promise((re,rej)=>{let body;res.onData((ab,isLast)=>{const b=Buffer.from(ab);body=body?Buffer.concat([body,b]):isLast?b:Buffer.concat([b]);if(isLast)re(body.toString())})})
```

**Comment by e3dio** [comment]
> const chunk_buffer = Buffer.from(chunk_arraybuffer.slice(0));

It looks like @joshxyzhimself example is making unnecessary copy of data when the first chunk is the last chunk with `arraybuffer.slice(0)`. If it is last you can skip data copy
