### ISSUE TITLE
ReferenceError: DEDICATED_COMPRESSOR_4KB is not defined

### ISSUE THREAD

**Issue by Tuner32** [uNetworking/uWebSockets.js#607]
What is wrong with this? I use normal  code and I just changed for nothing except SSLApp to App. it wor wll if I remove compressor option It work well. I used example code

code: 
/* Non-SSL is simply App() */
require('uWebSockets.js').App().ws('/*', {

  /* There are many common helper features */
  idleTimeout: 30,
  maxBackpressure: 1024,
  maxPayloadLength: 512,
  compression: DEDICATED_COMPRESSOR_3KB,

  /* For brevity we skip the other events (upgrade, open, ping, pong, close) */
  message: (ws, message, isBinary) => {
    /* You can do app.publish('sensors/home/temperature', '22C') kind of pub/sub as well */
    
    /* Here we echo the message back, using compression if available */
    let ok = ws.send(message, isBinary, true);
  }
  
}).get('/*', (res, req) => {

  /* It does Http as well */
  res.writeStatus('200 OK').writeHeader('IsExample', 'Yes').end('Hello there!');
  
}).listen(9001, (listenSocket) => {

  if (listenSocket) {
    console.log('Listening to port 9001');
  }
  
});

I used this on node 14.17.6
and it on window 10 1803

**Comment by alexhultman** [comment]
If you want people to look into your issue you have to put more effort to it than just roll  your head randomly over the keyboard. Nobody can read this.

**Comment by alexhultman** [comment]
After your edit:

The issue is pretty much spelled out for you already, DEDICATED_COMPRESSOR_3KB is not defined. It's supposed to be uWS. DEDICATED_COMPRESSOR_3KB like the examples, importing a JS module does not change any globals, it only gives you the uWS object.
