### ISSUE TITLE
DEDICATED_DECOMPRESSOR is broken

### ISSUE THREAD

**Issue by jdelk** [uNetworking/uWebSockets.js#633]
I saw this issue posted here: https://github.com/uNetworking/uWebSockets/issues/1347

I tried using DEDICATED_DECOMPRESSOR in node like this (using uWebsockets.js 20.1.0 with Node.js 16.12.0):

```
uWS.App().ws('/*', {
    idleTimeout: 0,
    maxBackpressure: 100 * 1024 * 1024,
    maxPayloadLength: 100 * 1024 * 1024,
    compression: (uWS.DEDICATED_COMPRESSOR_3KB | uWS.DEDICATED_DECOMPRESSOR),

    upgrade: (res, req, context) => {
    res.upgrade({
        "cookie": req.getHeader("cookie"),
        "user-agent": req.getHeader("user-agent")
    },
        req.getHeader('sec-websocket-key'),
        req.getHeader('sec-websocket-protocol'),
        req.getHeader('sec-websocket-extensions'),
        context);
    },

    message: (ws, message, isBinary) => {
        ws.send(message, true, true);
    },

    close: (ws, code, message) => {
        console.log("disconnected:", code, Buffer.from(message).toString());
    }
```

After the client sends 2 messages to the server, the server disconnects the client

Here's the message when the websocket closes:

```
1006 Received too big message, or other inflation error
```

Am I just using DEDICATED_DECOMPRESSOR wrong?

Thanks

**Comment by alexhultman** [comment]
This is strange, if I send "hello" two times it is the following two chunks. After the second one it fails with Z_DATA_ERROR 

inflating totally
ca
48
cd
c9
c9
7
0
0
0
ff
ff
inflating totally
ca
0
11
0
0
0
0
ff
ff

**Comment by alexhultman** [comment]
This is a total miss in the negotiation. I must have forgot to commit that part or just missed it.

It never really creates the per-socket inflation stream even though it negotiated to do so, so it inflates assuming every chunk starts from initial state, which is entirely wrong.

Easy to fix, totally broken

**Comment by alexhultman** [comment]
Alright can you try v20.3.0. You should be able to specify what decompressor you want now

**Comment by jdelk** [comment]
Thanks for looking at this so quickly

[After retrying the same code I used above](https://github.com/uNetworking/uWebSockets.js/issues/633#issuecomment-954253396), I get the error `Segmentation fault (core dumped)` after sending a few messages (of any length).

The client also never receives any message sent from the server.

Using uWebsockets 20.3.0 on Node.js 16.12.0

I've tried with the following compression options:

`compression: uWS.DEDICATED_COMPRESSOR_3KB,`

`compression: (uWS.DEDICATED_COMPRESSOR_3KB | uWS.DEDICATED_DECOMPRESSOR),`

It seems that compression is broken completely now, if I use `uWS.DISABLED` it works fine.

**Comment by alexhultman** [comment]
Classic; fix one thing break 2. Should be fixed now 🤞 Try v20.4.0

**Comment by jdelk** [comment]
v20.4.0 works perfectly

Thanks for fixing it so quickly. 

Love all the work you're doing with uWS

**Comment by alexhultman** [comment]
Thanks for reporting. I have tested it a bit now and it looks correct in all cases.
