### ISSUE TITLE
Possible documentation bug in regard to res.write return value

### ISSUE THREAD

**Issue by snowbldr** [uNetworking/uWebSockets.js#638]
I'm super noob with c++ so forgive me if this is just all wrong.

It appears that this is the wrapper code for the response.write method:
https://github.com/uNetworking/uWebSockets.js/blob/c70d2e6d2d923183885e991c6cb4189419b521a5/src/HttpResponseWrapper.h#L259
and is attached to each response object here
https://github.com/uNetworking/uWebSockets.js/blob/c70d2e6d2d923183885e991c6cb4189419b521a5/src/HttpResponseWrapper.h#L367

This res_write method seems to be returning a boolean. 

However, this file https://github.com/uNetworking/uWebSockets.js/blob/c70d2e6d2d923183885e991c6cb4189419b521a5/docs/index.d.ts#L147 

which appears to power the generated online docs states that response.write returns an HttpResponse.

Should this type file be updated to say it returns a boolean? Or am I misreading this.

**Comment by alexhultman** [comment]
You're precisely right. It's a documentation flaw. Write does return a boolean so that streaming with backpressure is possible. The docs sound change

**Comment by snowbldr** [comment]
I can publish an update for this. I'll also review the other methods to ensure everything is in order. Thanks a bunch :)

**Comment by alexhultman** [comment]
I have updated this but if you want to review the docs that would be awesome. There are definitely things in the docs that lag behind reality.

**Comment by snowbldr** [comment]
I found a few other discrepancies. Seems to be in order now. Thanks again, and nice work on this thing. It rips.
