### ISSUE TITLE
Congrats + body parser

### ISSUE THREAD

**Issue by orefalo** [uNetworking/uWebSockets.js#64]
This library performs better than turbo-http under high load, congrats.

Now I am a little confused about the api, how would you implement a body parser?

I am trying to stitch it to an Apollo GraphQL instance

Thanks!

**Comment by alexhultman** [comment]
```

/* Simple examples of getting JSON from a POST */

const uWS = require('../dist/uws.js');
const port = 9001;

const app = uWS./*SSL*/App({
  key_file_name: 'misc/key.pem',
  cert_file_name: 'misc/cert.pem',
  passphrase: '1234'
}).post('/*', (res, req) => {

  /* Note that you cannot read from req after returning from here */
  let url = req.getUrl();

  /* Read the body until done or error */
  readJson(res, (obj) => {
    console.log('Posted to ' + url + ': ');
    console.log(obj);

    res.end('Thanks for this json!');
  }, () => {
    /* Request was prematurely aborted, stop reading */
    console.log('Ugh!');
  });

}).listen(port, (token) => {
  if (token) {
    console.log('Listening to port ' + port);
  } else {
    console.log('Failed to listen to port ' + port);
  }
});

/* Helper function for reading a posted JSON body */
function readJson(res, cb, err) {
  let buffer;
  /* Register data cb */
  res.onData((ab, isLast) => {
    let chunk = Buffer.from(ab);
    if (isLast) {
      if (buffer) {
        cb(JSON.parse(Buffer.concat([buffer, chunk])));
      } else {
        cb(JSON.parse(chunk));
      }
    } else {
      if (buffer) {
        buffer = Buffer.concat([buffer, chunk]);
      } else {
        buffer = Buffer.concat([chunk]);
      }
    }
  });

  /* Register error cb */
  res.onAborted(err);
}

```

You mean like getting json from a post or something?

**Comment by iamsimakov** [comment]
hello, thanks for project. Can anybody say how to check empty or no empty data?

**Comment by alexhultman** [comment]
I guess onData has to be called with isLast set immediately if there was no data otherwise we hang the connection forever

**Comment by iamsimakov** [comment]
@alexhultman Yes, that is why I was need to check empty data, or there is another way to check and immediately close the connection. thanks

**Comment by alexhultman** [comment]
Yeah it is a bug - onData needs to return false/true or immediately call the callback with isLast. Something like that. I guess the most automatically compatible way is to call with isLast immediately

**Comment by alexhultman** [comment]
Okay this is fixed now. You can see the JsonPost example. It tells you when there is no data and when there is

**Comment by orefalo** [comment]
Thank you!

**Comment by orefalo** [comment]
You mean like getting json from a post or something?

Yes - json body parsing.   graphql body parsing to be exact.
