### ISSUE TITLE
Passing a live socket to a child process in uWS.js

### ISSUE THREAD

**Issue by Gedo80** [uNetworking/uWebSockets.js#649]
Hi,
First of all, big thanks for the great job with uWs.

I would like to create an application that for each ws connection fork a new process and in it handles the application logic. I am wondering if it is possible to catch an upgrade to ws and pass the handler connection to a new process, similar to [https://github.com/websockets/ws/issues/154)](https://github.com/websockets/ws/issues/154) ( Passing a live socket to a child process #154) ?

I tried somthink like this, but it's throw na error
```js
upgrade: (res, req, context) => {
    const child = fork(path.join(__dirname,'client.js'), ['child'], {signal} );
    message = {
      type: "connection",
      url: req.getUrl(),
      key: req.getHeader('sec-websocket-key'),
      protocol: req.getHeader('sec-websocket-protocol'),
      extensions: req.getHeader('sec-websocket-extensions'),
    }
      child.send(message,context) <-- throw error: "Uncaught TypeError [ERR_INVALID_HANDLE_TYPE]: This handle type cannot be sent"
}
```
Next, can I call in child process matching function in uWS.js to: 
```js
wss.handleUpgrade(request, socket, undefined, (ws) => {
```

Thanks in advance for your reply.

**Comment by alexhultman** [comment]
No it sounds like shoehorning something that doesn't fit. Uws is single threaded and not suited for 1 process per connection
