### ISSUE TITLE
Replace SSL cert without having to restart server

### ISSUE THREAD

**Issue by Antriel** [uNetworking/uWebSockets.js#65]
This is especially useful with let's encrypt certificates lasting only 3 months.

**Comment by alexhultman** [comment]
This is probably a very niche thing - very low priority unless someone really needs it. You can kind of do this already, by starting a new App while draining the old one.

**Comment by Antriel** [comment]
I would assume it would be a popular feature. But assumptions aside, starting up a new App would work, as long as it won't disconnect active connections. I would appreciate an example, but hopefully I can figure it out. Thanks.

**Comment by orefalo** [comment]
last on my humble priority list: with proper balancing this becomes an operation process issue.

**Comment by alexhultman** [comment]
I also think this is kind of a pointless feature, you always can manage it by spinning up/down appropriate instances until done. Or, just deal with a second of downtime.

**Comment by alexhultman** [comment]
Not pointless* but unnecessary

**Comment by Antriel** [comment]
In the context of real-time multiplayer games, a second of downtime also means disconnecting bunch of players, unless I misunderstood.

**Comment by ohenepee** [comment]
I'm probably misunderstanding something... so does NginX with Let's Encrypt also go through this winding down thing? If so what happens to connected clients?

**Comment by slavaGanzin** [comment]
> In the context of real-time multiplayer games, a second of downtime also means disconnecting bunch of players, unless I misunderstood.

You can't change cypher keys inside connection, so you should hold your old server until last user  who connected with old certificate will disconnect. While serving new connections with new ssl certificate.  So you can do this now easily. But implementing this into uWebSockets is huge overkill.

**Comment by ohenepee** [comment]
I think its pretty much understandable, after all one is getting a "free" SSL/TLS certificate.

**Comment by arpu** [comment]
this looks like a good implementation https://github.com/nimiq/core-js/pull/514/files
