### ISSUE TITLE
How to detach ws endpoint for new connections?

### ISSUE THREAD

**Issue by NaumovEvgeniy** [uNetworking/uWebSockets.js#650]
Is it possible do this like in the following example?

```
import uWS from 'uWebSockets.js';
const port = 9001;

const app = uWS.App()

const endpoint1 =	app.ws('/endpoint/1', {
	// some actions
})
const endpoint2 =	app.ws('/endpoint/2', {
	// some actions
})

app.listen(port, (token) => {
	if (token) {
		console.log('Listening to port ' + port);
	} else {
		console.log('Failed to listen to port ' + port);
	}
});

setTimeout(() => {
	// Here I want to detach "/endpoint/1" to prevent new connections
	// Also I want to keep "/endpoint/2" to new connections
}, 1000)

```

As I know `us_listen_socket_close` close all endpoints and it can't close certain endpoints. 

Maybe your library has another method for my goal or my approach to separate endpoints is wrong.

I'm waiting your feedback, Thanks!

**Comment by e3dio** [comment]
You can't remove or change routes after adding them currently, so you need to do like `app.ws('/endpoint/:id',{upgrade:(res,req,context)=>{}})` and in your upgrade function change the behavior of the route depending on `req.getParameter(0)`

**Comment by alexhultman** [comment]
This is something that we WANT to have but in practise it will never happen because the "websocket route" holds a bunch of callbacks and settings and memory that is persistently shared with sockets that are connected to that route. Allowing the removal of WS routes ("endpoints") would be too complex, so it will never happen.

**Comment by NaumovEvgeniy** [comment]
For performance, this restrictions are nothing
