### ISSUE TITLE
Notify socket close: cannot get remote address to identify closed socket

### ISSUE THREAD

**Issue by teocns** [uNetworking/uWebSockets.js#651]
I identify sockets by their remote address (since AFAIK I'm unable to get their ID).
I want to be able to identify which socket address or ID fired the `close` event, however it seems the `WebSocket` is unaccessible on `close` as it throws the following error:
_Error: Invalid access of closed uWS.WebSocket/SSLWebSocket_

```

const connected_sockets = {}; // Addresses stored here
...
open: async (ws) => {
        
        const address = await decryptMessage(ws.getRemoteAddressAsText());
        console.log('socket connected ', address);
        connected_sockets[address] = {...};


},
close: async (ws, code, message) => {

        console.log('socket closed', code, message);

        const address = await decryptMessage(ws.getRemoteAddressAsText()); // This throws an error

        delete connected_sockets[address];
}
```

How could I be able to know which socket fired `close`? What properties are there available about the socket client both in `close` and also in `open` to make a connection between the two?

**Comment by alexhultman** [comment]
You can't call methods in close. But the Object passed in open is the same passed in close so whatever you attached to the Object before close is still valid.

**Comment by teocns** [comment]
@alexhultman fair enough, referencing.

Issue solved.
