### ISSUE TITLE
Error: WebSocket must not subscribe or unsubscribe to topics while iterating its topics!

### ISSUE THREAD

**Issue by thaaddeus** [uNetworking/uWebSockets.js#653]
Hi, with latest release I'm getting: `Error: WebSocket must not subscribe or unsubscribe to topics while iterating its topics!` which wasn't occurring with v19.x. Is that something to be expected?

**Comment by e3dio** [comment]
JS people are not supposed to get that error because internal function is wrapped to avoid it https://github.com/uNetworking/uWebSockets.js/blob/master/src/WebSocketWrapper.h#L285

But I don't get that error, can you post code to produce it?
```javascript
require('uWebSockets.js').App()
.get('/',res=>res.end(`<script>ws=new WebSocket('ws://localhost:8080')</script>`))
.ws('/',{open:ws=>{ws.subscribe('123');console.log(ws.getTopics())}})
.listen(8080,s=>{})
```

**Comment by e3dio** [comment]
Ok I figured it out, I was looking through your public repo and the uWebSocket source code, this error only occurs when you try to unsubscribe from a topic when the websocket is not subscribed to any topics, this code will reproduce:

```javascript
require('uWebSockets.js').App()
.get('/',res=>res.end(`<script>ws=new WebSocket('ws://localhost:8080')</script>`))
.ws('/',{open:ws=>ws.unsubscribe('123')})
.listen(8080,s=>{})
```

There needs to be a check added here to fix that: https://github.com/uNetworking/uWebSockets/blob/master/src/WebSocket.h#L252

Side note, I see you are using the websocket Ratelimit code, nice https://github.com/tardis-dev/serum-vial/blob/master/src/minion.ts#L36

**Comment by thaaddeus** [comment]
@e3dio thank you! I really appreciate it, that's great. Even without a fix I can handle that by simply checking first if socket is already subscribed `isSubscribed` and only then unsubscribe? I should actually do that anyways I think.
Thanks again!

**Comment by e3dio** [comment]
You can do that for now to prevent error, it's fixed in master branch and the next release will return "false" instead of throwing error for that situation so checking isSubscribed won't be necessary
