### ISSUE TITLE
Unable to listen is not reported

### ISSUE THREAD

**Issue by choofy** [uNetworking/uWebSockets.js#678]
*Observed:* On windows (I am not sure if it happens on other OSes as well), I notice that when I have another process running that listens on a certain port, and then I start up a 2nd process that binds to the same port, the binding succeeds for the 2nd process: the callback delivers a socket, and `us_socket_local_port(socket)` gives the configured port number.

However, of course, this 2nd process does not receive any incoming connections, because the 1st process is already bound to this port.

*Expected:* When a listening port is already in use, the listen callback should return socket=false

Code:
```
      try {
        server2.listen(parseInt(address.split(':')[1], 10), (socket) => {
          console.log('SOCKET', socket, JSON.stringify(socket), uws.us_socket_local_port(socket) );
          if (socket) {
            this.listenSocket = socket;
            resolve(0);
          } else {
            reject('Failed to listen');
          }
        });
      } catch (e) {
        this.logger.warning('Failed to listen on [Address]: [Error]', () => ({ Address: address, Error: e }));
        reject('Failed to listen');
      }
```
Generates following output when another process already listens on port 6001:
```
  SOCKET [External: 1fa4a337c00] {} 6001
```

**Comment by e3dio** [comment]
I tried this, the 2nd process does listen but it waits for the 1st process to exit before accepting connections. Maybe you could have 1 process tracking what ports are being used, and use worker threads to listen to the different ports

**Comment by choofy** [comment]
Hi, thank you for your quick response.

I would not expect this behaviour. Looking at how other NodeJS components behave (like the builtin server socket https://nodejs.org/api/net.html#serverlisten ):

> One of the most common errors raised when listening is EADDRINUSE. This happens when another server is already listening on the requested port/path/handle. One way to handle this would be to retry after a certain amount of time:

When the address is in use, you get an error. As far as I know, that is the expected behaviour from a `listen` method. For most applications I can think of, you want to know whether the listen did succeed or not, and whether you are actually listening. Imho, it is of little interest to know that you will be listening at some point in the future when another process dies (which will very likely never happen).

I would either like to see the current behaviour documented (as it is non-standard), or fixed. I prefer the last one (fixed, possible with a flag to turn this behaviour on or off) :)

**Comment by e3dio** [comment]
Looks like for Windows you need to add this `SO_EXCLUSIVEADDRUSE` for exclusive ports https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse

There is also IO completion ports for binding many on 1 port for worker threads etc: https://docs.microsoft.com/en-us/windows/win32/fileio/i-o-completion-ports

**Comment by alexhultman** [comment]
app.listen takes host, port, options, callback. Options can be uWS.LIBUS_LISTEN_EXCLUSIVE_PORT

**Comment by e3dio** [comment]
LIBUS_LISTEN_EXCLUSIVE_PORT option doesn't work on Windows, looks like SO_REUSEADDR gets called either way 2 lines below https://github.com/uNetworking/uSockets/blob/master/src/bsd.c#L256 so then it would need SO_EXCLUSIVEADDRUSE

**Comment by choofy** [comment]
My experience is that the SO_REUSEADDR and/or SO_EXCLUSIVEADDRUSE are normally not used on windows. Normally, you assume you have control over your server (or just run in docker where you are basically the only process), so that there are no malicious processes listening on your port.

When you do not specify any of SO_REUSEADDR and/or SO_EXCLUSIVEADDRUSE, the socket behaviour is "as expected by developers": the 2nd process simply gets refused. (according to the first link of e3dio).

I think that that SO_REUSEADDR and/or SO_EXCLUSIVEADDRUSE are advanced use cases that people should use only when they really need this extra level of control. So, instead of being the default of using them, *the default should be not using any of them*, and flags would allow a developer to use them when required.

In addition, SO_EXCLUSIVEADDRUSE can only be used when in Administrator mode. Applications that use SO_EXCLUSIVEADDRUSE will shouw different behaviour depending on how they are started. That does not seem right.

**Comment by e3dio** [comment]
This is a Linux priority library, Linux distributes connections to processes listening on the same port and Window does not, you have to use special IO ports for that, they all handle these settings differently

> In addition, SO_EXCLUSIVEADDRUSE can only be used when in Administrator mode.

That is only for Windows XP and earlier. I think the above PR is fine for now, ideally by default Windows would use IO port but for now do SO_REUSEADDR and SO_EXCLUSIVEADDRUSE

**Comment by choofy** [comment]
You are right about XP, I misread. I do not oversee all of the complexities of SO_REUSEADDR and SO_EXCLUSIVEADDRUSE, but I think that you rproposal is ok.

**Comment by uasan** [comment]
Hi, unfortunately when using the new SO_EXCLUSIVEADDRUSE option, Windows 11 users still don't get an error when the specified port is already in use by another process.
I know that this problem has a low priority, it is not reproduced in production, only for those developers who work locally on Windows 11, there are enough of them in our company ), do you know what is the reason and how can this be fixed?

**Comment by e3dio** [comment]
I helped with this by reading Microsoft docs but I don't know how to compile on windows so was not tested, but I also noticed still not working correctly, I'd help but don't know how to fix

**Comment by astutesoftware** [comment]
Running the command window with administrator privileges fixes this issue on Windows 11 22H2.
