### ISSUE TITLE
Could send take offset + len?

### ISSUE THREAD

**Issue by ronag** [uNetworking/uWebSockets.js#679]
It would be nice if I instead of doing this:

```js
ws.send(buf.slice(0, 16)
```

could do something like:

```js
ws.send(buf, 0, 16)
```

Skipping the extra Buffer allocation.

**Comment by alexhultman** [comment]
new Uint8Array(buffer, byteOffset, length);

**Comment by ronag** [comment]
I was thinking of avoiding that allocation.

**Comment by ronag** [comment]
maybe nano optimization

**Comment by alexhultman** [comment]
Yeah if allocating a view is a concern then why the heck are you even using JavaScript

**Comment by e3dio** [comment]
`new Uint8Array(buffer, start, length)` is 65% faster than `buffer.slice(start, end)` if you need slice of array buffer
