### ISSUE TITLE
Incorrect headers decode

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#686]
Hi.
Please, correct me, if I am mistake.
You are always trying to decode header to `utf8` when `getHeader()` called.
This is not quite correct and can lead to loose header value.
According to the spec http headers can be us-ascii strings only. Some headers can be specially encoded and decoded by user. But application server must always return ascii strings.
Look at example below, value of `utf` header is lost.

```
#!/usr/bin/env node

import http from "node:http";
import uws from "uWebSockets.js";

const app = uws.App().get( "/*", ( res, req ) => {
    console.log( "-- ascii:", req.getHeader( "ascii" ) );
    console.log( "-- utf:", req.getHeader( "utf" ) );

    res.end();
} );

await new Promise( resolve => app.listen( 80, resolve ) );

http.request( "http://127.0.0.1/",
    {
        "headers": {
            "ascii": "test",
            "utf": Buffer.from( "тест" ).toString( "binary" ),
        },
    },
    res => {
        process.exit();
    } ).end();
```

**Comment by e3dio** [comment]
> "utf": Buffer.from( "тест" ).toString( "binary" )

[Binary](https://nodejs.org/api/buffer.html#buffers-and-character-encodings) here is referring to [latin1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) encoding, this is not ascii or utf8 so you should not expect the server to give you the correct string back. The server would need to add latin1 decode instead of the ascii decode which would not be standard. Most clients don't let you send non-ascii strings for the header including Node http, so your best option is just send standard ascii characters

**Comment by alexhultman** [comment]
There is no interpretation of utf8 or latin1 or whatever - you get what the client sent you

**Comment by e3dio** [comment]
> When I send header with pure, not encoded utf8 octets - uws getHeader() returns utf8 string. That's why I think, that uws tries to decode headers to utf8 and ignore header, if decode was failed.

@zdm But you are saying you want it to decode with latin1 instead of utf8. If utf8 works then why don't you send with utf8 encoding? Neither are standard for http header, so the current behavior seems correct

**Comment by zdm** [comment]
I tested using browser and cookies with utf8 vals, uws returns `cookie` header utf8 encoded. This is incorrect, I think, It should return latin1 string, Otherwise, headers, that can not be decoded to utf8 will be lost.

**Comment by zdm** [comment]
@alexhultman could you explain, why in example above uws returns no data for header `utf`? I expected to get sent value.

**Comment by e3dio** [comment]
> I think, It should return latin1 string

So you personally think it should return latin1 string, but the spec says ascii which is not latin1. To me utf8 makes more sense than latin1. Utf8 is a lot more useful than latin1. I am still confused, if Utf8 is working for you, why not just send with Utf8?

**Comment by e3dio** [comment]
> could you explain, why in example above uws returns no data for header utf? I expected to get sent value.

It's because the string you are sending is not valid ascii or valid utf8, the server would need to specifically decode with latin1. getHeader returns a JS string not ArrayBuffer so it needs to decode it somehow

**Comment by zdm** [comment]
When I send seruest from the browser with cookie `a=ыыыы`, `uws.getHeader("cookie")` returns `utf8` string?
It is also not valid ascii string.

**Comment by e3dio** [comment]
I just tried that, sending cookie with utf8 via browser with Russian characters, and uWS.js correctly gave utf8 decoded JS string, so this is correct behavior to me. You are saying you want to mess that up and give latin1 decoded string? Why? Just send with Utf8 and it will be fine

**Comment by zdm** [comment]
Look at code above, it clearly reproduces the problem.

**Comment by e3dio** [comment]
The browser is sending Utf8 headers as I just tested with cookie, so you definitely want to support Utf8 decode for headers, so latin1 decode would mess that up for all browsers sending Utf8 cookies. Node http client will not let you send Utf8 but you can probably find a different http client that will let you send Utf8 header, there are many http clients

**Comment by zdm** [comment]
Not every header is valid utf8. Header can contain some binary data in latin1.
So, the portable and correct way is to accept and return latin1, without converting to utf.

**Comment by e3dio** [comment]
The spec says ascii so latin1 is not correct, that is just your preferred way to send binary data in a header. If the major Browsers are sending Utf8 headers you don't have a choice, you need to decode Utf8 header. If you are trying to send Russian letters Utf8 is much easier than latin1. If you are trying to send Binary data you can send Base64 encoded string. So I don't see what your issue is with current behavior

**Comment by zdm** [comment]
It looks as if there is an error in the HTTP/1.1 specs. As you pointed out, §4.2 describes the field content as OCTET:

field-content = the OCTETs making up the field-value

And OCTET is defined in §2.2 as:

OCTET = any 8-bit sequence of data

**Comment by zdm** [comment]
8-bit = latin1

**Comment by zdm** [comment]
latin1 - is common sense and supported by other web servers, like nginx
and no one tries to encode values to utf8 automatically

**Comment by zdm** [comment]
In any case uws has problem with the headers decoding. It accepts some latin1 headers (which can be encodede to utf8) and rejects other.

**Comment by e3dio** [comment]
Looks like uWS.js is using the v8 `String::NewFromUtf8` function to decode header https://github.com/uNetworking/uWebSockets.js/blob/master/src/HttpRequestWrapper.h#L89

[Looks](https://stackoverflow.com/a/4410331) like updated http [spec](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.4) says: 

> Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].
   
> <b>Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.</b>

So supporting latin1 or utf8 is optional, up to the server how to handle, Utf8 makes sense to me as major browsers are sending and receiving it

**Comment by zdm** [comment]
I dont know how to understand "opaque data"?
Such headers should be ignored or leave as is or what?

If you will choose to use utf8 - you will need to encode all headers in the request to utf8. Correct?
This may not work in all cases, because you can have cookie or content-disposition filename in utf8, and authentication or etag or other cookie in latin1, which can not be properly decoded to utf.

Portable and correct way is to use latin1 and user will decide by himself, what headers he want to decode to utf.
Nodejs http client and server returns headers in latin1. And this choice was dictated by use cases.

**Comment by e3dio** [comment]
Maybe this was what @alexhultman meant:
> There is no interpretation of utf8 or latin1 or whatever - you get what the client sent you

You are supposed to get the ArrayBuffer and you can decode however you want? This would be inconvenient to do `Buffer.from(req.getHeader(name)).toString()` but is doable

**Comment by zdm** [comment]
Yes, return header as raw buffer will solve problem with encoding.
But will be not handy to use. In almost all cases user want to compare header value with some string or number, and we will need to write additional code to convert buffer to the string all the time.
Better is to return something like this (assume, that internally values stored as ArrayBuffers):
```
// this will return ArrayBuffer as latin1 encoded string
Buffer.from( ArrayBuffer ).toString( "binary" );
```

**Comment by alexhultman** [comment]
https://v8docs.nodesource.com/node-16.13/d2/db3/classv8_1_1_string.html#a9a8e9bfa8743b53f30acdcac3a1bfdd7

**Comment by e3dio** [comment]
I think V8 `String::NewFromOneByte` with the latin1 decode is technically the correct thing to do, can probably switch that out with the current `String::NewFromUtf8` and it won't break anyone's server and will fix issue for people relying on 1 byte latin1 decode https://github.com/uNetworking/uWebSockets.js/blob/master/src/HttpRequestWrapper.h#L89

**Comment by zdm** [comment]
I am sorry, but this still not fixed in v20.7.0.
I updated example, so you can compare how uws and node http servers works:

```
#!/usr/bin/env node

import http from "node:http";
import uws from "uWebSockets.js";

const app = uws.App().get( "/*", ( res, req ) => {
    console.log( "uws:" );
    console.log( "  ascii:", req.getHeader( "ascii" ) );
    console.log( "  utf8:", req.getHeader( "utf8" ) );
    console.log( "---------------------------------" );

    res.end();
} );

await new Promise( resolve => app.listen( 80, resolve ) );

const server = http.createServer( ( req, res ) => {
    console.log( "node http server:" );
    console.log( "  ascii:", req.headers["ascii"] );
    console.log( "  utf8:", req.headers["utf8"] );
    console.log( "---------------------------------" );

    res.end();
} );

server.listen( 81 );

http.request( "http://127.0.0.1:80/",
    {
        "headers": {
            "ascii": "test",
            "utf8": Buffer.from( "тест" ).toString( "latin1" ),
        },
    },
    res => {} ).end();

http.request( "http://127.0.0.1:81/",
    {
        "headers": {
            "ascii": "test",
            "utf8": Buffer.from( "тест" ).toString( "latin1" ),
        },
    },
    res => {} ).end();

// process.exit();
```

**Comment by zdm** [comment]
`uws` still returns empty value instead of `latin1` representation of `utf8` string.

**Comment by alexhultman** [comment]
I think you are relying too much on exact details of implementations.

> Buffer.from( "тест" )
<Buffer d1 **82** d0 b5 d1 81 d1 82>

Char **0x82** is an Extended Control Char in latin1 and I don't know what that means, but I can definitely understand if V8 refuses to accept it (which it obviously is). Just because Node.js happens to do X does not mean all servers will follow with exact behavior. Best would be to NOT depend on very specific behavior and just pass ASCII.

**Comment by alexhultman** [comment]
NewFromOneByte can indeed hold "тест" so it has to be the http parser that messes things up. Can you test a raw C++ example

**Comment by zdm** [comment]
I am not c++ dev. Can do something only if you will give me instructions.

**Comment by alexhultman** [comment]
Nothing in the parser should hinder "тест"

**Comment by alexhultman** [comment]
root@5d057ec32e43:/uWebSockets.js/node-v18.0.0-linux-arm64/bin# ./node bug.mjs 
uws:
  ascii: test
  utf8: ÑÐµÑÑ
---------------------------------
node http server:
  ascii: test
  utf8: ÑÐµÑÑ
---------------------------------

**Comment by alexhultman** [comment]
What platform are you on?

**Comment by zdm** [comment]
linux and windows

**Comment by zdm** [comment]
tested under windows

**Comment by alexhultman** [comment]
Something is messy with the http parser. The parser gives empty string before V8 is even used.

**Comment by zdm** [comment]
yes, possible
tell me, if i can help somehow

**Comment by alexhultman** [comment]
Yeah it reproduces with raw C++ example. Very strange

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/releases/tag/v20.13.0

This will release at some point (it is a really minor issue)

**Comment by zdm** [comment]
Thank you very much.

**Comment by alexhultman** [comment]
What is your use case? Why is this an issue for you?

**Comment by zdm** [comment]
I had a problems with the cookies, previous developer used binary value 
for token, encoded as latin1.

**Comment by alexhultman** [comment]
Okay but HTTP headers are terminated with CRLF so using raw binary can break it anyways. So it seems like a bad solution anyways.

**Comment by zdm** [comment]
yes, i know, tokens did not contain crlf, but can obtained bytes > 128.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.8.0

Can you test this?

**Comment by zdm** [comment]
Tested under windows - stoll not works.

**Comment by zdm** [comment]
Yes, it works now, thank you.
