### ISSUE TITLE
Connection not closed when calling end() from open handler

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#690]
I need to close ws connection with some error code just after it was opened (in `open` handler).

This code works:
```
open ( ws ) {
    ws.close();
}
```

this not works, remote peer stays in the connected state and doesn't receives end message:
```
open ( ws ) {
    ws.end( "4000", "test" );
}
```

**Comment by e3dio** [comment]
I tried that and it works, `ws.end('4000','test')` closes ws connection with correct code and message received on client. Docs say code should be a number but string also works

**Comment by zdm** [comment]
I am testing. Seems, that this is a bug in node `ws` package.

**Comment by zdm** [comment]
Yes, it works in browser, but not in the nodejs. I will close this issue, sorry.

**Comment by zdm** [comment]
No, this is definitely thw problem in uws. It not works in the browser too. Websocket in the browser become opened and stays in the open state forever.
THis is only when I use `.end()`, with the `.close()` call it works as expected.

**Comment by zdm** [comment]
Also It works with `.end()` if I call `.end()` after some short timeout. But set timer for this is not an option.

**Comment by e3dio** [comment]
Works for me on Firefox and Chrome as I described above, no timeout before call end etc, are you sure you are doing correctly, did you try minimal example

**Comment by zdm** [comment]
yes. i am trying minimal code
not works for me in chrome and under nodejs.
i will keep testing

**Comment by e3dio** [comment]
I tried this with Node `ws` client, works there too:

```javascript
// server
require('uWebSockets.js').App().ws('/',{open:ws=>ws.end('4000','test')}).listen(3000,()=>{})

// client
const {WebSocket}=require('ws')
const ws=new WebSocket('ws://localhost:3000')
ws.on('close',(code,reason)=>console.log('close',code,reason))

```

**Comment by zdm** [comment]
yes, this is a very strange behavior, i am debugging, but it is not related to uws.
