### ISSUE TITLE
What is the default value for sendPingsAutomatically?

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#694]
It accepts number in seconds?
What is the default value?
0 - do not ping?

This is not described in the docs.
Thanks for answers.

**Comment by e3dio** [comment]
True or False, default is True. It sends ping a couple seconds before idleTimeout value, default idleTimeout is 120 seconds https://github.com/uNetworking/uWebSockets/blob/master/src/App.h#L227

**Comment by zdm** [comment]
Thank you.

It sends websockets ping on tcp keep-alive packet?

And in `index.d.ts` need to change `sendPingsAutomatically?: number;` to `sendPingsAutomatically?: boolean;`
