### ISSUE TITLE
uWebsockets.js - The open event does not trigger

### ISSUE THREAD

**Issue by vandercijr** [uNetworking/uWebSockets.js#696]
I am using version 18 of uwebsocket.js lib, nodejs 12 lts, I've already tested using latest version of uws and node 16
Everything works fine but the open event  does not trigger 

Looking on websocket wrapper I did not find open. Was It removed, or listen replaced it ?

I appreciate any help.

[gist of my example](https://gist.github.com/vandercijr/234c174bc2b890edfc4a4a8ec22f29aa)

**Comment by e3dio** [comment]
Your `.get()` and `.ws()` routes are the same, they need to be different

**Comment by e3dio** [comment]
Your code is working for me, with websocket client code `new WebSocket('ws://localhost:9000')`

**Comment by vandercijr** [comment]
> Your code is working for me, with websocket client code `new WebSocket('ws://localhost:9000')`

Forget my previous message. I was wrong (should I take a vacation ? maybe lol)

the open, close are events related to the client, not the instance, so that's ok

sorry
