### ISSUE TITLE
Need getHeaders()

### ISSUE THREAD

**Issue by orefalo** [uNetworking/uWebSockets.js#70]
Enhancement request.

Need a function to get all headers added to the API. Something like the following function.

getHeaders():Dictionary(String: String)

Apollo transforms the request from a standard http req, to a more generic request (with fields such as { method: string, headers: Headers ... }

```
export declare class Headers implements Iterable<[string, string]> {
  constructor(init?: HeadersInit);

  append(name: string, value: string): void;
  delete(name: string): void;
  get(name: string): string | null;
  has(name: string): boolean;
  set(name: string, value: string): void;

  entries(): Iterator<[string, string]>;
  keys(): Iterator<string>;
  values(): Iterator<[string]>;
  [Symbol.iterator](): Iterator<[string, string]>;
}
```

more here : https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-env/src/fetch.d.ts

and that's the transformation function for node standard pkg:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/nodeHttpToRequest.ts

Tks

**Comment by alexhultman** [comment]
I think an iterator for req is okay:

```
for (auto header : req) {
  std::cout << header << std::endl;
}
```



But you have to benchmark and see if this messes up everything.

**Comment by alexhultman** [comment]
There's an example called Headers.js doing this now

**Comment by orefalo** [comment]
Thank you! Do you have accept donations?

**Comment by alexhultman** [comment]
I have this one https://www.paypal.me/uwebsockets

**Comment by alexhultman** [comment]
Thanks :+1:

**Comment by orefalo** [comment]
np, small contribution in fact.
