### ISSUE TITLE
Server Side Event

### ISSUE THREAD

**Issue by webigorkiev** [uNetworking/uWebSockets.js#709]
I am trying to implement Server Side Event back end.
How do I handle the connection reset(close) event?

In node.js http package it is
req.on('close', () => { });
How to do it in
uWebSockets.js?

Thanks

**Comment by webigorkiev** [comment]
onAborted - works fine. 
It would probably be cool to have an example on **Server Send Event**

**Comment by techvlad** [comment]
@webigorkiev I create example of Server-sent Events #711
