### ISSUE TITLE
closeOnBackpressureLimit not in TS Docs

### ISSUE THREAD

**Issue by DakotaLarson** [uNetworking/uWebSockets.js#717]
In the interface `WebSocketBehavior`, `closeOnBackpressureLimit` is not detailed as an option, however, it is referenced as a controlling option. 

Should the option be present in this interface? I had to ignore a TS error when trying to enable the behavior.

![image](https://user-images.githubusercontent.com/6530255/158704453-3c24741d-c1d3-4f74-89a1-d362a0d878a1.png)

**Comment by e3dio** [comment]
Needs to be added can you open PR
