### ISSUE TITLE
HttpResponse pause and resume not in TS doc

### ISSUE THREAD

**Issue by Zubnix** [uNetworking/uWebSockets.js#724]
Judging by the wrapper code these should be available in js land?https://github.com/uNetworking/uWebSockets.js/blob/master/src/HttpResponseWrapper.h#L43

**Comment by e3dio** [comment]
Needs to be added to docs see https://github.com/uNetworking/uWebSockets.js/issues/661

**Comment by alexhultman** [comment]
Please add it
