### ISSUE TITLE
Pls, release this update "Use latin1 in getHeader"

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#727]
Could you, please, make a release for the latest code, including this commit "[Use latin1 in getHeader](https://github.com/uNetworking/uWebSockets.js/commit/4ac42ec21b2bb8d9bb8214671b95ca107c0d9071)"?

Thanks you.

**Comment by alexhultman** [comment]
Next release will come when Nodejs 18 releases in 2 days

**Comment by zdm** [comment]
Thank you for reply.
