### ISSUE TITLE
high memory usage on https

### ISSUE THREAD

**Issue by Vladislavik** [uNetworking/uWebSockets.js#73]
hi, i was try your code without https and with https, and on 80000 simultanues connections there are results:

> 1) no https - used memory: 600Mb
> 2) with https - used memory: 3.5Gb

i am use SHARED_COMPRESSOR
How i can reduse memory usage? (Nodejs 11.10)

**Comment by alexhultman** [comment]
We can add a setting to uSockets prefer_memory or similar that sets the SSL_MODE_RELEASE_BUFFERS mode, it skips quite a bit of memory usage.

**Comment by alexhultman** [comment]
ssl_prefer_low_memory_usage true/false

**Comment by mrlika** [comment]
I will be great to have this configuration option

**Comment by ozra** [comment]
What's the downside to enabling it?

**Comment by alexhultman** [comment]
This option is now implemented and documented

**Comment by alexhultman** [comment]
Benchmarks put it at 85k req/sec vs. 77 req/sec so this will lower performance hence the option
