### ISSUE TITLE
Content-Length is invalid when method is head

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#739]
Head method should return headers only without body.

So I write headers, including body Content-Length, then finish request with res.end();

res.ens() adds Content-Length: 0 automatically, if body is not provided.
This leads to the error, because response will contain two Content-Length headers with different values.

Correct behavior: if res.end() called without body - do not add Content-Length header.

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/blob/b498b61532d7d37834323bace243e6f115312d24/src/HttpResponse.h#L386

**Comment by zdm** [comment]
Should I use endWithoutBody()?

**Comment by zdm** [comment]
endWithoutBody is not a function, not exposed to the nodejs level.

**Comment by zdm** [comment]
will you add this?

**Comment by alexhultman** [comment]
endWithoutBody is in binaries branch (no release yet)

**Comment by zdm** [comment]
thank you, could you release it pls?

**Comment by alexhultman** [comment]
20.10.0

**Comment by zdm** [comment]
`endWithoutBody( reportedContentLength, closeConnection )` 

It works only when called without arguments.
If I call it like: `endWithoutBody( 0, true ) - it does not finish response headers with "\r\n\r\n" so all communication become frozen.
It works only when called without arguments.

**Comment by alexhultman** [comment]
only endWithoutBody() is implemented. It's an issue in C++ repo
