### ISSUE TITLE
`writeStatus` ignored if called after `writeHeader`

### ISSUE THREAD

**Issue by timkendall** [uNetworking/uWebSockets.js#74]
It seems like calls to `writeStatus` are ignored if called after `writeHeader`. For example, this results in the HTTP status `200 OK`:

```js
res.writeHeader('Content-Type', 'application/health+json');
res.writeStatus('503')
res.end(JSON.stringify({ status: 'fail' }))
```

**Comment by timkendall** [comment]
Ah guess this is standard HTTP message semantics (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages). 

As this library is somewhat lower-level than other HTTP frameworks Node devs are likely used to we should perhaps call this out clearly in the docs. I'm not really familiar with the C++ side of things, could we perhaps throw an error into JS if these methods are called out of order?

**Comment by visbio** [comment]
I have the same issue. I have to store all my writeHeaders and then write them after I set the status in my route.

**Comment by alexhultman-2fa** [comment]
If this is how you see things then clearly you're not the intended user base

**Comment by lusatiro** [comment]
I would be more respectful with people trying my work. I could use it in my company to get more performance, that's why
i'm trying it out.

**Comment by alexhultman-2fa** [comment]
Respect has nothing to do with any of this. I'm just stating neutral facts. If you see things this way, you're not seeing things the intended user would see things.

**Comment by hst-m** [comment]
@lusatiro you are replying to someone from Feb 2019 to make random statement so I think you are just confusing people. And you just posted noobish question in other issue about Options method so sounds like you don't know what you are doing, maybe other people at your company know what they are doing

**Comment by lusatiro** [comment]
You are just arguing that everyone jumps directly to mid or senior
positions. Everyone has to start from some point. I work in the industry
for some quite time now. Yes, I never had to config an options cors method
protocol myself, all this stuff generally comes out of the box. I replied
'cause I need the solutions and there's little to no information about this
lib out there, thus the issues are the only place I could find some
solution. I could stick with express, but I preferred to learn new stuff.

Em sex., 16 de out. de 2020 às 11:42, hst-m <notifications@github.com>
escreveu:

**Comment by lusatiro** [comment]
Stop trying to be Linux, you're far away from this.

Em sex., 16 de out. de 2020 às 13:20, Lucas Sátiro <ljsatiro@gmail.com>
escreveu:

**Comment by hst-m** [comment]
I am saying you should stop spamming this repo with noob http questions and use Google instead to do some basic learning, come back when you are ready
