### ISSUE TITLE
Question: should I reply with error in res.onAborted callback?

### ISSUE THREAD

**Issue by piliugin-anton** [uNetworking/uWebSockets.js#744]
Hello. Thank for your work, I really enjoy working with your library. I'm asking about callback from this example: https://github.com/uNetworking/uWebSockets.js/blob/fbfc250451a917f6361832f2efd123382470516a/examples/JsonPost.js#L71

Should I reply with some error code or this callback is only an indication that user aborted page loading and I don't need to do anything?
Thanks in advance!

**Comment by alexhultman** [comment]
You don't need to do anything the connection is broken

**Comment by piliugin-anton** [comment]
Do I get your code right: I can add as many callbacks for onAborted, but only last one added will be called?
