### ISSUE TITLE
response header expose that the server is uWebSockets

### ISSUE THREAD

**Issue by tahonaPL** [uNetworking/uWebSockets.js#764]
This can tell to hacker what kind of service code he needs to start looking into to develop hack. 
This should be available in debug mode or something. not as a default.

**Comment by alexhultman** [comment]
It's a common question (or opinion), it has come up a few times before.

uWS only exposes major version by default and that's by design (or rather by marketing).

**Comment by tahonaPL** [comment]
well you know that it will be shadowed by gateway or anything else. could be as well optional

**Comment by tahonaPL** [comment]
so why doing that a problem. option with default show (true). would be the same

**Comment by alexhultman** [comment]
If that's **the same** then why are you complaining?
