### ISSUE TITLE
HTTP connection Timeout then half closed socket

### ISSUE THREAD

**Issue by uasan** [uNetworking/uWebSockets.js#770]
We are using a proxy that has HTTP connection pool to uWebSockets.js backend.
If a connection from the pool is idle for more than 20 minutes, requests sent to this connection are not processed, it looks like the incoming connection was closed on the server side and it is in a half-closed state, the proxy did not receive a close signal and is trying to use this connection, this is still an assumption based on behavior this errors.
Has anyone had a similar experience or have other thoughts?

**Comment by alexhultman** [comment]
This description is way too abstract and generic to give any real info. uWS will close any http connection that is idle for more than 10 seconds, so if you want to keep them alive you have to send them some requests

**Comment by uasan** [comment]
> close any http connection that is idle for more than 10 seconds

Is this value `10 seconds` configurable or hard coded?

**Comment by alexhultman** [comment]
TCP keep alive is not related to that timeout. You need to send actual requests (phony) to keep it open. But why do you need them open? If you have no traffic to keep them open they don't need to be open. If you have lots of traffic they will stay open.

**Comment by uasan** [comment]
> But why do you need them open?

For some unknown reason, the proxy considers connections that the server timeout to be open connections.
This is a stupid logic of the proxy connection pool, it keeps the pool even when there is no traffic, I can’t fix the proxy logic, so I’m looking for options on how to fix it on server side.

**Comment by alexhultman** [comment]
Which proxy?

**Comment by uasan** [comment]
itsio envoy - it works slower than our backend, but the business client required it, it's all on AWS
https://istio.io/latest/docs/ops/deployment/architecture/

**Comment by uasan** [comment]
This may have been discussed but I couldn't find it.

If the handler is assigned in the next microtask after receiving the request, will the onData event occur or is there a risk that in the previous microtask the server read the entire request body and the event assigned in the next microtask will never wait for the call and I will never receive the body of this request?
Example, code:
```JS
rout.post('/', async (res, req) => {
 let isAborted = false;
 res.onAborted(() => { isAborted = true });

 if (isAborted === false) {
     await asyncMethod();
     res.onData(() => {
        //... Is there a risk that I started listening too late and the request body is no longer readable?
     })
  }
})

```

**Comment by alexhultman** [comment]
You need to set onData immediately before any await

**Comment by uasan** [comment]
I thought so, it seems that this is the reason for the 504 error from the proxy, I get into eternal waiting and the proxy is not to blame.

**Comment by uasan** [comment]
Thanks, I'm closing the ticket.
