### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by Wyzix33** [uNetworking/uWebSockets.js#774]
Hi, 
how can i redirect http to https 
I have this setup:
```
 APP = uWS
  .SSLApp({ key_file_name: './privkey.pem', cert_file_name: './fullchain.pem' })
  .any('/*', processRequest)
  .listen(443, (token) => {
   if (token) console.log('Listening to port 443' );
   else console.log('Failed to listen to port 443');
  });
```
do i need to start another instance of uWS on port 80 and respond with a redirect or is there another way?
Thanks

**Comment by e3dio** [comment]
Port 80 redirect with Location header, same as every other server

**Comment by e3dio** [comment]
You come on here open issue for a question that is easy to google and leave it open? Are you still confused?
