### ISSUE TITLE
Error: Cannot find module './uws_linux_x64_102.node'

### ISSUE THREAD

**Issue by bugs181** [uNetworking/uWebSockets.js#781]
Related #627 

Unfortunately, I'm still receiving this error even though my system appears like it meets all requirements.

### Installation
```
$ npm install uNetworking/uWebSockets.js#v20.10.0

added 1 package, and audited 2 packages in 3m

found 0 vulnerabilities
```
### Error
```
$ node index
/.../ProjectName/node_modules/uWebSockets.js/uws.js:22
                throw new Error('This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).\n\n' + e.toString());
                ^

Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: Cannot find module './uws_linux_x64_102.node'
```

### System:
```
(kernel >= 4.18)
$ uname -r
5.11.0-7620-generic

(glibc >= 2.28)
$ ldd --version
ldd (Ubuntu GLIBC 2.32-0ubuntu3) 2.32 

$ node --version 
v17.4.0
```

Let me know if I'm missing any information or can test further. Thanks.

**Comment by alexhultman** [comment]
If you read the text you just posted, the answer is clearly visible in English text.

**Comment by alexhultman** [comment]
I mean the error message **literally is the very explanation** written in human readable text. The whole point of a message is you read it with your eyeballs.

**Comment by bugs181** [comment]
By your own words in reply, is this not correct?

> And as of v20.1.0, this is fixed. Thank you!

_Originally posted by @FallingSnow in https://github.com/uNetworking/uWebSockets.js/issues/627#issuecomment-950397649_

> Yes please test it out and also test SSL. These binaries now use BoringSSL

_Originally posted by @alexhultman in https://github.com/uNetworking/uWebSockets.js/issues/627#issuecomment-950400349_

**Comment by alexhultman** [comment]
Node.js 17 is not supported. Only LTS versions.
