### ISSUE TITLE
App construction failed on SSLApp

### ISSUE THREAD

**Issue by x8BitRain** [uNetworking/uWebSockets.js#788]
Trying to create an SSLApp with cert and key but no matter where I put the cert (same level, folder above or below) and the key or how I name them it fails with ```Error: App construction failed```.

If I remove the ```cert_file_name``` and ```key_file_name``` settings it launches just fine.

The code in question is basic, readFileSync doesn't work either:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/15372551/184902769-4d797b8a-c9a5-4de5-88fd-25b6f3f00be2.png">

The error:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/15372551/184902835-45370cc7-7ff0-4f3c-98da-aeea76d0f650.png">

Doesn't work in docker images like node:16-bullseye, node:16-buster or even on earlier versions of the natively on macos. Downgrading to version v20.7.0 doesn't work either. 

EDIT: Soketi doesn't work either, same error.

This seems like a bug to me, any ideas? Thanks.

**Comment by x8BitRain** [comment]
Does not work either, I tried Soketi and I get the same issue. Maybe related to this? https://github.com/uNetworking/uSockets/issues/131

Using --trace-uncaught doesn't reveal anything new.

**Comment by e3dio** [comment]
Either you are not linking to the correct pem files which needs private key and full chain, or I just confirmed the pem path you give is relative to where you called Node from and not relative to where the app JS file is, so if you called Node with `node dir/to/app.js` the pem path is not relative to app.js, it is relative to node so you would need pem path as `dir/to/privkey.pem`

**Comment by e3dio** [comment]
Or use `__dirname` like ``{ key_file_name: `${__dirname}/privkey.pem` }``

**Comment by x8BitRain** [comment]
Thanks, the above worked!
