### ISSUE TITLE
async/await is slow

### ISSUE THREAD

**Issue by mattiasewers** [uNetworking/uWebSockets.js#79]
**Description**

Using async function and await a promise is slow

* OS: Mac OS 10.14
* Node: Homebrew v11.10.0

**Reproduction**

Benchmark (wrk, 2 threads, 10 conn):
example/AsyncFunction.js - 16.7k req/sec
example/HelloWorld.js - 106k req/sec

**Comment by alexhultman** [comment]
Yep it will be significantly slower until we add res.begin function, this is tracked in main repo

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/issues/816

**Comment by alexhultman** [comment]
npm install uNetworking/uWebSockets.js#binaries

Try now

**Comment by mattiasewers** [comment]
@alexhultman confirmed much better

**Comment by alexhultman** [comment]
Great, what did you get?

Let me guess - 80k?

**Comment by mattiasewers** [comment]
Tested on ubuntu and got 165K, but I would guess something like 80k on osx :+1:
