### ISSUE TITLE
app.close()

### ISSUE THREAD

**Issue by jjjuk** [uNetworking/uWebSockets.js#794]
Hello dear contributors! Please make simple `app.close()`. I use uWS as api gateway, when service restarts app doesn't close. 
`uWS.us_listen_socket_close(listenSocket)` doesn't help. 
After restart port is busy. 
I love this project, but this is ridiculous.
Or any thoughts how to overcome this? I use moleculer for microservices

**Comment by jjjuk** [comment]
#592 copy of this I know. Need your attention to this problem

**Comment by e3dio** [comment]
This is how you graceful close app + websockets:
```javascript
import { App, us_listen_socket_close } from 'uWebSockets.js';

const wsMap = new Map();
let id = 0, listenSocket;

const app = App()
   .get('/', res => res.end('123'))
   .ws('/', {
      open: ws => {
         wsMap.set(ws.id = ++id, ws);
         console.log('open', ws.id);
      },
      close: (ws, code) => {
         console.log('close', ws.id, code);
         wsMap.delete(ws.id);
      }  
   })
   .listen(8002, s => console.log(listenSocket = s));

const shutdown = sig => {
   console.log('shutting down');
   us_listen_socket_close(listenSocket);
   listenSocket = null;
   wsMap.forEach(ws => ws.close());
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
// ctr+c will send SIGINT
```
Other than websockets, an Http connection could keep app open for up to 10 seconds (tcp timeout), which is extended 10 more seconds for every `response.onData()` event if you have any of those set up, so you could add `if (!listenSocket) res.close()` in onData handler to close any open connections. It could be something other than uWS.js is keeping your app open, library like https://github.com/myndzi/wtfnode can help you find what it is

**Comment by jjjuk** [comment]
Thank you for answer, but there wasn't any problem to stop the process, there was a problem to reload local service (one process runs multiple local services), after reload requests don't reach the server. 

I fixed this by running the server with fork, and killing process on service restart. 
I'll try to reproduce this problem outside of moleculer. But basically it seems like if you stop server gracefully and run it again in the same process it wouldn't be available. 

I work on windows so maybe after graceful stop port is still busy.

**Comment by e3dio** [comment]
Linux has no issue with close and re-open on same port in same process, looks like does not work in Windows, recommend running Linux if you need that
