### ISSUE TITLE
Automated Builds For Windows Seem Broken

### ISSUE THREAD

**Issue by RatherLogical** [uNetworking/uWebSockets.js#811]
The https://github.com/uNetworking/uWebSockets.js/tree/binaries branch has not had a windows `.node` update in 5 months. When I forked the project to add a custom version no `.node` binary was emitted to the `dist` folder in the `build-windows` job. It would appear that Windows CI builds are broken.

**Comment by uNetworkingAB** [comment]
Everything but Linux is broken because the code currently do not compile on anything but Linux.
