### ISSUE TITLE
Missing wrapper for listening to unix domain socket

### ISSUE THREAD

**Issue by mikrosystheme** [uNetworking/uWebSockets.js#815]
The signature was added in [uWebSockets#1486](https://github.com/uNetworking/uWebSockets/pull/1486), but as far as I can tell it has not been wrapped yet. I know that this is a niche feature with very little use, but it would reduce the mental burden of having to pick a port number when running different applications behind a proxy.

**Comment by OmgImAlexis** [comment]
Is there currently any way to manually access this with the `.js` lib or does it need to be wrapped first?
