### ISSUE TITLE
HTTP3 example not working

### ISSUE THREAD

**Issue by dalisoft** [uNetworking/uWebSockets.js#841]
Hi @uNetworkingAB

I'm trying to run HTTP3 server but it does not work.
Here minimal repo to reproduce: https://github.com/nanoexpress/http3-uws

## Steps to reproduce
- Follow steps **Open in VSCode** from README
- Opening in browser **local url with port**, e.g. `https://localhost:50624/`

## Actual

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/3511344/208461781-b8f40c3d-c824-40d3-b7cb-04a00e1665bb.png">

## Expected

Working web-server with response of `H3llo World!`

**Comment by devalexqt** [comment]
not working
