### ISSUE TITLE
uWebsocket Client in Node

### ISSUE THREAD

**Issue by SchahinRohani** [uNetworking/uWebSockets.js#850]
I've seen the Example of the uWebsockets Client inside the Main Repo : [uWebsockets Client](https://github.com/uNetworking/uWebSockets/blob/master/examples/Client.cpp)

Can the node version get updated to integrate the client?
It would remove the needs of a different dependency for the websocket client.

I would give it a try if i can get somehow some guidance. 

best regards,

Schahin

**Comment by uNetworkingAB** [comment]
There is no client that's an empty shell for eventual future implementation but how come you dig down to find this, but you don't care to open the files and see they are empty 🤔
