### ISSUE TITLE
uWS not running on node v16

### ISSUE THREAD

**Issue by a-tonchev** [uNetworking/uWebSockets.js#858]
After updating to uWS v20.18.0 the server won't start. I get message that the node version is not supported, even I am using node v 16.18.0

(Ubuntu 20.04 on WSL)

![image](https://user-images.githubusercontent.com/54528540/211313363-ce96d35e-329e-4617-bdd2-566cdbda5be4.png)

**Comment by uNetworkingAB** [comment]
Try 20.19.0

**Comment by a-tonchev** [comment]
@uNetworkingAB it seems to work, thanks Alex
