### ISSUE TITLE
Error in uws.js

### ISSUE THREAD

**Issue by atshushi** [uNetworking/uWebSockets.js#863]
Error: This version of uWS.js supports only Node.js 16 and 18, and 19 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

My node version is `v18.13.0` and i'm using yarn

**Comment by uNetworkingAB** [comment]
I'm not going to read your mind for details. Nobody can infer anything of value from this report

**Comment by atshushi** [comment]
what information do you want?

**Comment by uNetworkingAB** [comment]
Read the text and figure that out

**Comment by eudaimos** [comment]
@atshushi are you using a bundler in front of running the app?

I was and had the same problem, but with some help figured out the issue.
You need to mark `uWebSockets.js` as an `external` dependency so the bundler doesn't try to bundle it into the single file.

**Comment by uNetworkingAB** [comment]
I don't see why we should play 20 questions to try and pinpoint what he could have said from the start. This is not how a report is written, it's not for us to play detective for other people's gain
