### ISSUE TITLE
include in TechEmpower Framework Benchmarks

### ISSUE THREAD

**Issue by ewwink** [uNetworking/uWebSockets.js#87]
Hi,
I saw a lot good web server in there and it will be great if uWebSockets.js is also listed.

website: https://www.techempower.com/benchmarks/
github: https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by alexhultman** [comment]
No, that is a common request. I do not recommend anything TechEmpower. They are incompetent and cannot properly handle fast servers. No discussion thanks.
