### ISSUE TITLE
build for android

### ISSUE THREAD

**Issue by a7210232** [uNetworking/uWebSockets.js#875]
wo need a lib for android uws_android_arm64_108.node

**Comment by uNetworkingAB** [comment]
You have misunderstood what this project is.

**Comment by a7210232** [comment]
my nodejs run on android  .
Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_android_arm64_108.node'

**Comment by uNetworkingAB** [comment]
What kind of thing are you building?

**Comment by a7210232** [comment]
I bind arm64, but not useful on android nodejs v18 - v19  . I install a arm64 package nodejs on android it work now
