### ISSUE TITLE
Please publish this library to npm

### ISSUE THREAD

**Issue by Geequlim** [uNetworking/uWebSockets.js#876]
GitHub has been completely blocked in China and we are unable to use it normally, but we can still use libraries on npm through mirrors.

**Comment by Nishchit14** [comment]
How do you feel in China?

**Comment by uNetworkingAB** [comment]
Then unlock it

**Comment by pietrovismara** [comment]
I'm sorry has this been published on npm? 
The only package I can find is https://npm.io/package/uwebsockets.js, last published 3 years ago.

**Comment by uNetworkingAB** [comment]
None of those are correct (yet again reaffirming my disgust of NPM as they can't properly uphold IP rights, but just do whatever they feel like). None of those are the product of uNetworking and are in no way representative of this work.

**Comment by pietrovismara** [comment]
@uNetworkingAB so the correct way is to install from github or is there a correct npm package?

**Comment by christian-bromann** [comment]
@uNetworkingAB why would you not just have some install instructions especially if you decide not to host your package on NPM. Most of the people just install from NPM, if you have something against them, that's your thing.
