### ISSUE TITLE
Getting socket hangups when using uWS as a proxy

### ISSUE THREAD

**Issue by samuelgozi** [uNetworking/uWebSockets.js#878]
When running a "native" node http server, express, or even bun (which uses uws behind the scenes), the request handling callback is called. When running the code below I get a socket hangup, or a curl error `curl: (52) Empty reply from server`.

Am I doing something wrong?

```ts
import forge from 'node-forge';
import uWS from 'uWebSockets.js';

const PORT = 9090;

const app = uWS
  .App()
  .any('*', (res, req) => {
    console.log(req); // <-- This is never called
    res.end('Hello World!');
  })
  .listen(PORT, (token) => {
    if (token) return console.log('Listening to port ' + PORT);
    console.log('Failed to listen to port ' + PORT);
  });
```

This is the CURL command I use to test this:
``` bash
curl -x 127.0.0.1:9090 http://example.com/
```

**Comment by uNetworkingAB** [comment]
![](https://media.tenor.com/IY0FiSVJRKIAAAAC/seriously-disbelief.gif)
