### ISSUE TITLE
Using Hyper-Express in a Deno runtime with uWebSockets

### ISSUE THREAD

**Issue by pxCaptcha** [uNetworking/uWebSockets.js#884]
Hello everyone. This issue is related to an issue I face with Hyper-Express.

I'm aware of that this was build with a focus on NodeJS. I wanted to ask if theres any way to get this project to run within Deno it self, as I think this would bring even better results than in JS. 
Deno has a problem handling the .node files coming with this project, as Deno doesnt support handling for .node files.

Is there any way around this issue?

Thanks!:)

**Comment by uNetworkingAB** [comment]
Deno is not supported and is not planned. It's a completely different platform and they don't expose any native apis.
