### ISSUE TITLE
Node.js v20 LTS

### ISSUE THREAD

**Issue by e3dio** [uNetworking/uWebSockets.js#886]
[Node.js v20 Release Announcement ](https://nodejs.org/en/blog/announcements/v20-release-announce)

> Newly formed Node.js Performance team has renewed focus on performance since the last Major release. Node.js 20 includes many improvements to the fundamental parts of the runtime like fetch() and EventTarget. If you have a passion for performance and Node.js we are actively looking for contributors for our [performance team](https://github.com/nodejs/performance)

> Includes new version of V8 engine (v11.3 part of Chromium 113) bringing improved performance and new language features like Resizable ArrayBuffer

> Now includes Stable Test Runner

> New experimental Node.js Permission Model

**Comment by uNetworkingAB** [comment]
This will be the full transition to "latest 3 LTS" version support. 16, 18 and 20 will be supported but nothing else. From then on we slide forwards on every new LTS.

If you are on a current nodejs version that is not an LTS it will not work.

New release will be in less than 2 hours.
