### ISSUE TITLE
v20.22.0 release provide wrong version via package.json 

### ISSUE THREAD

**Issue by webcarrot** [uNetworking/uWebSockets.js#887]
`package.json` provided by `v20.22.0` looks like:

```json
{
  "name": "uWebSockets.js",
  "version": "20.21.0",
  "main": "uws.js",
  "types": "./index.d.ts",
  "exports": {
    "import": "./ESM_wrapper.mjs",
    "require": "./uws.js",
    "types": "./index.d.ts"
  }
}
```

**Comment by webcarrot** [comment]
I also noticed some segmentation fault errors during unit test runs.

They are quite strange - I will try to debug them.

**Comment by webcarrot** [comment]
Looks like from now we should just wrap everything with `res.cork`:

```
server.get('/*', (res, req) => {
	res.cork(() => {
		console.log('Req start');
		res.onAborted(() => {
			console.log('Aborted');
		});
		setImmediate(() => {
			res.writeStatus('200 OK');
			res.writeHeader('content-type', 'application/octet-stream');
			res.end(Buffer.allocUnsafe(16388));
			console.log('Req end');
		});
	});
});
```

**Comment by uNetworkingAB** [comment]
What Node.js version has the problems? Nothing should have changed for older Node.js versions. Can you confirm that only Node.js 20 has the problems?

**Comment by webcarrot** [comment]
Node v18.16.0

**Comment by uNetworkingAB** [comment]
Is this crash new for v20.22 or did it exit in prior versions?

**Comment by uNetworkingAB** [comment]
Ah okay I can reproduce the crash from v20.21.0 and forwards but not before. So something broke recently

**Comment by uNetworkingAB** [comment]
Should be fixed in next release, waiting for CI

**Comment by uNetworkingAB** [comment]
Confirmed fixed, thanks for reporting. Will release any time now
