### ISSUE TITLE
Server get/post/...etc handlers cannot be async and return promise according to current TS typings

### ISSUE THREAD

**Issue by JerryCauser** [uNetworking/uWebSockets.js#889]
Right now if I try to use async function as any kind of handlers (get/post/etc...) typescript will alarming me about non-correct type of handler function. It accepts only plain void function.

**Comment by JerryZhongJ** [comment]
> Right now if I try to use async function as any kind of handlers (get/post/etc...) typescript will alarming me about non-correct type of handler function. It accepts only plain void function.

I am doing a research about bugs in TypeScript, and I am trying to reproduce this bug. But I succeed to assign a async function to a property typed as returning void, just like `WebSocketBehavior.message`, without alarming. 

May I ask what your case was and how the alarm showed?

**Comment by JerryCauser** [comment]
I'm using `ts-standard` and it was pushing some error. I don't remember which one. You can try to reimplement it by yourself by installing ts-standard and desired version of uWS.js.

**Comment by JerryCauser** [comment]
@JerryZhongJ I'm using `ts-standard` and it was pushing some error. I don't remember which one. You can try to reimplement it by yourself by installing ts-standard and desired version of uWS.js.

**Comment by JerryCauser** [comment]
@JerryZhongJ `@typescript-eslint/no-misused-promises`

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-misused-promises.md#checksvoidreturn
