### ISSUE TITLE
Noticed message is ArrayBuffer, wouldn't Buffer be preferred?

### ISSUE THREAD

**Issue by ozra** [uNetworking/uWebSockets.js#91]
I just downloaded uws and played a little, so don't shoot me if the immediate reaction is moot, just throwing a ball here

Seeing that this is not gonna run in a browser.

Such a simple thing as doing a slice on it for some protocol parsing or whatever, generates a copy with `ArrayBuffer`, while creating a view with `Buffer`. 

_[edit:]_ Also: `ArrayBuffer` zeroes the buffer according to spec, while `Buffer` can be allocated "unsafe" and avoid unnecessary work.

Bra skit!

**Comment by alexhultman** [comment]
In a nutshell this has the same answer as for #93:

"Do X because that's what Nodejs does".

Following Nodejs rules will only give you yet another Nodejs.

The point of this project is essentially "Let's do negative X because that's the complete opposite of what Nodejs does".

**Comment by ozra** [comment]
I... don't quite know what to make of that.
Cool.

**Comment by alexhultman** [comment]
The point is your comments, 1, 2, 3, 4 and 5 all have the same general structure:

"Do X because that's what everyone does."

It's not how this project is run

**Comment by ozra** [comment]
Ok, I don't find this in this issue at all, and frankly it was not my intention — it's all about performance here... Buffer just happens to be the most transparent fastest way of shuffling data between add-on and v8 memory space — plus in an app, one will have to do something more with the data, and then the options are endless with Buffer, with minimal overhead. Using the rawest type on the platform that uw.js is implemented on, and, well with _the bonus_ of it being "standard", but that was not the end goal here.

**Comment by alexhultman** [comment]
Buffer is not standard. It is an inefficient garbage wrapper around ArrayBuffer, made by Node.js for Node.js. ArrayBuffer is the standard base made by Google, native to V8 and much more efficient. I know this because I did a 100% performance increase back in 2016 simply by replacing Buffer with ArrayBuffer. Fact is everything made by Node.js for Node.js is by tradition far worse off than the native thing.

**Comment by jimmywarting** [comment]
>  It is an inefficient garbage wrapper around ArrayBuffer

I totally agree. When you are only dealing with raw data and don't need any of the fancy hex/base64 string encoding conversion or advance binary manipulation like read/write(u)int then it's just a garbage wrapper of things that you don't use. like when you are piping a file to to a req/res for example. 

It's true that using some of nodes buffer method is faster like `buf.toString('hex')` and using DataView is slower then nodes Buffer internal methods

You can avoid copying ArrayBuffer's and typed arrays with the use of [subarray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/subarray) too.
`buf.slice(start, end)` is essentially the same thing as calling `buf.subarray(start, end)` an alternativ is `new Uint8Array(buf.buffer [, start, end])` 

I'm also a bit against using Buffer when it's not needed. As it dramatically decrease the dependencies size if you or someone else plan to use it in the browser later. The use of ArrayBuffer and typed arrays makes it a independent of Node.js and makes it possible to work in browser too

**Comment by alexhultman** [comment]
https://v8.dev/blog/dataview

DataView should be just as fast as anything else with recent V8 versions, besides you have this:

https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_arraybuffer_byteoffset_length

**Comment by jimmywarting** [comment]
> DataView should be just as fast as anything else with recent V8 versions

Oh, Cool - finally :) 
That wasn't the case the last time i used it

**Comment by ozra** [comment]
Thanks for the pointers (no pun...) and detailed explanation! :-)
