### ISSUE TITLE
async then res.cork(() => { res.writeStatus('101').writeHeader('test', '123'); res.upgrade(...); }) fail

### ISSUE THREAD

**Issue by e3dio** [uNetworking/uWebSockets.js#911]
after async calling res.cork(() => { res.writeStatus('101').writeHeader('test', '123'); res.upgrade(...); }) fails. If you separate the res.upgrade into its own cork it works

**Comment by e3dio** [comment]
Nevermind works fine sorry I had wrong code

**Comment by uNetworkingAB** [comment]
Maybe you were on an older version? It was broken before

**Comment by e3dio** [comment]
Not sure but is good now, this is my current upgrade handler:
```js
app.ws('/ws', {
   upgrade: auth({ new: true }, (res, context) => {
      if (res.ab) return;
      if (res.setCookie) res.cork(() => res.writeStatus('101').writeHeader('Set-Cookie', res.setCookie).upgrade({ user: res.user }, ...res.wsHeaders, context));
      else res.cork(() => res.upgrade({ user: res.user }, ...res.wsHeaders, context));
   })
})
```

**Comment by uNetworkingAB** [comment]
That looks good but you shouldn't need to call cork since you are executing inside upgrade handler which already is default corked. But it doesn't harm but still

**Comment by uNetworkingAB** [comment]
Oh wait you posted this as an example for failure my brain just locked up ńvm

**Comment by e3dio** [comment]
the `auth` middleware is async so it needs to cork

**Comment by uNetworkingAB** [comment]
Oh, cool!

**Comment by uNetworkingAB** [comment]
That usage looks pretty nice, clean and simple and now with proper corking you get a gold star ⭐
