### ISSUE TITLE
Different behavior for uWS 20.28 and 20.23

### ISSUE THREAD

**Issue by Mupli** [uNetworking/uWebSockets.js#913]
Hi I've found a problem with async execution in newer versions  (after .25) 

```
Error: Using uWS.HttpRequest / uWS.Http3Request past its request handler return is forbidden (it is stack allocated).
```

This example starts crashing  after upgrade to 20.25 and still there is error in 20.28.

```javascript
import { App } from "uWebSockets.js";

const getHeader = async (req, res) => {
    req.getHeader("test")      // <----------------------------------------------------Error 
}

async function end(res) {
    res.end("OK");
}

function pack(actions) {
    return async (...data) => {
        for (let index = 0; index < actions.length; index++) {
            let result = actions[index](...data);
            result = await result
            if (result !== undefined) return result;
        }
    };
}

const actions = pack([getHeader, getHeader, getHeader, getHeader])

const run = async (req, res) => {
    const mres = await actions(req, res)
    await end(res);
};

const app = App({});
app.any("/*", async (res, req) => {
        res.onAborted(() => {
            console.log("on aboard error");
        });
        run(req, res);
   
}).listen(3000, (listenSocket) => {
    if (listenSocket) {
        console.log("Listening to port 3000");
    }
});

```

Testing this with : 
autocannon -c 50 -d 5 -p 1 http://localhost:3000/test

Versions: 
Node.js v18.5.0
"autocannon": "^7.10.0",

**Comment by Mupli** [comment]
@uNetworkingAB  Hi You closed my ticket, but why ?

**Comment by Mupli** [comment]
@uNetworkingAB  I have updated my example. Maybe now is more clear. Not sure why I have errors as everything should be done in sequential order.

**Comment by uNetworkingAB** [comment]
Well, it's an invalid bug report for many reasons. I know from your other posts that you aren't telling the full story here, and the message you get is a fault in your own app. You have the first error mentioned in this post:

https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.29.0

**Comment by Mupli** [comment]
@uNetworkingAB ? Well I'm just surprised that upgrade from 20.23 to 20.25 broke my app. I've nailed error to this small example (first post). Thought that this is a bug. But apparently you are just changing behavior (limiting/restricting) or fixing it if that worked before by mistake.

In my case I wrote small middleware layer that can iterate trough some checks passing just req, res. (some needs to be async). Now executing them one by one will not be possible :(   

Now I need to fetch all data before I will go to async (queries, headers + cookies, ip, hostname, body, etc.). 

Hm I see problem here: 
1. Fetching all params and headers before await  will hit really hard readability of the code. Especially the complex methods (20+ params and  headers). 
2. Conditional fetching params/headers will be limited ( only works with sync methods) . 
3. Grouping params and functionalities into methods will be extremely limited as well.


Nice to have : 

```javascript
app.any("/user", async (res, req) => {

sendLogsMiddleware(req, res)
await checkSecurityMiddleware(req, res)
await validateBody(req, res, ...)
await userController.doSomething(req, res)
})
````

**Comment by uNetworkingAB** [comment]
Your code was always broken. You then turned on a non-default mode you didn't understand and now your broken code won't run. And you haven't even told me this, but I have to play detective to figure out your own fault

**Comment by Mupli** [comment]
@uNetworkingAB - sorry I'm not smart enough to find yours and my mistakes before they even show. 
And I could say that your code was broken before and now hit you twice.

I think there are many things that creates that situation:
- documentation is ...difficult 
- server lifecycle/flow is "specific"
- no tutorials 
- modifications change behavior which breaks contracts,  
- invalid semantic versioning
- no migration info

**Comment by uNetworkingAB** [comment]
Did you set environment variable ALIEN_UWS?

**Comment by Mupli** [comment]
yeah I had ALIEN_UWS=0, but now I see it still runs with ALIEN_UWS

**Comment by uNetworkingAB** [comment]
...Which is why I closed the issue and tagged it invalid.
