### ISSUE TITLE
Please register "uws" or "uwebsockets" package name on npmjs...

### ISSUE THREAD

**Issue by ozra** [uNetworking/uWebSockets.js#92]
...before someone else does it. 

Lowercase (hyphenated) packages is de facto norm, and being able to simply use `yarn add uws`, `yarn add uwebsockets` / `npm i -S uwebsockets` from the registry will promote the project I'd think.

Or "@unetworking/*", if you intend to add a lot of different js modules that compose well together — but I think "uws" would rock.

**Comment by alexhultman** [comment]
I did that three years ago.

**Comment by ozra** [comment]
xD

**Comment by iMoses** [comment]
@alexhultman and it was fabulous! but is it not used today for the new versions of the library?

I'm not sure why this library can only be installed from github which doesn't inform me about any new versions, which doesn't respect the semver logic of `package.json`, which is basically very patchy.. Is there an official reason why it isn't in the npm registry?
