### ISSUE TITLE
Would it be possible to add a (small) stack trace to the warnings related to `res.cork` which started from v20.26.0?

### ISSUE THREAD

**Issue by hawkerboy7** [uNetworking/uWebSockets.js#920]
Hi Alex Hultman,

Thank you for this project!
Would it be possible to add a (small) stack trace to the warnings related to `res.cork` which started from v20.26.0?

It looks asif I've placed all ` .writeStatus, .writeHeader, .end, .write, .tryEnd, .upgrade, .endWithoutBody, or similar` within a `res.cork`, and am not running any async actions afterwards, but I am still seeing some warnings and it is a bit hard to see where they come from.

Though not nessisary, since the instructions are clear, this would help in identifing the source of the problem a lot better.

**Comment by hawkerboy7** [comment]
In the meantime I did find the source of where the res.cork was missing.
> and am not running any async actions afterwards

This was incorrect.
Question still stands though :)

**Comment by uNetworkingAB** [comment]
Good. It means the warning is working :D
