### ISSUE TITLE
Is it possible to get client IP from request in ws::open

### ISSUE THREAD

**Issue by ozra** [uNetworking/uWebSockets.js#93]
I tried the DRY way of using `request-ip` module, which didn't work out.

I noticed the req-object differed from the standard Request class hierarchy of node, which is quite understandable given the differing uWS network stack.

I guess it would be neat if, whatever is exposed to JS on the object, is structured the same way as the node Request / HttpRequest classes to help discoverability and maintain patterns.

_[edit:]_
### For reference:

**These are the properties that request-ip tries, where available:**
```typescript
interface Request {
    headers: RequestHeaders;
    connection: {
        remoteAddress?: string;
        socket?: {
            remoteAddress?: string
        };
    };
    info?: {
        remoteAddress?: string
    };
    socket?: {
        remoteAddress?: string
    };
}
```
**...and the headers it tries to scrape:**
```typescript
interface RequestHeaders extends http.IncomingHttpHeaders {
    'x-client-ip'?: string;
    'x-forwarded-for'?: string;
    'x-real-ip'?: string;
    'x-cluster-client-ip'?: string;
    'x-forwarded'?: string;
    'forwarded-for'?: string;
    'forwarded'?: string;
}
```

**Comment by PeterHewat** [comment]
check: https://github.com/uNetworking/uWebSockets.js/issues/58

**Comment by ozra** [comment]
Still valid in any real world deployment scenario I'd think, as per comment in #58?
