### ISSUE TITLE
uWebsocket won't work on 18.0.0 node version?

### ISSUE THREAD

**Issue by AhmetcanFR** [uNetworking/uWebSockets.js#930]
![image](https://github.com/uNetworking/uWebSockets.js/assets/46138581/ac58f3b4-c7f1-4cf4-9c80-1d80a407737d)
![image](https://github.com/uNetworking/uWebSockets.js/assets/46138581/979af24d-d55b-4ff2-ad91-c063d93971c8)

My node version is 18.0.0?
![image](https://github.com/uNetworking/uWebSockets.js/assets/46138581/3cdd6aed-b2ea-45df-8a05-04e57223202e)

Not sure what i should do?

**Comment by uNetworkingAB** [comment]
![image](https://github.com/uNetworking/uWebSockets.js/assets/110806833/31a8360f-4497-4472-ac9d-3777ff1f5702)

What does the French mean?

**Comment by uNetworkingAB** [comment]
You posted a french message. I don't read french, and you don't seem interested in figuring out
