### ISSUE TITLE
Improving access to the module

### ISSUE THREAD

**Issue by spartanz51** [uNetworking/uWebSockets.js#935]
I don't understand why every time I create a project, I have to deal with special treatment for this module. It's the only dependency that causes issues.

Moreover, the number of beginners who are confused by the lack of accessibility to the module is unusually high, and they end up using less stable or less performant alternatives. I am outraged by the state of the module which impacts everyone's access to this great module.

Perhaps it is time to put the module back on npm, or at the very least, not release a "broken" version that introduces even more conflicts. If the purpose of this npm version was to redirect people to GitHub, why not simply add a note in the readme without compromising/deleting the module, like most people do when they migrate?

Maybe after all these years, it's time to calm the situation and move forward. What do you think?

Thank you for considering my publication, which solely aims to improve the community and ensure equal access to the best conditions for everyone, while setting aside ego and quarrels.

**Comment by uNetworkingAB** [comment]
We have no intention to use Npm

**Comment by superboss224** [comment]
> We have no intention to use Npm

Why ? it's the most common package manager for node, and the easiest way to install a module

**Comment by uNetworkingAB** [comment]
It's not in our interest to do so
