### ISSUE TITLE
res.end() doesn't end request

### ISSUE THREAD

**Issue by slavaGanzin** [uNetworking/uWebSockets.js#94]
Hello Alex.

If you call `res.end()` without writing something, e.g. `res.end('something')` or `res.write('something'); res.end()` request just hangs. And by HTTP specification it's perfectly ok to not have any content.

It's minor, but unexpected.

Thanks

**Comment by alexhultman** [comment]
It doesn't hang for me

**Comment by slavaGanzin** [comment]
Thanks for checking.


It was versioning issue. Same code hang request on 15.0.0 and works ok on 15.4.0:

```js
require('uWebSockets.js').App()
.any('/*', (res, req) => {
    res.end();
  })
.listen(80, console.log)
```
