### ISSUE TITLE
Proper use of topics

### ISSUE THREAD

**Issue by mkgn** [uNetworking/uWebSockets.js#943]
This is with reference to the comment made [here](https://github.com/uNetworking/uWebSockets.js/issues/527#issuecomment-844028492). I am coming from a .Net background and in SignalR, they say it's ok to create a so called "group/topic" per connection. Initially I was planning to subscribe every connected socket to a topic with the name of [user.id] (who owns that socket). This way when someone wants to send a message to this user you can just publish to user.id topic. If I go down this path, it'll end up having MANY topics (for single users and groups) which is not the best according to what I gathered.

So, the next option then is to keep a look up table with [user.id][socket] pairs for sending individual messages. 

Am I thinking correct here?

**Comment by uNetworkingAB** [comment]
You can do either way. Those comments no longer apply, we have a completely different pub/sub since v20.
