### ISSUE TITLE
Session Resume

### ISSUE THREAD

**Issue by grijjly** [uNetworking/uWebSockets.js#944]
main idea of this project is performance, but no information about tls session resume. Is it handle session resume ? if it is when i check multithread example there is no shared session resume example. If this library has no session resume, nodejs itself a lot of faster than this library. If main idea is only websocket (session resume still matter) why there is http3 etc?

**Comment by uNetworkingAB** [comment]
Default is to have a session cache:

SSL_SESS_CACHE_SERVER
Server sessions are added to the session cache. When a client proposes a session to be reused, the server looks for the corresponding session in (first) the internal session cache (unless SSL_SESS_CACHE_NO_INTERNAL_LOOKUP is set), then (second) in the external cache if available. If the session is found, the server will try to reuse the session. This is the default.

**Comment by civilianatpoint** [comment]
thank you for information, how can i share them between threads ?

**Comment by uNetworkingAB** [comment]
You could use a read through the user manual to get an idea of how things is designed, first
