### ISSUE TITLE
Disable uwebsockets header?

### ISSUE THREAD

**Issue by markg85** [uNetworking/uWebSockets.js#956]
Hi,

I've noticed uwebsocket is exposing it's major version in a header.
The C++ version of this library has a compile time option to disable this "watermark" under the define `UWS_HTTPRESPONSE_NO_WRITEMARK` but that won't work with the js version.

I do get that it's a bit of a pride thing too and you're probably not eager to disable it by default.

How about an environment variable to disable it at startup time:
```UWS_HTTPRESPONSE_NO_WRITEMARK=1 node index.js```

Best regards,
Mark

**Comment by uNetworkingAB** [comment]
It's not a pride thing. It's a business thing. If you want to remove the header you can do so in your proxy. Alternatively I might put it under a code, which can be retrieved by registering your company with us for statistics.
