### ISSUE TITLE
Close connection if there is no response on auto ping

### ISSUE THREAD

**Issue by zdm** [uNetworking/uWebSockets.js#957]
I it possible to add possibility to automatically close websocket connection it there is no `pong` response to the auto ping?
This would be useful to close broken connections.

For example it could be implemented like this:
1. add new timeout - `noDataReceiveTimeout`;
2. noDataReceiveTimeout` reached;
3. send auto ping;
4. if pong or other data was received - ok, do nothing;
5. second noDataReceiveTimeout` reached - if no data was received between two timeouts - close connection;

**Comment by e3dio** [comment]
It does that now since [v19](https://github.com/uNetworking/uWebSockets/releases/tag/v19.0.0), auto send ping before `idleTimeout ` and close connection if no response

**Comment by zdm** [comment]
Ah, perfect
thank you
