### ISSUE TITLE
Performance benchmark: uWebSockets.js is beaten by happx

### ISSUE THREAD

**Issue by jim-king-2000** [uNetworking/uWebSockets.js#962]
See (removed link) for the detail.

Speak concisely:
Request per second: uWebSockets.js is 182 365 and happx is 259 556.

Does it mean that uWebSockets.js could be even faster in the future?

**Comment by uNetworkingAB** [comment]
This is nothing new. uWS.js runs with at least a 40% performance hit compared to uWS. uWS.js is limited by node::MakeCallback and JavaScript garbage collection as well as Node.js async hooks, etc.

> Nim is a statically typed compiled systems programming language

Yeah this is basic computer science 101. A scripting environment is not for speed.
