### ISSUE TITLE
Bun install fails 

### ISSUE THREAD

**Issue by doloboyz** [uNetworking/uWebSockets.js#966]
When attempting to install uWebSockets.js with the command provided in the README, install fails. The following is the output of running the command:

```
bun install uNetworking/uWebSockets.js#v20.31.0
zsh: no matches found: uNetworking/uWebSockets.js#v20.31.0
```

The same command without version specification results in the following output:
```
 bun install uNetworking/uWebSockets.js
bun add v1.0.1 (31aec4eb)
  🚚 uNetworking/uWebSockets.js [2/2] error: InstallFailed extracting tarball for uNetworking/uWebSockets.

error: "package.json" for "uNetworking/uWebSockets.js" failed to open: FileNotFound
```

**Comment by Jarred-Sumner** [comment]
This is a bug in Bun, not in uWebSockets - please file an issue in Bun's repository

**Comment by doloboyz** [comment]
> This is a bug in Bun, not in uWebSockets - please file an issue in Bun's repository

Sorry just saw this. I'll recreate the issue in the Bun repo.

**Comment by just-maik** [comment]
According to https://github.com/oven-sh/bun/issues/5870 this occurs because this repository does not provide a package.json file.

**Comment by uNetworkingAB** [comment]
This repository does provide a package.json. The issue is that you've skipped the readme where you have extensive info on installation. You're referencing an issue in which the person have just fine whatever he thought. Read the readme

**Comment by uNetworkingAB** [comment]
Autocorrect is shit
