### ISSUE TITLE
Can't find or install from npm registery. 

### ISSUE THREAD

**Issue by Gantushig77** [uNetworking/uWebSockets.js#968]
Basically, I can't install the js package. 

- (Fails) bun install uNetworking/uWebSockets.js#v20.31.0
- (Fails) pnpm install uNetworking/uWebSockets.js
- (Fails) npm install uNetworking/uWebSockets.js

The js [package](https://npm.io/package/uwebsockets.js) in the npm latest version is 19. And it's not compatible with arm macs. It installs from the npm and it fails to work. I think developers need a slightly easier solution to use the package. 

The only option is to clone the git repo and compile it yourself.

**Comment by uNetworkingAB** [comment]
> bun install uNetworking/uWebSockets.js#v20.31.0

Works perfectly.

**Comment by sonyarianto** [comment]
Me too, not working, confuse.

![image](https://github.com/uNetworking/uWebSockets.js/assets/333051/5ced4d03-7bcf-4e59-881c-b6f3eab4d95d)

hang...

**Comment by uNetworkingAB** [comment]
Then report it in respective project.

**Comment by rtritto** [comment]
@sonyarianto https://github.com/uNetworking/uWebSockets.js/pull/1007#issuecomment-2395067007
