### ISSUE TITLE
.close() handler not being called on graceful shutdown

### ISSUE THREAD

**Issue by SiNONiMiTY** [uNetworking/uWebSockets.js#972]
Greetings,

I am trying to handle a graceful shutdown scenario with this code.

```
# Add the ws reference on socket open
const wsClientMap = new Map<string, uWS.WebSocket>()

# Sample uWS server code
uWS.App()
    .ws( '/', {
        open: ( ( ws ) => {
            wsClientMap.set( id, ws )
        } ),
        close: ( () => {
            console.log( 'TRIGGERED' )
        } )
    } )


# Handle Interrupt Signal
process.on( 'SIGINT', () => {
    wsClientMap.forEach( ( socket ) => {
        socket.end()
    } )

    process.exit( 0 )
} )
```

When disconnecting from the Client code, TRIGGERED is shown on the server console, however, when I try to trigger it via CTRL + C,
the close event handler is not invoked, Am I missing anything on this one? It seems that the close() handler is not being called.

**Comment by uNetworkingAB** [comment]
You have to debug your code on your own. That code doesn't even pass basic syntax checking

**Comment by SiNONiMiTY** [comment]
Thank you for your answer, that was just to show a basic gist of what I am doing. Anyways, was able to pinpoint the issue.

Very disappointing to ask questions here. I ask a question and all that can be given is "That code doesn't even pass basic syntax checking". You expect examples to be perfect @uNetworkingAB? Can't get the gist of the code? The scenario was explained.

Anyways thank you. and have a nice day.

**Comment by uNetworkingAB** [comment]
You expect people to debug _your application bugs_ based on incomplete code that doesn't even "compile"? How on earth?

* "This calculation is not working: 1 + 5 ++- 4"
* "Dude your calculation is not even valid syntax"
* "I will let you know that I want to speak with the manager! How dare you lalala"

We aren't thought readers, you need to be able to communicate a reality in proper grammar if you want to be taken for anything other than a fool lost in his own pocket
