### ISSUE TITLE
ARM64 binary wrong for Node20

### ISSUE THREAD

**Issue by jbenguira** [uNetworking/uWebSockets.js#987]
I noticed recently that on ARM64 / Node 20 I'm getting this error:
Error: uws_linux_arm64_115.node: wrong ELF class: ELFCLASS32

I also tried with Node 21 and there the binary is accepted but I'm getting this error:
Error: idleTimeout must not be greater than 960 seconds!
terminate called without an active exception
Aborted (core dumped)

No issues with Node 18, so my guess is the binary for Node 20 (uws_linux_arm64_115.node) is containing a wrong version (compiled for 32 bits CPU?) and version for node 21 have another issue

**Comment by e3dio** [comment]
Arm64 Node v20 works fine, Node v21 works too, with uWS.js binaries from many months ago and latest

**Comment by jbenguira** [comment]
Hum ... Then please let me redo my tests and update here with details and steps

**Comment by uNetworkingAB** [comment]
Make sure to use a released tag

**Comment by jbenguira** [comment]
> Make sure to use a released tag
Thanks, tested with this one and it worked! (v20.34.0)

about my second issue (idleTimeout must not be greater than 960 seconds!) it was just my code setting it by default to 1 day, it was working with older versions of uWS but seems to be now capped to 960 seconds. That's ok with me.

Thanks for your help :)

**Comment by uNetworkingAB** [comment]
If you don't want idleTimeout the disabled is 0, 16 minutes is maximum but default is probably 120 seconds
