### ISSUE TITLE
open with one ID but closes with another ID

### ISSUE THREAD

**Issue by MariuzM** [uNetworking/uWebSockets.js#989]
I'm using Bun + Elysia, when i make connection it opens with one ID but when i close same connection it closes with another ID

Not really sure if this is normal when i used Fastify + SocketIO it would close with same ID.

Repo: https://github.com/MariuzM/bun/blob/main/src/app.ts

<img width="215" alt="image" src="https://github.com/uNetworking/uWebSockets.js/assets/36937039/264ceb75-f1f3-4202-b737-50194a095b73">

Same goes with messaging 
🚀 ~ open: 1700400730449
🚀 ~ message: 1700400731624
🚀 ~ message: 1700400737554
🚀 ~ message: 1700400739822

Are those ID more like instances? but then how do i keep track of my connections? so lets say i assign user name / ID to specific connection ID but if are different each time i do action on client in WS?

**Comment by uNetworkingAB** [comment]
None of those 4 mentioned projects are uWS.js so posting here is not really the way to go. There is no such concept "ID" in uWS.js and I have no idea what those projects do, ask them.

**Comment by MariuzM** [comment]
@uNetworkingAB ? what do you mean about 4 different projects? Bun + Elysia (1 project) under the hood they use uWebSockets

Is ws does not have id what is this `ws.id` ? 
<img width="471" alt="image" src="https://github.com/uNetworking/uWebSockets.js/assets/36937039/69970d03-249d-428d-9381-1833b76df607">

https://github.com/uNetworking/uWebSockets.js/discussions/843

**Comment by uNetworkingAB** [comment]
I built a pull up bar using wooden beams and metal screws. Now I am complaining to the screw manufacturer for my crooked build.

Please infer

**Comment by e3dio** [comment]
Why are you opening issue here when you use completely different library, elysiajs is adding id to ws. This is why you should not blindly use random libraries with blackbox functionality, just use uWS.js and do it right https://elysiajs.com/patterns/websocket.html#open

**Comment by MariuzM** [comment]
I get you guys are annoyed about this, but from my perspective and reading discussion how people use your package is that there is `ws.id` so how I'm suppose to know Elysia is adding? For me the syntax is same as your API `ws.id` that's it, i only needed confirmation if this is how it works from your end and if not i would have went back to Elysia or Bun. 

@uNetworkingAB no need to be all high and mighty about this...

**Comment by uNetworkingAB** [comment]
If you ask here, I _assume_ you want an answer. The problem is, you _already got an answer_ but you seem to want another answer. There _is no other answer_. Read it, consume it and understand it.

**Comment by MariuzM** [comment]
You have issues, hope you sort them out, good luck

**Comment by uNetworkingAB** [comment]
Yes my issue is you, bye bye
