### ISSUE TITLE
PubSub SLL error

### ISSUE THREAD

**Issue by boojum** [uNetworking/uWebSockets.js#991]
In the latest version (2.34.0) the `PubSub.js` example is not working with ssl/wss.

The only change I did to the example code was the import statement, `import uWS from 'uWebSockets.js'`. Then I tried to connect with `wscat`, and while `wscat -n --connect ws://chatterer.local:9001` works just fine trying `wscat -n --connect wss://chatterer.local:9001` is erroring out:
```sh
error: write EPROTO 00483D629E7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354
```

**Comment by uNetworkingAB** [comment]
Did you get it to work with a previous version or example?

**Comment by boojum** [comment]
I used current `PubSub.js` example with modified `import` and path to certs only:
```js
import uWS from 'uWebSockets.js'
const port = 9001;

const app = uWS./*SSL*/App({
  key_file_name: 'certs/key.pem',
  cert_file_name: 'certs/cert.pem',
  passphrase: '1234'
}).ws('/*', {
  /* Options */
  compression: uWS.SHARED_COMPRESSOR,
  maxPayloadLength: 16 * 1024 * 1024,
  idleTimeout: 10,
  maxBackpressure: 1024,

  /* Todo, Setting 1: merge messages in one, or keep them as separate WebSocket frames - mergePublishedMessages */
  /* Todo, Setting 4: send to all including us, or not? That's not a setting really just use ws.publish or global uWS.publish */

  /* Handlers */
  open: (ws) => {
    /* Let this client listen to all sensor topics */
    ws.subscribe('home/sensors/#');
  },
  message: (ws, message, isBinary) => {
    /* Parse this message according to some application
     * protocol such as JSON [action, topic, message] */

    /* Let's pretend this was a temperature message
     * [pub, home/sensors/temperature, message] */
    ws.publish('home/sensors/temperature', message);

    /* Let's also pretend this was a light message
     * [pub, home/sensors/light, message] */
    ws.publish('home/sensors/light', message);

    /* If you have good imagination you can also
     * pretend some message was a subscription
     * like so: [sub, /home/sensors/humidity].
     * I hope you get how any application protocol
     * can be implemented with these helpers. */
  },
  drain: (ws) => {

  },
  close: (ws, code, message) => {
    /* The library guarantees proper unsubscription at close */
  }
}).any('/*', (res, req) => {
  res.end('Nothing to see here!');
}).listen(port, (token) => {
  if (token) {
    console.log('Listening to port ' + port);
  } else {
    console.log('Failed to listen to port ' + port);
  }
});
```
I check few previous version but each one is erroring out:

**2.34.0** `error: write EPROTO 00C89028C67F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:`

**2.31.0 - 2.33.0** `error: write EPROTO C0F73138637F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:`

**2.30.0 - 2.20.0** `error: Client network socket disconnected before secure TLS connection was established`

**2.19.0 - 2.11.0** skipped

**2.10.0** `error: Client network socket disconnected before secure TLS connection was established`

**2.9.0 - 2.2.0** skipped

**2.1.0 - 2.0.0** `error: Client network socket disconnected before secure TLS connection was established`

**19.5.0**
```sh
npm ERR! code 1
npm ERR! The git reference could not be found
npm ERR! command git --no-replace-objects checkout v1.19.5
npm ERR! error: pathspec 'v1.19.5' did not match any file(s) known to git
```

**Comment by uNetworkingAB** [comment]
You are not using SSLApp
