### ISSUE TITLE
Is possible to run in FreeBSD?

### ISSUE THREAD

**Issue by manuelfhp** [uNetworking/uWebSockets.js#992]
I'm trying to run in a FreeBSD but I'm facing this error:

**Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms**

It seems that uWS.js is trying looking for uws_freebsd_x64_108.node, but this versions does not exist.
Do you think is possible to use uWS.js in FreeBSD environment or plans to support it?

FreeBSD 12.4
Node Version v18.12.1

**Comment by uNetworkingAB** [comment]
FreeBSD is not even supported officially by Node.js itself and I haven't come across any single company that actually runs on FreeBSD. So while it's definitely possible, it's not motivated.

**Comment by uNetworkingAB** [comment]
Can also add, that running Node.js by default invalidates every possible performance argument one can make about the low level platform on which it runs, as 99% of overhead is going to be in JavaScript and Node.js itself. Not from any supposed inferiority of the linux kernel. You already lose at least 50% of performance just from having JavaScript invoke a single function call with a single integral argument, so to make arguments of low level components is irrelevant and pointless not to add that they are idiotically false
